Repository microsoft/STL, pull requests merged in 2020-11, with the labels that each got.

#1305 Implement ranges::common_view
  stl/inc/ranges
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_views_common/env.lst
  tests/std/tests/P0896R4_views_common/test.cpp
Labels: cxx20, ranges

#1375 Implement views::counted
  stl/inc/ranges
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_views_counted/env.lst
  tests/std/tests/P0896R4_views_counted/test.cpp
  tests/std/tests/P0896R4_views_counted_death/env.lst
  tests/std/tests/P0896R4_views_counted_death/test.cpp
Labels: cxx20, ranges

#1397 Shrink DLL 2% by removing dead code for Windows XP
  stl/src/filesystem.cpp
  stl/src/winapinls.cpp
  tests/std/tests/Dev11_1086953_call_once_overhaul/test.cpp
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: enhancement

#1425 Status Chart: Weekly update
  daily_table.js
  monthly_table.js
  package-lock.json
  package.json
  weekly_table.js
Labels: documentation, uncharted

#1414 Accelerate tests by dividing them into shards
  azure-devops/run-build.yml
  azure-pipelines.yml
Labels: test

#1336 <cmath>: Use intrinsics where possible
  stl/inc/cmath
Labels: performance

#1341 <chrono>: [time.duration.io] output
  stl/inc/chrono
  stl/inc/string
  tests/std/test.lst
  tests/std/tests/P0355R7_calendars_and_time_zones_io/env.lst
  tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp
Labels: cxx20

#1358 Prevent crash when custom streambuf implementation throws
  stl/inc/xiosbase
  stl/src/ios.cpp
  tests/std/test.lst
  tests/std/tests/GH_001105_custom_streambuf_throws/env.lst
  tests/std/tests/GH_001105_custom_streambuf_throws/test.cpp
Labels: bug

#1366 Implement drop_while_view
  stl/inc/algorithm
  stl/inc/ranges
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_views_drop_while/env.lst
  tests/std/tests/P0896R4_views_drop_while/test.cpp
  tests/std/tests/P0896R4_views_drop_while_death/env.lst
  tests/std/tests/P0896R4_views_drop_while_death/test.cpp
Labels: cxx20, ranges

#1372 Implement ranges::take_while_view
  stl/inc/ranges
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_views_take_while/env.lst
  tests/std/tests/P0896R4_views_take_while/test.cpp
  tests/std/tests/P0896R4_views_take_while_death/env.lst
  tests/std/tests/P0896R4_views_take_while_death/test.cpp
Labels: cxx20, ranges

#1405 Include <cmeow> instead of <meow.h>
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/__msvc_system_error_abi.hpp
  stl/inc/atomic
  stl/inc/barrier
  stl/inc/cassert
  stl/inc/cctype
  stl/inc/cerrno
  stl/inc/cfenv
  stl/inc/charconv
  stl/inc/chrono
  stl/inc/cinttypes
  stl/inc/clocale
  stl/inc/csetjmp
  stl/inc/csignal
  stl/inc/cstdarg
  stl/inc/cstring
  stl/inc/ctime
  stl/inc/cuchar
  stl/inc/cwctype
  stl/inc/experimental/coroutine
  stl/inc/experimental/resumable
  stl/inc/latch
  stl/inc/mutex
  stl/inc/random
  stl/inc/ratio
  stl/inc/semaphore
  stl/inc/tuple
  stl/inc/xatomic.h
  stl/inc/xatomic_wait.h
  stl/inc/xcharconv.h
  stl/inc/xcharconv_ryu.h
  stl/inc/xcharconv_ryu_tables.h
  stl/inc/xfilesystem_abi.h
  stl/inc/xlocinfo.h
  stl/inc/xthreads.h
  stl/inc/xtimec.h
  stl/src/xstol.cpp
  stl/src/xstoll.cpp
  stl/src/xstoul.cpp
  stl/src/xstoull.cpp
  tests/std/test.lst
  tests/std/tests/GH_001411_core_headers/env.lst
  tests/std/tests/GH_001411_core_headers/test.cpp
Labels: enhancement, test

#1406 Implement ranges::elements_view
  stl/inc/ranges
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_views_elements/env.lst
  tests/std/tests/P0896R4_views_elements/test.cpp
Labels: cxx20, ranges

#1410 Move from rvalue range adaptor closures
  stl/inc/ranges
  tests/std/tests/P0896R4_views_filter/test.cpp
  tests/std/tests/P0896R4_views_transform/test.cpp
Labels: performance, ranges

#1413 Improve type traits usage
  stl/inc/random
  stl/inc/xmemory
  stl/inc/xtree
  stl/inc/xutility
Labels: throughput

#1415 Always remove_cvref_t the argument to enable_borrowed_range
  tests/std/tests/P0896R4_views_all/test.cpp
  tests/std/tests/P0896R4_views_reverse/test.cpp
Labels: ranges, test

#1417 Fix noexcept(noexcept(is_nothrow_v))
  stl/inc/iterator
  stl/inc/ranges
Labels: bug, ranges

#1420 Rename _Iterator_base to _Category_base in <ranges>
  stl/inc/ranges
Labels: enhancement, ranges

#1423 hash<coroutine_handle<>>::operator() should be const
  stl/inc/coroutine
  tests/std/tests/P0912R5_coroutine/test.cpp
Labels: bug

#1426 Extracted _Choice<T>._Strategy to variable
  stl/inc/ranges
  stl/inc/xutility
Labels: enhancement, ranges

#1427 README.md: Update DevCom and Pipelines links
  README.md
Labels: documentation

#1431 Port MSVC-internal changes, again
  stl/aliases/arm64ec/std_init_once_begin_initialize.obj
  stl/aliases/arm64ec/std_init_once_complete.obj
  stl/aliases/generate.cmd
  stl/aliases/std_init_once_begin_initialize-arm64ec.txt
  stl/aliases/std_init_once_complete-arm64ec.txt
  stl/msbuild/stl_1/stl_1.files.settings.targets
  stl/msbuild/stl_2/msvcp_2.settings.targets
  stl/msbuild/stl_2/stl_2.files.settings.targets
  stl/msbuild/stl_atomic_wait/stl_atomic_wait.files.settings.targets
  stl/msbuild/stl_base/libcp.settings.targets
  stl/msbuild/stl_base/msvcp.settings.targets
  stl/msbuild/stl_codecvt_ids/msvcp_codecvt_ids.settings.targets
  stl/msbuild/stl_post/msvcp_post.settings.targets
Labels: enhancement

#935 <complex>: Improve numerical accuracy of sqrt and log
  stl/inc/complex
  stl/inc/xutility
  tests/std/include/fenv_prefix.hpp
  tests/std/test.lst
  tests/std/tests/GH_000935_complex_numerical_accuracy/env.lst
  tests/std/tests/GH_000935_complex_numerical_accuracy/floating_point_utils.hpp
  tests/std/tests/GH_000935_complex_numerical_accuracy/log_test_cases.hpp
  tests/std/tests/GH_000935_complex_numerical_accuracy/sqrt_test_cases.hpp
  tests/std/tests/GH_000935_complex_numerical_accuracy/test.cpp
  tests/std/tests/GH_000935_complex_numerical_accuracy/test.hpp
  tests/std/tests/floating_point_model_matrix.lst
  tests/utils/stl/test/features.py
  tests/utils/stl/test/tests.py
Labels: bug

#1440 Status Chart: Weekly update
  daily_table.js
  index.html
  weekly_table.js
Labels: documentation, uncharted

#1378 [feature/format] parse format specs
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_parsing/test.cpp
Labels: cxx20, format

#1451 VS 2019 16.9 Preview 1 toolset update
  .github/ISSUE_TEMPLATE/cxx23-feature.md
  CMakeLists.txt
  README.md
  azure-devops/create-vmss.ps1
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  stl/inc/filesystem
  stl/inc/memory_resource
  stl/inc/tuple
  stl/inc/utility
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/std/tests/P0433R2_deduction_guides/test.cpp
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_views_common/test.cpp
  tests/std/tests/P0896R4_views_drop_while/test.cpp
  tests/std/tests/P0896R4_views_filter/test.cpp
  tests/std/tests/P0896R4_views_reverse/test.cpp
  tests/std/tests/P0896R4_views_take_while/test.cpp
  tests/std/tests/P0896R4_views_transform/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: infrastructure

#1434 Tests using /analyze:only should also use /analyze:autolog-
  tests/std/tests/P0088R3_variant/env.lst
  tests/std/tests/P1502R1_standard_library_header_units/env.lst
  tests/std/tests/VSO_0157762_feature_test_macros/env.lst
  tests/std/tests/concepts_matrix.lst
  tests/std/tests/impure_matrix.lst
  tests/std/tests/locale0_implib_cpp_matrix.lst
  tests/std/tests/native_17_matrix.lst
  tests/std/tests/native_matrix.lst
  tests/std/tests/native_winsdk_matrix.lst
  tests/std/tests/strict_concepts_matrix.lst
  tests/std/tests/strict_winsdk_concepts_matrix.lst
  tests/std/tests/usual_17_matrix.lst
  tests/std/tests/usual_17_winsdk_matrix.lst
  tests/std/tests/usual_latest_matrix.lst
  tests/std/tests/usual_latest_winsdk_matrix.lst
  tests/std/tests/usual_matrix.lst
  tests/std/tests/usual_winsdk_matrix.lst
  tests/tr1/env.lst
  tests/tr1/env_minus_md_idl.lst
  tests/tr1/env_minus_pure.lst
  tests/tr1/env_threads.lst
Labels: test

#1439 Updated _MSVC_STL_UPDATE to November 2020
  stl/inc/yvals_core.h
Labels: enhancement

#1441 README.md: Add llvm-project and --progress
  README.md
Labels: documentation

#1456 Remove comments for resolved LWG issues
  stl/inc/compare
  stl/inc/iterator
  stl/inc/ranges
  stl/inc/xutility
  tests/std/tests/P0896R4_counted_iterator_death/test.cpp
Labels: documentation

#1473 Skip the flaky parts of VSO_0226079_mutex
  tests/std/tests/VSO_0226079_mutex/test.cpp
Labels: test

#1481 Status Chart: Weekly update
  README.md
  daily_table.js
  weekly_table.js
Labels: documentation, uncharted

#1499 Status Chart: Add cxx23 line
  daily_table.js
  gather_stats.js
  index.html
  weekly_table.js
Labels: documentation
