Repository microsoft/STL, pull requests merged in 2020-10, with the labels that each got.

#1159 Fixes incorrect rounding in rejection method.
  stl/inc/charconv
  stl/inc/random
  stl/inc/xbit_ops.h
  tests/std/test.lst
  tests/std/tests/GH_001001_random_rejection_rounding/env.lst
  tests/std/tests/GH_001001_random_rejection_rounding/test.cpp
  tests/std/tests/GH_001123_random_cast_out_of_range/env.lst
  tests/std/tests/GH_001123_random_cast_out_of_range/test.cpp
Labels: bug

#1220 <charconv>: simplify _Assemble_floating_point_value and optimize _Right_shift_with_rounding
  stl/inc/charconv
  tests/std/tests/P0067R5_charconv/test.cpp
Labels: performance

#1228 prevent random distributions from returning NaN/Inf
  stl/inc/random
  tests/std/tests/GH_001017_discrete_distribution_out_of_range/test.cpp
Labels: bug

#1287 Workaround VSO-1222776 in <ranges>
  stl/inc/ranges
  stl/inc/xutility
Labels: bug, ranges

#1293 Pre-decay template arguments to _Front_binder
  stl/inc/functional
  tests/std/tests/P0356R5_bind_front/test.cpp
Labels: bug

#1299 Removes pow(complex,int) overload
  stl/inc/complex
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: bug

#1307 Remove macros and a compiler workaround
  stl/inc/chrono
  stl/inc/complex
  stl/inc/deque
  stl/inc/filesystem
  stl/inc/functional
  stl/inc/xlocale
  stl/inc/xlocinfo.h
  stl/inc/xstddef
  stl/inc/xtimec.h
  stl/inc/ymath.h
  stl/src/xferaise.cpp
  stl/src/xmath.hpp
Labels: enhancement

#1325 Remove unused ConcRT wrappers
  stl/src/primitives.hpp
Labels: enhancement

#1328 Support upstream EDG in the std test suite
  tests/utils/stl/compiler.py
  tests/utils/stl/test/config.py
  tests/utils/stl/test/format.py
  tests/utils/stl/test/tests.py
Labels: test

#1330 <vector>: prevent move ctor initializes members twice
  stl/inc/memory
  stl/inc/vector
  stl/inc/xhash
  stl/inc/xstring
  tests/std/tests/Dev10_722102_shared_ptr_nullptr/test.cpp
Labels: performance

#1340 Updated _MSVC_STL_UPDATE to October 2020
  stl/inc/yvals_core.h
Labels: enhancement

#1326 <iomanip>: std::get_time should not fail when format is longer than the stream
  stl/inc/xloctime
  tests/std/tests/Dev11_0836436_get_time/test.cpp
Labels: test

#1348 Status Chart: Weekly update
  daily_table.js
  monthly_table.js
  weekly_table.js
Labels: documentation, uncharted

#1356 _Execute_once bug fix.
  stl/src/xonce.cpp
Labels: bug

#1281 P0896R4 stream iterator changes
  stl/inc/iterator
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/P0896R4_stream_iterators/env.lst
  tests/std/tests/P0896R4_stream_iterators/test.cpp
Labels: cxx20, ranges

#1310 _Node_handle: destroy with value_type allocator
  stl/inc/xnode_handle.h
  tests/std/tests/P0083R3_splicing_maps_and_sets/test.cpp
Labels: bug

#1327 Remove workarounds for several compiler bugs
  stl/inc/functional
  stl/inc/iterator
  stl/inc/ranges
  stl/inc/utility
  stl/inc/xutility
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P0896R4_P1614R2_comparisons/test.cpp
  tests/std/tests/P0896R4_ranges_alg_heap/test.cpp
  tests/std/tests/P0896R4_ranges_alg_move/test.cpp
  tests/std/tests/P0896R4_ranges_alg_move_backward/test.cpp
  tests/std/tests/P0896R4_ranges_alg_nth_element/test.cpp
  tests/std/tests/P0896R4_ranges_alg_partial_sort/test.cpp
  tests/std/tests/P0896R4_ranges_alg_partial_sort_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_partition/test.cpp
  tests/std/tests/P0896R4_ranges_alg_permutations/test.cpp
  tests/std/tests/P0896R4_ranges_alg_remove/test.cpp
  tests/std/tests/P0896R4_ranges_alg_remove_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_reverse/test.cpp
  tests/std/tests/P0896R4_ranges_alg_rotate/test.cpp
  tests/std/tests/P0896R4_ranges_alg_sort/test.cpp
  tests/std/tests/P0896R4_ranges_alg_swap_ranges/test.cpp
  tests/std/tests/P0896R4_ranges_alg_unique/test.cpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
  tests/std/tests/P0896R4_views_transform/test.cpp
Labels: enhancement

#1337 Azure Pipelines: Skip tests if build fails, run both tools even if other fails
  azure-devops/run-build.yml
  azure-pipelines.yml
Labels: infrastructure

#1354 Update cgmanifest for 16.8
  docs/cgmanifest.json
Labels: documentation

#1355 _M_ARM64EC cleanups, v5
  stl/inc/xutility
  stl/msbuild/stl_atomic_wait/stl_atomic_wait.files.settings.targets
  stl/msbuild/stl_base/msvcp.settings.targets
  stl/src/vector_algorithms.cpp
Labels: enhancement

#1362 Add _CONTAINER_DEBUG_LEVEL checks for optional
  stl/inc/optional
  tests/std/include/test_death.hpp
  tests/std/test.lst
  tests/std/tests/P0220R1_optional_death/env.lst
  tests/std/tests/P0220R1_optional_death/test.cpp
  tests/std/tests/P0660R10_stop_token_death/test.cpp
  tests/std/tests/P0896R4_common_iterator_death/test.cpp
  tests/std/tests/P0896R4_counted_iterator_death/test.cpp
  tests/std/tests/P0896R4_views_filter_death/test.cpp
  tests/std/tests/P0896R4_views_transform_death/test.cpp
Labels: enhancement

#1368 Status Chart: Weekly update
  daily_table.js
  weekly_table.js
Labels: documentation, uncharted

#1333 [feature/format] add parse_precision.
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_parsing/test.cpp
Labels: cxx20, format

#1371 VS 2019 16.8 Preview 4, Python 3.9.0, absolute time fix
  README.md
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  stl/inc/condition_variable
  stl/inc/mutex
  stl/inc/shared_mutex
  stl/inc/thread
  tests/CMakeLists.txt
  tests/std/tests/P0660R10_jthread_and_cv_any/test.cpp
Labels: bug, infrastructure

#1315 Implement Smart Pointer Creation With Default Initialization
  stl/inc/memory
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P1020R1_smart_pointer_for_overwrite/env.lst
  tests/std/tests/P1020R1_smart_pointer_for_overwrite/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: cxx20

#1373 generator refactoring
  stl/inc/experimental/generator
Labels: bug, high priority

#1377 Remove unneeded case in uninitialized_default_construct_n
  stl/inc/memory
Labels: enhancement

#1380 feature/spaceship: Merge toolset update
  README.md
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  stl/inc/condition_variable
  stl/inc/experimental/generator
  stl/inc/memory
  stl/inc/mutex
  stl/inc/optional
  stl/inc/shared_mutex
  stl/inc/thread
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/CMakeLists.txt
  tests/std/include/test_death.hpp
  tests/std/test.lst
  tests/std/tests/P0220R1_optional_death/env.lst
  tests/std/tests/P0220R1_optional_death/test.cpp
  tests/std/tests/P0660R10_jthread_and_cv_any/test.cpp
  tests/std/tests/P0660R10_stop_token_death/test.cpp
  tests/std/tests/P0896R4_common_iterator_death/test.cpp
  tests/std/tests/P0896R4_counted_iterator_death/test.cpp
  tests/std/tests/P0896R4_views_filter_death/test.cpp
  tests/std/tests/P0896R4_views_transform_death/test.cpp
  tests/std/tests/P1020R1_smart_pointer_for_overwrite/env.lst
  tests/std/tests/P1020R1_smart_pointer_for_overwrite/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: infrastructure, uncharted

#1379 feature/format: Merge toolset update
  README.md
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  stl/inc/condition_variable
  stl/inc/experimental/generator
  stl/inc/memory
  stl/inc/mutex
  stl/inc/optional
  stl/inc/shared_mutex
  stl/inc/thread
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/CMakeLists.txt
  tests/std/include/test_death.hpp
  tests/std/test.lst
  tests/std/tests/P0220R1_optional_death/env.lst
  tests/std/tests/P0220R1_optional_death/test.cpp
  tests/std/tests/P0660R10_jthread_and_cv_any/test.cpp
  tests/std/tests/P0660R10_stop_token_death/test.cpp
  tests/std/tests/P0896R4_common_iterator_death/test.cpp
  tests/std/tests/P0896R4_counted_iterator_death/test.cpp
  tests/std/tests/P0896R4_views_filter_death/test.cpp
  tests/std/tests/P0896R4_views_transform_death/test.cpp
  tests/std/tests/P1020R1_smart_pointer_for_overwrite/env.lst
  tests/std/tests/P1020R1_smart_pointer_for_overwrite/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: infrastructure, uncharted

#1386 Status Chart: Weekly update
  daily_table.js
  index.html
  weekly_table.js
Labels: documentation, uncharted

#1388 Test P1502R1 Standard Library Header Units
  stl/inc/memory_resource
  tests/std/test.lst
  tests/std/tests/P1502R1_standard_library_header_units/__init__.py
  tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
  tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
  tests/std/tests/P1502R1_standard_library_header_units/env.lst
  tests/std/tests/P1502R1_standard_library_header_units/lit.local.cfg
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
Labels: cxx20, high priority, test

#1363 No, unique address!
  stl/inc/algorithm
  stl/inc/xmemory
Labels: bug

#1391 Fix small typo
  stl/inc/cvt/ebcdic
Labels: documentation

#1392 Updated working draft revision to n4868
  README.md
Labels: documentation

#1399 Upgrade CI to 32-core VMs and VS 2019 16.8 Preview 5
  README.md
  azure-devops/create-vmss.ps1
  azure-pipelines.yml
Labels: infrastructure

#1403 feature/format: Merge toolset update
  README.md
  azure-devops/create-vmss.ps1
  azure-pipelines.yml
  stl/inc/algorithm
  stl/inc/cvt/ebcdic
  stl/inc/memory_resource
  stl/inc/xmemory
  tests/std/test.lst
  tests/std/tests/P1502R1_standard_library_header_units/__init__.py
  tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
  tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
  tests/std/tests/P1502R1_standard_library_header_units/env.lst
  tests/std/tests/P1502R1_standard_library_header_units/lit.local.cfg
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
Labels: infrastructure, uncharted

#1404 feature/spaceship: Merge toolset update
  README.md
  azure-devops/create-vmss.ps1
  azure-pipelines.yml
  stl/inc/algorithm
  stl/inc/cvt/ebcdic
  stl/inc/memory_resource
  stl/inc/xmemory
  tests/std/test.lst
  tests/std/tests/P1502R1_standard_library_header_units/__init__.py
  tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
  tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
  tests/std/tests/P1502R1_standard_library_header_units/env.lst
  tests/std/tests/P1502R1_standard_library_header_units/lit.local.cfg
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
Labels: infrastructure, uncharted

#1408 Status Chart: Weekly update
  README.md
  daily_table.js
  weekly_table.js
Labels: documentation, uncharted

#1273 Use memset in even more cases
  stl/inc/algorithm
  stl/inc/memory
  stl/inc/xmemory
  stl/inc/xutility
  tests/std/tests/P0674R1_make_shared_for_arrays/test.cpp
  tests/std/tests/P0896R4_ranges_alg_fill/test.cpp
  tests/std/tests/P0896R4_ranges_alg_fill_n/test.cpp
  tests/std/tests/P0896R4_ranges_alg_uninitialized_fill/test.cpp
  tests/std/tests/P0896R4_ranges_alg_uninitialized_fill_n/test.cpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
  tests/std/tests/VSO_0180469_fill_family/test.cpp
Labels: performance

#1280 <iomanip>: fixes get_time to parse without delimiters
  stl/inc/xloctime
  tests/std/tests/Dev11_0836436_get_time/test.cpp
Labels: bug

#1334 Implement ranges::istream_view
  stl/inc/ranges
  tests/std/test.lst
  tests/std/tests/P0896R4_istream_view/env.lst
  tests/std/tests/P0896R4_istream_view/test.cpp
  tests/std/tests/P0896R4_istream_view_death/env.lst
  tests/std/tests/P0896R4_istream_view_death/test.cpp
Labels: cxx20, ranges

#1357 <xtree>: Fixes _Tree move constructor
  stl/inc/xtree
  tests/std/tests/Dev11_0437519_container_requirements/test.cpp
Labels: bug

#1370 Finish P0768R1 by adding Spaceship CPOs
  stl/inc/charconv
  stl/inc/compare
  stl/inc/concepts
  stl/inc/cstdint
  stl/inc/type_traits
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/P0768R1_spaceship_cpos/env.lst
  tests/std/tests/P0768R1_spaceship_cpos/test.cpp
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: cxx20, spaceship

#1390 Unsigned changed to unsigned int due to convention
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
Labels: test

#1393 Fix inconsistencies in range adaptor tests
  tests/std/tests/P0896R4_views_all/test.cpp
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_filter/test.cpp
  tests/std/tests/P0896R4_views_reverse/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
  tests/std/tests/P0896R4_views_transform/test.cpp
Labels: ranges, test

#1398 Move structs into unnamed namespaces
  stl/src/syserror.cpp
  stl/src/xonce.cpp
Labels: enhancement

#1400 initializer_lists constructed using values
  tests/tr1/tests/algorithm/test.cpp
  tests/tr1/tests/deque/test.cpp
  tests/tr1/tests/forward_list/test.cpp
  tests/tr1/tests/hash_map/test.cpp
  tests/tr1/tests/hash_set/test.cpp
  tests/tr1/tests/iterator/test.cpp
  tests/tr1/tests/list/test.cpp
  tests/tr1/tests/map/test.cpp
  tests/tr1/tests/random4/test.cpp
  tests/tr1/tests/random5/test.cpp
  tests/tr1/tests/regex1/test.cpp
  tests/tr1/tests/set/test.cpp
  tests/tr1/tests/string1/test.cpp
  tests/tr1/tests/string2/test.cpp
  tests/tr1/tests/unordered_map/test.cpp
  tests/tr1/tests/unordered_set/test.cpp
  tests/tr1/tests/valarray/test.cpp
  tests/tr1/tests/vector/test.cpp
Labels: test

#1396 Update the <ranges> header unit test
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
Labels: test
