Repository microsoft/STL, pull requests merged in 2020-07, with the labels that each got.

#961 Implement noop_coroutine()
  stl/inc/coroutine
  stl/inc/experimental/coroutine
  stl/inc/experimental/resumable
Labels: cxx20

#795 MSVC <bit>
  stl/inc/bit
  stl/inc/limits
  stl/inc/numeric
  stl/inc/type_traits
  stl/inc/xtr1common
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0553R4_bit_rotating_and_counting_functions/test.cpp
  tests/std/tests/P0556R3_bit_integral_power_of_two_operations/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: cxx20

#904 Implement ranges::fill and ranges::fill_n
  stl/inc/algorithm
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_fill/env.lst
  tests/std/tests/P0896R4_ranges_alg_fill/test.cpp
  tests/std/tests/P0896R4_ranges_alg_fill_n/env.lst
  tests/std/tests/P0896R4_ranges_alg_fill_n/test.cpp
Labels: cxx20

#923 Implement LWG-3070
  stl/inc/filesystem
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: LWG

#930 Implement ranges heap algorithms
  stl/inc/algorithm
  stl/inc/array
  stl/inc/iterator
  stl/inc/xstring
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_heap/env.lst
  tests/std/tests/P0896R4_ranges_alg_heap/test.cpp
Labels: cxx20

#703 constexpr INVOKE and related utilities
  stl/inc/functional
  stl/inc/memory
  stl/inc/type_traits
  stl/inc/yvals_core.h
  tests/std/tests/Dev11_0535636_functional_overhaul/test.cpp
  tests/std/tests/P0356R5_bind_front/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: cxx20

#959 Updates to Ranges test machinery
  tests/std/include/range_algorithm_support.hpp
  tests/std/tests/P0896R4_ranges_alg_adjacent_find/test.cpp
  tests/std/tests/P0896R4_ranges_alg_all_of/test.cpp
  tests/std/tests/P0896R4_ranges_alg_any_of/test.cpp
  tests/std/tests/P0896R4_ranges_alg_binary_search/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy_n/test.cpp
  tests/std/tests/P0896R4_ranges_alg_count/test.cpp
  tests/std/tests/P0896R4_ranges_alg_count_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_equal/test.cpp
  tests/std/tests/P0896R4_ranges_alg_fill/test.cpp
  tests/std/tests/P0896R4_ranges_alg_fill_n/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_end/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_first_of/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_if_not/test.cpp
  tests/std/tests/P0896R4_ranges_alg_for_each/test.cpp
  tests/std/tests/P0896R4_ranges_alg_for_each_n/test.cpp
  tests/std/tests/P0896R4_ranges_alg_is_sorted/test.cpp
  tests/std/tests/P0896R4_ranges_alg_mismatch/test.cpp
  tests/std/tests/P0896R4_ranges_alg_move/test.cpp
  tests/std/tests/P0896R4_ranges_alg_none_of/test.cpp
  tests/std/tests/P0896R4_ranges_alg_swap_ranges/test.cpp
Labels: test

#972 Revert "<chrono>: Cache QueryPerformanceFrequency() and divide just o…
  stl/inc/chrono
  stl/inc/xatomic.h
Labels: bug, high priority

#977 Cleanup `using _Pred` and `using operator<` comments
  stl/inc/algorithm
  stl/inc/execution
  stl/inc/forward_list
  stl/inc/list
  stl/inc/utility
  stl/inc/xutility
Labels: documentation

#978 Code cleanups: remove workarounds, use braces
  stl/inc/algorithm
  stl/inc/memory
  stl/inc/regex
  stl/inc/utility
  stl/inc/vector
  stl/inc/xpolymorphic_allocator.h
  stl/inc/xstring
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: enhancement

#979 Fix ranges test infrastructure
  tests/std/include/range_algorithm_support.hpp
Labels: test

#984 Implement ranges::replace_if
  stl/inc/algorithm
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_replace_if/env.lst
  tests/std/tests/P0896R4_ranges_alg_replace_if/test.cpp
Labels: cxx20

#986 Use new 64-bit interlocked intrinsics on x86
  stl/inc/atomic
Labels: performance

#989 Update _MSVC_STL_UPDATE for July 2020
  stl/inc/yvals_core.h
Labels: enhancement

#999 Style cleanup of requires\s*\(
  stl/inc/concepts
  stl/inc/xutility
  tests/std/include/range_algorithm_support.hpp
  tests/std/tests/P0896R4_P1614R2_comparisons/test.cpp
  tests/std/tests/P0896R4_ranges_algorithm_machinery/test.cpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
Labels: enhancement

#1011 Correct naked `if constexpr` in C++14 mode
  stl/inc/limits
Labels: bug, high priority

#1007 Status Chart improvements
  index.html
Labels: documentation

#1015 Update VM Scale Set to VS 2019 Preview 3
  README.md
  azure-devops/provision-image.ps1
  azure-devops/run-build.yml
  azure-pipelines.yml
Labels: high priority, infrastructure

#1021 feature/spaceship: Merge #1015 (Update VM Scale Set)
  README.md
  azure-devops/provision-image.ps1
  azure-devops/run-build.yml
  azure-pipelines.yml
Labels: spaceship

#1031 Disable /analyze in concepts_matrix.lst
  tests/std/tests/concepts_matrix.lst
Labels: test

#905 Implement ranges::generate and ranges::generate_n
  stl/inc/algorithm
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_generate/env.lst
  tests/std/tests/P0896R4_ranges_alg_generate/test.cpp
  tests/std/tests/P0896R4_ranges_alg_generate_n/env.lst
  tests/std/tests/P0896R4_ranges_alg_generate_n/test.cpp
Labels: cxx20, ranges

#956 Modernize ranges::copy
  stl/inc/algorithm
  tests/std/tests/P0896R4_ranges_alg_copy/test.cpp
Labels: enhancement, ranges

#957 Remove invalid overload of ranges::copy_n
  stl/inc/algorithm
  tests/std/tests/P0896R4_ranges_alg_copy_n/test.cpp
Labels: bug, ranges

#958 Modernize ranges::copy_if
  stl/inc/algorithm
  tests/std/tests/P0896R4_ranges_alg_copy_if/test.cpp
Labels: enhancement, ranges

#970 Modernize ranges::move
  stl/inc/algorithm
  tests/std/include/range_algorithm_support.hpp
  tests/std/tests/P0896R4_ranges_alg_move/test.cpp
Labels: enhancement, ranges

#974 Modernize ranges::count
  stl/inc/algorithm
  tests/std/tests/P0896R4_ranges_alg_count/test.cpp
Labels: enhancement, ranges

#975 Modernize ranges::count_if
  stl/inc/algorithm
  tests/std/tests/P0896R4_ranges_alg_count_if/test.cpp
Labels: enhancement, ranges

#976 Implement most ranges partition algorithms
  stl/inc/algorithm
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_partition/env.lst
  tests/std/tests/P0896R4_ranges_alg_partition/test.cpp
  tests/std/tests/P0896R4_ranges_alg_partition_copy/env.lst
  tests/std/tests/P0896R4_ranges_alg_partition_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_partition_point/env.lst
  tests/std/tests/P0896R4_ranges_alg_partition_point/test.cpp
Labels: cxx20, ranges

#1020 Code cleanup: Brace for impact
  stl/inc/algorithm
  stl/inc/execution
  stl/inc/forward_list
  stl/inc/list
  stl/inc/numeric
  stl/inc/xutility
Labels: enhancement

#1022 Provide comparison operators for map/set/etc. instead of _Tree
  stl/inc/map
  stl/inc/set
  stl/inc/xtree
Labels: enhancement

#983 Implement ranges::replace
  stl/inc/algorithm
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_replace/env.lst
  tests/std/tests/P0896R4_ranges_alg_replace/test.cpp
  tests/std/tests/P0896R4_ranges_alg_replace_copy/env.lst
  tests/std/tests/P0896R4_ranges_alg_replace_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_replace_copy_if/env.lst
  tests/std/tests/P0896R4_ranges_alg_replace_copy_if/test.cpp
Labels: cxx20, ranges

#1034 feature/spaceship: Merge #1022 (tree comparison)
  stl/inc/algorithm
  stl/inc/execution
  stl/inc/forward_list
  stl/inc/list
  stl/inc/map
  stl/inc/numeric
  stl/inc/set
  stl/inc/xtree
  stl/inc/xutility
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy_n/test.cpp
  tests/std/tests/P0896R4_ranges_alg_count/test.cpp
  tests/std/tests/P0896R4_ranges_alg_count_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_generate/env.lst
  tests/std/tests/P0896R4_ranges_alg_generate/test.cpp
  tests/std/tests/P0896R4_ranges_alg_generate_n/env.lst
  tests/std/tests/P0896R4_ranges_alg_generate_n/test.cpp
  tests/std/tests/P0896R4_ranges_alg_move/test.cpp
  tests/std/tests/P0896R4_ranges_alg_partition/env.lst
  tests/std/tests/P0896R4_ranges_alg_partition/test.cpp
  tests/std/tests/P0896R4_ranges_alg_partition_copy/env.lst
  tests/std/tests/P0896R4_ranges_alg_partition_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_partition_point/env.lst
  tests/std/tests/P0896R4_ranges_alg_partition_point/test.cpp
  tests/std/tests/P0896R4_ranges_alg_replace/env.lst
  tests/std/tests/P0896R4_ranges_alg_replace/test.cpp
  tests/std/tests/P0896R4_ranges_alg_replace_copy/env.lst
  tests/std/tests/P0896R4_ranges_alg_replace_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_replace_copy_if/env.lst
  tests/std/tests/P0896R4_ranges_alg_replace_copy_if/test.cpp
  tests/std/tests/concepts_matrix.lst
Labels: spaceship

#1038 Status Chart: Add GitHub PR/issue/bug data
  index.html
Labels: documentation

#941 Implement ranges::transform
  stl/inc/algorithm
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_move/test.cpp
  tests/std/tests/P0896R4_ranges_alg_replace_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_replace_copy_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_transform_binary/env.lst
  tests/std/tests/P0896R4_ranges_alg_transform_binary/test.cpp
  tests/std/tests/P0896R4_ranges_alg_transform_unary/env.lst
  tests/std/tests/P0896R4_ranges_alg_transform_unary/test.cpp
Labels: cxx20, ranges

#1005 Implement ranges::remove family
  stl/inc/algorithm
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_remove/env.lst
  tests/std/tests/P0896R4_ranges_alg_remove/test.cpp
  tests/std/tests/P0896R4_ranges_alg_remove_copy/env.lst
  tests/std/tests/P0896R4_ranges_alg_remove_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_remove_copy_if/env.lst
  tests/std/tests/P0896R4_ranges_alg_remove_copy_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_remove_if/env.lst
  tests/std/tests/P0896R4_ranges_alg_remove_if/test.cpp
Labels: cxx20, ranges

#1010 Use permissive wide-to-narrow transcoding in filesystem_error
  stl/inc/filesystem
  stl/inc/xfilesystem_abi.h
  stl/src/filesystem.cpp
  tests/std/test.lst
  tests/std/tests/GH_001010_filesystem_error_encoding/env.lst
  tests/std/tests/GH_001010_filesystem_error_encoding/test.cpp
Labels: bug

#1026 Implement ranges::copy_backward
  stl/inc/algorithm
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_copy_backward/env.lst
  tests/std/tests/P0896R4_ranges_alg_copy_backward/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_heap/test.cpp
  tests/std/tests/P0896R4_ranges_alg_mismatch/test.cpp
  tests/std/tests/P0896R4_ranges_alg_move/test.cpp
  tests/std/tests/P0896R4_ranges_alg_replace_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_replace_copy_if/test.cpp
  tests/std/tests/P0896R4_ranges_test_machinery/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/std/tests/concepts_matrix.lst
  tests/tr1/include/tspec_random.h
Labels: cxx20, ranges

#1056 Status Chart: Add Combined PR Age and GitHub API script
  .gitignore
  daily_table.js
  gather_stats.js
  index.html
  package-lock.json
  package.json
  weekly_table.js
Labels: documentation

#1028 Implement ranges::reverse
  stl/inc/algorithm
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_reverse/env.lst
  tests/std/tests/P0896R4_ranges_alg_reverse/test.cpp
Labels: cxx20, ranges

#1049 Remove obsolete conditional compilation from <compare>
  stl/inc/compare
  stl/inc/span
  stl/inc/xutility
  tests/std/tests/P0768R1_spaceship_operator/test.cpp
Labels: bug

#1064 feature/spaceship: Merge #1049 (fix <compare> and simplify guards)
  stl/inc/algorithm
  stl/inc/compare
  stl/inc/filesystem
  stl/inc/span
  stl/inc/xfilesystem_abi.h
  stl/inc/xutility
  stl/inc/yvals_core.h
  stl/src/filesystem.cpp
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/GH_001010_filesystem_error_encoding/env.lst
  tests/std/tests/GH_001010_filesystem_error_encoding/test.cpp
  tests/std/tests/P0768R1_spaceship_operator/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy_backward/env.lst
  tests/std/tests/P0896R4_ranges_alg_copy_backward/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_heap/test.cpp
  tests/std/tests/P0896R4_ranges_alg_mismatch/test.cpp
  tests/std/tests/P0896R4_ranges_alg_move/test.cpp
  tests/std/tests/P0896R4_ranges_alg_remove/env.lst
  tests/std/tests/P0896R4_ranges_alg_remove/test.cpp
  tests/std/tests/P0896R4_ranges_alg_remove_copy/env.lst
  tests/std/tests/P0896R4_ranges_alg_remove_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_remove_copy_if/env.lst
  tests/std/tests/P0896R4_ranges_alg_remove_copy_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_remove_if/env.lst
  tests/std/tests/P0896R4_ranges_alg_remove_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_replace_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_replace_copy_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_reverse/env.lst
  tests/std/tests/P0896R4_ranges_alg_reverse/test.cpp
  tests/std/tests/P0896R4_ranges_alg_transform_binary/env.lst
  tests/std/tests/P0896R4_ranges_alg_transform_binary/test.cpp
  tests/std/tests/P0896R4_ranges_alg_transform_unary/env.lst
  tests/std/tests/P0896R4_ranges_alg_transform_unary/test.cpp
  tests/std/tests/P0896R4_ranges_test_machinery/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/std/tests/concepts_matrix.lst
  tests/tr1/include/tspec_random.h
Labels: spaceship

#1016 <system_error> Enable [[msvc::noop_dtor]] from Visual Studio 2019 version 16.8.
  stl/inc/system_error
  stl/src/excptptr.cpp
Labels: performance

#804 Vectorize reverse_copy()
  stl/inc/algorithm
  stl/inc/xutility
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#1025 <random>: Fix discrete_distribution result out of range
  stl/inc/random
  tests/std/test.lst
  tests/std/tests/GH_001017_discrete_distribution_out_of_range/bad_random_engine.hpp
  tests/std/tests/GH_001017_discrete_distribution_out_of_range/env.lst
  tests/std/tests/GH_001017_discrete_distribution_out_of_range/test.cpp
Labels: bug

#1039 Implement ranges::unique family
  stl/inc/algorithm
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_unique/env.lst
  tests/std/tests/P0896R4_ranges_alg_unique/test.cpp
  tests/std/tests/P0896R4_ranges_alg_unique_copy/env.lst
  tests/std/tests/P0896R4_ranges_alg_unique_copy/test.cpp
Labels: cxx20, ranges

#1052 Implement ranges::sample and ranges::shuffle
  stl/inc/algorithm
  stl/inc/random
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_sample/env.lst
  tests/std/tests/P0896R4_ranges_alg_sample/test.cpp
  tests/std/tests/P0896R4_ranges_alg_shuffle/env.lst
  tests/std/tests/P0896R4_ranges_alg_shuffle/test.cpp
Labels: cxx20, ranges

#1058 Modernize the ranges::find family
  stl/inc/algorithm
  tests/std/tests/P0896R4_ranges_alg_find/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_first_of/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_if_not/test.cpp
Labels: enhancement, ranges

#1060 Modernize ranges::for_each
  stl/inc/algorithm
  tests/std/tests/P0896R4_ranges_alg_for_each/test.cpp
  tests/std/tests/P0896R4_ranges_alg_for_each_n/test.cpp
Labels: enhancement, ranges

#1061 Modernize ranges::all_of and friends
  stl/inc/algorithm
  tests/std/tests/P0896R4_ranges_alg_all_of/test.cpp
  tests/std/tests/P0896R4_ranges_alg_any_of/test.cpp
  tests/std/tests/P0896R4_ranges_alg_none_of/test.cpp
Labels: enhancement, ranges

#1075 Update .clang-format for Clang 10
  .clang-format
  stl/src/filesystem.cpp
  tests/std/tests/P0896R4_ranges_alg_is_permutation/test.cpp
  tests/std/tests/P0896R4_ranges_alg_search/test.cpp
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tools/inc/stljobs.h
Labels: enhancement

#1080 _Uglify the current member of move_iterator
  stl/inc/xutility
Labels: bug

#1094 Status Chart: Daily cxx20/LWG stats, GraphQL rewrite
  daily_table.js
  gather_stats.js
  index.html
  package-lock.json
  package.json
  query_prs_and_issues.graphql
  query_total_counts.graphql
  weekly_table.js
Labels: documentation

#1046 feature/spaceship: Clause 22: Containers
  stl/inc/array
  stl/inc/deque
  stl/inc/forward_list
  stl/inc/list
  stl/inc/map
  stl/inc/queue
  stl/inc/set
  stl/inc/stack
  stl/inc/unordered_map
  stl/inc/unordered_set
  stl/inc/utility
  stl/inc/vector
  tests/std/test.lst
  tests/std/tests/Dev11_0135139_vector_bool_comparisons/env.lst
  tests/std/tests/Dev11_0135139_vector_bool_comparisons/test.cpp
  tests/std/tests/Dev11_0135139_vector_bool_equality_perf/test.cpp
  tests/std/tests/P1614R2_spaceship/env.lst
  tests/std/tests/P1614R2_spaceship/test.cpp
Labels: cxx20, spaceship

#1044 Implement Ranges Set Operations
  stl/inc/algorithm
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_includes/env.lst
  tests/std/tests/P0896R4_ranges_alg_includes/test.cpp
  tests/std/tests/P0896R4_ranges_alg_set_difference/env.lst
  tests/std/tests/P0896R4_ranges_alg_set_difference/test.cpp
  tests/std/tests/P0896R4_ranges_alg_set_intersection/env.lst
  tests/std/tests/P0896R4_ranges_alg_set_intersection/test.cpp
  tests/std/tests/P0896R4_ranges_alg_set_symmetric_difference/env.lst
  tests/std/tests/P0896R4_ranges_alg_set_symmetric_difference/test.cpp
  tests/std/tests/P0896R4_ranges_alg_set_union/env.lst
  tests/std/tests/P0896R4_ranges_alg_set_union/test.cpp
  tests/std/tests/P0896R4_ranges_algorithm_machinery/test.cpp
Labels: cxx20, ranges

#1053 Implement ranges::move_backward
  stl/inc/algorithm
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_move_backward/env.lst
  tests/std/tests/P0896R4_ranges_alg_move_backward/test.cpp
Labels: cxx20, ranges

#1091 Fix the interaction between _Pass_fn and invoke
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_algorithm_machinery/test.cpp
Labels: bug, ranges

#1100 Status Chart: Implement Average PR Age
  daily_table.js
  gather_stats.js
  index.html
Labels: documentation

#988 <valarray>: Implement copies for slice_array, gslice_array, mask_array, and indirect_array
  stl/inc/valarray
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/GH_000940_missing_valarray_copy/env.lst
  tests/std/tests/GH_000940_missing_valarray_copy/test.cpp
Labels: bug, high priority

#1048 Finish P0811R3 midpoint and lerp
  stl/inc/cmath
  stl/inc/numeric
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0811R3_midpoint_lerp/env.lst
  tests/std/tests/P0811R3_midpoint_lerp/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: cxx20

#1072 Fix thinko in ranges::iter_swap
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
Labels: bug, ranges

#1073 Implement ranges::rotate and ranges::rotate_copy
  stl/inc/algorithm
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_rotate/env.lst
  tests/std/tests/P0896R4_ranges_alg_rotate/test.cpp
  tests/std/tests/P0896R4_ranges_alg_rotate_copy/env.lst
  tests/std/tests/P0896R4_ranges_alg_rotate_copy/test.cpp
Labels: cxx20, ranges

#1065 Comparison category types become aggregates
  stl/inc/compare
Labels: performance, spaceship
