Repository microsoft/STL, pull requests merged in 2020-09, with the labels that each got.

#1057 Latch, Semaphore, Barrier (part of #52, P1135R6)
  stl/CMakeLists.txt
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/barrier
  stl/inc/latch
  stl/inc/semaphore
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/P1135R6_barrier/env.lst
  tests/std/tests/P1135R6_barrier/test.cpp
  tests/std/tests/P1135R6_latch/env.lst
  tests/std/tests/P1135R6_latch/test.cpp
  tests/std/tests/P1135R6_semaphore/env.lst
  tests/std/tests/P1135R6_semaphore/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
  tests/std/tests/include_each_header_alone_matrix.lst
Labels: cxx20

#1229 Implement views::all and views::reverse
  stl/inc/concepts
  stl/inc/ranges
  stl/inc/xstring
  stl/inc/xutility
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_ranges_subrange/test.cpp
  tests/std/tests/P0896R4_views_all/env.lst
  tests/std/tests/P0896R4_views_all/test.cpp
  tests/std/tests/P0896R4_views_reverse/env.lst
  tests/std/tests/P0896R4_views_reverse/test.cpp
Labels: cxx20, ranges

#1249 Implement non-concepts fallback for coroutine_handle operator<=>
  stl/inc/coroutine
  stl/inc/experimental/generator
  tests/std/tests/VSO_0971246_legacy_await_headers/env.lst
Labels: enhancement

#1180 feature/spaceship: Clause 19: Diagnostics
  stl/inc/system_error
  tests/std/tests/P1614R2_spaceship/env.lst
  tests/std/tests/P1614R2_spaceship/test.cpp
Labels: cxx20, spaceship

#1092 Implement common_iterator
  stl/inc/iterator
  stl/inc/xmemory
  stl/inc/xutility
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_common_iterator/env.lst
  tests/std/tests/P0896R4_common_iterator/test.cpp
  tests/std/tests/P0896R4_common_iterator_death/env.lst
  tests/std/tests/P0896R4_common_iterator_death/test.cpp
Labels: cxx20, ranges

#1160 Use memset and memcmp in a bit more cases
  stl/inc/algorithm
  stl/inc/memory
  stl/inc/xmemory
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_alg_fill/test.cpp
  tests/std/tests/P0896R4_ranges_alg_fill_n/test.cpp
  tests/std/tests/VSO_0180469_fill_family/test.cpp
  tests/std/tests/VSO_0180469_ptr_cat/test.cpp
Labels: bug, performance

#1231 Implement ranges::partial_sort and ranges::partial_sort_copy
  stl/inc/algorithm
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_partial_sort/env.lst
  tests/std/tests/P0896R4_ranges_alg_partial_sort/test.cpp
  tests/std/tests/P0896R4_ranges_alg_partial_sort_copy/env.lst
  tests/std/tests/P0896R4_ranges_alg_partial_sort_copy/test.cpp
Labels: cxx20, ranges

#1241 Cleanup conditional explicit clauses
  stl/inc/utility
Labels: enhancement

#1245 P1391R4 "Range Constructor for string_view"
  stl/inc/xstring
  tests/std/tests/P0220R1_string_view/test.cpp
Labels: cxx20, ranges

#1247 add bound check assertion to valarray::operator[]
  stl/inc/valarray
Labels: bug

#1250 Replace 0 with nullptr where appropriate
  stl/src/cthread.cpp
  stl/src/filesys.cpp
  stl/src/filesystem.cpp
  stl/src/fiopen.cpp
  stl/src/ios.cpp
  stl/src/taskscheduler.cpp
  stl/src/winapisupp.cpp
  stl/src/xstoul.cpp
  stl/src/xstoull.cpp
  stl/src/xstoxflt.cpp
Labels: enhancement

#1252 Implement views::filter
  stl/inc/algorithm
  stl/inc/ranges
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_views_filter/env.lst
  tests/std/tests/P0896R4_views_filter/test.cpp
  tests/std/tests/P0896R4_views_filter_death/env.lst
  tests/std/tests/P0896R4_views_filter_death/test.cpp
Labels: cxx20, high priority, ranges

#1265 Revert "Implement common_iterator (#1092)"
  stl/inc/iterator
  stl/inc/xmemory
  stl/inc/xutility
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_common_iterator/env.lst
  tests/std/tests/P0896R4_common_iterator/test.cpp
  tests/std/tests/P0896R4_common_iterator_death/env.lst
  tests/std/tests/P0896R4_common_iterator_death/test.cpp
Labels: bug, high priority, uncharted

#1253 Implement views::take and views::drop
  stl/inc/iterator
  stl/inc/ranges
  stl/inc/xutility
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_views_drop/env.lst
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_take/env.lst
  tests/std/tests/P0896R4_views_take/test.cpp
Labels: cxx20, high priority, ranges

#1258 Implement views::transform
  stl/inc/ranges
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_views_transform/env.lst
  tests/std/tests/P0896R4_views_transform/test.cpp
  tests/std/tests/P0896R4_views_transform_death/env.lst
  tests/std/tests/P0896R4_views_transform_death/test.cpp
Labels: cxx20, high priority, ranges

#1262 enforce "non-array trivial standard-layout" for string and string_view
  stl/inc/xstring
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: bug

#1251 Status Chart: Add README
  README.md
  daily_table.js
  monthly_table.js
  weekly_table.js
Labels: documentation

#1286 Enable __cpp_lib_concepts for IntelliSense
  stl/inc/yvals_core.h
Labels: enhancement

#1268 Revert "Revert "Implement common_iterator (#1092)" (#1265)"
  stl/inc/iterator
  stl/inc/xmemory
  stl/inc/xutility
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_common_iterator/env.lst
  tests/std/tests/P0896R4_common_iterator/test.cpp
  tests/std/tests/P0896R4_common_iterator_death/env.lst
  tests/std/tests/P0896R4_common_iterator_death/test.cpp
Labels: cxx20, ranges, uncharted

#1271 Integrate P1391 into views::take and views::drop
  stl/inc/ranges
  stl/inc/yvals_core.h
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
Labels: cxx20, ranges

#1272 <yvals_core.h>: Updated _MSVC_STL_UPDATE to September 2020
  stl/inc/yvals_core.h
Labels: enhancement

#1290 VS 2019 16.8 Preview 3 toolset update
  README.md
  azure-pipelines.yml
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: infrastructure

#1297 feature/format: Merge toolset update
  README.md
  azure-pipelines.yml
  stl/inc/iterator
  stl/inc/ranges
  stl/inc/xmemory
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_common_iterator/env.lst
  tests/std/tests/P0896R4_common_iterator/test.cpp
  tests/std/tests/P0896R4_common_iterator_death/env.lst
  tests/std/tests/P0896R4_common_iterator_death/test.cpp
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
Labels: infrastructure, uncharted

#1308 Status Chart: Post-CppCon update
  README.md
  daily_table.js
  package-lock.json
  package.json
  weekly_table.js
Labels: documentation, uncharted

#1232 feature/format arg_id parsing, align parsing, width parsing, skeleton classes
  stl/CMakeLists.txt
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/format
  tests/std/test.lst
  tests/std/tests/P0645R10_text_formatting_parse_contexts/env.lst
  tests/std/tests/P0645R10_text_formatting_parse_contexts/test.cpp
  tests/std/tests/P0645R10_text_formatting_parsing/env.lst
  tests/std/tests/P0645R10_text_formatting_parsing/test.cpp
  tests/std/tests/include_each_header_alone_matrix.lst
Labels: cxx20

#1313 Minimal changes to support constexpr allocation in MSVC
  stl/inc/memory
  stl/inc/xmemory
  stl/inc/yvals_core.h
  tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
  tests/std/tests/P0896R4_ranges_alg_uninitialized_move/test.cpp
Labels: cxx20, ranges

#1196 Implement <stop_token> and jthread.
  stl/CMakeLists.txt
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/atomic
  stl/inc/condition_variable
  stl/inc/memory
  stl/inc/stop_token
  stl/inc/thread
  stl/inc/yvals_core.h
  tests/std/include/new_counter.hpp
  tests/std/test.lst
  tests/std/tests/P0660R10_jthread_and_cv_any/env.lst
  tests/std/tests/P0660R10_jthread_and_cv_any/test.cpp
  tests/std/tests/P0660R10_stop_token/env.lst
  tests/std/tests/P0660R10_stop_token/test.cpp
  tests/std/tests/P0660R10_stop_token_death/env.lst
  tests/std/tests/P0660R10_stop_token_death/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
  tests/std/tests/include_each_header_alone_matrix.lst
Labels: cxx20

#1278 Use constexpr is_sorted, add charconv tests, update comments
  stl/inc/execution
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0067R5_charconv/double_general_precision_to_chars_test_cases.hpp
  tests/std/tests/P0067R5_charconv/double_scientific_precision_to_chars_test_cases_1.hpp
  tools/parallelize/parallelize.cpp
Labels: documentation, enhancement, test

#1282 Account for C++17 deferred temporary materialization in invocable_r
  stl/inc/type_traits
  tests/std/tests/VSO_0105317_expression_sfinae/test.cpp
Labels: bug

#1291 Fix 2 VS 16.8p3 blocked issues
  tests/libcxx/expected_results.txt
  tests/std/tests/P0896R4_P1614R2_comparisons/test.cpp
Labels: test

#1303 _Ty -> _TVal for atomic_ref, one missed occurrence
  stl/inc/atomic
  tests/std/tests/P0019R8_atomic_ref/test.cpp
Labels: bug

#1306 enable std::assume_aligned
  stl/inc/memory
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P1007R3_assume_aligned/env.lst
  tests/std/tests/P1007R3_assume_aligned/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: cxx20

#1294 <complex>: prevent invalid conversions
  stl/inc/complex
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: bug

#1314 mark `memory_resource` dtor as `default` to enable constant destruction of `memory_resource`
  stl/inc/xpolymorphic_allocator.h
Labels: bug

#1318 XFG: made _Execute_once XFG-compatible.
  stl/src/xonce.cpp
Labels: enhancement

#1194 Remove XP (and Server 2003) support from STL
  stl/CMakeLists.txt
  stl/msbuild/stl_base/msvcp.settings.targets
  stl/src/StlCompareStringA.cpp
  stl/src/StlCompareStringW.cpp
  stl/src/StlLCMapStringA.cpp
  stl/src/StlLCMapStringW.cpp
  stl/src/awint.hpp
  stl/src/filesys.cpp
  stl/src/filesystem.cpp
  stl/src/primitives.hpp
  stl/src/taskscheduler.cpp
  stl/src/winapinls.cpp
  stl/src/winapisupp.cpp
  stl/src/xalloc.cpp
  stl/src/xdateord.cpp
  stl/src/xmtx.cpp
  stl/src/xonce.cpp
Labels: performance

#1285 <filesystem>: create_directories() throw for empty paths
  stl/inc/filesystem
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: bug

#1311 Implement polymorphic_allocator<>
  stl/inc/xpolymorphic_allocator.h
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P0339R6_polymorphic_allocator/env.lst
  tests/std/tests/P0339R6_polymorphic_allocator/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: cxx20

#1316 Accept 80-bit long double in <complex>
  stl/inc/complex
Labels: bug

#1322 Status Chart: Weekly update
  daily_table.js
  weekly_table.js
Labels: documentation, uncharted
