Repository microsoft/STL, pull requests merged in 2020-02, with the labels that each got.

#481 syserror.cpp: Use range-for #479
  stl/src/syserror.cpp
Labels: enhancement

#401 Fix #379: <complex>: asinh(-1e+307 + 2e+307i) is wrong
  stl/inc/complex
Labels: bug

#457 Reduce memory consumption of system_category().message()
  stl/CMakeLists.txt
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/__msvc_system_error_abi.hpp
  stl/inc/system_error
  stl/msbuild/stl_base/stl.files.settings.targets
  stl/src/syserror.cpp
  stl/src/syserror_import_lib.cpp
Labels: performance

#487 Changed macro constants to constexpr variables #270
  stl/src/filesys.cpp
  stl/src/ios.cpp
  stl/src/iosptrs.cpp
  stl/src/xlock.cpp
  stl/src/xnotify.cpp
  stl/src/xstoflt.cpp
  stl/src/xstoul.cpp
  stl/src/xstoull.cpp
  stl/src/xstoxflt.cpp
  stl/src/xtime.cpp
  stl/src/xwstoflt.cpp
  stl/src/xwstoxfl.cpp
Labels: enhancement

#385 <compare>,<functional> Concept-constrained comparisons
  stl/inc/algorithm
  stl/inc/compare
  stl/inc/concepts
  stl/inc/functional
  stl/inc/memory
  stl/inc/utility
  stl/inc/xstddef
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/P0896R4_P1614R2_comparisons/env.lst
  tests/std/tests/P0896R4_P1614R2_comparisons/test.cpp
Labels: cxx20

#482 Reduce the amount of content included by <array>
  stl/inc/algorithm
  stl/inc/array
  stl/inc/charconv
  stl/inc/deque
  stl/inc/execution
  stl/inc/forward_list
  stl/inc/fstream
  stl/inc/functional
  stl/inc/iterator
  stl/inc/list
  stl/inc/memory_resource
  stl/inc/numeric
  stl/inc/sstream
  stl/inc/utility
  stl/inc/vector
  stl/inc/xhash
  stl/inc/xlocale
  stl/inc/xlocinfo
  stl/inc/xmemory
  stl/inc/xstring
  stl/inc/xtree
  stl/inc/xutility
  stl/src/excptptr.cpp
Labels: throughput

#501 <memory> construct_at()
  stl/inc/memory
  tests/std/test.lst
  tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/env.lst
  tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
Labels: cxx20

#497 Fix construct tag
  stl/inc/codecvt
  stl/inc/cvt/one_one
  stl/inc/cvt/utf16
  stl/inc/deque
  stl/inc/execution
  stl/inc/forward_list
  stl/inc/functional
  stl/inc/list
  stl/inc/memory
  stl/inc/regex
  stl/inc/scoped_allocator
  stl/inc/tuple
  stl/inc/type_traits
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/xstring
  stl/inc/xtree
  stl/inc/xutility
  stl/src/memory_resource.cpp
  stl/src/xsinh.cpp
Labels: enhancement

#512 concepts: Implement resolution to LWG-3329
  stl/inc/concepts
Labels: LWG

#548 span: Implement resolution to LWG-3320
  stl/inc/span
  tests/libcxx/skipped_tests.txt
  tests/std/tests/Dev10_709168_marking_iterators_as_checked/test.cpp
  tests/std/tests/Dev11_0000000_null_forward_iterators/test.cpp
  tests/std/tests/P0122R7_span/test.cpp
Labels: LWG

#550 Refactored declaring multiple variables on a single line
  stl/inc/cvt/wbuffer
  stl/inc/iostream
  stl/inc/random
  stl/inc/xiosbase
  stl/inc/ymath.h
  stl/src/filesys.cpp
  stl/src/xstol.cpp
  stl/src/xstoll.cpp
  stl/src/xstoul.cpp
  stl/src/xstoull.cpp
  stl/src/xxxprec.h
Labels: enhancement

#566 Return size_type for erase()/erase_if()
  stl/inc/deque
  stl/inc/forward_list
  stl/inc/list
  stl/inc/map
  stl/inc/set
  stl/inc/unordered_map
  stl/inc/unordered_set
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/xstring
  stl/inc/yvals_core.h
  tests/libcxx/skipped_tests.txt
  tests/std/tests/Dev11_0000000_user_defined_literals/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: cxx20

#567 Adopt LWG-3390
  stl/inc/xutility
Labels: LWG

#568 <xutility>: remove LWG issue comment
  stl/inc/xutility
Labels: documentation

#569 detect Perl code as Perl instead of Raku
  .gitattributes
Labels: documentation
