Repository microsoft/STL, pull requests merged in 2020-06, with the labels that each got.

#685 Fix not unlocking and relocking in condition_variable_any::wait_for
  stl/inc/condition_variable
  stl/inc/mutex
  stl/inc/xthreads.h
  stl/src/cond.cpp
  stl/src/mutex.cpp
  tests/std/test.lst
  tests/std/tests/GH_000685_condition_variable_any/env.lst
  tests/std/tests/GH_000685_condition_variable_any/test.cpp
  tests/tr1/tests/chrono/test.cpp
  tests/tr1/tests/condition_variable/test.cpp
  tests/tr1/tests/ratio/test.cpp
  tests/tr1/tests/thread/test.cpp
Labels: bug, high priority

#875 Rework test_range/test_iterator Ranges test machinery
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy_n/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_first_of/test.cpp
  tests/std/tests/P0896R4_ranges_alg_for_each_n/test.cpp
  tests/std/tests/P0896R4_ranges_subrange/test.cpp
  tests/std/tests/P0896R4_ranges_test_machinery/env.lst
  tests/std/tests/P0896R4_ranges_test_machinery/test.cpp
Labels: test

#878 <optional>: Don't zero storage in default constructor
  stl/inc/optional
Labels: performance

#881 The problem with Clang's tgmath.h is now tracked as LLVM-46207
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: documentation

#894 Library support for C++20 coroutines
  stl/CMakeLists.txt
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/coroutine
  stl/inc/experimental/generator
  stl/inc/experimental/resumable
  stl/inc/yvals_core.h
  tests/std/tests/VSO_0971246_legacy_await_headers/env.lst
  tests/std/tests/include_each_header_alone_matrix.lst
Labels: cxx20

#851 Update VMSS pool to one with vs16.7p2
  azure-devops/provision-image.ps1
  azure-pipelines.yml
Labels: high priority, infrastructure

#888 <algorithm>: Implemented ranges::move
  stl/inc/algorithm
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_move/env.lst
  tests/std/tests/P0896R4_ranges_alg_move/test.cpp
Labels: cxx20

#897 Updated _MSVC_STL_UPDATE macro
  stl/inc/yvals_core.h
Labels: enhancement

#899 Cleanup ranges test machinery
  tests/std/include/range_algorithm_support.hpp
  tests/std/tests/P0896R4_ranges_subrange/test.cpp
  tests/std/tests/P0896R4_ranges_test_machinery/test.cpp
Labels: test

#900 Code cleanups in stl/src
  stl/src/awint.h
  stl/src/cout.cpp
  stl/src/fiopen.cpp
  stl/src/iosptrs.cpp
  stl/src/iostream.cpp
  stl/src/locale.cpp
  stl/src/locale0.cpp
  stl/src/mpiostream.cpp
  stl/src/stdthrow.cpp
  stl/src/ushiostr.cpp
  stl/src/wcout.cpp
  stl/src/winapinls.cpp
  stl/src/winapisupp.cpp
  stl/src/wiostrea.cpp
  stl/src/wlocale.cpp
  stl/src/xgetwctype.cpp
  stl/src/xlocale.cpp
Labels: enhancement

#901 Implement ranges::_Ubegin and ranges::_Uend CPOs
  stl/inc/algorithm
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
Labels: enhancement

#906 tests: Avoid dialog boxes, prevent stdout from being lost
  tests/std/include/force_include.hpp
  tests/std/tests/P0024R2_parallel_algorithms_set_difference/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_set_intersection/test.cpp
  tests/std/tests/P0067R5_charconv/test.cpp
  tests/std/tests/P0218R1_filesystem/test.cpp
  tests/std/tests/P0220R1_searchers/test.cpp
  tests/std/tests/include_each_header_alone_matrix.lst
  tests/std/tests/prefix.lst
  tests/tr1/lit.site.cfg.in
  tests/tr1/prefix.lst
Labels: test

#852 P0896R4_P1614R2_comparisons/test.cpp: Increase test coverage for MSVC
  tests/std/tests/P0896R4_P1614R2_comparisons/test.cpp
Labels: test

#877 [span] Make span standard_layout
  stl/inc/span
  tests/std/tests/P0122R7_span/test.cpp
Labels: enhancement

#903 Remove pow(floating, int) overloads
  stl/inc/cmath
  tests/std/test.lst
  tests/std/tests/GH_000890_pow_template/env.lst
  tests/std/tests/GH_000890_pow_template/test.cpp
  tests/std/tests/VSO_0099869_pow_float_overflow/test.cpp
Labels: bug

#911 Require VS 2019 16.7 Preview 2 or later
  README.md
  stl/inc/yvals_core.h
Labels: enhancement

#896 Implement ranges::search
  stl/inc/algorithm
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_find_end/test.cpp
  tests/std/tests/P0896R4_ranges_alg_search/env.lst
  tests/std/tests/P0896R4_ranges_alg_search/test.cpp
Labels: cxx20

#884 LWG-2597 std::log misspecified for complex numbers
  stl/inc/complex
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/LWG2597_complex_branch_cut/env.lst
  tests/std/tests/LWG2597_complex_branch_cut/test.cpp
Labels: LWG

#925 Implement std::permutable and std::sortable
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_algorithm_machinery/test.cpp
Labels: cxx20

#915 Implement ranges::is_sorted and ranges::is_sorted_until
  stl/inc/algorithm
  stl/inc/xutility
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_all_of/test.cpp
  tests/std/tests/P0896R4_ranges_alg_any_of/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy_n/test.cpp
  tests/std/tests/P0896R4_ranges_alg_count/test.cpp
  tests/std/tests/P0896R4_ranges_alg_count_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_equal/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_first_of/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_if_not/test.cpp
  tests/std/tests/P0896R4_ranges_alg_for_each/test.cpp
  tests/std/tests/P0896R4_ranges_alg_for_each_n/test.cpp
  tests/std/tests/P0896R4_ranges_alg_is_sorted/env.lst
  tests/std/tests/P0896R4_ranges_alg_is_sorted/test.cpp
  tests/std/tests/P0896R4_ranges_alg_mismatch/test.cpp
  tests/std/tests/P0896R4_ranges_alg_move/test.cpp
  tests/std/tests/P0896R4_ranges_alg_none_of/test.cpp
  tests/std/tests/P0896R4_ranges_test_machinery/test.cpp
Labels: cxx20

#694 #651, for 64 bit type on x86 __iso_volatile_store64
  stl/inc/atomic
  stl/inc/chrono
  stl/inc/memory
  stl/inc/xatomic.h
Labels: performance

#914 Implement ranges::search_n
  stl/inc/algorithm
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_search_n/env.lst
  tests/std/tests/P0896R4_ranges_alg_search_n/test.cpp
Labels: cxx20

#916 Implement ranges min/max/minmax algorithms
  stl/inc/algorithm
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_minmax/env.lst
  tests/std/tests/P0896R4_ranges_alg_minmax/test.cpp
  tests/std/tests/P0896R4_ranges_algorithm_machinery/test.cpp
Labels: cxx20

#917 Implement the "binary search" ranges algorithm family
  stl/inc/algorithm
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_binary_search/env.lst
  tests/std/tests/P0896R4_ranges_alg_binary_search/test.cpp
Labels: cxx20

#920 Cleanup: remove unneeded [[maybe_unused]] annotations
  stl/inc/algorithm
  stl/inc/xutility
Labels: enhancement

#936 update cgmanifest.json
  docs/cgmanifest.json
Labels: documentation
