Repository microsoft/STL, pull requests merged in 2020-04, with the labels that each got.

#646 <chrono>: Cache QueryPerformanceFrequency()
  stl/src/xtime.cpp
Labels: performance

#640 lerp() noexcept is now required, so we should remove comments
  stl/inc/cmath
Labels: documentation

#649 Changing VCLIBS_SUFFIX to be a cache CMake variable
  CMakeLists.txt
Labels: enhancement, infrastructure

#650 Add static_assert to is_sorted() for the lookup tables in validate.cpp
  tools/CMakeLists.txt
  tools/validate/validate.cpp
Labels: enhancement, infrastructure

#672 Disable warning C4648 'standard attribute 'meow' is ignored'
  stl/inc/yvals_core.h
Labels: enhancement

#644 Update pull request template for tests-in-Azure infrastructure
  .github/pull_request_template.md
Labels: documentation

#662 Replace __pragma with _Pragma
  stl/inc/yvals_core.h
Labels: enhancement

#675 Revert "Replace __pragma with _Pragma (#662)"
  stl/inc/yvals_core.h
Labels: bug

#676 Updated _MSVC_STL_UPDATE to April 2020
  stl/inc/yvals_core.h
Labels: enhancement

#671 <bitset>: Make bitset::all work like bitset::any
  stl/inc/bitset
Labels: performance

#692 Library support for P0722R3 - Efficient sized delete for variable siz…
  stl/inc/new
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: cxx20

#309 make_shared() For Arrays
  stl/inc/memory
  stl/inc/yvals_core.h
  tests/std/tests/P0674R1_make_shared_for_arrays/env.lst
  tests/std/tests/P0674R1_make_shared_for_arrays/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
  tests/tr1/test.lst
Labels: cxx20

#682 Run format validation as its own stage and enable /BE
  azure-devops/create-new-agent-image.ps1
  azure-devops/provision-image.ps1
  azure-devops/run-build.yml
  azure-devops/sysprep.ps1
  azure-pipelines.yml
  tests/std/expected_results.txt
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
  tests/utils/stl/test/config.py
  tests/utils/stl/util.py
Labels: infrastructure, test

#695 <yvals_core.h>: Fix <bit> feature-test macros
  stl/inc/yvals_core.h
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: bug

#601 Implement P0718R2 atomic<shared_ptr<T>>, atomic<weak_ptr<T>>
  stl/inc/memory
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/Dev11_1066589_shared_ptr_atomic_deadlock/test.cpp
  tests/std/tests/P0718R2_atomic_smart_ptrs/env.lst
  tests/std/tests/P0718R2_atomic_smart_ptrs/test.cpp
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
  tests/tr1/tests/atomic4/test.cpp
Labels: cxx20

#699 validate.cpp: Validate paths for length and spaces
  tools/validate/validate.cpp
Labels: infrastructure

#657 More Clang 10 support
  stl/inc/concepts
  tests/std/include/range_algorithm_support.hpp
  tests/std/tests/P0896R4_ranges_alg_all_of/test.cpp
  tests/std/tests/native_latest_matrix.lst
  tests/std/tests/usual_latest_matrix.lst
  tests/std/tests/usual_latest_winsdk_matrix.lst
Labels: test

#681 Update FixNamespaceComments to true in various clang-format files
  .clang-format
  stl/inc/xutility
  stl/src/excptptr.cpp
  stl/src/winapisupp.cpp
  tests/std/include/input_iterator.hpp
  tests/std/include/instantiate_algorithms.hpp
  tests/std/include/range_algorithm_support.hpp
  tests/std/tests/Dev11_0483851_vector_debug_allocator_use/test.cpp
  tests/std/tests/Dev11_0535636_functional_overhaul/test.cpp
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P0092R1_polishing_chrono/test.cpp
  tests/std/tests/P0220R1_any/test.cpp
  tests/std/tests/P0220R1_sample/adapterator.hpp
  tests/std/tests/P0220R1_sample/test.cpp
  tests/std/tests/P0896R4_ranges_algorithm_machinery/test.cpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/std/tests/VSO_0000000_fancy_pointers/test.cpp
  tests/std/tests/VSO_0000000_instantiate_containers/test.cpp
  tests/std/tests/VSO_0000000_instantiate_type_traits/test.cpp
  tests/std/tests/VSO_0000000_type_traits/test.cpp
  tests/std/tests/VSO_0121440_is_iterator_iterator_traits/test.cpp
  tests/std/tests/VSO_0180466_algorithm_overhauls/test.cpp
  tests/std/tests/VSO_0224478_scoped_allocator/test.cpp
  tests/std/tests/VSO_0961751_hash_range_erase/test.cpp
Labels: documentation

#658 <chrono>: Explain steady_clock::now frequency scaling
  stl/inc/chrono
Labels: documentation

#665 <numeric> Optimize gcd to use builtins
  stl/inc/bit
  stl/inc/limits
  stl/inc/numeric
Labels: performance

#687 Add a Question issue template
  .github/ISSUE_TEMPLATE/cxx20-feature.md
  .github/ISSUE_TEMPLATE/question.md
Labels: documentation

#708 Require MSVC 19.26 and Clang 10 in the STL
  stl/inc/execution
  stl/inc/scoped_allocator
  stl/inc/xmemory
  stl/inc/xpolymorphic_allocator.h
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0595R2_is_constant_evaluated/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
  tests/std/tests/concepts_matrix.lst
  tests/std/tests/native_winsdk_matrix.lst
  tests/std/tests/usual_17_winsdk_matrix.lst
  tests/std/tests/usual_latest_winsdk_matrix.lst
  tests/std/tests/usual_winsdk_matrix.lst
  tests/tr1/tests/ciso646/test.cpp
Labels: enhancement

#701 Use the temp disk
  azure-devops/run-build.yml
  tests/utils/stl/test/format.py
Labels: infrastructure

#712 Point TMP to the D drive
  azure-devops/run-build.yml
  azure-pipelines.yml
Labels: infrastructure

#724 Fix boyer_moore_searcher with the Rytter correction
  stl/inc/functional
  tests/std/tests/P0220R1_searchers/test.cpp
Labels: bug, high priority

#730 Suppress C5219 in the STL
  stl/inc/xhash
  stl/src/special_math.cpp
  tests/std/tests/VSO_0792651_unordered_set_rehash_invalidates_key/test.cpp
  tests/tr1/include/tdefs.h
  tests/tr1/tests/unordered_map/test.cpp
  tests/tr1/tests/unordered_set/test.cpp
Labels: bug

#634 Deprecate Volatile
  stl/inc/atomic
  stl/inc/utility
  stl/inc/variant
  stl/inc/yvals_core.h
  tests/std/tests/Dev11_0863628_atomic_compare_exchange/test.cpp
Labels: cxx20

#698 <functional>: std::function doesn't handle over-aligned types
  stl/inc/functional
  tests/std/test.lst
  tests/std/tests/GH_000690_overaligned_function/env.lst
  tests/std/tests/GH_000690_overaligned_function/test.cpp
Labels: bug

#709 Refactored some `for` loops to normal pattern.
  stl/inc/random
  stl/inc/valarray
  stl/inc/yvals_core.h
  stl/src/ios.cpp
Labels: enhancement

#723 <atomic>: removing _ENABLE_ATOMIC_ALIGNMENT_FIX
  stl/inc/atomic
  tests/std/tests/Dev11_0863628_atomic_compare_exchange/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_is_sorted/test.cpp
  tests/tr1/tests/atomic/test.cpp
Labels: enhancement

#733 remove EDG related workaround related to bit_cast
  stl/inc/bit
  stl/inc/yvals_core.h
  tests/std/tests/P0476R2_bit_cast/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: enhancement

#735 Remove _ITERATOR_DEBUG_ARRAY_OVERLOADS
  stl/inc/algorithm
  stl/inc/array
  stl/inc/execution
  stl/inc/memory
  stl/inc/numeric
  stl/inc/regex
  stl/inc/xmemory
  stl/inc/xutility
  stl/inc/yvals.h
  tests/std/include/instantiate_algorithms.hpp
  tests/std/tests/Dev11_0000000_dual_range_algorithms/test.cpp
  tests/std/tests/VSO_0000000_regex_interface/test.cpp
  tests/std/tests/VSO_0180466_algorithm_overhauls/test.cpp
Labels: throughput

#737 Silence Clang -Wc++20-extensions
  stl/inc/yvals_core.h
Labels: enhancement

#734 Implement ranges::subrange and ranges::view_interface
  stl/inc/xutility
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_algorithm_machinery/test.cpp
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_ranges_subrange/env.lst
  tests/std/tests/P0896R4_ranges_subrange/test.cpp
Labels: cxx20

#752 Remove compiler specific feature test macro tests
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: test

#367 <complex> Implement p0415r1
  stl/inc/charconv
  stl/inc/complex
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/P0415R1_constexpr_complex/env.lst
  tests/std/tests/P0415R1_constexpr_complex/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: cxx20

#742 Remove and update compiler bug workarounds
  stl/inc/charconv
  stl/inc/execution
  stl/inc/functional
  stl/inc/memory
  stl/inc/numeric
  stl/inc/random
  stl/inc/tuple
  stl/inc/variant
  stl/inc/xlocale
  stl/inc/xmemory
  stl/inc/xsmf_control.h
  stl/inc/xtree
  stl/inc/xutility
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/Dev11_0000000_tuple_cat/test.cpp
  tests/std/tests/P0083R3_splicing_maps_and_sets/test.cpp
  tests/std/tests/P0896R4_P1614R2_comparisons/test.cpp
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
Labels: enhancement

#743 Spelling
  stl/inc/experimental/filesystem
  stl/src/xmbtowc.cpp
  tests/std/tests/Dev08_496675_iostream_int_reading/test.cpp
  tests/std/tests/Dev11_0000000_user_defined_literals/test.cpp
  tests/std/tests/P0220R1_optional/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/std/tests/VSO_0000000_type_traits/test.cpp
  tests/utils/stl/test/config.py
Labels: enhancement

#746 N4861 is the post-Prague Working Paper
  README.md
Labels: documentation

#755 Clang warnings cleanup
  stl/inc/algorithm
  stl/inc/cvt/one_one
  stl/inc/cvt/sjis_0208
  stl/inc/exception
  stl/inc/execution
  stl/inc/random
  stl/inc/tuple
  stl/inc/type_traits
  stl/inc/vector
  stl/inc/xutility
  stl/inc/yvals.h
  tests/std/tests/Dev11_0316853_find_memchr_optimization/test.cpp
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/include_each_header_alone_matrix.lst
  tests/tr1/include/tfuns.h
  tests/tr1/tests/cvt/sjis_0208/test.cpp
  tests/utils/stl/test/config.py
Labels: enhancement

#764 Improve build instructions and cleanup code
  README.md
  stl/inc/experimental/filesystem
  stl/inc/filesystem
  stl/inc/functional
  stl/inc/future
  stl/inc/mutex
  stl/inc/stdexcept
  stl/inc/system_error
  stl/inc/tuple
  stl/inc/typeinfo
  stl/inc/xiosbase
  stl/inc/yvals.h
  stl/src/_tolower.cpp
  stl/src/_toupper.cpp
  stl/src/cthread.cpp
  stl/src/dllmain.cpp
  stl/src/filesys.cpp
  stl/src/ppltasks.cpp
  stl/src/xstrcoll.cpp
  stl/src/xstrxfrm.cpp
  stl/src/xwcscoll.cpp
  stl/src/xwcsxfrm.cpp
  stl/src/xwctomb.cpp
  tests/std/tests/Dev11_0437519_container_behavior/test.cpp
  tests/tr1/tests/chrono/test.cpp
  tests/tr1/tests/random1/test.cpp
  tools/validate/validate.cpp
Labels: documentation, enhancement

#740 Optimize `atomic_thread_fence`
  stl/inc/atomic
Labels: performance

#765 __cpp_consteval indicates support for consteval
  stl/inc/yvals_core.h
Labels: bug

#760 Remove _For_each_tuple_element in scoped_lock
  stl/inc/mutex
  stl/inc/tuple
  tests/std/tests/VSO_0000000_instantiate_containers/test.cpp
Labels: enhancement

#768 Silence Clang warning in <variant>
  stl/inc/variant
Labels: bug
