Repository microsoft/STL, pull requests merged in 2020-12, with the labels that each got.

#1442 Code cleanups: Unify _Float_traits and _Floating_type_traits
  stl/inc/complex
  stl/inc/strstream
  stl/inc/typeinfo
  stl/inc/xlocnum
  stl/inc/xstring
  stl/inc/xutility
  stl/inc/yvals_core.h
  stl/src/cond.cpp
  stl/src/mutex.cpp
  tests/std/tests/GH_000935_complex_numerical_accuracy/floating_point_utils.hpp
  tests/std/tests/P0092R1_polishing_chrono/test.cpp
  tests/std/tests/P0513R0_poisoning_the_hash/test.cpp
  tests/std/tests/P0896R4_istream_view/test.cpp
  tests/std/tests/P0896R4_views_take_while/test.cpp
  tests/std/tests/VSO_0000000_type_traits/test.cpp
  tests/std/tests/VSO_0180469_ptr_cat/test.compile.pass.cpp
  tests/tr1/tests/filesystem1/test.cpp
Labels: enhancement

#1506 Status Chart: Weekly update
  daily_table.js
  monthly_table.js
  package-lock.json
  package.json
  weekly_table.js
Labels: documentation, uncharted

#1460 LWG-3211 std::tuple<> should be trivially constructible
  stl/inc/tuple
  tests/std/tests/Dev11_0000000_tuple_cat/test.cpp
Labels: LWG

#1474 _NODISCARD for function objects
  stl/inc/compare
  stl/inc/functional
  stl/inc/xstddef
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
Labels: enhancement

#1475 <compare>: Improve floating-point spaceship CPO codegen
  stl/inc/compare
  tests/std/tests/P0768R1_spaceship_cpos/test.cpp
Labels: performance

#1476 Correct member comment for _List_val::_Sort.
  stl/inc/list
Labels: documentation

#1501 LWG-3170 is_always_equal added to std::allocator makes the standard library treat derived types as always equal
  stl/inc/xmemory
Labels: LWG

#1452 LWG-3460 Unimplementable noop_coroutine_handle guarantees
  stl/inc/coroutine
  tests/std/tests/P0912R5_coroutine/test.cpp
Labels: LWG

#1495 [[nodiscard]] for constructors
  stl/inc/atomic
  stl/inc/condition_variable
  stl/inc/memory
  stl/inc/mutex
  stl/inc/shared_mutex
  stl/inc/thread
  stl/inc/xhash
  stl/inc/xlocale
  stl/inc/xmemory
  stl/inc/yvals_core.h
  stl/src/atomic_wait.cpp
Labels: cxx20

#1496 valarray: Fix delete in order to satisfy ASan
  stl/inc/valarray
Labels: bug

#1507 Add a pragma comment to pull in the synchronization lib
  stl/src/atomic_wait.cpp
Labels: ARM, ARM64, bug

#1510 Correct overly-strengthened noexcept-specifier for basic_string_view constructor
  stl/inc/xstring
Labels: bug

#1455 LWG-3036 polymorphic_allocator::destroy is extraneous
  stl/inc/xpolymorphic_allocator.h
  stl/inc/yvals_core.h
  tests/std/tests/P0220R1_polymorphic_memory_resources/test.cpp
Labels: LWG

#1458 LWG-3448 transform_view's sentinel<false> not comparable with iterator<true>
  stl/inc/ranges
  tests/std/tests/P0896R4_views_transform/test.cpp
Labels: LWG, ranges

#1483 LWG-3464 istream::gcount() can overflow
  stl/inc/istream
Labels: LWG

#1490 Add _STD to improve tuple throughput
  stl/inc/tuple
Labels: throughput

#1493 LWG-3117 Missing packaged_task deduction guides
  stl/inc/future
  tests/std/tests/P0433R2_deduction_guides/test.cpp
Labels: LWG

#1494 <regex>: Follow the Standard in regex_traits::transform()
  stl/inc/regex
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: bug

#1500 Allow atomic_ref<const T>
  stl/inc/atomic
  tests/std/tests/P0019R8_atomic_ref/test.cpp
Labels: bug

#1509 Rewrite InterlockedExchange128_nf with intrinsics on clang
  stl/inc/atomic
Labels: ARM64, bug

#1514 Allow discarding unique_lock and shared_lock
  stl/inc/mutex
  stl/inc/shared_mutex
  tests/std/tests/VSO_0226079_mutex/test.cpp
Labels: bug, high priority

#1515 Port internal stl/msbuild changes
  stl/msbuild/stl_1/msvcp_1.settings.targets
  stl/msbuild/stl_2/msvcp_2.settings.targets
  stl/msbuild/stl_atomic_wait/msvcp_atomic_wait.settings.targets
  stl/msbuild/stl_base/msvcp.settings.targets
  stl/msbuild/stl_codecvt_ids/msvcp_codecvt_ids.settings.targets
Labels: infrastructure

#1517 Status Chart: Weekly update
  daily_table.js
  weekly_table.js
Labels: documentation, uncharted

#1522 silence future "unused capture" warning
  tests/std/tests/Dev11_0748972_function_crash_out_of_memory/test.cpp
Labels: test

#1513 Minimize the size of clones in the CI
  azure-devops/run-build.yml
  azure-pipelines.yml
Labels: infrastructure

#1457 Implement resolution of LWG-3449 for take_view
  stl/inc/ranges
  tests/std/tests/P0896R4_views_take/test.cpp
Labels: LWG, ranges

#1503 <regex>: Fixes regex character class case insensitive search problem
  stl/inc/regex
  tests/std/include/test_regex_support.hpp
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: bug

#1519 Add an nvcc test which compiles all the headers at once
  tests/std/CMakeLists.txt
  tests/std/lit.site.cfg.in
  tests/std/tests/GH_000639_nvcc_include_all/env.lst
  tests/std/tests/GH_000639_nvcc_include_all/test.compile.pass.cpp
  tests/tr1/CMakeLists.txt
  tests/tr1/lit.site.cfg.in
  tests/utils/stl/test/config.py
  tests/utils/stl/test/format.py
  tests/utils/stl/test/tests.py
Labels: test

#1529 Build header units in parallel
  tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
  tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
Labels: test

#1536 feature/format: Merge CI update
  azure-devops/run-build.yml
  azure-pipelines.yml
  stl/inc/ranges
  stl/inc/regex
  tests/std/CMakeLists.txt
  tests/std/include/test_regex_support.hpp
  tests/std/lit.site.cfg.in
  tests/std/tests/Dev11_0748972_function_crash_out_of_memory/test.cpp
  tests/std/tests/GH_000639_nvcc_include_all/env.lst
  tests/std/tests/GH_000639_nvcc_include_all/test.compile.pass.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
  tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
  tests/std/tests/VSO_0000000_regex_use/test.cpp
  tests/tr1/CMakeLists.txt
  tests/tr1/lit.site.cfg.in
  tests/utils/stl/test/config.py
  tests/utils/stl/test/format.py
  tests/utils/stl/test/tests.py
Labels: infrastructure, uncharted

#1537 feature/spaceship: Merge CI update
  azure-devops/run-build.yml
  azure-pipelines.yml
  stl/inc/ranges
  stl/inc/regex
  tests/std/CMakeLists.txt
  tests/std/include/test_regex_support.hpp
  tests/std/lit.site.cfg.in
  tests/std/tests/Dev11_0748972_function_crash_out_of_memory/test.cpp
  tests/std/tests/GH_000639_nvcc_include_all/env.lst
  tests/std/tests/GH_000639_nvcc_include_all/test.compile.pass.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
  tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
  tests/std/tests/VSO_0000000_regex_use/test.cpp
  tests/tr1/CMakeLists.txt
  tests/tr1/lit.site.cfg.in
  tests/utils/stl/test/config.py
  tests/utils/stl/test/format.py
  tests/utils/stl/test/tests.py
Labels: infrastructure, uncharted

#1535 Updated _MSVC_STL_UPDATE to December 2020
  stl/inc/yvals_core.h
Labels: enhancement

#1539 Add target architectures as features
  tests/utils/stl/test/features.py
Labels: bug, high priority, test
