Repository microsoft/STL, pull requests merged in 2020-05, with the labels that each got.

#772 Fix CUDA warnings/errors, _Noinit shadowing, other cleanups
  stl/inc/istream
  stl/inc/memory
  stl/inc/random
  stl/inc/string
  stl/inc/xlocmon
  stl/inc/xlocnum
  stl/inc/xstring
  stl/inc/xutility
  stl/inc/yvals_core.h
Labels: enhancement

#786 Implement LWG-3420
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
Labels: LWG

#793 Updated _MSVC_STL_UPDATE to May 2020
  stl/inc/yvals_core.h
Labels: enhancement

#791 Fix complex's Sufficient Additional Overloads
  stl/inc/complex
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/Dev10_555491_complex_linker_errors/test.cpp
Labels: bug

#769 Make several improvements to the way the CI runs the tests.
  README.md
  azure-devops/run-build.yml
  azure-pipelines.yml
  tests/CMakeLists.txt
  tests/libcxx/CMakeLists.txt
  tests/std/CMakeLists.txt
  tests/tr1/CMakeLists.txt
  tests/utils/stl-lit/CMakeLists.txt
Labels: test

#794 C6294 is suppressed STL-wide; remove local suppressions
  stl/inc/bitset
  stl/inc/xutility
Labels: enhancement

#796 Skip /clr tests
  tests/utils/stl/test/tests.py
Labels: test

#800 Fix filesystem's handling of nonexistent network paths emitting ERROR_INVALID_NAME
  stl/src/syserror.cpp
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: bug

#771 fix using *_Prev_iter(it) instead of *(it - 1)
  stl/inc/algorithm
Labels: performance

#783 Update README.md Build example
  README.md
Labels: documentation

#790 Apply cleanups suggested when bringing this ADO VMSS support to vcpkg
  azure-devops/create-vmss.ps1
  azure-devops/provision-image.ps1
  azure-devops/run-build.yml
  azure-devops/sysprep.ps1
Labels: infrastructure

#803 Use _Next_iter(it) and _Prev_iter(it) instead of it + 1 and it - 1
  stl/inc/algorithm
  stl/inc/deque
  stl/inc/vector
Labels: enhancement

#688 Improve call_once performance by using Init­Once­Begin­Initialize / InitOnceComplete
  stl/CMakeLists.txt
  stl/aliases/amd64/std_init_once_begin_initialize.obj
  stl/aliases/amd64/std_init_once_complete.obj
  stl/aliases/arm/std_init_once_begin_initialize.obj
  stl/aliases/arm/std_init_once_complete.obj
  stl/aliases/arm64/std_init_once_begin_initialize.obj
  stl/aliases/arm64/std_init_once_complete.obj
  stl/aliases/chpe/std_init_once_begin_initialize.obj
  stl/aliases/chpe/std_init_once_complete.obj
  stl/aliases/generate.cmd
  stl/aliases/i386/std_init_once_begin_initialize.obj
  stl/aliases/i386/std_init_once_complete.obj
  stl/inc/future
  stl/inc/mutex
  stl/msbuild/stl_base/stl.files.settings.targets
  stl/msbuild/stl_post/msvcp_post.settings.targets
  stl/src/ppltasks.cpp
  stl/src/xonce.cpp
  stl/src/xonce2.cpp
Labels: performance

#684 atomic_flag_test, lock free type aliases
  stl/inc/atomic
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/P1135R6_atomic_flag_test/env.lst
  tests/std/tests/P1135R6_atomic_flag_test/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: cxx20

#810 Fail if the version of Python found is too old
  tests/CMakeLists.txt
Labels: test

#812 Update libcxx expected_results.txt, skipped_tests.txt
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: test

#815 Implement ranges::find_end
  stl/inc/algorithm
  stl/inc/xutility
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_find_end/env.lst
  tests/std/tests/P0896R4_ranges_alg_find_end/test.cpp
Labels: cxx20

#816 Fix race in parallel adjacent_find
  stl/inc/execution
Labels: bug

#621 <utility> P0586R2 Integer Comparison Functions
  stl/inc/utility
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P0586R2_integer_comparison/env.lst
  tests/std/tests/P0586R2_integer_comparison/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: cxx20

#821 Implement ranges::find_first_of
  stl/inc/algorithm
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_find/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_first_of/env.lst
  tests/std/tests/P0896R4_ranges_alg_find_first_of/test.cpp
Labels: cxx20

#822 Implement ranges::adjacent_find
  stl/inc/algorithm
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_adjacent_find/env.lst
  tests/std/tests/P0896R4_ranges_alg_adjacent_find/test.cpp
Labels: cxx20

#653 <chrono>: Cache QueryPerformanceFrequency() and divide just once
  stl/inc/chrono
  stl/inc/xatomic.h
Labels: performance

#827 Code cleanups
  stl/inc/atomic
  stl/inc/bitset
  stl/inc/chrono
  stl/inc/exception
  stl/inc/execution
  stl/inc/experimental/filesystem
  stl/inc/filesystem
  stl/inc/forward_list
  stl/inc/functional
  stl/inc/future
  stl/inc/istream
  stl/inc/limits
  stl/inc/locale
  stl/inc/memory
  stl/inc/memory_resource
  stl/inc/mutex
  stl/inc/random
  stl/inc/ratio
  stl/inc/regex
  stl/inc/scoped_allocator
  stl/inc/shared_mutex
  stl/inc/streambuf
  stl/inc/system_error
  stl/inc/thread
  stl/inc/tuple
  stl/inc/unordered_map
  stl/inc/utility
  stl/inc/valarray
  stl/inc/variant
  stl/inc/xfacet
  stl/inc/xiosbase
  stl/inc/xlocale
  stl/inc/xlocmes
  stl/inc/xlocmon
  stl/inc/xlocnum
  stl/inc/xloctime
  stl/inc/xpolymorphic_allocator.h
  stl/inc/xstring
  stl/inc/xutility
  stl/src/locale0.cpp
  stl/src/memory_resource.cpp
Labels: enhancement

#834 Allow both ::value_type and ::element_type in indirectly_readable_traits
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
Labels: bug

#829 Use a GitHub Workflow to automate Code Reviews Project
  .github/workflows/new-pr-triage.yml
Labels: infrastructure

#847 Fix #842 "GitHub: Workflow automation is failing".
  .github/workflows/new-pr-triage.yml
Labels: infrastructure

#835 Add charconv test cases
  tests/std/tests/P0067R5_charconv/double_general_precision_to_chars_test_cases.hpp
  tests/std/tests/P0067R5_charconv/double_scientific_precision_to_chars_test_cases_1.hpp
  tests/std/tests/P0067R5_charconv/double_to_chars_test_cases.hpp
  tests/std/tests/P0067R5_charconv/float_to_chars_test_cases.hpp
Labels: test

#837 bug: fix warning by variable named last due to C++20 addition to std::chrono
  tests/std/tests/P0067R5_charconv/test.cpp
Labels: test

#841 LWG-3446 now has a number
  stl/inc/xutility
Labels: documentation

#491 Misc constexpr
  stl/inc/array
  stl/inc/functional
  stl/inc/iterator
  stl/inc/tuple
  stl/inc/utility
  stl/inc/xstring
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/Dev11_0343056_pair_tuple_ctor_sfinae/test.cpp
  tests/std/tests/P0220R1_string_view/test.cpp
  tests/std/tests/P1032R1_miscellaneous_constexpr/env.lst
  tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: cxx20

#677 add /Zc:preprocessor to our tests
  tests/libcxx/usual_matrix.lst
  tests/std/tests/VSO_0157762_feature_test_macros/env.lst
  tests/std/tests/concepts_matrix.lst
  tests/std/tests/impure_matrix.lst
  tests/std/tests/locale0_implib_cpp_matrix.lst
  tests/std/tests/native_17_matrix.lst
  tests/std/tests/native_matrix.lst
  tests/std/tests/native_winsdk_matrix.lst
  tests/std/tests/usual_17_matrix.lst
  tests/std/tests/usual_17_winsdk_matrix.lst
  tests/std/tests/usual_latest_matrix.lst
  tests/std/tests/usual_latest_winsdk_matrix.lst
  tests/std/tests/usual_matrix.lst
  tests/std/tests/usual_winsdk_matrix.lst
Labels: test

#831 [xutility] Modernize _Equal_memcmp_is_safe to use variable templates
  stl/inc/algorithm
  stl/inc/xstring
  stl/inc/xutility
  tests/std/tests/VSO_0180469_ptr_cat/test.cpp
Labels: enhancement

#833 shared_ptr<function>
  tests/std/test.lst
  tests/std/tests/LWG3018_shared_ptr_function/env.lst
  tests/std/tests/LWG3018_shared_ptr_function/test.cpp
Labels: LWG

#849 <execution>: comment early return control flow #818
  stl/inc/execution
Labels: documentation

#858 <variant>: silence useless warning
  stl/inc/type_traits
  stl/inc/variant
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/VSO_0180469_fill_family/test.cpp
  tests/tr1/tests/functional1/test.cpp
Labels: bug

#861 C++20 constexpr _Copy_s and simplify char8_t compare
  stl/inc/xstring
  tests/std/tests/P0220R1_string_view/test.cpp
  tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp
Labels: enhancement

#866 tests: Note unsupported locales, but don't warn.
  tests/utils/stl/test/target_info.py
Labels: test

#865 Code cleanup: avoid macro-like identifiers, remove double newlines
  stl/inc/atomic
  stl/inc/bitset
  stl/inc/charconv
  stl/inc/chrono
  stl/inc/concepts
  stl/inc/cvt/ebcdic
  stl/inc/cvt/euc_0208
  stl/inc/cvt/jis_0208
  stl/inc/cvt/utf16
  stl/inc/cvt/utf8_utf16
  stl/inc/cvt/wbuffer
  stl/inc/execution
  stl/inc/experimental/filesystem
  stl/inc/forward_list
  stl/inc/future
  stl/inc/iostream
  stl/inc/iterator
  stl/inc/memory
  stl/inc/mutex
  stl/inc/ostream
  stl/inc/random
  stl/inc/ratio
  stl/inc/regex
  stl/inc/scoped_allocator
  stl/inc/shared_mutex
  stl/inc/string
  stl/inc/tuple
  stl/inc/type_traits
  stl/inc/utility
  stl/inc/xlocmon
  stl/inc/xmemory
  stl/inc/xstring
  stl/inc/xutility
Labels: enhancement

#868 Use a cryptographically secure RNG to generate admin passwords.
  azure-devops/create-vmss.ps1
Labels: infrastructure

#862 Link with /MANIFEST:EMBED to avoid UNRESOLVED tests
  tests/libcxx/usual_matrix.lst
  tests/std/tests/prefix.lst
  tests/tr1/prefix.lst
  tests/universal_prefix.lst
Labels: test
