Repository microsoft/STL, pull requests merged in 2020-03, with the labels that each got.

#573 Fix missing SFINAE in operator/ and operator% for std::chrono::duration
  stl/inc/chrono
  tests/libcxx/skipped_tests.txt
Labels: bug

#580 Apply a new attribute '[[msvc::known_semantics]]'
  stl/inc/span
  stl/inc/utility
  stl/inc/yvals_core.h
Labels: enhancement

#577 Update byte detection by using __cpp_lib_byte
  stl/inc/cstddef
  stl/inc/span
  stl/inc/xutility
  tests/std/tests/VSO_0180466_algorithm_overhauls/test.cpp
  tests/std/tests/VSO_0180469_fill_family/test.cpp
Labels: enhancement

#576 Cache the "installed" vcpkg directory only.
  azure-devops/run_build.yml
Labels: infrastructure

#562 <filesystem>: Fix directory_iterator returning "dot" and "dotdot" entries
  stl/inc/filesystem
Labels: bug

#553 Add Azure provisioning scripts we use for our builders.
  azure-devops/install-scale-set-extension.ps1
  azure-devops/install_msvc_preview.ps1
  azure-devops/provision-agent-bootstrap.cmd
  azure-devops/provision-agent.ps1
  azure-devops/run-build.yml
  azure-pipelines.yml
Labels: infrastructure

#552 <filesystem>::space fails with no read access to root
  stl/CMakeLists.txt
  stl/msbuild/stl_base/stl.files.settings.targets
  stl/src/filesystem.cpp
  stl/src/filesystem_space.cpp
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: bug

#513 Compare all the things.
  stl/inc/typeindex
  stl/inc/utility
  tests/std/test.lst
  tests/std/tests/GH_000545_include_compare/env.lst
  tests/std/tests/GH_000545_include_compare/test.cpp
  tests/std/tests/GH_000545_include_compare/test_array.cpp
  tests/std/tests/GH_000545_include_compare/test_chrono.cpp
  tests/std/tests/GH_000545_include_compare/test_coroutine.cpp
  tests/std/tests/GH_000545_include_compare/test_deque.cpp
  tests/std/tests/GH_000545_include_compare/test_filesystem.cpp
  tests/std/tests/GH_000545_include_compare/test_forward_list.cpp
  tests/std/tests/GH_000545_include_compare/test_iterator.cpp
  tests/std/tests/GH_000545_include_compare/test_list.cpp
  tests/std/tests/GH_000545_include_compare/test_map.cpp
  tests/std/tests/GH_000545_include_compare/test_memory.cpp
  tests/std/tests/GH_000545_include_compare/test_optional.cpp
  tests/std/tests/GH_000545_include_compare/test_queue.cpp
  tests/std/tests/GH_000545_include_compare/test_ranges.cpp
  tests/std/tests/GH_000545_include_compare/test_regex.cpp
  tests/std/tests/GH_000545_include_compare/test_set.cpp
  tests/std/tests/GH_000545_include_compare/test_stack.cpp
  tests/std/tests/GH_000545_include_compare/test_string.cpp
  tests/std/tests/GH_000545_include_compare/test_string_view.cpp
  tests/std/tests/GH_000545_include_compare/test_system_error.cpp
  tests/std/tests/GH_000545_include_compare/test_thread.cpp
  tests/std/tests/GH_000545_include_compare/test_tuple.cpp
  tests/std/tests/GH_000545_include_compare/test_typeindex.cpp
  tests/std/tests/GH_000545_include_compare/test_unordered_map.cpp
  tests/std/tests/GH_000545_include_compare/test_unordered_set.cpp
  tests/std/tests/GH_000545_include_compare/test_utility.cpp
  tests/std/tests/GH_000545_include_compare/test_variant.cpp
  tests/std/tests/GH_000545_include_compare/test_vector.cpp
Labels: LWG

#584 Replace `_STATIC_UNLESS_PURE` with `static`.
  stl/inc/regex
  stl/inc/xlocmon
  stl/inc/xlocnum
  stl/inc/yvals_core.h
Labels: enhancement

#514 Implement range_size_t
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
Labels: LWG

#565 Several range algorithms
  stl/inc/algorithm
  stl/inc/concepts
  stl/inc/functional
  stl/inc/ranges
  stl/inc/span
  stl/inc/xstring
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/include/instantiate_algorithms.hpp
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0122R7_span/test.cpp
  tests/std/tests/P0896R4_ranges_alg_all_of/env.lst
  tests/std/tests/P0896R4_ranges_alg_all_of/test.cpp
  tests/std/tests/P0896R4_ranges_alg_any_of/env.lst
  tests/std/tests/P0896R4_ranges_alg_any_of/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy/env.lst
  tests/std/tests/P0896R4_ranges_alg_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy_if/env.lst
  tests/std/tests/P0896R4_ranges_alg_copy_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_copy_n/env.lst
  tests/std/tests/P0896R4_ranges_alg_copy_n/test.cpp
  tests/std/tests/P0896R4_ranges_alg_count/env.lst
  tests/std/tests/P0896R4_ranges_alg_count/test.cpp
  tests/std/tests/P0896R4_ranges_alg_count_if/env.lst
  tests/std/tests/P0896R4_ranges_alg_count_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_equal/env.lst
  tests/std/tests/P0896R4_ranges_alg_equal/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find/env.lst
  tests/std/tests/P0896R4_ranges_alg_find/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_if/env.lst
  tests/std/tests/P0896R4_ranges_alg_find_if/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_if_not/env.lst
  tests/std/tests/P0896R4_ranges_alg_find_if_not/test.cpp
  tests/std/tests/P0896R4_ranges_alg_for_each/env.lst
  tests/std/tests/P0896R4_ranges_alg_for_each/test.cpp
  tests/std/tests/P0896R4_ranges_alg_for_each_n/env.lst
  tests/std/tests/P0896R4_ranges_alg_for_each_n/test.cpp
  tests/std/tests/P0896R4_ranges_alg_mismatch/env.lst
  tests/std/tests/P0896R4_ranges_alg_mismatch/test.cpp
  tests/std/tests/P0896R4_ranges_alg_none_of/env.lst
  tests/std/tests/P0896R4_ranges_alg_none_of/test.cpp
  tests/std/tests/P0896R4_ranges_algorithm_machinery/env.lst
  tests/std/tests/P0896R4_ranges_algorithm_machinery/test.cpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
Labels: cxx20

#588 enable_view<T> now defaults to derived_from<T, view_base>
  stl/inc/hash_set
  stl/inc/regex
  stl/inc/set
  stl/inc/span
  stl/inc/unordered_set
  stl/inc/xstring
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
Labels: LWG

#583 add bit_cast and tests
  stl/inc/bit
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P0476R2_bit_cast/env.lst
  tests/std/tests/P0476R2_bit_cast/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: cxx20

#585 <functional> Avoid layers of forwards in invoke
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/algorithm
  stl/inc/tuple
  stl/inc/type_traits
  stl/inc/variant
  stl/inc/xatomic.h
  stl/inc/yvals_core.h
  tests/libcxx/skipped_tests.txt
  tests/std/tests/Dev09_158181_tr1_unordered_meow_swap/test.cpp
  tests/std/tests/Dev10_729003_bind_reference_wrapper/test.cpp
  tests/std/tests/Dev11_0535636_functional_overhaul/test.cpp
  tests/std/tests/VSO_0000000_instantiate_containers/test.cpp
Labels: enhancement

#500 [span] Implement P1976R2
  stl/inc/span
  stl/inc/yvals_core.h
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0122R7_span/test.cpp
  tests/std/tests/P0122R7_span_death/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: cxx20

#506 span: Implement solution to LWG-3255
  stl/inc/span
  tests/std/tests/P0122R7_span/test.cpp
Labels: LWG

#515 <xutility> lexicographical_compare_three_way
  stl/inc/xutility
  tests/std/tests/P0768R1_spaceship_operator/test.cpp
Labels: cxx20

#581 Add "/build/" to the .gitignore
  .gitignore
Labels: enhancement

#587 [span] Remove tuple interface
  stl/inc/span
  stl/inc/yvals_core.h
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0122R7_span/test.cpp
Labels: cxx20

#590 Improve GitHub templates and VSCode config
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/cxx20-feature.md
  .github/pull_request_template.md
  .vscode/settings.json
Labels: documentation

#589 P0896R4 changes to insert iterators
  stl/inc/iterator
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
Labels: cxx20

#607 P1871R1 disable_sized_sentinel_for
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
Labels: cxx20

#609 psx is 0, so don't even bother checking
  stl/src/xfdscale.cpp
Labels: enhancement

#610 Fix #608 : CMakeLists.txt: /O2 is not working
  CMakeLists.txt
Labels: infrastructure

#614 Work around compiler bug in atomic.
  stl/inc/atomic
Labels: enhancement

#603 Cleanup feature_test_macros/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: test

#617 Repair feature-test macros test.
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: test

#616 <filesystem> Treat ERROR_BAD_NETPATH as file not found.
  stl/inc/filesystem
  stl/inc/xfilesystem_abi.h
  stl/src/filesystem.cpp
  stl/src/syserror.cpp
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: bug

#417 Remove STL workarounds for VSO-1006185
  stl/inc/memory
  tests/std/tests/Dev11_1140665_unique_ptr_array_conversions/test.cpp
Labels: enhancement

#630 Repoint the README to the changelog
  README.md
Labels: documentation

#629 Update devcrt to std in the README
  README.md
Labels: documentation

#620 Update dependencies for CI machines
  README.md
  azure-devops/provision-agent.ps1
Labels: infrastructure

#631 <filesystem>: Fix damage caused by redefinition of _Iter_value_t to iter_value_t in concepts mode
  stl/inc/filesystem
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: bug

#633 Add scripts to generate new Virtual Machine Scale Sets and images for build machines
  azure-devops/create-new-agent-image.ps1
  azure-devops/install-scale-set-extension.ps1
  azure-devops/provision-agent-bootstrap.cmd
  azure-devops/provision-agent.ps1
  azure-devops/provision-image.ps1
  azure-devops/run-build.yml
Labels: infrastructure

#408 Fix #239: Improve _Invoke_traits throughput
  stl/inc/type_traits
Labels: throughput

#627 <xutility>: strengthen noexcept for array iterators
  stl/inc/xutility
  tests/std/tests/P0122R7_span/test.cpp
Labels: enhancement

#637 Bump _MSVC_STL_UPDATE for March 2020
  stl/inc/yvals_core.h
Labels: enhancement

#638 Remove comment following acceptance of LWG-3150
  stl/inc/random
Labels: documentation

#635 <concepts>: Implement is-default-initializable via placement new
  stl/inc/concepts
  tests/std/tests/P0898R3_concepts/test.cpp
Labels: LWG

#642 Try to run with fewer workers to avoid overwhelming the VM
  azure-devops/run-build.yml
Labels: infrastructure, test

#643 update cgmanifest
  docs/cgmanifest.json
Labels: documentation

#641 Add futures.unique_future/wait.pass.cpp to the skip lists
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: test

#652 Add tr1 testsuite
  azure-devops/run-build.yml
  tests/CMakeLists.txt
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/tr1/CMakeLists.txt
  tests/tr1/expected_results.txt
  tests/tr1/lit.cfg
  tests/tr1/lit.site.cfg.in
  tests/tr1/tests/cwchar1/__init__.py
  tests/tr1/tests/cwchar1/custom_format.py
  tests/tr1/tests/cwchar1/lit.local.cfg
Labels: test

#647 Add testing instructions to the README
  CMakeLists.txt
  README.md
  azure-devops/run-build.yml
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/tr1/tests/cwchar1/__init__.py
  tests/tr1/tests/cwchar1/custom_format.py
  tests/tr1/tests/cwchar1/lit.local.cfg
  tests/utils/stl/test/format.py
Labels: documentation, infrastructure

#599 constexpr for std::array Comparisons
  stl/inc/array
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/P1023R0_constexpr_for_array_comparisons/env.lst
  tests/std/tests/P1023R0_constexpr_for_array_comparisons/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.cpp
Labels: cxx20
