Repository microsoft/STL, pull requests merged in 2021-11, with the labels that each got.

#2189 `<fstream>`: `fstream::close` shouldn't corrupt heap (after `putback`)
  stl/inc/fstream
  tests/std/test.lst
  tests/std/tests/GH_000342_filebuf_close/env.lst
  tests/std/tests/GH_000342_filebuf_close/test.cpp
Labels: bug

#2261 LWG-3554 Add `const charT*` overloads for `chrono::parse`
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp
Labels: LWG, chrono

#2282 `weak_ptr` conversions can sometimes avoid locking
  stl/inc/memory
  tests/std/tests/Dev10_851347_weak_ptr_virtual_inheritance/test.cpp
Labels: performance

#2293 More precise check message for `binary_semaphore`
  stl/inc/semaphore
Labels: enhancement

#2297 update working draft revision to N4901
  README.md
Labels: documentation

#2304 `filesystem`: two assignments of the same value
  stl/inc/filesystem
Labels: performance

#2313 `<ranges>`: Fix `views::reverse` for `ranges::reverse_view` lvalues
  stl/inc/ranges
  tests/std/tests/P0896R4_views_reverse/test.cpp
Labels: bug, ranges

#2318 Update cgmanifest.json for 17.0
  docs/cgmanifest.json
Labels: documentation

#2324 Status Chart: chart.js 3.6.0, improve type info, weekly updates
  README.md
  index.html
  package-lock.json
  package.json
  src/gather_stats.ts
  weekly_table.js
Labels: documentation

#2327 Toolset update: VS 2022 17.1 Preview 1
  README.md
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  stl/inc/vector
  stl/inc/xstring
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
  tests/std/tests/P2231R1_complete_constexpr_optional_variant/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: infrastructure

#2043 Optimize `is_permutation` for reversed sequences
  stl/inc/algorithm
  stl/inc/xutility
  tests/std/tests/Dev11_0000000_dual_range_algorithms/test.cpp
  tests/std/tests/P0202R3_constexpr_algorithm_and_exchange/test.cpp
  tests/std/tests/P0896R4_ranges_alg_is_permutation/test.cpp
Labels: performance

#2258 Implement P1072R10 `basic_string::resize_and_overwrite`
  stl/inc/xstring
  stl/inc/yvals_core.h
  tests/std/tests/P0980R1_constexpr_strings/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#2259 P2251R1 Update yvals_core.h and the comments in the tests
  stl/inc/yvals_core.h
  tests/std/tests/P0122R7_span/test.cpp
  tests/std/tests/P0220R1_string_view/test.cpp
Labels: cxx23

#2273 P2372R3: Fix handling of locale in chrono formatters
  stl/inc/chrono
  stl/inc/yvals_core.h
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
Labels: cxx20, format, chrono, defect report

#2275 P2415 What Is A `view`?
  stl/inc/ranges
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_views_all/test.cpp
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_drop_while/test.cpp
  tests/std/tests/P0896R4_views_elements/test.cpp
  tests/std/tests/P0896R4_views_filter/test.cpp
  tests/std/tests/P0896R4_views_join/test.cpp
  tests/std/tests/P0896R4_views_lazy_split/test.cpp
  tests/std/tests/P0896R4_views_reverse/test.cpp
  tests/std/tests/P0896R4_views_split/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
  tests/std/tests/P0896R4_views_take_while/test.cpp
  tests/std/tests/P0896R4_views_transform/test.cpp
  tests/std/tests/P2415R2_owning_view/env.lst
  tests/std/tests/P2415R2_owning_view/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx20, ranges, defect report

#2314 Don't /LTCG CRT initializers
  stl/CMakeLists.txt
Labels: build

#2321 updated _MSVC_STL_UPDATE to November 2021
  stl/inc/yvals_core.h
Labels: enhancement

#2331 `<format>`: delay vformat instantiation
  stl/inc/format
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
Labels: throughput, format

#2333 Remove attempt to use tzcnt as bsf
  stl/inc/limits
  tests/std/tests/GH_001103_countl_zero_correctness/test.cpp
Labels: bug

#2222 Implement changes missed from P1148R0
  stl/inc/xstring
Labels: bug

#2231 Fix chronat tests to deal with locale-dependent time zones abbreviations
  tests/std/include/timezone_data.hpp
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_time_zones/test.cpp
Labels: test, chrono

#2270 Fix ranges::find_end return for bidi-common case
  stl/inc/algorithm
  tests/std/tests/P0896R4_ranges_alg_find_end/test.cpp
Labels: bug, ranges

#2290 Workaround Devcom-1559808 in ranges::sort
  stl/inc/algorithm
  stl/inc/ranges
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_alg_find_end/test.cpp
  tests/std/tests/P0896R4_ranges_alg_search/test.cpp
  tests/std/tests/P0896R4_ranges_alg_sort/test.cpp
  tests/std/tests/P0896R4_views_split/test.cpp
Labels: bug, ranges

#2296 Specially handle `array<T, 0>` for non-default-constructible `T`
  stl/inc/array
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: bug

#2328 Remove improper use of __declspec(allocator)
  stl/inc/xmemory
Labels: bug

#2348 Status Chart: Weekly updates, increase PR Age
  index.html
  package-lock.json
  package.json
  weekly_table.js
Labels: documentation, uncharted
