Repository microsoft/STL, pull requests merged in 2021-05, with the labels that each got.

#1836 Avoid calling size() in empty() member functions
  stl/inc/vector
  stl/inc/xstring
  stl/inc/xtree
Labels: performance

#1843 filesys.cpp: Remove C casts
  stl/src/filesys.cpp
Labels: enhancement

#1844 Fix error in take_view::begin by casting to the appropriate size
  stl/inc/ranges
  tests/std/tests/P0896R4_views_take/test.cpp
Labels: bug, ranges

#1874 Fix more code bloat issues in <format>
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Labels: format, performance

#1878 [ranges] Apply resolution of LWG3502 to elements_view
  stl/inc/ranges
  tests/std/tests/P0896R4_views_elements/test.cpp
Labels: LWG

#1884 Toolset update: VS 2019 16.10 Preview 2
  .github/workflows/update-status-chart.yml
  .gitignore
  CMakeLists.txt
  README.md
  azure-devops/create-vmss.ps1
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
  tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
  tests/std/tests/P1614R2_spaceship/test.cpp
  tools/CMakeLists.txt
Labels: infrastructure

#1895 Status Chart: Avoid emitting consecutive zeros
  gather_stats.js
  index.html
  package-lock.json
  usernames_contributors.txt
  weekly_table.js
Labels: documentation

#1855 Visualize `🛸_ordering`
  stl/debugger/STL.natvis
Labels: visualizer

#1837 Visualise `source_location`
  stl/debugger/STL.natvis
Labels: visualizer

#1920 Toolset update: VS 2019 16.10 Preview 4
  README.md
  azure-devops/create-vmss.ps1
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  stl/inc/chrono
  stl/inc/execution
  stl/inc/queue
  stl/inc/stack
  stl/inc/tuple
  stl/inc/type_traits
  stl/inc/variant
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/Dev11_0535636_functional_overhaul/test.cpp
  tests/std/tests/P0067R5_charconv/float_to_chars_test_cases.hpp
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P0122R7_span/test.cpp
  tests/std/tests/P0220R1_optional/test.cpp
  tests/std/tests/P0325R4_to_array/test.cpp
  tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp
  tests/std/tests/P0608R3_improved_variant_converting_constructor/test.cpp
  tests/std/tests/P0674R1_make_shared_for_arrays/test.cpp
  tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/std/tests/P0980R1_constexpr_strings/test.cpp
  tests/std/tests/P1004R2_constexpr_vector/test.cpp
  tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
  tests/std/tests/VSO_0000000_more_pair_tuple_sfinae/test.cpp
Labels: infrastructure

#1342 Replace __pragma with _Pragma
  stl/inc/yvals_core.h
Labels: enhancement

#1809 Adding _NODISCARD in String and Locale CPP
  stl/inc/locale
  stl/inc/string
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/Dev11_0835323_to_string/test.cpp
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
  tests/tr1/tests/string1/test.cpp
  tests/tr1/tests/string2/test.cpp
Labels: enhancement

#1877 Conditionally Borrowed Ranges
  stl/inc/ranges
  stl/inc/yvals_core.h
  tests/std/tests/P0896R4_views_common/test.cpp
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_drop_while/test.cpp
  tests/std/tests/P0896R4_views_elements/test.cpp
  tests/std/tests/P0896R4_views_reverse/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
Labels: LWG

#1897 Updated to MAY21
  stl/inc/yvals_core.h
Labels: enhancement

#1930 Status Chart: Weekly updates, chart.js 3.3.0.
  index.html
  package-lock.json
  package.json
  query_prs_and_issues.graphql
  weekly_table.js
Labels: documentation, uncharted
