Repository microsoft/STL, pull requests merged in 2021-07, with the labels that each got.

#2051 Port internal msbuild changes for ARM64EC
  stl/msbuild/stl_1/md/msvcp_1_netfx/msvcp_1.nativeproj
  stl/msbuild/stl_1/stl_1.files.settings.targets
  stl/msbuild/stl_1/xmd/msvcp_1_netfx/msvcp_1.nativeproj
  stl/msbuild/stl_2/md/msvcp_2_netfx/msvcp_2.nativeproj
  stl/msbuild/stl_2/stl_2.files.settings.targets
  stl/msbuild/stl_2/xmd/msvcp_2_netfx/msvcp_2.nativeproj
  stl/msbuild/stl_atomic_wait/md/msvcp_atomic_wait_netfx/msvcp_atomic_wait.nativeproj
  stl/msbuild/stl_atomic_wait/xmd/msvcp_atomic_wait_netfx/msvcp_atomic_wait.nativeproj
  stl/msbuild/stl_base/md/msvcp_netfx/msvcp.nativeproj
  stl/msbuild/stl_base/stl.files.settings.targets
  stl/msbuild/stl_base/xmd/msvcp_netfx/msvcp.nativeproj
  stl/msbuild/stl_codecvt_ids/md/msvcp_codecvt_ids_netfx/msvcp_codecvt_ids.nativeproj
  stl/msbuild/stl_codecvt_ids/stl_codecvt_ids.files.settings.targets
  stl/msbuild/stl_codecvt_ids/xmd/msvcp_codecvt_ids_netfx/msvcp_codecvt_ids.nativeproj
  stl/msbuild/stl_post/md/msvcp_post_netfx/msvcp_post.nativeproj
  stl/msbuild/stl_post/xmd/msvcp_post_netfx/msvcp_post.nativeproj
Labels: compiler

#2023 Forward declare uses_allocator_construction_args
  stl/inc/xmemory
  tests/std/tests/P0475R1_P0591R4_uses_allocator_construction/test.cpp
Labels: bug

#2025 Adapt some return statements to P2266R1 "Simpler implicit move"
  stl/inc/string
  stl/inc/xstring
Labels: bug

#2031 `<format>`/`<chrono>`: Remove `<array>` dependency.
  stl/inc/chrono
  stl/inc/format
Labels: throughput

#2035 Chore: Update _MSVC_STL_UPDATE to July 2021
  stl/inc/yvals_core.h
Labels: enhancement

#2055 Optimize `<xstring>` memmove function
  stl/inc/xstring
Labels: enhancement

#2063 Status Chart: Weekly updates, chart.js 3.4.1, solid C++23
  index.html
  package-lock.json
  package.json
  weekly_table.js
Labels: documentation, uncharted

#2076 Status Chart: Weekly update, fix Luxon 2.0 breaking change
  gather_stats.js
  package-lock.json
  usernames_contributors.txt
  weekly_table.js
Labels: documentation, uncharted

#1993 Adopt LWG-3533 Make `base() const &` consistent across iterator wrappers that support `input_iterator`s
  stl/inc/ranges
  tests/std/test.lst
  tests/std/tests/P0896R4_views_filter_iterator/env.lst
  tests/std/tests/P0896R4_views_filter_iterator/test.cpp
  tests/std/tests/P0896R4_views_transform/test.cpp
Labels: LWG, ranges

#1998 Implement P1132R7 out_ptr() and inout_ptr()
  stl/inc/memory
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P1132R7_out_ptr/env.lst
  tests/std/tests/P1132R7_out_ptr/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#2009 implement P1951R1: Default Template Arguments For pair's Forwarding Constructor
  stl/inc/utility
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P0067R5_charconv/test.cpp
  tests/std/tests/P1951R1_default_arguments_pair_forward_ctor/env.lst
  tests/std/tests/P1951R1_default_arguments_pair_forward_ctor/test.compile.pass.cpp
Labels: cxx23

#2036 Implement P0401R6 Providing Size Feedback In The Allocator Interface
  stl/inc/xmemory
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P0401R6_allocate_at_least/env.lst
  tests/std/tests/P0401R6_allocate_at_least/test.cpp
  tests/std/tests/VSO_0000000_fancy_pointers/test.compile.pass.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#2041 `<bit>`: `bit_ceil`(T(-1)) is not a constant expression
  stl/inc/bit
Labels: bug

#2044 `<type_traits>`: `std::byte` is `_Is_trivially_swappable_v`
  stl/inc/chrono
  stl/inc/type_traits
  tests/std/test.lst
  tests/std/tests/GH_002039_byte_is_not_trivially_swappable/env.lst
  tests/std/tests/GH_002039_byte_is_not_trivially_swappable/test.compile.pass.cpp
Labels: performance

#2048 Extend `swap_ranges` vectorization
  stl/inc/algorithm
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_alg_swap_ranges/test.cpp
Labels: performance

#2057 Add missing precondition check in `forward_list::splice_after`
  stl/inc/forward_list
Labels: enhancement

#2070 Fix VSO_0000000_c_math_functions to run in the test harness
  tests/std/tests/VSO_0000000_c_math_functions/both.cpp
  tests/std/tests/VSO_0000000_c_math_functions/cmath.cpp
  tests/std/tests/VSO_0000000_c_math_functions/cstdlib.cpp
  tests/std/tests/VSO_0000000_c_math_functions/env.lst
  tests/std/tests/VSO_0000000_c_math_functions/test.compile.pass.cpp
Labels: test

#2054 `_STL_VERIFY` shouldn't emit long strings for function names
  stl/inc/yvals.h
Labels: performance

#2056 `<iostream>`: `clog` shouldn't be tied to `cout`
  stl/src/clog.cpp
  stl/src/cout.cpp
  stl/src/wclog.cpp
  stl/src/wcout.cpp
  tests/std/test.lst
  tests/std/tests/GH_001850_clog_tied_to_cout/env.lst
  tests/std/tests/GH_001850_clog_tied_to_cout/test.cpp
Labels: bug

#2060 Fix race condition in iterator debug machinery
  stl/inc/regex
  stl/inc/xmemory
  tests/std/test.lst
  tests/std/tests/GH_002058_debug_iterator_race/env.lst
  tests/std/tests/GH_002058_debug_iterator_race/test.cpp
Labels: bug, high priority

#2080 Use LWG-3518 to add `noexcept`
  stl/inc/xstring
Labels: LWG
