Repository microsoft/STL, pull requests merged in 2021-12, with the labels that each got.

#2266 Clearing the way for LLVM 13
  stl/inc/iomanip
  stl/inc/regex
  tests/std/tests/Dev10_561430_list_and_tree_leaks/test.cpp
  tests/std/tests/Dev11_0863628_atomic_compare_exchange/test.cpp
  tests/std/tests/VSO_0191296_allocator_construct/test.compile.pass.cpp
  tests/tr1/tests/functional/test.cpp
  tests/tr1/tests/memory3/test.cpp
  tests/tr1/tests/string1/test.cpp
Labels: enhancement

#2338 Internally disable `subrange` workaround
  stl/inc/xutility
  tests/std/include/timezone_data.hpp
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
  tests/std/tests/P0645R10_text_formatting_utf8/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
Labels: enhancement

#2340 Implement LWG-3480, `directory_iterator` and `recursive_directory_iterator` are ranges
  stl/inc/filesystem
  tests/std/test.lst
  tests/std/tests/LWG3480_directory_iterator_range/env.lst
  tests/std/tests/LWG3480_directory_iterator_range/test.compile.pass.cpp
Labels: LWG, ranges, defect report

#2346 Don't hide format string from the compiler
  tests/tr1/include/tdefs.h
Labels: test

#2351 Remove outdated `#if` guard
  tests/std/tests/P0898R3_concepts/test.cpp
Labels: test

#2352 Applied LLVM-47414 workaround to `std::ranges::join_view`
  stl/inc/ranges
  tests/std/tests/P0896R4_views_join/test.cpp
Labels: bug, ranges

#2356 Workaround clang-format misbehavior in `P0898R3_concepts` test
  tests/std/tests/P0898R3_concepts/test.cpp
Labels: test

#2357 Remove DevCom-936696 workaround
  stl/inc/type_traits
Labels: enhancement

#2369 Rotate bits using intrinsics
  stl/inc/bit
  tests/std/tests/P0553R4_bit_rotating_and_counting_functions/test.cpp
Labels: performance

#2372 Change #pragma once to include guards.
  tests/std/tests/P0067R5_charconv/double_fixed_precision_to_chars_test_cases_1.hpp
  tests/std/tests/P0067R5_charconv/double_fixed_precision_to_chars_test_cases_2.hpp
  tests/std/tests/P0067R5_charconv/double_fixed_precision_to_chars_test_cases_3.hpp
  tests/std/tests/P0067R5_charconv/double_fixed_precision_to_chars_test_cases_4.hpp
  tests/std/tests/P0067R5_charconv/double_from_chars_test_cases.hpp
  tests/std/tests/P0067R5_charconv/double_general_precision_to_chars_test_cases.hpp
  tests/std/tests/P0067R5_charconv/double_hex_precision_to_chars_test_cases.hpp
  tests/std/tests/P0067R5_charconv/double_scientific_precision_to_chars_test_cases_1.hpp
  tests/std/tests/P0067R5_charconv/double_scientific_precision_to_chars_test_cases_2.hpp
  tests/std/tests/P0067R5_charconv/double_scientific_precision_to_chars_test_cases_3.hpp
  tests/std/tests/P0067R5_charconv/double_scientific_precision_to_chars_test_cases_4.hpp
  tests/std/tests/P0067R5_charconv/double_to_chars_test_cases.hpp
  tests/std/tests/P0067R5_charconv/float_fixed_precision_to_chars_test_cases.hpp
  tests/std/tests/P0067R5_charconv/float_from_chars_test_cases.hpp
  tests/std/tests/P0067R5_charconv/float_general_precision_to_chars_test_cases.hpp
  tests/std/tests/P0067R5_charconv/float_hex_precision_to_chars_test_cases.hpp
  tests/std/tests/P0067R5_charconv/float_scientific_precision_to_chars_test_cases.hpp
  tests/std/tests/P0067R5_charconv/float_to_chars_test_cases.hpp
  tests/std/tests/P0067R5_charconv/test.hpp
  tests/std/tests/P0067R5_charconv/wchar_test_cases.hpp
Labels: test

#2374 updated _MSVC_STL_UPDATE to December 2021
  stl/inc/yvals_core.h
Labels: documentation

#2376 implemented the proposed resolution for LWG-2762
  stl/inc/memory
  stl/inc/optional
  tests/std/tests/P0220R1_optional/test.cpp
Labels: LWG

#2377 Clarify vector_algorithms a bit
  stl/src/vector_algorithms.cpp
Labels: enhancement

#2385 Compiler type trait optimizations
  stl/inc/type_traits
  stl/inc/xtr1common
Labels: throughput, compiler

#2071 `<vector>`: Add ASan annotations.
  stl/CMakeLists.txt
  stl/inc/vector
  stl/inc/xmemory
  stl/msbuild/stl_asan/dirs.proj
  stl/msbuild/stl_asan/stl_asan.files.settings.targets
  stl/msbuild/stl_asan/stl_asan.nativeproj
  stl/msbuild/stl_asan/stl_asan.settings.targets
  stl/msbuild/stl_base/libcp.settings.targets
  stl/msbuild/stl_base/stl.files.settings.targets
  stl/src/asan.cpp
  stl/src/asan_noop.cpp
  tests/std/test.lst
  tests/std/tests/GH_002030_asan_annotate_vector/env.lst
  tests/std/tests/GH_002030_asan_annotate_vector/test.cpp
  tests/utils/stl/test/format.py
  tests/utils/stl/test/tests.py
Labels: enhancement, high priority

#2098 LWG-2774 `std::function` construction vs assignment
  stl/inc/functional
Labels: LWG

#2208 `<random>`: Implement LWG-3519
  stl/inc/iterator
  stl/inc/random
  stl/inc/xhash
  stl/inc/yvals_core.h
Labels: LWG

#2221 <format>: compile time checks
  stl/inc/chrono
  stl/inc/format
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
  tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
  tests/std/tests/P0645R10_text_formatting_legacy_text_encoding/test.cpp
  tests/std/tests/P0645R10_text_formatting_parse_contexts/test.cpp
  tests/std/tests/P0645R10_text_formatting_utf8/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx20, format, defect report

#2267 P0288R9 move_only_function
  stl/inc/functional
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/GH_000690_overaligned_function/test.cpp
  tests/std/tests/P0288R9_move_only_function/env.lst
  tests/std/tests/P0288R9_move_only_function/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tools/move_only_function_specializations/move_only_function_specializations.py
Labels: cxx23

#2301 Implement P0798R8 monadic operations for std::optional
  stl/inc/optional
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P0798R8_monadic_operations_for_std_optional/env.lst
  tests/std/tests/P0798R8_monadic_operations_for_std_optional/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#2305 Fix bugs in std::string
  stl/inc/xstring
  tests/std/tests/P0980R1_constexpr_strings/test.cpp
Labels: bug

#2337 Update test for bsf private helper
  stl/inc/limits
  tests/std/tests/GH_001103_countl_zero_correctness/test.cpp
Labels: enhancement, test

#2350 P2077R3 Heterogeneous Erasure Overloads
  stl/inc/xhash
  stl/inc/xtree
  stl/inc/yvals_core.h
  tests/std/tests/Dev11_0823534_transparent_lookup/test.cpp
  tests/std/tests/P0919R3_heterogeneous_unordered_lookup/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#2361 Fix Efficient access to streambuf buffer
  stl/inc/sstream
  tests/std/tests/P0408R7_efficient_access_to_stringbuf_buffer/test.cpp
Labels: bug

#2382 Strike "with concepts support" from the GH-1814 messages
  stl/inc/format
  stl/inc/ranges
Labels: documentation

#2404 Implement LWG-3590: `split_view::base() const &` is overconstrained
  stl/inc/ranges
  tests/std/tests/P0896R4_views_split/test.cpp
Labels: LWG, ranges

#2406 Implement LWG-3557: The `static_cast` expression in `convertible_to` has the wrong operand
  stl/inc/concepts
Labels: LWG

#2409 Implement LWG-3146: Excessive unwrapping in `std::ref`/`cref`
  stl/inc/type_traits
  tests/std/test.lst
  tests/std/tests/LWG3146_excessive_unwrapping_ref_cref/env.lst
  tests/std/tests/LWG3146_excessive_unwrapping_ref_cref/test.compile.pass.cpp
Labels: LWG

#2410 Implement LWG-3574 and LWG-3595: `common_iterator` should be completely `constexpr`-able
  stl/inc/iterator
  tests/std/include/range_algorithm_support.hpp
  tests/std/tests/P0896R4_common_iterator/test.cpp
  tests/std/tests/P0896R4_counted_iterator/test.cpp
  tests/std/tests/P0896R4_views_counted/test.cpp
Labels: LWG, ranges

#2411 Implement LWG-3591 and LWG-3592 for `lazy_split_view`
  stl/inc/ranges
Labels: LWG, ranges

#2414 Implement LWG-3470: `convertible-to-non-slicing` seems to reject valid case
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_subrange/test.compile.pass.cpp
Labels: LWG, ranges

#2417 improve iota_view's iterator's binary operator+ (LWG-3580)
  stl/inc/ranges
Labels: LWG, ranges

#2419 Prefer `friend constexpr` to `constexpr friend`
  stl/inc/iterator
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/include/range_algorithm_support.hpp
  tests/std/tests/P0896R4_ranges_alg_copy_if/test.cpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
Labels: enhancement

#2420 `<vector>`: Correctly pass target size, not size change to ASan annotator
  stl/inc/vector
  tests/std/tests/GH_002030_asan_annotate_vector/test.cpp
Labels: bug, high priority

#2428 Status Chart: Weekly updates, chart.js 3.6.2
  index.html
  package-lock.json
  package.json
  usernames_contributors.txt
  weekly_table.js
Labels: documentation, uncharted
