Repository microsoft/STL, pull requests merged in 2021-01, with the labels that each got.

#1544 Always use `if constexpr`, require CUDA 10.1 Update 2
  stl/inc/algorithm
  stl/inc/atomic
  stl/inc/bitset
  stl/inc/cmath
  stl/inc/codecvt
  stl/inc/cvt/one_one
  stl/inc/cvt/utf16
  stl/inc/cvt/utf8
  stl/inc/cvt/utf8_utf16
  stl/inc/cvt/xtwo_byte
  stl/inc/deque
  stl/inc/exception
  stl/inc/forward_list
  stl/inc/fstream
  stl/inc/functional
  stl/inc/limits
  stl/inc/list
  stl/inc/memory
  stl/inc/random
  stl/inc/string
  stl/inc/type_traits
  stl/inc/vector
  stl/inc/xhash
  stl/inc/xlocale
  stl/inc/xmemory
  stl/inc/xstring
  stl/inc/xtree
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/tests/VSO_0157762_feature_test_macros/env.lst
  tests/std/tests/eha_matrix.lst
  tests/std/tests/impure_matrix.lst
  tests/std/tests/locale0_implib_cpp_matrix.lst
  tests/std/tests/native_matrix.lst
  tests/std/tests/native_winsdk_matrix.lst
  tests/std/tests/usual_matrix.lst
  tests/std/tests/usual_winsdk_matrix.lst
  tests/tr1/env.lst
  tests/tr1/env_minus_md_idl.lst
  tests/tr1/env_minus_pure.lst
  tests/tr1/env_threads.lst
Labels: enhancement

#1552 Updated _MSVC_STL_UPDATE to January 2021
  stl/inc/yvals_core.h
Labels: enhancement

#1554 Status Chart: Monthly update
  README.md
  daily_table.js
  index.html
  monthly_table.js
  weekly_table.js
Labels: documentation, uncharted

#1369 <xmemory> Add constexpr to allocator traits
  stl/inc/memory
  stl/inc/xmemory
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx20

#1527 Convert contiguous_iterators to pointers correctly
  stl/inc/algorithm
  stl/inc/xutility
  tests/std/tests/VSO_0180469_ptr_cat/test.compile.pass.cpp
Labels: bug

#1568 Merge master into feature/format
  stl/inc/algorithm
  stl/inc/atomic
  stl/inc/bitset
  stl/inc/cmath
  stl/inc/codecvt
  stl/inc/cvt/one_one
  stl/inc/cvt/utf16
  stl/inc/cvt/utf8
  stl/inc/cvt/utf8_utf16
  stl/inc/cvt/xtwo_byte
  stl/inc/deque
  stl/inc/exception
  stl/inc/forward_list
  stl/inc/fstream
  stl/inc/functional
  stl/inc/limits
  stl/inc/list
  stl/inc/memory
  stl/inc/random
  stl/inc/string
  stl/inc/type_traits
  stl/inc/vector
  stl/inc/xhash
  stl/inc/xlocale
  stl/inc/xmemory
  stl/inc/xstring
  stl/inc/xtree
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/env.lst
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tests/std/tests/VSO_0180469_ptr_cat/test.compile.pass.cpp
  tests/std/tests/eha_matrix.lst
  tests/std/tests/impure_matrix.lst
  tests/std/tests/locale0_implib_cpp_matrix.lst
  tests/std/tests/native_matrix.lst
  tests/std/tests/native_winsdk_matrix.lst
  tests/std/tests/usual_matrix.lst
  tests/std/tests/usual_winsdk_matrix.lst
  tests/tr1/env.lst
  tests/tr1/env_minus_md_idl.lst
  tests/tr1/env_minus_pure.lst
  tests/tr1/env_threads.lst
  tests/utils/stl/test/features.py
Labels: format, uncharted

#1540 <bit>: Remove tzcnt special case for small integers in countr_zero
  stl/inc/limits
Labels: performance

#1543 Fix boolalpha extraction to be case-sensitive again
  stl/inc/xlocale
  stl/inc/xlocnum
  stl/inc/xloctime
  tests/std/test.lst
  tests/std/tests/GH_001541_case_sensitive_boolalpha/env.lst
  tests/std/tests/GH_001541_case_sensitive_boolalpha/test.cpp
Labels: bug, high priority

#1545 Add header-units.json
  .vscode/settings.json
  stl/CMakeLists.txt
  stl/inc/header-units.json
Labels: enhancement

#1557 <algorithm>: fill does not accept volatile byte pointers
  stl/inc/xutility
  tests/std/tests/VSO_0180469_fill_family/test.cpp
Labels: bug

#1561 Add missed increment of _Current in the early return path
  stl/inc/algorithm
  tests/std/tests/P0896R4_ranges_alg_unique/test.cpp
  tests/std/tests/P0896R4_ranges_alg_unique_copy/test.cpp
Labels: bug, ranges

#1565 Test each list which can contain /BE independently
  tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
Labels: test

#919 Efficient Access To basic_stringbuf's Buffer
  stl/inc/regex
  stl/inc/sstream
  stl/inc/xstring
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P0408R7_efficient_access_to_stringbuf_buffer/env.lst
  tests/std/tests/P0408R7_efficient_access_to_stringbuf_buffer/test.cpp
  tests/std/tests/VSO_0000000_fancy_pointers/test.compile.pass.cpp
Labels: cxx20

#1571 Status Chart: Mid-January update
  README.md
  daily_table.js
  package-lock.json
  weekly_table.js
Labels: documentation, uncharted

#1570 Avoid conflict with ICU macroizing _No
  stl/inc/memory
  stl/inc/xlocale
  stl/inc/xloctime
Labels: bug

#1572 LWG-3466: specify the requirements for promise/future/shared_future consistently
  stl/inc/future
Labels: LWG

#1577 Toolset update: VS 2019 16.9 Preview 3
  CMakeLists.txt
  README.md
  azure-devops/create-vmss.ps1
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  tests/std/tests/P0220R1_optional/test.cpp
Labels: high priority, infrastructure

#1578 feature/format: Merge toolset update
  .vscode/settings.json
  CMakeLists.txt
  README.md
  azure-devops/create-vmss.ps1
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  stl/CMakeLists.txt
  stl/inc/algorithm
  stl/inc/future
  stl/inc/header-units.json
  stl/inc/limits
  stl/inc/memory
  stl/inc/regex
  stl/inc/sstream
  stl/inc/xlocale
  stl/inc/xlocnum
  stl/inc/xloctime
  stl/inc/xstring
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/GH_001541_case_sensitive_boolalpha/env.lst
  tests/std/tests/GH_001541_case_sensitive_boolalpha/test.cpp
  tests/std/tests/P0220R1_optional/test.cpp
  tests/std/tests/P0408R7_efficient_access_to_stringbuf_buffer/env.lst
  tests/std/tests/P0408R7_efficient_access_to_stringbuf_buffer/test.cpp
  tests/std/tests/P0896R4_ranges_alg_unique/test.cpp
  tests/std/tests/P0896R4_ranges_alg_unique_copy/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
  tests/std/tests/VSO_0000000_fancy_pointers/test.compile.pass.cpp
  tests/std/tests/VSO_0180469_fill_family/test.cpp
Labels: infrastructure, uncharted

#1589 Move the macro for MSVC-internal testing
  tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
Labels: test

#1146 Use _mm_pause, load loop
  stl/inc/atomic
  stl/inc/xatomic.h
  tests/std/include/test_atomic_wait.hpp
Labels: performance

#1573 Implement LWG-3171 "LWG-2989 breaks directory_entry stream insertion"
  stl/inc/filesystem
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: LWG

#1574 _NODISCARD for <hash_map> and <hash_set>
  stl/inc/hash_map
  stl/inc/hash_set
Labels: enhancement

#1383 Implement allocating algorithms for ranges
  stl/inc/algorithm
  stl/inc/execution
  stl/inc/memory
  stl/inc/xmemory
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_alg_inplace_merge/env.lst
  tests/std/tests/P0896R4_ranges_alg_inplace_merge/test.cpp
  tests/std/tests/P0896R4_ranges_alg_stable_partition/env.lst
  tests/std/tests/P0896R4_ranges_alg_stable_partition/test.cpp
  tests/std/tests/P0896R4_ranges_alg_stable_sort/env.lst
  tests/std/tests/P0896R4_ranges_alg_stable_sort/test.cpp
Labels: cxx20, ranges

#1505 Build, but don't run, ARM/ARM64 tests
  azure-devops/checkout-sources.yml
  azure-devops/cmake-configure-build.yml
  azure-devops/cross-build.yml
  azure-devops/native-build-test.yml
  azure-devops/run-build.yml
  azure-devops/run-tests.yml
  azure-devops/vcpkg-dependencies.yml
  azure-pipelines.yml
  stl/inc/atomic
  stl/inc/bit
  tests/CMakeLists.txt
  tests/libcxx/lit.site.cfg.in
  tests/std/include/test_atomic_wait.hpp
  tests/std/lit.site.cfg.in
  tests/std/tests/GH_000690_overaligned_function/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/tr1/lit.site.cfg.in
  tests/utils/stl/test/format.py
  tests/utils/stl/test/tests.py
Labels: ARM, ARM64, test

#1590 feature/spaceship: Clause 32: Thread support
  stl/inc/thread
  tests/std/tests/P1614R2_spaceship/test.cpp
Labels: cxx20, spaceship

#1575 <type_traits>: Implement Layout-compatibility and Pointer-interconvertibility Traits
  stl/inc/type_traits
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/env.lst
  tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx20
