Repository microsoft/STL, pull requests merged in 2021-02, with the labels that each got.

#1599 Status Chart: Semi-monthly update
  daily_table.js
  index.html
  monthly_table.js
  package-lock.json
  package.json
  weekly_table.js
Labels: documentation, uncharted

#323 <chrono> Partially implement P0355R7
  stl/inc/chrono
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/P0355R7_calendars_and_time_zones_clocks/env.lst
  tests/std/tests/P0355R7_calendars_and_time_zones_clocks/test.compile.pass.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_dates/env.lst
  tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_dates_literals/env.lst
  tests/std/tests/P0355R7_calendars_and_time_zones_dates_literals/test.compile.pass.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_hms/env.lst
  tests/std/tests/P0355R7_calendars_and_time_zones_hms/test.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_time_point_and_durations/env.lst
  tests/std/tests/P0355R7_calendars_and_time_zones_time_point_and_durations/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
Labels: cxx20

#1585 <xmemory>: remove deprecated std::allocator members in C++20
  stl/inc/xmemory
  stl/inc/yvals_core.h
  tests/std/tests/Dev11_0920385_list_sort_allocator/test.cpp
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
  tests/tr1/tests/memory/test.cpp
Labels: bug

#1608 Status Chart: <chrono> update
  daily_table.js
  package-lock.json
Labels: documentation, uncharted

#1612 Update cgmanifest.json for 16.9
  docs/cgmanifest.json
Labels: documentation

#1605 Attempt to fix VM llvm-project submodule contamination
  azure-devops/checkout-sources.yml
Labels: infrastructure

#1609 README.md: Update Azure Pipelines badge, Working Paper
  README.md
Labels: documentation

#1593 feature/spaceship: Clause 28: Localization, Clause 29: Input/output
  stl/inc/filesystem
  stl/inc/xlocale
  tests/std/tests/P1614R2_spaceship/test.cpp
Labels: cxx20, spaceship

#1546 Prepare the constexpr machinery needed for string and vector
  stl/inc/regex
  stl/inc/xmemory
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx20

#1587 charconv internal functions for wchar_t buffers
  stl/inc/xcharconv_ryu.h
  stl/inc/xcharconv_ryu_tables.h
  tests/std/tests/P0067R5_charconv/test.cpp
  tests/std/tests/P0067R5_charconv/test.hpp
  tests/std/tests/P0067R5_charconv/wchar_test_cases.hpp
Labels: enhancement, format

#1633 Status Chart: Weekly update, save/load options
  daily_table.js
  gather_stats.js
  package-lock.json
  package.json
  usernames_contributors.txt
  weekly_table.js
Labels: documentation

#1627 feature/spaceship: Clause 26: Numerics
  stl/inc/complex
  stl/inc/valarray
  tests/std/tests/P1614R2_spaceship/test.cpp
Labels: cxx20, spaceship

#1625 Implement a packed format store
  stl/inc/format
  tests/std/test.lst
  tests/std/tests/P0645R10_text_formatting_args/env.lst
  tests/std/tests/P0645R10_text_formatting_args/test.cpp
Labels: cxx20, format

#1636 VS 2019 16.9 Preview 4 toolset update
  README.md
  azure-pipelines.yml
  tools/CMakeLists.txt
Labels: infrastructure

#1531 <random>: Improve binomial_distribution accuracy
  stl/inc/random
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/GH_001530_binomial_accuracy/env.lst
  tests/std/tests/GH_001530_binomial_accuracy/test.cpp
Labels: bug

#1601 <random>: Fix min/max of a few random distributions and gamma_distribution::param_type::operator==
  stl/inc/random
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: bug

#1604 Add test coverage for GH-1603 (default_initializable)
  tests/std/tests/P0898R3_concepts/test.cpp
Labels: test

#1622 <charconv>: small optimization of _Integer_to_chars for bases 3,6,5,7,9
  stl/inc/charconv
Labels: performance

#1626 Update _MSVC_STL_UPDATE for Feb 2021
  stl/inc/yvals_core.h
Labels: enhancement

#1628 Partially activate more Header Units test coverage
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
Labels: test

#1634 Optimize calendar date conversion
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp
Labels: performance

#1639 <xhash>: Fix compiler error when dllexporting a class derived from unordered_set
  stl/inc/xhash
  tests/std/test.lst
  tests/std/tests/GH_001638_dllexport_derived_classes/env.lst
  tests/std/tests/GH_001638_dllexport_derived_classes/test.compile.pass.cpp
Labels: bug

#1643 feature/format: Merge toolset update
  README.md
  azure-pipelines.yml
  stl/inc/charconv
  stl/inc/chrono
  stl/inc/random
  stl/inc/regex
  stl/inc/xhash
  stl/inc/xmemory
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/GH_001530_binomial_accuracy/env.lst
  tests/std/tests/GH_001530_binomial_accuracy/test.cpp
  tests/std/tests/GH_001638_dllexport_derived_classes/env.lst
  tests/std/tests/GH_001638_dllexport_derived_classes/test.compile.pass.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp
  tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tools/CMakeLists.txt
Labels: infrastructure, uncharted

#1644 feature/spaceship: Merge toolset update
  README.md
  azure-pipelines.yml
  stl/inc/charconv
  stl/inc/chrono
  stl/inc/random
  stl/inc/regex
  stl/inc/xhash
  stl/inc/xmemory
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/GH_001530_binomial_accuracy/env.lst
  tests/std/tests/GH_001530_binomial_accuracy/test.cpp
  tests/std/tests/GH_001638_dllexport_derived_classes/env.lst
  tests/std/tests/GH_001638_dllexport_derived_classes/test.compile.pass.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp
  tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tools/CMakeLists.txt
Labels: infrastructure, uncharted

#1651 Status Chart: Weekly update, strict mode
  daily_table.js
  gather_stats.js
  index.html
  monthly_table.js
  package-lock.json
  package.json
  weekly_table.js
Labels: documentation, uncharted

#1407 Implement constexpr std::vector
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/Dev10_816787_swap_vector_bool_elements/test.cpp
  tests/std/tests/P0784R7_library_machinery/env.lst
  tests/std/tests/P0784R7_library_machinery/test.cpp
  tests/std/tests/P1004R2_constexpr_vector/env.lst
  tests/std/tests/P1004R2_constexpr_vector/test.cpp
  tests/std/tests/P1004R2_constexpr_vector_bool/env.lst
  tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx20

#1654 Azure Pipelines: Move VMSS location, don't publish artifacts
  azure-devops/create-vmss.ps1
  azure-devops/cross-build.yml
  azure-pipelines.yml
Labels: high priority, infrastructure

#1656 feature/format: Merge VMSS update
  azure-devops/create-vmss.ps1
  azure-devops/cross-build.yml
  azure-pipelines.yml
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/Dev10_816787_swap_vector_bool_elements/test.cpp
  tests/std/tests/P0784R7_library_machinery/env.lst
  tests/std/tests/P0784R7_library_machinery/test.cpp
  tests/std/tests/P1004R2_constexpr_vector/env.lst
  tests/std/tests/P1004R2_constexpr_vector/test.cpp
  tests/std/tests/P1004R2_constexpr_vector_bool/env.lst
  tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: infrastructure, uncharted

#1655 Feature/spaceship: Merge VMSS update
  azure-devops/create-vmss.ps1
  azure-devops/cross-build.yml
  azure-pipelines.yml
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/Dev10_816787_swap_vector_bool_elements/test.cpp
  tests/std/tests/P0784R7_library_machinery/env.lst
  tests/std/tests/P0784R7_library_machinery/test.cpp
  tests/std/tests/P1004R2_constexpr_vector/env.lst
  tests/std/tests/P1004R2_constexpr_vector/test.cpp
  tests/std/tests/P1004R2_constexpr_vector_bool/env.lst
  tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: infrastructure, uncharted

#1629 <variant>: P0608R3 Improving variant's converting constructor/assignment
  stl/inc/variant
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P0088R3_variant/env.lst
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P0608R3_improved_variant_converting_constructor/env.lst
  tests/std/tests/P0608R3_improved_variant_converting_constructor/test.cpp
Labels: cxx20

#1645 feature/spaceship: Clause 23: Iterators
  stl/inc/iterator
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: cxx20, spaceship

#1632 Fix reliability issues in the parallelize tool
  tools/inc/stljobs.h
Labels: infrastructure

#1548 Fix uninitialized_meow memcpy optimization
  stl/inc/memory
  stl/inc/xmemory
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_alg_uninitialized_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_uninitialized_copy_n/test.cpp
  tests/std/tests/P0896R4_ranges_alg_uninitialized_move/test.cpp
  tests/std/tests/P0896R4_ranges_alg_uninitialized_move_n/test.cpp
Labels: bug

#1635 feature/spaceship: Clause 21: Strings
  stl/inc/xstring
  tests/std/tests/P1614R2_spaceship/test.cpp
Labels: cxx20, spaceship

#1616 std::format parsing callbacks and machinery
  stl/inc/format
  tests/std/test.lst
  tests/std/tests/P0645R10_text_formatting_formatting/env.lst
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
  tests/std/tests/P0645R10_text_formatting_parsing/test.cpp
Labels: cxx20, format

#1657 feature/spaceship: Clause 20: variant, monostate
  stl/inc/variant
  tests/std/tests/P1614R2_spaceship/test.cpp
Labels: cxx20, spaceship

#1602 P1614R2 Spaceship: Clause 27: Time (partial, pre-C++20 types)
  stl/inc/chrono
  tests/std/test.lst
  tests/std/tests/P1614R2_spaceship/env.lst
  tests/std/tests/P1614R2_spaceship/test.cpp
Labels: cxx20, spaceship

#1648 feature/spaceship: Clause 22: Container Iterators
  stl/inc/array
  stl/inc/deque
  stl/inc/filesystem
  stl/inc/forward_list
  stl/inc/iterator
  stl/inc/list
  stl/inc/vector
  stl/inc/xhash
  stl/inc/xstring
  stl/inc/xtree
  tests/std/tests/P1614R2_spaceship/test.cpp
Labels: cxx20, spaceship

#1564 <syncstream>: implement basic_syncbuf and basic_osyncstream
  stl/CMakeLists.txt
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/header-units.json
  stl/inc/iosfwd
  stl/inc/ostream
  stl/inc/syncstream
  stl/inc/yvals_core.h
  stl/msbuild/stl_atomic_wait/stl_atomic_wait.files.settings.targets
  stl/msbuild/stl_base/stl.files.settings.targets
  stl/src/msvcp_atomic_wait.src
  stl/src/syncstream.cpp
  tests/std/test.lst
  tests/std/tests/P0053R7_cpp_synchronized_buffered_ostream/env.lst
  tests/std/tests/P0053R7_cpp_synchronized_buffered_ostream/test.cpp
  tests/std/tests/P0053R7_cpp_synchronized_buffered_ostream/test.hpp
  tests/std/tests/P0753R2_manipulators_for_cpp_synchronized_buffered_ostream/env.lst
  tests/std/tests/P0753R2_manipulators_for_cpp_synchronized_buffered_ostream/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
  tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
  tests/std/tests/VSO_0000000_fancy_pointers/test.compile.pass.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tests/std/tests/include_each_header_alone_matrix.lst
Labels: cxx20

#1661 <format>: vformat_to parsing and escaping tests
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Labels: cxx20, format

#1665 feature/spaceship: Clause 20: various synthesized equality operators
  stl/inc/functional
  stl/inc/scoped_allocator
  stl/inc/xmemory
  stl/inc/xpolymorphic_allocator.h
  tests/std/tests/P1614R2_spaceship/test.cpp
Labels: cxx20, spaceship

#1660 feature/spaceship: Clause 20: bitset, charconv, and typeindex
  stl/inc/bitset
  stl/inc/charconv
  stl/inc/typeindex
  stl/inc/xcharconv.h
  tests/std/tests/P1614R2_spaceship/test.cpp
Labels: cxx20, spaceship

#1669 feature/spaceship: Merge duration/time_point tests from main
  stl/CMakeLists.txt
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/chrono
  stl/inc/header-units.json
  stl/inc/iosfwd
  stl/inc/memory
  stl/inc/ostream
  stl/inc/syncstream
  stl/inc/variant
  stl/inc/xmemory
  stl/inc/xutility
  stl/inc/yvals_core.h
  stl/msbuild/stl_atomic_wait/stl_atomic_wait.files.settings.targets
  stl/msbuild/stl_base/stl.files.settings.targets
  stl/src/msvcp_atomic_wait.src
  stl/src/syncstream.cpp
  tests/std/test.lst
  tests/std/tests/P0053R7_cpp_synchronized_buffered_ostream/env.lst
  tests/std/tests/P0053R7_cpp_synchronized_buffered_ostream/test.cpp
  tests/std/tests/P0053R7_cpp_synchronized_buffered_ostream/test.hpp
  tests/std/tests/P0088R3_variant/env.lst
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P0608R3_improved_variant_converting_constructor/env.lst
  tests/std/tests/P0608R3_improved_variant_converting_constructor/test.cpp
  tests/std/tests/P0753R2_manipulators_for_cpp_synchronized_buffered_ostream/env.lst
  tests/std/tests/P0753R2_manipulators_for_cpp_synchronized_buffered_ostream/test.cpp
  tests/std/tests/P0896R4_ranges_alg_uninitialized_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_uninitialized_copy_n/test.cpp
  tests/std/tests/P0896R4_ranges_alg_uninitialized_move/test.cpp
  tests/std/tests/P0896R4_ranges_alg_uninitialized_move_n/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
  tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
  tests/std/tests/P1614R2_spaceship/test.cpp
  tests/std/tests/VSO_0000000_fancy_pointers/test.compile.pass.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tests/std/tests/include_each_header_alone_matrix.lst
  tools/inc/stljobs.h
Labels: spaceship, test

#1666 feature/spaceship: Clause 20: unique_ptr/shared_ptr
  stl/inc/memory
  tests/std/tests/P1614R2_spaceship/test.cpp
  tests/tr1/tests/memory1/test.cpp
Labels: cxx20, spaceship

#1672 feature/spaceship: Clause 17: Feature-test macro, yvals_core.h comment
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx20, spaceship

#1206 feature/spaceship: Clause 20: pair, tuple, optional
  stl/inc/compare
  stl/inc/optional
  stl/inc/regex
  stl/inc/tuple
  stl/inc/utility
  tests/std/tests/P1614R2_spaceship/test.cpp
Labels: cxx20, spaceship

#1667 Status Chart: Weekly update, show/hide params
  daily_table.js
  index.html
  package-lock.json
  weekly_table.js
Labels: documentation

#1690 Enable constexpr vector internal tests
  stl/inc/vector
  tests/std/tests/P1004R2_constexpr_vector/test.cpp
Labels: test

#1567 Test deduction guides with header units internally
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
Labels: test

#1675 <format>: initial replacement field tests (and numeric arg indexing)
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Labels: cxx20, format, test

#1678 P1614R2 Adding Spaceship <=> To The Library
  stl/inc/array
  stl/inc/bitset
  stl/inc/charconv
  stl/inc/compare
  stl/inc/complex
  stl/inc/deque
  stl/inc/filesystem
  stl/inc/forward_list
  stl/inc/functional
  stl/inc/iterator
  stl/inc/list
  stl/inc/map
  stl/inc/memory
  stl/inc/optional
  stl/inc/queue
  stl/inc/ranges
  stl/inc/regex
  stl/inc/scoped_allocator
  stl/inc/set
  stl/inc/stack
  stl/inc/system_error
  stl/inc/thread
  stl/inc/tuple
  stl/inc/typeindex
  stl/inc/unordered_map
  stl/inc/unordered_set
  stl/inc/utility
  stl/inc/valarray
  stl/inc/variant
  stl/inc/vector
  stl/inc/xcharconv.h
  stl/inc/xhash
  stl/inc/xlocale
  stl/inc/xmemory
  stl/inc/xpolymorphic_allocator.h
  stl/inc/xstring
  stl/inc/xtree
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/Dev11_0135139_vector_bool_comparisons/env.lst
  tests/std/tests/Dev11_0135139_vector_bool_comparisons/test.cpp
  tests/std/tests/Dev11_0135139_vector_bool_equality_perf/test.cpp
  tests/std/tests/P1614R2_spaceship/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tests/tr1/tests/memory1/test.cpp
Labels: cxx20, spaceship

#1697 Skip tr1/tests/thread, minor style cleanups
  stl/inc/memory
  stl/inc/queue
  stl/inc/scoped_allocator
  stl/inc/stack
  tests/tr1/expected_results.txt
  tests/tr1/test.lst
Labels: test

#1646 Comment calendar date conversion algorithm
  stl/inc/chrono
Labels: chrono, documentation

#1663 <chrono>: fix year_month_day_last::day()
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp
Labels: bug, chrono

#1664 Update outdated test options in readme (#1659)
  README.md
Labels: documentation

#1668 Uses-Allocator and guaranteed copy elision For piecewise construction
  stl/inc/scoped_allocator
  stl/inc/xmemory
  stl/inc/xpolymorphic_allocator.h
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/P0475R1_P0591R4_uses_allocator_construction/env.lst
  tests/std/tests/P0475R1_P0591R4_uses_allocator_construction/test.cpp
  tests/std/tests/VSO_0224478_scoped_allocator/test.cpp
Labels: cxx20

#1670 to_chars libc++ compatibility
  stl/inc/xcharconv_ryu.h
  tests/std/tests/P0067R5_charconv/test.cpp
  tests/std/tests/P0220R1_searchers/test.cpp
Labels: enhancement

#1689 <memory>: Guard aligned allocation with __cpp_aligned_new
  stl/inc/memory
Labels: bug

#1692 <xkeycheck.h>: Fix circular inclusion for Header Units
  stl/inc/xkeycheck.h
Labels: bug

#1693 Implement ranges::iota_view
  stl/inc/ranges
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_iota/env.lst
  tests/std/tests/P0896R4_views_iota/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
Labels: cxx20, ranges

#1696 <format>: Fix _Get_format_arg_storage_type
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Labels: cxx20, format

#1502 [P0980R1] constexpr std::string
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/xstring
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/include/test_death.hpp
  tests/std/test.lst
  tests/std/tests/P0218R1_filesystem/test.cpp
  tests/std/tests/P0980R1_constexpr_strings/env.lst
  tests/std/tests/P0980R1_constexpr_strings/test.cpp
  tests/std/tests/VSO_0102478_moving_allocators/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx20
