Repository microsoft/STL, pull requests merged in 2021-10, with the labels that each got.

#2229 Status Chart: Weekly updates, PR Age max, call `toFixed()` directly
  gather_stats.js
  index.html
  package-lock.json
  package.json
  weekly_table.js
Labels: documentation

#2088 `<random>`: Fixes subtract_with_carry_engine io
  stl/inc/random
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/GH_000442_random_subtract_with_carry_engine_io/env.lst
  tests/std/tests/GH_000442_random_subtract_with_carry_engine_io/test.cpp
Labels: bug

#2096 Use static_cast for <void*> outside of converting to and from integers
  stl/inc/memory_resource
  stl/inc/xmemory
  stl/src/ppltasks.cpp
Labels: enhancement

#2203 Optimize `std::count` even more for `vector<👻>`
  stl/inc/limits
  stl/inc/vector
Labels: performance

#2220 condition_variable_any with stop_token: Unlock inner mutex before relocking outer mutex
  stl/inc/condition_variable
Labels: bug

#2226 <yvals_core.h> Remove unnecessary _HAS_CXX23 definition
  stl/inc/yvals_core.h
Labels: enhancement

#2260 LWG-3422: Issues of seed_seq's constructors
  stl/inc/random
  tests/std/test.lst
  tests/std/tests/LWG3422_seed_seq_ctors/env.lst
  tests/std/tests/LWG3422_seed_seq_ctors/test.compile.pass.cpp
Labels: LWG

#2262 Implement P1147R1 "Printing volatile Pointers"
  stl/inc/ostream
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P1147R1_printing_volatile_pointers/env.lst
  tests/std/tests/P1147R1_printing_volatile_pointers/test.cpp
Labels: cxx23

#2269 Remove LWG comments
  stl/inc/optional
  stl/inc/ranges
  stl/inc/syncstream
  stl/inc/xstring
  stl/inc/xutility
Labels: LWG

#2284 Compile TypeScript in `update-status-chart.yml`
  .github/workflows/update-status-chart.yml
Labels: infrastructure, uncharted
