Repository microsoft/STL, pull requests merged in 2021-06, with the labels that each got.

#1829 Build the STL with /ZH:SHA_256
  CMakeLists.txt
Labels: build

#1753 Static partition forward ranges correctly
  stl/inc/execution
  tests/std/include/parallel_algorithms_utilities.hpp
  tests/std/tests/P0024R2_parallel_algorithms_adjacent_find/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_count/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_find_first_of/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_is_heap/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_is_partitioned/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_is_sorted/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_mismatch/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_set_difference/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_set_intersection/test.cpp
Labels: bug

#1927 Split/fuse `xlocinfo.h` to fix unintentional export in `format.cpp`
  stl/CMakeLists.txt
  stl/inc/__msvc_xlocinfo_types.hpp
  stl/inc/header-units.json
  stl/inc/xlocinfo
  stl/inc/xlocinfo.h
  stl/src/_tolower.cpp
  stl/src/_toupper.cpp
  stl/src/format.cpp
  stl/src/xgetwctype.cpp
  stl/src/xmbtowc.cpp
  stl/src/xstrcoll.cpp
  stl/src/xstrxfrm.cpp
  stl/src/xtowlower.cpp
  stl/src/xtowupper.cpp
  stl/src/xwcscoll.cpp
  stl/src/xwcsxfrm.cpp
  stl/src/xwctomb.cpp
Labels: bug, format

#1933 <algorithm>: fix GH-1932
  stl/inc/algorithm
  tests/std/tests/P0896R4_ranges_alg_unique_copy/test.cpp
Labels: bug

#1953 Toolset update: VS 2019 16.11 Preview 1
  README.md
  azure-devops/create-vmss.ps1
  azure-pipelines.yml
  tests/utils/stl/test/tests.py
Labels: infrastructure

#1131 Specialize find and count for vector<bool>
  stl/inc/bit
  stl/inc/limits
  stl/inc/vector
  stl/inc/xutility
  tests/std/tests/GH_000625_vector_bool_optimization/test.cpp
Labels: performance

#1810 Optimizations for unreachable sentinels
  stl/inc/algorithm
  stl/inc/memory
  stl/inc/xmemory
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_alg_equal/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find/test.cpp
  tests/std/tests/P0896R4_ranges_alg_lexicographical_compare/test.cpp
  tests/std/tests/P0896R4_ranges_alg_uninitialized_copy_n/env.lst
  tests/std/tests/P0896R4_ranges_alg_uninitialized_copy_n/test.cpp
  tests/std/tests/P0896R4_ranges_alg_uninitialized_move_n/env.lst
  tests/std/tests/P0896R4_ranges_alg_uninitialized_move_n/test.cpp
Labels: performance, ranges

#1950 `<type_traits>`: Implement `is_scoped_enum`
  stl/inc/type_traits
  stl/inc/yvals_core.h
  tests/std/tests/VSO_0000000_instantiate_type_traits/test.compile.pass.cpp
  tests/std/tests/VSO_0000000_type_traits/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#1951 `<format>`: parameter name consistency: `_First`/`_Last` vs `_Begin`/`_End`
  stl/inc/format
Labels: enhancement, format

#1955 <yvals_core.h>: Update _MSVC_STL_UPDATE to June 2021
  stl/inc/yvals_core.h
Labels: enhancement

#1958 <ranges>: Relax constraints on view_drop and view_take range adaptors
  stl/inc/ranges
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
Labels: bug, ranges

#1962 Fix missing `_CONSTEXPR20_CONTAINER` on _Alloc_temporary
  stl/inc/xmemory
  tests/std/tests/P1004R2_constexpr_vector/test.cpp
Labels: bug

#1966 Adding `native_handle` to `jthread`
  stl/inc/thread
Labels: bug

#1967 `<ranges>`: Remove "per LWG" comments
  stl/inc/ranges
Labels: LWG

#2004 Status Chart: Weekly updates, chart.js 3.3.2, `spanGaps: false`
  gather_stats.js
  index.html
  package-lock.json
  package.json
  weekly_table.js
Labels: documentation, uncharted

#2024 Status Chart: Weekly updates
  index.html
  package-lock.json
  package.json
  weekly_table.js
Labels: documentation, uncharted

#2014 Toolset update: VS 2019 16.11 Preview 2
  README.md
  azure-pipelines.yml
Labels: infrastructure

#2012 Implement P2325R3 Views Should Not Be Required To Be Default Constructible
  stl/inc/iterator
  stl/inc/ranges
  stl/inc/span
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/include/range_algorithm_support.hpp
  tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
  tests/std/tests/P0896R4_counted_iterator/test.cpp
  tests/std/tests/P0896R4_istream_view/test.cpp
  tests/std/tests/P0896R4_istream_view_death/test.cpp
  tests/std/tests/P0896R4_ranges_alg_adjacent_find/test.cpp
  tests/std/tests/P0896R4_ranges_alg_binary_search/test.cpp
  tests/std/tests/P0896R4_ranges_alg_equal/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_end/test.cpp
  tests/std/tests/P0896R4_ranges_alg_heap/test.cpp
  tests/std/tests/P0896R4_ranges_alg_includes/test.cpp
  tests/std/tests/P0896R4_ranges_alg_inplace_merge/test.cpp
  tests/std/tests/P0896R4_ranges_alg_is_permutation/test.cpp
  tests/std/tests/P0896R4_ranges_alg_lexicographical_compare/test.cpp
  tests/std/tests/P0896R4_ranges_alg_merge/test.cpp
  tests/std/tests/P0896R4_ranges_alg_minmax/test.cpp
  tests/std/tests/P0896R4_ranges_alg_mismatch/test.cpp
  tests/std/tests/P0896R4_ranges_alg_nth_element/test.cpp
  tests/std/tests/P0896R4_ranges_alg_partial_sort_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_partition/test.cpp
  tests/std/tests/P0896R4_ranges_alg_partition_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_partition_point/test.cpp
  tests/std/tests/P0896R4_ranges_alg_permutations/test.cpp
  tests/std/tests/P0896R4_ranges_alg_reverse/test.cpp
  tests/std/tests/P0896R4_ranges_alg_reverse_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_set_difference/test.cpp
  tests/std/tests/P0896R4_ranges_alg_set_intersection/test.cpp
  tests/std/tests/P0896R4_ranges_alg_set_symmetric_difference/test.cpp
  tests/std/tests/P0896R4_ranges_alg_set_union/test.cpp
  tests/std/tests/P0896R4_ranges_alg_sort/test.cpp
  tests/std/tests/P0896R4_ranges_alg_stable_partition/test.cpp
  tests/std/tests/P0896R4_ranges_alg_stable_sort/test.cpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
  tests/std/tests/P0896R4_ranges_ref_view/test.cpp
  tests/std/tests/P0896R4_ranges_subrange/test.compile.pass.cpp
  tests/std/tests/P0896R4_ranges_test_machinery/test.compile.pass.cpp
  tests/std/tests/P0896R4_stream_iterators/test.cpp
  tests/std/tests/P0896R4_views_all/test.cpp
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_drop_while/test.cpp
  tests/std/tests/P0896R4_views_drop_while_death/test.cpp
  tests/std/tests/P0896R4_views_elements/test.cpp
  tests/std/tests/P0896R4_views_filter/test.cpp
  tests/std/tests/P0896R4_views_filter_death/test.cpp
  tests/std/tests/P0896R4_views_join/test.cpp
  tests/std/tests/P0896R4_views_reverse/test.cpp
  tests/std/tests/P0896R4_views_split/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
  tests/std/tests/P0896R4_views_take_while/test.cpp
  tests/std/tests/P0896R4_views_take_while_death/test.cpp
  tests/std/tests/P0896R4_views_transform/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx20, high priority, ranges

#1478 P1679 string contains
  stl/inc/xstring
  stl/inc/yvals_core.h
  tests/std/tests/P0220R1_string_view/test.cpp
  tests/std/tests/P0980R1_constexpr_strings/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#1559 Fix filesystem::remove to remove readonly files also
  stl/src/filesystem.cpp
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: bug

#1631 <random>: Fix mersenne_twister_engine special case behavior
  stl/inc/random
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: bug

#1771 Cleanup vector a bit
  stl/inc/vector
Labels: enhancement

#1879 <chrono>: Adjust for leap seconds when formatting `file_time`
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
Labels: bug, chrono

#1894 <format>: Optimize container insertion
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Labels: format, performance

#1907 `<format>`: Simplify type-erased argument storage
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_args/test.cpp
Labels: enhancement, format

#1828 `<utility>`: Implement `to_underlying()`
  stl/inc/utility
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P1682R3_to_underlying/env.lst
  tests/std/tests/P1682R3_to_underlying/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#1940 `<chrono>`: Allows the parsing of year + day-of-year to a `time_point`
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp
Labels: bug, chrono

#1943 `filesystem::u8path` should accept `char8_t` sources
  stl/inc/filesystem
  tests/std/tests/P1423R3_char8_t_remediation/test.compile.pass.cpp
Labels: bug

#1968 `<fstream>`: Implement LWG-3430
  stl/inc/fstream
Labels: LWG

#1939 Repairing `counted_iterator`
  stl/inc/iterator
  stl/inc/yvals_core.h
  tests/std/tests/P0896R4_common_iterator/test.cpp
  tests/std/tests/P0896R4_counted_iterator/test.cpp
Labels: LWG

#1989 Adopt LWG-3555 `{transform,elements}_view::iterator::iterator_concept` should consider `const`-qualification of the underlying range
  stl/inc/ranges
Labels: LWG, ranges

#1990 Adopt LWG-3553 Useless constraint in `split_view::outer-iterator::value_type::begin()`
  stl/inc/ranges
Labels: LWG, ranges

#2007 Implement LWG-3548 shared_ptr construction from unique_ptr should move (not copy) the deleter
  stl/inc/memory
  tests/std/tests/Dev10_722102_shared_ptr_nullptr/test.cpp
Labels: LWG

#1987 `<chrono>` parse subseconds when the underlying type supports it
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp
Labels: bug, chrono

#2016 Update cgmanifest for 16.11
  docs/cgmanifest.json
Labels: documentation

#2018 update working draft revision to N4892
  README.md
Labels: documentation

#1995 P2166R1 Prohibiting basic_string And basic_string_view Construction From nullptr
  stl/inc/xstring
  stl/inc/yvals_core.h
  tests/std/tests/P0220R1_string_view/test.cpp
Labels: cxx23

#2006 update the feature-test macro for P2162R2 for variant
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/P2162R2_std_visit_for_derived_classes_from_variant/env.lst
  tests/std/tests/P2162R2_std_visit_for_derived_classes_from_variant/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#2015 Tests: Prepare for P2251 (trivially copyable `span`/`basic_string_view`)
  tests/std/tests/P0122R7_span/test.cpp
  tests/std/tests/P0220R1_string_view/test.cpp
Labels: test

#2017 `<chrono>` Estimate width of aligned chronat strings
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/env.lst
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
Labels: bug, chrono

#1992 Adopt LWG-3541 `indirectly_readable_traits` should be SFINAE-friendly for all types
  stl/inc/xutility
Labels: LWG

#2000 P1989R2 Range Constructor For `string_view`
  stl/inc/xstring
  stl/inc/yvals_core.h
  tests/std/tests/P0220R1_string_view/test.cpp
Labels: cxx23, ranges

#2011 GH-1674 is now LWG-3566
  stl/inc/optional
Labels: documentation

#2013 Don't rely on MSVC/Clang bugs in ranges test machinery
  tests/std/include/range_algorithm_support.hpp
Labels: ranges, test

#2010 Implement P2186R2 Removing Garbage Collection Support
  stl/inc/memory
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
  tests/tr1/tests/memory/test.cpp
Labels: cxx23
