Repository microsoft/STL, pull requests merged in 2022-04, with the labels that each got.

#2434 SSE2 & AVX2 std::find & std::count
  stl/inc/algorithm
  stl/inc/xutility
  stl/src/vector_algorithms.cpp
  tests/std/test.lst
  tests/std/tests/Dev11_0316853_find_memchr_optimization/test.cpp
  tests/std/tests/GH_002431_byte_range_find_with_unreachable_sentinel/env.lst
  tests/std/tests/GH_002431_byte_range_find_with_unreachable_sentinel/test.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: bug, performance

#2621 More various cleanups
  .github/workflows/update-status-chart.yml
  stl/inc/charconv
  stl/inc/codecvt
  stl/inc/cwctype
  stl/inc/future
  stl/inc/shared_mutex
  stl/inc/sstream
  stl/inc/variant
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/xtree
  tests/libcxx/expected_results.txt
Labels: enhancement

#2622 Use `_NODISCARD_FRIEND` everywhere
  stl/inc/charconv
  stl/inc/compare
  stl/inc/exception
  stl/inc/filesystem
  stl/inc/functional
  stl/inc/iosfwd
  stl/inc/iterator
  stl/inc/ranges
  stl/inc/span
  stl/inc/stop_token
  stl/inc/system_error
  stl/inc/valarray
  stl/inc/xcharconv.h
  stl/inc/xutility
Labels: bug

#2623 `<charconv>`: `_Divide` can trim `_Big_integer_flt` more efficiently
  stl/inc/charconv
Labels: performance

#2627 Remove parallel `copy_backward()` and `move_backward()`
  stl/inc/xutility
  tests/std/include/instantiate_algorithms.hpp
  tests/std/tests/Dev11_0253803_debug_pointer/test.cpp
Labels: bug

#2630 Implement workaround for LLVM-46269 by ensuring that constrained destructor appears after the unconstrained one
  stl/inc/iterator
  stl/inc/ranges
  tests/std/tests/P0896R4_common_iterator/test.cpp
  tests/std/tests/P0896R4_views_join/test.cpp
  tests/std/tests/P0896R4_views_single/test.cpp
Labels: bug, ranges

#2634 Update `_MSVC_STL_UPDATE`
  stl/inc/yvals_core.h
Labels: enhancement

#2632 Status Chart: Weekly updates, increase time units
  .github/workflows/compile-typescript.yml
  README.md
  index.html
  package-lock.json
  package.json
  src/status_chart.ts
  src/weekly_table.ts
Labels: documentation, uncharted

#2654 Coordinated fix for capturing continuation context for tasks in Desktop apps
  stl/CMakeLists.txt
  stl/msbuild/stl_base/msvcp.settings.targets
  stl/src/ppltasks.cpp
Labels: bug, affects redist

#2651 Toolset update: VS 2022 17.2 Preview 3
  CMakeLists.txt
  README.md
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
Labels: infrastructure

#2637 Update env.lsts for improved vcruntime detection of Clang mode
  tests/libcxx/usual_matrix.lst
  tests/std/tests/GH_002030_asan_annotate_vector/env.lst
  tests/std/tests/P0088R3_variant/env.lst
  tests/std/tests/P0645R10_text_formatting_legacy_text_encoding/env.lst
  tests/std/tests/P0912R5_coroutine/env.lst
  tests/std/tests/VSO_0157762_feature_test_macros/env.lst
  tests/std/tests/concepts_20_matrix.lst
  tests/std/tests/concepts_latest_matrix.lst
  tests/std/tests/floating_point_model_matrix.lst
  tests/std/tests/impure_matrix.lst
  tests/std/tests/include_each_header_alone_matrix.lst
  tests/std/tests/locale0_implib_cpp_matrix.lst
  tests/std/tests/native_17_matrix.lst
  tests/std/tests/native_matrix.lst
  tests/std/tests/native_winsdk_matrix.lst
  tests/std/tests/strict_concepts_20_matrix.lst
  tests/std/tests/strict_concepts_latest_matrix.lst
  tests/std/tests/strict_winsdk_concepts_20_matrix.lst
  tests/std/tests/strict_winsdk_concepts_latest_matrix.lst
  tests/std/tests/usual_17_matrix.lst
  tests/std/tests/usual_17_winsdk_matrix.lst
  tests/std/tests/usual_20_matrix.lst
  tests/std/tests/usual_20_winsdk_matrix.lst
  tests/std/tests/usual_latest_matrix.lst
  tests/std/tests/usual_latest_winsdk_matrix.lst
  tests/std/tests/usual_matrix.lst
  tests/tr1/env.lst
Labels: test

#2638 fix `treat_as_floating_point_v<_DurationType>`
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp
Labels: bug

#2640 Implement LWG-3121: `tuple` constructor constraints for `UTypes&&...` overloads
  stl/inc/tuple
  tests/std/test.lst
  tests/std/tests/LWG3121_constrained_tuple_forwarding_ctor/env.lst
  tests/std/tests/LWG3121_constrained_tuple_forwarding_ctor/test.cpp
Labels: LWG

#2647 `<bit>`: fix `countl_zero` on arm64
  stl/inc/bit
Labels: bug, ARM64

#2649 Guard use of custom attributes against macroization
  stl/inc/system_error
  stl/inc/yvals_core.h
  stl/src/excptptr.cpp
Labels: bug

#2656 Even more various cleanups
  stl/inc/atomic
  stl/inc/codecvt
  stl/inc/execution
  stl/inc/fstream
  stl/inc/random
  stl/inc/regex
  stl/inc/variant
  stl/inc/xlocale
  stl/inc/xlocmon
  stl/inc/xlocnum
  stl/inc/yvals.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/libcxx/usual_matrix.lst
  tests/std/tests/prefix.lst
  tests/tr1/prefix.lst
Labels: enhancement, test

#2658 Annotate some functions `_MSVC_CONSTEXPR`
  stl/inc/memory
  stl/inc/xutility
  stl/inc/yvals_core.h
Labels: enhancement, compiler

#2663 update cgmanifest for april
  docs/cgmanifest.json
Labels: documentation

#2119 <format>: Add grapheme clusterization support for width computation
  NOTICE.txt
  stl/CMakeLists.txt
  stl/inc/__msvc_format_ucd_tables.hpp
  stl/inc/algorithm
  stl/inc/format
  stl/inc/header-units.json
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/P0645R10_text_formatting_grapheme_clusterization/env.lst
  tests/std/tests/P0645R10_text_formatting_grapheme_clusterization/test.cpp
  tests/std/tests/P0645R10_text_formatting_utf8/test.cpp
  tools/parallelize/parallelize.cpp
  tools/unicode_properties_parse/.gitignore
  tools/unicode_properties_parse/grapheme_break_property_data_gen.py
  tools/unicode_properties_parse/grapheme_break_test_data_gen.py
Labels: enhancement, format

#2657 Reduce memory consumption of two ranges tests
  tests/std/tests/P0896R4_ranges_alg_remove_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_remove_copy_if/test.cpp
Labels: test, ranges
