Repository microsoft/STL, pull requests merged in 2022-12, with the labels that each got.

#3255 ppltasks.cpp: Fix bincompat for VS 2015
  stl/src/ppltasks.cpp
Labels: bug, high priority, affects redist

#3263 Status Chart: chart.js 4.0.1, weekly updates
  built/status_chart.mjs
  index.html
  package-lock.json
  package.json
  src/status_chart.ts
  src/weekly_table.ts
Labels: documentation

#3247 fix and rename `_Within_limits`, add tests
  stl/inc/algorithm
  stl/inc/xutility
  tests/std/tests/Dev11_0316853_find_memchr_optimization/test.cpp
Labels: bug, high priority

#3204 Add error_code, error_category support to visualizer
  stl/debugger/STL.natvis
Labels: visualizer

#3242 Implement LWG-3545 `std::pointer_traits` should be SFINAE-friendly
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/LWG3545_pointer_traits_sfinae/env.lst
  tests/std/tests/LWG3545_pointer_traits_sfinae/test.compile.pass.cpp
Labels: LWG

#3243 fix stl.natvis `std::optional<*>`
  stl/debugger/STL.natvis
Labels: visualizer

#3250 `<xlocale>`: Avoid allocation when comparing two `locale` values
  stl/inc/xlocale
  tests/std/tests/Dev09_056375_locale_cleanup/test.cpp
Labels: performance

#3252 `<__msvc_int128.hpp>`: Move UDLs to test code
  stl/inc/__msvc_int128.hpp
  tests/std/tests/P1522R1_difference_type/test.cpp
Labels: throughput

#3253 Convert arguments to double in `_GENERIC_MATH2_BASE`
  stl/inc/cmath
  tests/std/test.lst
  tests/std/tests/GH_003246_cmath_narrowing/env.lst
  tests/std/tests/GH_003246_cmath_narrowing/test.compile.pass.cpp
Labels: bug

#3256 `<execution>`, `<iosfwd>`: Cleanup for `operator!=` and `operator==` with reversed order
  stl/inc/execution
  stl/inc/iosfwd
Labels: throughput

#3258 Implement P2167R3 Improving `boolean-testable` Usage (for comparison fallback CPOs)
  stl/inc/compare
  stl/inc/yvals_core.h
  tests/std/tests/P0768R1_spaceship_cpos/test.cpp
Labels: cxx23

#3261 Implement LWG-3646 `std::ranges::view_interface::size` returns a signed type
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
Labels: LWG

#3262 `<algorithm>`: `count()` could use vectorization in C++14/C++17
  stl/inc/xutility
Labels: performance

#3264 Update _MSVC_STL_UPDATE to December 2022 #3251
  stl/inc/yvals_core.h
Labels: enhancement

#3265 Implement LWG-3746 `optional`'s spaceship with `U` with a type derived from `optional` causes infinite constraint meta-recursion
  stl/inc/optional
  stl/inc/xutility
  tests/std/tests/P1614R2_spaceship/test.cpp
Labels: LWG

#3266 Implement LWG-3717 `common_view::end` should improve `random_access_range` case
  stl/inc/ranges
  tests/std/tests/P0896R4_views_common/test.cpp
Labels: LWG

#3288 Toolset update: VS 2022 17.5 Preview 2
  CMakeLists.txt
  README.md
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  benchmarks/CMakeLists.txt
  stl/inc/xstring
  stl/inc/yvals_core.h
  tests/std/tests/P2321R2_views_zip/test.cpp
  tests/std/tests/P2465R3_standard_library_modules/env.lst
  tools/CMakeLists.txt
  tools/format/CMakeLists.txt
  tools/validate/CMakeLists.txt
Labels: infrastructure

#3164 Re-enable ASAN string annotations
  stl/CMakeLists.txt
  stl/inc/__msvc_sanitizer_annotate_container.hpp
  stl/inc/header-units.json
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/xstring
  tests/std/tests/GH_002030_asan_annotate_string/env.lst
  tests/std/tests/GH_002030_asan_annotate_string/test.cpp
  tests/std/tests/GH_002030_asan_annotate_vector/env.lst
  tests/std/tests/GH_002030_asan_annotate_vector/test.cpp
Labels: enhancement

#3206 Update `source_location` to use `__builtin_FUNCSIG`
  stl/inc/source_location
  tests/std/include/test_header_units_and_modules.hpp
  tests/std/tests/P1208R6_source_location/header.h
  tests/std/tests/P1208R6_source_location/test.cpp
Labels: enhancement

#3234 P2278R4: `views::as_const`
  stl/inc/ranges
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2278R4_views_as_const/env.lst
  tests/std/tests/P2278R4_views_as_const/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23

#3267 `<algorithm>`: `find`/`count` vectorize moar
  stl/inc/xutility
  tests/std/tests/Dev11_0316853_find_memchr_optimization/test.cpp
Labels: performance

#3268 P1223R5: find_last, et al.
  stl/inc/algorithm
  stl/inc/functional
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P1223R5_ranges_alg_find_last/env.lst
  tests/std/tests/P1223R5_ranges_alg_find_last/test.cpp
  tests/std/tests/P1223R5_ranges_alg_find_last_if/env.lst
  tests/std/tests/P1223R5_ranges_alg_find_last_if/test.cpp
  tests/std/tests/P1223R5_ranges_alg_find_last_if_not/env.lst
  tests/std/tests/P1223R5_ranges_alg_find_last_if_not/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23

#3269 Implement LWG-3743 `ranges::to`'s `reserve` may be ill-formed
  stl/inc/ranges
  stl/inc/xutility
  tests/std/tests/P1206R7_vector_from_range/test.cpp
Labels: LWG

#3270 Qualify calls to helpers that are in both _STD and _RANGES
  stl/inc/algorithm
  stl/inc/execution
  stl/inc/format
  stl/inc/memory
  stl/inc/regex
  stl/inc/vector
  stl/inc/xlocnum
  stl/inc/xmemory
  stl/inc/xutility
  tests/std/tests/P0784R7_library_machinery/test.cpp
Labels: bug

#3272 Implement LWG-3629 `make_error_code` and `make_error_condition` are customization points
  stl/inc/future
  stl/inc/system_error
  stl/inc/valarray
  stl/inc/xiosbase
  tests/std/tests/Dev11_0493504_error_category_lifetime/test.cpp
Labels: LWG

#3276 Implement LWG-3594 `inout_ptr` - inconsistent `release()` in destructor
  stl/inc/memory
  tests/std/tests/P1132R7_out_ptr/test.cpp
Labels: LWG

#3279 Use emplace_front in filesystem
  stl/inc/experimental/filesystem
Labels: enhancement

#3282 Add checks for invalid iterator when _ITERATOR_DEBUG_LEVEL is non-zero
  stl/inc/vector
Labels: enhancement

#3284 Enhancements for `future` and `shared_future`
  stl/inc/future
  tests/std/tests/Dev11_0235721_async_and_packaged_task/test.cpp
Labels: bug, enhancement

#3285 Don't use `<intrin0.h>` with Clang
  stl/inc/__msvc_int128.hpp
  stl/inc/bit
  stl/inc/charconv
  stl/inc/cmath
  stl/inc/limits
  stl/inc/xatomic.h
  stl/inc/xbit_ops.h
  stl/inc/xcharconv_ryu.h
  stl/inc/yvals_core.h
  stl/src/vector_algorithms.cpp
  tests/std/tests/Dev11_1086953_call_once_overhaul/test.cpp
Labels: bug
