Repository microsoft/STL, pull requests merged in 2022-03, with the labels that each got.

#2478 Untag dispatch _Directory_iterator
  stl/inc/experimental/filesystem
Labels: throughput

#2480 Untag dispatch string constructor
  stl/inc/xstring
Labels: throughput

#2570 Revert "Add diagnostics for sporadic failures in a `<format>` test"
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Labels: test

#2586 Implement LWG-3612: Inconsistent pointer alignment in `std::format`
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Labels: LWG, format

#2587 Implement LWG-3648: `format` should not print `bool` with `'c'`
  stl/inc/format
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Labels: LWG, format

#2095 Optimize fiopen
  stl/src/fiopen.cpp
Labels: performance, affects redist

#2568 Allow promises to be constructed for non-default-constructible types
  stl/inc/future
  tests/std/test.lst
  tests/std/tests/GH_002488_promise_not_default_constructible_types/env.lst
  tests/std/tests/GH_002488_promise_not_default_constructible_types/test.cpp
  tests/tr1/tests/future/test.cpp
Labels: bug

#2602 fix 2601: update month to March 2022
  stl/inc/yvals_core.h
Labels: enhancement

#2460 Don't move from contained value of optional<const T>
  stl/inc/optional
  tests/std/tests/P0220R1_optional/test.cpp
Labels: bug

#2575 Azure Pipelines: Upload test logs as artifacts
  azure-devops/cross-build.yml
  azure-devops/run-tests.yml
  tools/scripts/print_failures.py
Labels: infrastructure, test

#2579 format (and friends) should reject volatile arguments
  stl/inc/format
Labels: bug, format

#2565 Implement P2443R1 views::chunk_by
  stl/inc/algorithm
  stl/inc/ranges
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2443R1_views_chunk_by/env.lst
  tests/std/tests/P2443R1_views_chunk_by/test.cpp
  tests/std/tests/P2443R1_views_chunk_by_death/env.lst
  tests/std/tests/P2443R1_views_chunk_by_death/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23

#2418 Implement LWG-3571 and LWG-3570: `flush_emit` set `badbit` if the `emit` call fails
  stl/inc/ostream
  stl/inc/syncstream
  tests/std/tests/P0753R2_manipulators_for_cpp_synchronized_buffered_ostream/test.cpp
Labels: LWG

#2441 Orphan before reallocation in vector<:ghost:>
  stl/inc/deque
  stl/inc/vector
  tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp
Labels: bug

#2582 Implement P2273R3 `constexpr` `unique_ptr`
  stl/inc/memory
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2273R3_constexpr_unique_ptr/env.lst
  tests/std/tests/P2273R3_constexpr_unique_ptr/test.compile.pass.cpp
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tests/tr1/tests/memory3/test.cpp
Labels: cxx23

#2606 avoid relink `msvcp140_atomic_wait_oss.dll`
  stl/CMakeLists.txt
Labels: build

#2611 Toolset update: VS 2022 17.2 Preview 2
  README.md
  azure-devops/cmake-configure-build.yml
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  stl/inc/bit
  stl/inc/csignal
  stl/inc/cstdio
  tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
Labels: infrastructure

#2219 Misc untag dispatch
  stl/inc/algorithm
  stl/inc/exception
  stl/inc/functional
Labels: throughput

#2287 Untag dispatch tree
  stl/inc/xtree
Labels: throughput

#2383 Optimize reverse for 32-bit trivial types (optimize for all Intel and recent AMD, pessimize for Excavator/Zen/Zen+)
  stl/src/vector_algorithms.cpp
Labels: performance

#2471 Untag dispatch _Uses_allocator_construct
  stl/inc/xpolymorphic_allocator.h
Labels: throughput

#2479 Untag dispatch find_first_of
  stl/inc/xstring
Labels: throughput

#2484 Untag dispatch regex
  stl/inc/regex
Labels: throughput

#2576 Even rvalue `empty_view`s are `borrowed_range`s
  stl/inc/ranges
  tests/std/tests/P0896R4_views_empty/test.cpp
Labels: bug, ranges

#2589 Status Chart: Update GitHub Actions
  .github/workflows/update-status-chart.yml
Labels: infrastructure, uncharted

#2590 README.md: Convert Block Diagram to Mermaid
  README.md
  docs/msvc_libraries.plantuml
  docs/msvc_libraries.plantuml.svg
Labels: documentation

#2592 `<type_traits>`: Workaround for `common_reference`
  stl/inc/concepts
  stl/inc/type_traits
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/GH_002581_common_reference_workaround/env.lst
  tests/std/tests/GH_002581_common_reference_workaround/test.compile.pass.cpp
Labels: bug

#2595 Various cleanups
  stl/inc/algorithm
  stl/inc/chrono
  stl/inc/complex
  stl/inc/experimental/filesystem
  stl/inc/format
  stl/inc/istream
  stl/inc/limits
  stl/inc/locale
  stl/inc/random
  stl/inc/ranges
  stl/inc/regex
  stl/inc/variant
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/tests/Dev09_172666_tr1_tuple_odr/test.cpp
  tests/std/tests/Dev10_722102_shared_ptr_nullptr/test.cpp
  tests/std/tests/Dev11_0133625_locale0_implib_cpp/test.cpp
  tests/std/tests/Dev11_0535636_functional_overhaul/test.cpp
  tests/std/tests/Dev11_0579795_inplace_merge_out_of_memory/test.cpp
  tests/std/tests/GH_000545_include_compare/test_coroutine.cpp
  tests/std/tests/GH_001017_discrete_distribution_out_of_range/bad_random_engine.hpp
  tests/std/tests/GH_001411_core_headers/test.compile.pass.cpp
  tests/std/tests/P0083R3_splicing_maps_and_sets/test.cpp
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P0220R1_any/test.cpp
  tests/std/tests/P0912R5_coroutine/env.lst
  tests/std/tests/P0912R5_coroutine/test.cpp
  tests/std/tests/P0980R1_constexpr_strings/test.cpp
  tests/std/tests/VSO_0000000_container_allocator_constructors/test.cpp
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
  tests/std/tests/VSO_0000000_regex_use/test.cpp
  tests/std/tests/VSO_0102478_moving_allocators/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/env.lst
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tests/std/tests/VSO_0644691_utf_8_codecvt/test.cpp
  tests/tr1/expected_results.txt
  tests/tr1/test.lst
  tests/tr1/tests/atomic1/env.lst
  tests/tr1/tests/atomic1/test.cpp
  tests/tr1/tests/atomic2/env.lst
  tests/tr1/tests/atomic2/test.cpp
  tests/tr1/tests/atomic4/env.lst
  tests/tr1/tests/atomic4/test.cpp
  tests/tr1/tests/condition_variable/env.lst
  tests/tr1/tests/condition_variable/test.cpp
  tests/tr1/tests/thread/env.lst
  tests/tr1/tests/thread/test.cpp
Labels: enhancement

#2604 Split `<chrono>` into `<__msvc_chrono.hpp>`
  stl/CMakeLists.txt
  stl/inc/__msvc_chrono.hpp
  stl/inc/chrono
  stl/inc/condition_variable
  stl/inc/experimental/filesystem
  stl/inc/future
  stl/inc/header-units.json
  stl/inc/mutex
  stl/inc/semaphore
  stl/inc/thread
  tests/std/tests/P0660R10_jthread_and_cv_any/test.cpp
Labels: throughput, chrono

#2607 Add missing implicit SFINAE constraints
  stl/inc/any
  stl/inc/memory
  stl/inc/optional
  tests/std/test.lst
  tests/std/tests/GH_002299_implicit_sfinae_constraints/env.lst
  tests/std/tests/GH_002299_implicit_sfinae_constraints/test.compile.pass.cpp
Labels: bug

#2588 Status Chart: Mega TypeScript overhaul, PR/CI checks, libcxx change
  .github/workflows/compile-typescript.yml
  .gitignore
  .vscode/settings.json
  README.md
  built/status_chart.mjs
  index.html
  package-lock.json
  package.json
  src/daily_table.ts
  src/monthly_table.ts
  src/status_chart.ts
  src/tsconfig.json
  src/weekly_table.ts
  src_gather/gather_stats.ts
  src_gather/tsconfig.json
  status_chart.js
  tsconfig.universal.json
Labels: documentation, infrastructure

#2308 <deque>: _RERAISE -> scope guard
  stl/inc/deque
  tests/std/test.lst
  tests/std/tests/GH_002307_usual_scope_guard/env.lst
  tests/std/tests/GH_002307_usual_scope_guard/test.cpp
Labels: enhancement

#2457 `<filesystem>`: `path` should be `range`
  stl/inc/filesystem
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
Labels: bug, ranges

#2523 Fail time parsing if input is insufficient to supply all fields
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp
Labels: bug, chrono

#2600 Cache `_Fmt_codec<char, false>`
  stl/inc/format
Labels: performance, format

#2615 <stdatomic.h>: Fix preprocessor logic
  stl/inc/stdatomic.h
Labels: enhancement

#2616 README.md: WP N4910, drop Wandbox
  README.md
Labels: documentation, uncharted
