Repository microsoft/STL, pull requests merged in 2022-01, with the labels that each got.

#1898 `<algorithm>`: `ranges::clamp`, the projection may be applied at most three times.
  stl/inc/algorithm
  tests/std/tests/P0896R4_ranges_alg_minmax/test.cpp
Labels: bug, ranges

#2075 handle Clang-CUDA
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/yvals_core.h
Labels: bug

#2380 Untag dispatch find
  stl/inc/xutility
Labels: throughput

#2381 Use `/ALTERNATENAME` instead of checked-in OBJ files generated by `aliasobj`
  stl/CMakeLists.txt
  stl/aliases/amd64/std_init_once_begin_initialize.obj
  stl/aliases/amd64/std_init_once_complete.obj
  stl/aliases/arm/std_init_once_begin_initialize.obj
  stl/aliases/arm/std_init_once_complete.obj
  stl/aliases/arm64/std_init_once_begin_initialize.obj
  stl/aliases/arm64/std_init_once_complete.obj
  stl/aliases/arm64ec/std_init_once_begin_initialize.obj
  stl/aliases/arm64ec/std_init_once_complete.obj
  stl/aliases/chpe/std_init_once_begin_initialize.obj
  stl/aliases/chpe/std_init_once_complete.obj
  stl/aliases/generate.cmd
  stl/aliases/i386/std_init_once_begin_initialize.obj
  stl/aliases/i386/std_init_once_complete.obj
  stl/aliases/std_init_once_begin_initialize-arm64ec.txt
  stl/aliases/std_init_once_complete-arm64ec.txt
  stl/inc/mutex
  stl/msbuild/stl_base/stl.files.settings.targets
  stl/msbuild/stl_post/msvcp_post.settings.targets
  stl/src/xonce2.cpp
Labels: build, affects redist

#2455 updated _MSVC_STL_UPDATE to January 2022
  stl/inc/yvals_core.h
Labels: enhancement

#2482 Status Chart: Optimize, chart.js 3.7.0, weekly updates
  .vscode/settings.json
  README.md
  index.html
  package-lock.json
  package.json
  src/gather_stats.ts
  weekly_table.js
Labels: documentation

#2412 `<memory>`: Add `nullptr` check in `std::allocator`
  stl/inc/xmemory
  tests/std/tests/Dev09_126254_persistent_aux_allocators/test.cpp
Labels: bug

#2416 Activate `reverse_copy` optimization under C++20/C++23 mode
  stl/inc/algorithm
Labels: performance

#2423 `allocator::is_always_equal` is deprecated, not removed, in C++20
  stl/inc/xmemory
  stl/inc/yvals_core.h
Labels: bug

#2426 Render keys_view and values_view useless per LWG-3563
  stl/inc/ranges
  tests/std/tests/P0896R4_views_elements/test.cpp
Labels: LWG, ranges

#2429 `move_only_function`: more concise Python script
  tools/move_only_function_specializations/move_only_function_specializations.py
Labels: enhancement

#2435 Fix begin/end for valarray crashing on empty instance
  stl/inc/valarray
  tests/tr1/tests/valarray/test.cpp
Labels: bug

#2448 Remove some `strengthened` comments
  stl/inc/iterator
  stl/inc/ranges
  stl/inc/xutility
Labels: documentation, LWG

#2497 Status Chart: Modern modules, fix minor issues, weekly update
  index.html
  package-lock.json
  package.json
  src/gather_stats.ts
  tsconfig.json
  weekly_table.js
Labels: documentation

#2494 Add diagnostics for sporadic failures in a `<format>` test
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Labels: test, format

#2343 Alternative way to optimize `_Countr_zero`
  stl/inc/limits
  stl/inc/numeric
  tests/std/tests/Dev11_1074023_constexpr/test.cpp
Labels: performance

#2425 subrange `get<0>` requires a copyable iterator
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_subrange/test.compile.pass.cpp
Labels: LWG, ranges

#2424 Update counted_iterator's "same sequence" definition
  stl/inc/iterator
Labels: LWG, ranges

#2323 <format>: Implement P2418R2 support for `std::generator`-like types
  stl/inc/format
  stl/inc/yvals_core.h
  tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx20, format, defect report

#2450 `<ratio>`: Use `constexpr` functions instead of TMPs
  stl/inc/chrono
  stl/inc/ratio
Labels: enhancement

#2496 Toolset update: VS 2022 17.1 Preview 4, ARM64EC
  README.md
  azure-devops/create-vmss.ps1
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  stl/inc/format
  stl/inc/functional
  stl/inc/xutility
  tests/std/tests/P0220R1_optional/test.cpp
  tools/scripts/move_only_function_specializations.py
  tools/scripts/print_failures.py
Labels: infrastructure

#2509 Status Chart: Weekly update, extract `status_chart.js`
  index.html
  package-lock.json
  package.json
  status_chart.js
  weekly_table.js
Labels: documentation, uncharted
