Repository microsoft/STL, pull requests merged in 2022-08, with the labels that each got.

#2975 Status Chart: Fix mobile Safari
  README.md
  index.html
  package-lock.json
  package.json
  src/status_chart.ts
Labels: bug, documentation

#2897 Prettify STL error output
  stl/inc/any
  stl/inc/barrier
  stl/inc/bit
  stl/inc/charconv
  stl/inc/compare
  stl/inc/concepts
  stl/inc/coroutine
  stl/inc/execution
  stl/inc/expected
  stl/inc/filesystem
  stl/inc/format
  stl/inc/latch
  stl/inc/memory_resource
  stl/inc/numbers
  stl/inc/optional
  stl/inc/ranges
  stl/inc/semaphore
  stl/inc/source_location
  stl/inc/span
  stl/inc/spanstream
  stl/inc/stacktrace
  stl/inc/stdatomic.h
  stl/inc/stop_token
  stl/inc/string_view
  stl/inc/syncstream
  stl/inc/variant
  stl/inc/yvals.h
  stl/inc/yvals_core.h
Labels: enhancement

#2957 Implement LWG-3701: Make `formatter<remove_cvref_t<const charT[N]>, charT>` requirement explicit
  stl/inc/format
Labels: LWG, format

#2958 Implement P2520R0: `move_iterator<T*>` should be a random access iterator
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/GH_002581_common_reference_workaround/test.compile.pass.cpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#2959 Implement P2517R1: Conditional `noexcept` For `apply`
  stl/inc/tuple
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2517R1_apply_conditional_noexcept/env.lst
  tests/std/tests/P2517R1_apply_conditional_noexcept/test.compile.pass.cpp
Labels: cxx23

#2960 Implement P2408R5: Ranges Iterators As Inputs To Non-Ranges Algorithms
  stl/inc/algorithm
  stl/inc/execution
  stl/inc/functional
  stl/inc/regex
  stl/inc/vector
  stl/inc/xstring
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2408R5_ranges_iterators_to_classic_algorithms/env.lst
  tests/std/tests/P2408R5_ranges_iterators_to_classic_algorithms/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#2964 Pass rvalues to `_Seek_to` in `ranges::uninitialized_(copy|move)_n`
  stl/inc/memory
  tests/std/tests/P0896R4_ranges_alg_uninitialized_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_uninitialized_copy_n/test.cpp
  tests/std/tests/P0896R4_ranges_alg_uninitialized_move/test.cpp
  tests/std/tests/P0896R4_ranges_alg_uninitialized_move_n/test.cpp
Labels: bug, ranges

#2972 Implement P2417R2 More `constexpr` `bitset`
  stl/inc/bitset
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2417R2_constexpr_bitset/env.lst
  tests/std/tests/P2417R2_constexpr_bitset/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#2978 `<xutility>`: Some fixes around `std::ranges::enable_view`
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
Labels: bug, ranges

#2990 Temporarily disable ASAN string annotations
  stl/inc/xstring
  tests/std/tests/GH_002030_asan_annotate_string/env.lst
  tests/std/tests/GH_002030_asan_annotate_string/test.cpp
Labels: bug, test

#2890 `chunk_by_view`'s helper lambda returns `bool`
  stl/inc/ranges
  stl/inc/xutility
  tests/std/tests/P2443R1_views_chunk_by/test.cpp
Labels: bug, ranges

#2961 Implement LWG-3564: `transform_view::iterator<true>::value_type` and `iterator_category` should use `const F&`
  stl/inc/ranges
  tests/std/tests/P0896R4_views_transform/test.cpp
Labels: LWG, ranges

#2966 Implement LWG-3617: `function`/`packaged_task` deduction guides and deducing `this`
  stl/inc/type_traits
  tests/std/tests/Dev11_0535636_functional_overhaul/test.cpp
  tests/std/tests/P0433R2_deduction_guides/test.cpp
Labels: LWG

#2971 `<variant>`: Make `visit<R>` correctly handle conversions to non-movable types
  stl/inc/variant
  tests/std/tests/P0088R3_variant/test.cpp
Labels: bug

#2974 Implement P2445R1 `forward_like()`
  stl/inc/__msvc_iter_core.hpp
  stl/inc/utility
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2445R1_forward_like/env.lst
  tests/std/tests/P2445R1_forward_like/test.compile.pass.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#2988 `<chrono>`: `chrono::abs` incorrectly uses `?:` with expressions that don't always have a common type
  stl/inc/__msvc_chrono.hpp
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: bug, chrono

#2994 Add `__cpp_lib_concepts` guard for `__cpp_lib_move_iterator_concept`
  stl/inc/algorithm
  stl/inc/memory
  stl/inc/numeric
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/tests/GH_000545_include_compare/test_ranges.cpp
  tests/std/tests/P0220R1_string_view/test.cpp
  tests/std/tests/P0980R1_constexpr_strings/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: enhancement

#2981 P1899R3: `views::stride`
  stl/debugger/STL.natvis
  stl/inc/ranges
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P1899R3_views_stride/env.lst
  tests/std/tests/P1899R3_views_stride/test.cpp
  tests/std/tests/P1899R3_views_stride_death/env.lst
  tests/std/tests/P1899R3_views_stride_death/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23

#2996 `<xhash>` should avoid including `<xstring>`
  stl/inc/xhash
Labels: throughput

#3005 Status Chart: Filter out 'uncharted' issues
  index.html
  package-lock.json
  package.json
  src/weekly_table.ts
  src_gather/gather_stats.ts
  usernames_contributors.txt
Labels: documentation

#2980 `<xstring>`: `basic_string::_Is_elem_cptr` should be a variable template
  stl/inc/xstring
Labels: enhancement

#2998 `<functional>` should avoid including `<memory>`
  stl/inc/functional
  stl/inc/memory
  stl/inc/xmemory
Labels: throughput

#2999 Clarify that _two_ bugs are causing problems for the `visit<R>` test
  tests/std/tests/P0088R3_variant/test.cpp
Labels: test

#3001 <format>: all nans are "nan"
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Labels: bug, format

#3002 Use `_Invoke_result_t<_Urng&>` instead of `_Urng::result_type` in `_Rng_from_urng`
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_alg_shuffle/test.cpp
Labels: bug

#3011 Avoid `<atomic>` in `filesystem.cpp`
  stl/src/filesystem.cpp
Labels: bug, filesystem

#3017 Toolset update: VS 2022 17.4 Preview 1
  README.md
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  stl/inc/yvals_core.h
  tests/std/tests/P0220R1_string_view/test.cpp
Labels: infrastructure

#1263 detect forbidden aliasing
  stl/inc/algorithm
  stl/inc/vector
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/GH_000177_forbidden_aliasing/env.lst
  tests/std/tests/GH_000177_forbidden_aliasing/test.cpp
  tests/std/tests/P0202R3_constexpr_algorithm_and_exchange/test.cpp
  tests/std/tests/VSO_0180466_algorithm_overhauls/test.cpp
Labels: enhancement

#2973 `yvals_core.h`: Consistent diagnostics and warnings
  stl/inc/experimental/coroutine
  stl/inc/experimental/filesystem
  stl/inc/hash_map
  stl/inc/hash_set
  stl/inc/ranges
  stl/inc/type_traits
  stl/inc/yvals_core.h
Labels: enhancement

#3006 `<random>`: Improvements around `static constexpr` member variables
  stl/inc/random
Labels: enhancement

#3008 P2446R2: `views::as_rvalue`
  stl/inc/ranges
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2446R2_views_as_rvalue/env.lst
  tests/std/tests/P2446R2_views_as_rvalue/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23

#3018 Change `typedef` to `using`
  stl/inc/bitset
  stl/inc/ccomplex
  stl/inc/ciso646
  stl/inc/cstdalign
  stl/inc/cstdbool
  stl/inc/ctgmath
  stl/inc/filesystem
  stl/inc/functional
  stl/inc/map
  stl/inc/memory
  stl/inc/random
  stl/inc/system_error
  stl/inc/thread
  stl/inc/type_traits
  stl/inc/typeindex
  stl/inc/variant
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/xstddef
Labels: enhancement

#3019 Various cleanups
  stl/inc/forward_list
  stl/inc/list
  stl/inc/variant
  stl/inc/vector
  stl/inc/yvals.h
  stl/src/filesystem.cpp
  stl/src/xdateord.cpp
  stl/src/xrngdev.cpp
  stl/src/xtime.cpp
  tests/std/tests/P0220R1_polymorphic_memory_resources/test.cpp
  tools/validate/CMakeLists.txt
Labels: enhancement

#3020 <yvals_core.h> Update _MSVC_STL_UPDATE to #define _MSVC_STL_UPDATE 202208L
  stl/inc/yvals_core.h
Labels: enhancement

#3021 `<vector>`: Apply append-and-rotate for `vector<bool>` insertion
  stl/inc/vector
Labels: bug

#3023 Implement `(chunk_view<forward>|stride_view)::iterator::operator(\+=|-=)` in O(1)
  stl/inc/ranges
  tests/std/tests/P1899R3_views_stride_death/test.cpp
  tests/std/tests/P2442R1_views_chunk_death/test.cpp
Labels: bug, ranges

#3026 Split `tests/P1206R7_ranges_to` into four parts
  tests/std/test.lst
  tests/std/tests/P1206R7_ranges_to/test.cpp
  tests/std/tests/P1206R7_ranges_to_mappish/env.lst
  tests/std/tests/P1206R7_ranges_to_mappish/test.cpp
  tests/std/tests/P1206R7_ranges_to_misc/env.lst
  tests/std/tests/P1206R7_ranges_to_misc/test.cpp
  tests/std/tests/P1206R7_ranges_to_sequence/env.lst
  tests/std/tests/P1206R7_ranges_to_sequence/test.cpp
  tests/std/tests/P1206R7_ranges_to_settish/env.lst
  tests/std/tests/P1206R7_ranges_to_settish/test.cpp
Labels: test, ranges

#3027 Add escape hatches for source-breaking throughput improvements
  stl/inc/functional
  stl/inc/xhash
Labels: enhancement

#3028 `<xmemory>`: `_Uninitialized_copy` doesn't assign, it constructs
  stl/inc/xmemory
  tests/std/tests/P1206R7_vector_from_range/test.cpp
Labels: bug

#3033 Ignore submodules during code format validation
  azure-devops/create-prdiff.ps1
Labels: infrastructure

#1347 Improve exception specification of iterator machinery
  stl/inc/xutility
Labels: enhancement

#2991 make _Get_unwrapped noexcept when possible
  stl/inc/filesystem
  stl/inc/iterator
  stl/inc/ranges
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/GH_002989_nothrow_unwrappable/env.lst
  tests/std/tests/GH_002989_nothrow_unwrappable/test.cpp
Labels: enhancement

#3034 Cleanup tests to be friendlier to modules
  tests/std/include/parallel_algorithms_utilities.hpp
  tests/std/tests/Dev09_158181_tr1_unordered_meow_swap/test.cpp
  tests/std/tests/Dev09_181509_tr1_inf_loop_uniform_int_ull/test.cpp
  tests/std/tests/Dev11_0316853_find_memchr_optimization/test.cpp
  tests/std/tests/Dev11_0555154_system_clock_to_time_t/test.cpp
  tests/std/tests/Dev11_0579795_inplace_merge_out_of_memory/test.cpp
  tests/std/tests/Dev11_0845312_comprehensive_floating_point/test.cpp
  tests/std/tests/Dev11_1074023_constexpr/test.cpp
  tests/std/tests/P0067R5_charconv/test.cpp
  tests/std/tests/P0220R1_polymorphic_memory_resources/test.cpp
  tests/std/tests/P0220R1_string_view/test.cpp
  tests/std/tests/P0295R0_gcd_lcm/test.compile.pass.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp
  tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
  tests/std/tests/P0645R10_text_formatting_grapheme_clusterization/test.cpp
  tests/std/tests/P0896R4_istream_view/test.cpp
  tests/std/tests/P0896R4_ranges_alg_partial_sort_copy/test.cpp
  tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp
  tests/std/tests/P1206R7_map_from_range/test.cpp
  tests/std/tests/P1206R7_map_insert_range/test.cpp
  tests/std/tests/P1206R7_multimap_from_range/test.cpp
  tests/std/tests/P1206R7_multimap_insert_range/test.cpp
  tests/std/tests/P1206R7_multiset_from_range/test.cpp
  tests/std/tests/P1206R7_multiset_insert_range/test.cpp
  tests/std/tests/P1206R7_set_from_range/test.cpp
  tests/std/tests/P1206R7_set_insert_range/test.cpp
  tests/std/tests/P1206R7_unordered_map_from_range/test.cpp
  tests/std/tests/P1206R7_unordered_map_insert_range/test.cpp
  tests/std/tests/P1206R7_unordered_multimap_from_range/test.cpp
  tests/std/tests/P1206R7_unordered_multimap_insert_range/test.cpp
  tests/std/tests/P1206R7_unordered_multiset_from_range/test.cpp
  tests/std/tests/P1206R7_unordered_multiset_insert_range/test.cpp
  tests/std/tests/P1206R7_unordered_set_from_range/test.cpp
  tests/std/tests/P1206R7_unordered_set_insert_range/test.cpp
  tests/std/tests/VSO_0099869_pow_float_overflow/test.cpp
  tests/std/tests/VSO_0493909_is_aggregate/test.compile.pass.cpp
  tests/std/tests/VSO_0961751_hash_range_erase/test.cpp
Labels: test

#1937 Mark several functions as noexcept.
  stl/inc/optional
  stl/inc/type_traits
  stl/inc/xstddef
  stl/inc/xutility
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: performance

#3032 `<string_view>`: suppress warning about annotation 'NullTerminated'
  stl/inc/xstring
  tests/std/tests/P0220R1_string_view/test.cpp
Labels: bug

#3038 Fix null function check for `move_only_function` assigned from a DLL and issues caused by an unloaded DLL that constructed or assigned an empty `move_only_function`
  stl/inc/functional
Labels: bug

#3040 `.vscode/settings.json`: Teach Pylance about our paths
  .vscode/settings.json
Labels: test

#3042 Status Chart: Weekly updates, dependency updates
  index.html
  package-lock.json
  package.json
  src/weekly_table.ts
Labels: documentation, uncharted

#3046 Update `P1208R6_source_location` for a compiler fix
  tests/std/tests/P1208R6_source_location/test.cpp
Labels: test

#2124 Use `int = 0` SFINAE in `<memory>` to improve compiler throughput
  stl/inc/functional
  stl/inc/memory
Labels: enhancement

#2661 P2387R3 Pipe for user defined range adaptors
  stl/debugger/STL.natvis
  stl/inc/functional
  stl/inc/ranges
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2387R3_bind_back/env.lst
  tests/std/tests/P2387R3_bind_back/test.cpp
  tests/std/tests/P2387R3_pipe_support_for_user_defined_range_adaptors/env.lst
  tests/std/tests/P2387R3_pipe_support_for_user_defined_range_adaptors/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23

#2977 Implement P2419R2 Clarify Handling Of Encodings In Localized Formatting Of `chrono` Types
  stl/inc/chrono
  stl/inc/filesystem
  stl/inc/yvals_core.h
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
Labels: format, cxx23

#3039 Test ASAN SSO string copies; improve `basic_string::_Construct` preconditions
  stl/inc/xstring
  tests/std/tests/GH_002030_asan_annotate_string/test.cpp
Labels: enhancement

#3041 `_Fake_copy_init` unification
  stl/inc/expected
  stl/inc/ranges
  stl/inc/type_traits
  stl/inc/xstddef
  stl/inc/xutility
Labels: enhancement

#3045 Fix `pair::swap(const pair&)` and `tuple::swap(const tuple&)` errors with `__declspec(dllexport)`
  stl/inc/tuple
  stl/inc/utility
  tests/std/tests/GH_001638_dllexport_derived_classes/test.compile.pass.cpp
Labels: bug, high priority

#3054 1ES Hosted Pools
  .gitignore
  azure-devops/create-1es-hosted-pool.ps1
  azure-devops/provision-image.ps1
  azure-pipelines.yml
Labels: high priority, infrastructure

#2169 <regex>: add checks for integer overflow
  stl/inc/regex
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/GH_002168_regex_overflow/env.lst
  tests/std/tests/GH_002168_regex_overflow/test.cpp
Labels: bug

#2965 Implement P2494R2 Relaxing Range Adaptors To Allow Move-Only Types
  stl/inc/ranges
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2494R2_move_only_range_adaptors/env.lst
  tests/std/tests/P2494R2_move_only_range_adaptors/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23

#2987 `ranges::distance` fails to emulate the Standard's two overload presentation
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
Labels: bug, ranges

#3049 Implement P2291R3 `constexpr` Integral `<charconv>`
  stl/inc/charconv
  stl/inc/yvals_core.h
  tests/std/tests/P0067R5_charconv/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#3053 Cleanup product code uses of feature-test macros
  stl/inc/chrono
  stl/inc/deque
  stl/inc/expected
  stl/inc/format
  stl/inc/forward_list
  stl/inc/list
  stl/inc/map
  stl/inc/queue
  stl/inc/set
  stl/inc/stack
  stl/inc/system_error
  stl/inc/unordered_map
  stl/inc/unordered_set
  stl/inc/vector
  stl/inc/xhash
  stl/inc/xmemory
  stl/inc/xstring
  stl/inc/xtree
  stl/inc/yvals_core.h
  tests/std/tests/GH_000545_include_compare/test_ranges.cpp
  tests/std/tests/GH_002989_nothrow_unwrappable/test.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_clocks/test.cpp
  tests/std/tests/P0433R2_deduction_guides/test.cpp
  tests/std/tests/P0980R1_constexpr_strings/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: enhancement

#3061 Status Chart: Weekly update, TypeScript 4.8
  index.html
  package-lock.json
  package.json
  src/weekly_table.ts
  src_gather/gather_stats.ts
Labels: documentation

#3055 add `__forceinline` to `std::unreachable` instead of `inline`
  stl/inc/utility
Labels: performance

#3056 Parallel for_each iterators don't have to be mutable
  stl/inc/execution
Labels: bug

#2068 add _ENFORCE_ONLY_CORE_HEADERS
  stl/inc/yvals.h
  stl/inc/yvals_core.h
  tests/std/tests/GH_001411_core_headers/test.cpp
Labels: enhancement

#2211 [[nodiscard]] messages
  stl/inc/algorithm
  stl/inc/array
  stl/inc/barrier
  stl/inc/deque
  stl/inc/exception
  stl/inc/execution
  stl/inc/forward_list
  stl/inc/future
  stl/inc/latch
  stl/inc/list
  stl/inc/memory
  stl/inc/mutex
  stl/inc/new
  stl/inc/queue
  stl/inc/scoped_allocator
  stl/inc/semaphore
  stl/inc/shared_mutex
  stl/inc/stack
  stl/inc/stacktrace
  stl/inc/thread
  stl/inc/vector
  stl/inc/xhash
  stl/inc/xmemory
  stl/inc/xpolymorphic_allocator.h
  stl/inc/xstring
  stl/inc/xtree
  stl/inc/xutility
  stl/inc/yvals_core.h
Labels: documentation

#3024 Unwrappable iter/sent pairs!
  stl/inc/algorithm
  stl/inc/filesystem
  stl/inc/memory
  stl/inc/numeric
  stl/inc/ranges
  stl/inc/xmemory
  stl/inc/xutility
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/GH_002989_nothrow_unwrappable/test.cpp
  tests/std/tests/GH_002992_unwrappable_iter_sent_pairs/env.lst
  tests/std/tests/GH_002992_unwrappable_iter_sent_pairs/test.compile.pass.cpp
  tests/std/tests/P0896R4_ranges_alg_reverse_copy/test.cpp
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_ranges_test_machinery/test.compile.pass.cpp
Labels: bug

#3036 `<__msvc_int128.hpp>`: Backport 128-bit integer-class types to C++14 mode
  stl/inc/__msvc_int128.hpp
  tests/std/tests/P1522R1_difference_type/env.lst
  tests/std/tests/P1522R1_difference_type/test.cpp
Labels: enhancement
