Repository microsoft/STL, pull requests merged in 2022-05, with the labels that each got.

#2433 add comments for functions like `test_gh_XXXX` with short description
  tests/std/tests/Dev09_126254_persistent_aux_allocators/test.cpp
  tests/std/tests/Dev10_722102_shared_ptr_nullptr/test.cpp
  tests/std/tests/Dev10_851347_weak_ptr_virtual_inheritance/test.cpp
  tests/std/tests/GH_000431_equal_family/test.cpp
  tests/std/tests/GH_001001_random_rejection_rounding/test.cpp
  tests/std/tests/P0019R8_atomic_ref/test.cpp
  tests/std/tests/P0083R3_splicing_maps_and_sets/test.cpp
  tests/std/tests/P0220R1_optional/test.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp
  tests/std/tests/P0475R1_P0591R4_uses_allocator_construction/test.cpp
  tests/std/tests/P0674R1_make_shared_for_arrays/test.cpp
  tests/std/tests/P0896R4_common_iterator/test.cpp
  tests/std/tests/P0896R4_ranges_alg_minmax/test.cpp
  tests/std/tests/P0896R4_ranges_alg_stable_sort/test.cpp
  tests/std/tests/P0896R4_ranges_alg_unique_copy/test.cpp
  tests/std/tests/P0896R4_views_reverse/test.cpp
  tests/std/tests/P0896R4_views_split/test.cpp
  tests/std/tests/P0980R1_constexpr_strings/test.cpp
  tests/std/tests/VSO_0000000_regex_interface/test.cpp
  tests/std/tests/VSO_0000000_regex_use/test.cpp
  tests/std/tests/VSO_0224478_scoped_allocator/test.cpp
Labels: documentation

#2639 Implement LWG-3525: `uses_allocator_construction_args` fails to handle types convertible to `pair`
  stl/inc/xmemory
  stl/inc/xpolymorphic_allocator.h
  tests/std/tests/P0220R1_polymorphic_memory_resources/test.cpp
Labels: LWG

#2660 Untag dispatch `<xstring>`
  stl/inc/xstring
Labels: throughput

#2662 Untag dispatch `<execution>`
  stl/inc/execution
Labels: throughput

#2666 `<xloctime>`: apply two-digit year logic only if exactly two digits are read
  stl/inc/xloctime
  tests/std/tests/Dev11_0836436_get_time/test.cpp
Labels: bug, affects redist

#2669 <system_error>: explicitly pass the system locale ID for system_category messages
  stl/src/syserror_import_lib.cpp
Labels: bug

#2671 add format target to cmake
  CMakeLists.txt
  azure-devops/create-prdiff.ps1
  azure-devops/enforce-clang-format.cmd
  azure-devops/validate-files.cmd
  azure-pipelines.yml
  tools/CMakeLists.txt
  tools/format/CMakeLists.txt
  tools/parallelize/CMakeLists.txt
  tools/parallelize/parallelize.cpp
  tools/validate/CMakeLists.txt
  tools/validate/validate.cpp
Labels: infrastructure

#2673 Cleanups 1: Comments and formatting
  stl/inc/complex
  stl/inc/cstddef
  stl/inc/exception
  stl/inc/filesystem
  stl/inc/memory
  stl/inc/ostream
  stl/inc/random
  stl/inc/string
  stl/inc/type_traits
  stl/inc/utility
  stl/inc/xutility
Labels: documentation

#2674 Cleanups 2: Exception handling
  stl/inc/chrono
  stl/inc/format
  stl/inc/future
  stl/inc/system_error
  stl/src/future.cpp
Labels: enhancement

#2675 Cleanups 3: Simple changes
  stl/inc/array
  stl/inc/chrono
  stl/inc/complex
  stl/inc/exception
  stl/inc/execution
  stl/inc/future
  stl/inc/memory_resource
  stl/inc/scoped_allocator
  stl/inc/typeinfo
  stl/inc/xlocbuf
  stl/inc/xmemory
  stl/src/tzdb.cpp
  tests/std/tests/P0753R2_manipulators_for_cpp_synchronized_buffered_ostream/test.cpp
  tests/std/tests/VSO_0000000_initialize_everything/test.cpp
Labels: enhancement

#2676 Cleanups 4: `quoted()`
  stl/inc/iomanip
Labels: enhancement

#2677 Cleanups 5: `if constexpr` for `<scoped_allocator>` `operator==`
  stl/inc/scoped_allocator
Labels: throughput

#2678 Cleanups 6: iostreams: drop `extern`, hide `_Winit`
  stl/inc/fstream
  stl/inc/iostream
  stl/inc/xlocnum
Labels: enhancement

#2679 Cleanups 7: Unnecessary guard around `new_handler`
  stl/inc/new
Labels: enhancement

#2680 Cleanups 8: Deprecate `<strstream>` classes instead of the entire header
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/strstream
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
  tests/std/tests/include_each_header_alone_matrix.lst
Labels: enhancement

#2686 Update reason for libc++ test failure
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: test

#2689 Vectorize `swap` and `ranges::swap` for arrays
  stl/inc/concepts
  stl/inc/type_traits
  stl/inc/utility
  stl/inc/xutility
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#2690 Status Chart: Weekly/dependency updates, new maintainer
  index.html
  package-lock.json
  package.json
  src/weekly_table.ts
  usernames_maintainers.txt
Labels: documentation, uncharted

#2702 `<atomic>`: Fix missing ARM64EC ifdefs
  stl/inc/atomic
Labels: bug, ARM64

#1339 <memory>: Fix atomic smart pointers array type interaction
  stl/inc/memory
  tests/std/include/test_atomic_wait.hpp
  tests/std/tests/P0718R2_atomic_smart_ptrs/test.cpp
Labels: bug

#2113 `<cmath>`: add arithmetic overloads for `std::lerp`
  stl/inc/cmath
  tests/std/tests/P0811R3_midpoint_lerp/test.cpp
Labels: bug

#2373 `<filesystem>`: `__std_fs_get_stats` should work on FAT32
  stl/src/filesystem.cpp
Labels: bug

#2668 Reduce _Invoker_ret specializations with if constexpr
  stl/inc/functional
Labels: throughput

#2687 P2321R2 zip: Make `tuple`, `pair`, and `vector<bool>::reference` `indirectly_writable`
  stl/inc/tuple
  stl/inc/type_traits
  stl/inc/utility
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/Dev10_500860_overloaded_address_of/test.cpp
  tests/std/tests/P0475R1_P0591R4_uses_allocator_construction/test.cpp
  tests/std/tests/P2321R2_proxy_reference/env.lst
  tests/std/tests/P2321R2_proxy_reference/test.cpp
Labels: cxx23

#2693 Untag dispatch `<random>`
  stl/inc/random
Labels: throughput

#2694 Untag dispatch vector<👻>::_Insert
  stl/inc/vector
Labels: throughput

#2696 Update `_MSVC_STL_UPDATE` (may 2022)
  stl/inc/yvals_core.h
Labels: enhancement

#2697 [validate] add `validate` cmake target
  CMakeLists.txt
  azure-devops/create-prdiff.ps1
  azure-pipelines.yml
  tests/utils/stl/util.py
  tools/CMakeLists.txt
  tools/format/CMakeLists.txt
  tools/inc/stljobs.h
  tools/jobify/CMakeLists.txt
  tools/jobify/jobify.cpp
  tools/validate/CMakeLists.txt
Labels: infrastructure

#2700 Scalarize `swap` and `ranges::swap` for arrays
  stl/inc/concepts
  stl/inc/type_traits
  stl/inc/utility
  stl/inc/xutility
  tests/std/tests/Dev11_0836436_get_time/test.cpp
  tests/std/tests/GH_001411_core_headers/test.compile.pass.cpp
  tests/std/tests/GH_001411_core_headers/test.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: bug

#2703 Speculatively implement LWG-3234: Sufficient Additional Special Math Overloads
  stl/inc/cmath
  tests/std/test.lst
  tests/std/tests/LWG3234_math_special_overloads/env.lst
  tests/std/tests/LWG3234_math_special_overloads/test.cpp
Labels: bug

#2708 [CMakeLists.txt] add more information to the `/Os` transition comment
  CMakeLists.txt
Labels: build

#2709 Block C++98 `unexpected()` from being restored in C++23 mode
  stl/inc/yvals_core.h
Labels: enhancement

#2717 Remove unnecessary copy of _clr DLLS from internal build
  stl/msbuild/stl_1/msvcp_1.settings.targets
  stl/msbuild/stl_2/msvcp_2.settings.targets
  stl/msbuild/stl_atomic_wait/msvcp_atomic_wait.settings.targets
  stl/msbuild/stl_base/msvcp.settings.targets
  stl/msbuild/stl_codecvt_ids/msvcp_codecvt_ids.settings.targets
Labels: build

#2196 <string> Add asan annotations
  stl/CMakeLists.txt
  stl/inc/sstream
  stl/inc/vector
  stl/inc/xstring
  stl/msbuild/stl_base/libcp.settings.targets
  stl/src/asan.cpp
  stl/src/asan_noop.cpp
  tests/std/test.lst
  tests/std/tests/GH_002030_asan_annotate_string/env.lst
  tests/std/tests/GH_002030_asan_annotate_string/test.cpp
Labels: enhancement, high priority

#2583 P1413R3 Deprecate `aligned_storage` & `aligned_union`
  stl/inc/algorithm
  stl/inc/condition_variable
  stl/inc/mutex
  stl/inc/type_traits
  stl/inc/xnode_handle.h
  stl/inc/yvals_core.h
  stl/src/cond.cpp
  stl/src/mutex.cpp
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/libcxx/usual_matrix.lst
  tests/std/tests/Dev11_0000000_null_forward_iterators/test.cpp
  tests/std/tests/Dev11_0000000_user_defined_literals/test.cpp
  tests/std/tests/Dev11_0748972_function_crash_out_of_memory/test.cpp
  tests/std/tests/P0035R4_over_aligned_allocation/test.cpp
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P0220R1_polymorphic_memory_resources/test.cpp
  tests/std/tests/VSO_0000000_instantiate_type_traits/test.compile.pass.cpp
  tests/tr1/tests/type_traits1/test.cpp
  tests/tr1/tests/type_traits5/test.cpp
Labels: cxx23

#2670 <ranges> Implement P2442R1 slide_view
  stl/inc/ranges
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2442R1_views_slide/env.lst
  tests/std/tests/P2442R1_views_slide/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23

#2685 <ranges> Implement P2442R1 `chunk_view`
  stl/inc/ranges
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2442R1_views_chunk/env.lst
  tests/std/tests/P2442R1_views_chunk/test.cpp
  tests/std/tests/P2442R1_views_chunk_death/env.lst
  tests/std/tests/P2442R1_views_chunk_death/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23

#2710 `<ciso646>` is removed in C++20
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/ciso646
  stl/inc/yvals_core.h
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P0220R1_any/test.cpp
  tests/std/tests/P0220R1_optional/test.cpp
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
  tests/std/tests/include_each_header_alone_matrix.lst
  tests/tr1/tests/ciso646/test.cpp
Labels: enhancement

#2715 [filesystem] Don't error on weird system files
  stl/src/filesystem.cpp
Labels: bug, filesystem

#2718 [copy_file] allow `FILE_SHARE_*`
  stl/src/filesystem.cpp
Labels: bug, filesystem

#2643 <expected> Implement P0323R12
  stl/CMakeLists.txt
  stl/debugger/STL.natvis
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/expected
  stl/inc/header-units.json
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P0323R12_expected/env.lst
  tests/std/tests/P0323R12_expected/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/importable_cxx_library_headers.jsonc
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tests/std/tests/include_each_header_alone_matrix.lst
Labels: cxx23

#2706 STL.natvis: add specializations for `shared_ptr<void>`, `weak_ptr<void>`, and `unique_ptr<void, deleter>`
  stl/debugger/STL.natvis
Labels: visualizer

#2726 `<xmemory>`: Remove `std::allocator<void>` full specialization
  stl/inc/xmemory
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/GH_000527_remove_allocator_void/env.lst
  tests/std/tests/GH_000527_remove_allocator_void/test.compile.pass.cpp
Labels: bug

#2727 `<ranges>`: Temporarily disable `join_view` for non-`forward_range`s, pending resolution of LWG-3698
  stl/inc/ranges
  tests/libcxx/usual_matrix.lst
  tests/std/tests/P0896R4_views_join/test.cpp
Labels: ranges

#2729 CMakeLists.txt: Check the Windows SDK version
  CMakeLists.txt
Labels: build

#2732 remove `const` from `<random>`:distribution::`operator()`
  stl/inc/random
  tests/std/test.lst
  tests/std/tests/GH_001912_random_distribution_operator_const/env.lst
  tests/std/tests/GH_001912_random_distribution_operator_const/test.compile.pass.cpp
Labels: enhancement

#2734 Add an alias object to the import lib
  CMakeLists.txt
  stl/CMakeLists.txt
  stl/msbuild/stl_base/stl.files.settings.targets
  stl/src/alias.asm
  tests/std/test.lst
  tests/std/tests/GH_002655_alternate_name_broke_linker/env.lst
  tests/std/tests/GH_002655_alternate_name_broke_linker/test.cpp
Labels: bug, high priority

#2736 Status Chart: Weekly updates
  index.html
  package-lock.json
  package.json
  src/weekly_table.ts
Labels: documentation, uncharted

#2738 Avoid an assertion failure in alias.asm
  stl/CMakeLists.txt
  stl/msbuild/stl_base/stl.files.settings.targets
  stl/src/alias.asm
  stl/src/alias_init_once_begin_initialize.asm
  stl/src/alias_init_once_complete.asm
Labels: bug

#2747 Status Chart: Weekly update, chart.js 3.8.0
  index.html
  package-lock.json
  package.json
  src/weekly_table.ts
Labels: documentation, uncharted
