Repository microsoft/STL, pull requests merged in 2022-06, with the labels that each got.

#2193 <any>: std::any links when exceptions are disabled
  stl/inc/typeinfo
  tests/std/test.lst
  tests/std/tests/GH_000990_any_link_without_exceptions/env.lst
  tests/std/tests/GH_000990_any_link_without_exceptions/test.cpp
Labels: bug

#2336 clamp cmov codegen
  stl/inc/algorithm
  tests/std/test.lst
  tests/std/tests/GH_002334_branchless_clamp/env.lst
  tests/std/tests/GH_002334_branchless_clamp/test.cpp
Labels: performance

#2730 `<tuple>`: Becomes a core header
  stl/CMakeLists.txt
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/__msvc_iter_core.hpp
  stl/inc/header-units.json
  stl/inc/tuple
  stl/inc/utility
  stl/inc/xutility
Labels: enhancement

#2739 codecvt: no conversion for all char-like types of size 1.
  stl/inc/xlocale
Labels: performance

#2741 `<xstring>`: Restrict enabled `hash` specializations as required by the standard
  stl/inc/filesystem
  stl/inc/xstring
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: bug

#2743 [aliasobj] just build the alias objects once
  stl/CMakeLists.txt
Labels: build

#2754 Toolset update: Move to northeurope
  azure-devops/create-vmss.ps1
  azure-devops/provision-image.ps1
  azure-pipelines.yml
Labels: infrastructure

#2753 Mirror MSBuild changes
  stl/msbuild/stl_1/dirs.proj
  stl/msbuild/stl_1/md/dirs.proj
  stl/msbuild/stl_1/msvcp_1.settings.targets
  stl/msbuild/stl_1/xmd/dirs.proj
  stl/msbuild/stl_2/dirs.proj
  stl/msbuild/stl_2/md/dirs.proj
  stl/msbuild/stl_2/msvcp_2.settings.targets
  stl/msbuild/stl_2/xmd/dirs.proj
  stl/msbuild/stl_asan/dirs.proj
  stl/msbuild/stl_atomic_wait/dirs.proj
  stl/msbuild/stl_atomic_wait/md/dirs.proj
  stl/msbuild/stl_atomic_wait/msvcp_atomic_wait.settings.targets
  stl/msbuild/stl_atomic_wait/xmd/dirs.proj
  stl/msbuild/stl_base/dirs.proj
  stl/msbuild/stl_base/md/dirs.proj
  stl/msbuild/stl_base/msvcp.settings.targets
  stl/msbuild/stl_base/mt/dirs.proj
  stl/msbuild/stl_base/mt1/dirs.proj
  stl/msbuild/stl_base/xmd/dirs.proj
  stl/msbuild/stl_base/xmt/dirs.proj
  stl/msbuild/stl_base/xmt0/dirs.proj
  stl/msbuild/stl_base/xmt1/dirs.proj
  stl/msbuild/stl_codecvt_ids/dirs.proj
  stl/msbuild/stl_codecvt_ids/md/dirs.proj
  stl/msbuild/stl_codecvt_ids/msvcp_codecvt_ids.settings.targets
  stl/msbuild/stl_codecvt_ids/xmd/dirs.proj
  stl/msbuild/stl_post/dirs.proj
  stl/msbuild/stl_post/md/dirs.proj
  stl/msbuild/stl_post/msvcp_post.settings.targets
  stl/msbuild/stl_post/xmd/dirs.proj
Labels: build

#1794 Use iterator concept in vector's range constructor
  stl/inc/vector
  stl/inc/xmemory
  tests/std/tests/P0896R4_views_transform/test.cpp
  tests/std/tests/VSO_0000000_fancy_pointers/test.compile.pass.cpp
Labels: performance

#2502 stacktrace
  stl/CMakeLists.txt
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/header-units.json
  stl/inc/stacktrace
  stl/inc/yvals_core.h
  stl/msbuild/stl_base/stl.files.settings.targets
  stl/src/stacktrace.cpp
  tests/std/test.lst
  tests/std/tests/GH_000545_include_compare/test.cpp
  tests/std/tests/GH_000545_include_compare/test_stacktrace.cpp
  tests/std/tests/P0881R7_stacktrace/env.lst
  tests/std/tests/P0881R7_stacktrace/postexecute.pl
  tests/std/tests/P0881R7_stacktrace/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/importable_cxx_library_headers.jsonc
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tests/std/tests/include_each_header_alone_matrix.lst
Labels: cxx23

#2756 Untag dispatch `get` for `pair`
  stl/inc/utility
Labels: throughput

#2757 Compact the _Unicode_property_data tables.
  stl/inc/__msvc_format_ucd_tables.hpp
  tools/unicode_properties_parse/grapheme_break_property_data_gen.py
Labels: performance, format

#2758 `<complex>`: fix complex division by zero
  stl/inc/complex
  tests/std/tests/Dev10_555491_complex_linker_errors/test.cpp
Labels: bug, high priority

#2759 Deprecate primary complex
  stl/inc/complex
  stl/inc/yvals_core.h
  tests/libcxx/usual_matrix.lst
Labels: enhancement

#2763 `<syncstream>`: fix `std::osyncstream` memory leak
  stl/inc/syncstream
  tests/std/test.lst
  tests/std/tests/GH_002760_syncstream_memory_leak/env.lst
  tests/std/tests/GH_002760_syncstream_memory_leak/test.cpp
Labels: bug

#2764 <yvals_core.h>: Update _MSVC_STL_UPDATE to June 2022
  stl/inc/yvals_core.h
Labels: enhancement

#2768 fix `format` a `long` value with `formatter`
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_args/test.cpp
  tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp
Labels: bug, format

#2774 Don't assume that `_Hash_vec`'s size and capacity are always equal
  stl/inc/xhash
Labels: bug

#2775 `<deque>`: Properly destroy (fancy) pointers to blocks in the internal map
  stl/inc/deque
  tests/std/test.lst
  tests/std/tests/GH_002769_handle_deque_block_pointers/env.lst
  tests/std/tests/GH_002769_handle_deque_block_pointers/test.cpp
Labels: bug

#2791 Toolset update: VS 2022 17.3 Preview 2, CUDA 11.6.0
  CMakeLists.txt
  README.md
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  stl/inc/format
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/yvals_core.h
  tests/std/include/timezone_data.hpp
  tests/std/tests/GH_000639_nvcc_include_all/env.lst
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
  tests/std/tests/P0645R10_text_formatting_utf8/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
  tools/CMakeLists.txt
  tools/format/CMakeLists.txt
  tools/validate/CMakeLists.txt
Labels: infrastructure

#2164 When wchar_t is a real type, users shouldn't see unsigned short machinery
  stl/inc/fstream
  stl/inc/iosfwd
  stl/inc/locale
  stl/inc/xlocale
  stl/inc/xlocmes
  stl/inc/xlocmon
  stl/inc/xlocnum
  stl/inc/xloctime
  stl/inc/xstring
  stl/src/ushcerr.cpp
  stl/src/ushcin.cpp
  stl/src/ushclog.cpp
  stl/src/ushcout.cpp
  stl/src/ushiostr.cpp
  tests/std/tests/VSO_0397980_codecvt_length/test.cpp
Labels: enhancement

#2580 Implement P2440R1 ranges::iota, ranges::shift_left, ranges::shift_right
  stl/inc/algorithm
  stl/inc/numeric
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P0769R2_shift_left_shift_right/test.cpp
  tests/std/tests/P2440R1_ranges_alg_shift_left/env.lst
  tests/std/tests/P2440R1_ranges_alg_shift_left/test.cpp
  tests/std/tests/P2440R1_ranges_alg_shift_right/env.lst
  tests/std/tests/P2440R1_ranges_alg_shift_right/test.cpp
  tests/std/tests/P2440R1_ranges_numeric_iota/env.lst
  tests/std/tests/P2440R1_ranges_numeric_iota/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23

#2762 allow `%x` for formatting `year_month_day`
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
Labels: bug, format, chrono

#2790 Don't deallocate nullptr in _Hash_vec::_Tidy
  stl/inc/xhash
  tests/std/test.lst
  tests/std/tests/GH_002789_Hash_vec_Tidy/env.lst
  tests/std/tests/GH_002789_Hash_vec_Tidy/test.cpp
Labels: bug

#2792 Mark constants as `_INLINE_VAR constexpr`.
  stl/inc/functional
  stl/inc/regex
  stl/inc/vector
  stl/inc/xstring
Labels: enhancement

#2795 Fix non-deterministic test sharding with `--order=lexical`
  azure-devops/cross-build.yml
  azure-devops/native-build-test.yml
Labels: infrastructure, test

#1343 <filesystem>: `directory_entry(const path&, error_code&)` should return error code
  stl/inc/filesystem
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: bug, filesystem

#1735 Implement SSO for constexpr string
  stl/inc/xstring
  tests/std/tests/P0980R1_constexpr_strings/test.cpp
Labels: enhancement

#1915 <filesystem>: Avoid additional allocations in path::lexically_relative
  stl/inc/filesystem
Labels: performance, filesystem

#2447 Implement vectorized min_ / max_element for ints
  stl/inc/algorithm
  stl/inc/xtr1common
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#2624 change SFINAE constraint on `construct_at` (MSVC workaround)
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/GH_002620_construct_at_workaround/env.lst
  tests/std/tests/GH_002620_construct_at_workaround/test.cpp
Labels: bug

#2705 Fix leap second validation when parsing `time_point`s
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp
Labels: bug, chrono

#2781 Atomic wait: zero-initialize wait list head
  stl/src/atomic_wait.cpp
Labels: performance

#2793 P1328R1 `constexpr` `type_info::operator==()`
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P2273R3_constexpr_unique_ptr/test.compile.pass.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#2801 Various source cleanups, especially `ushMEOW.cpp` and `fiopen.cpp`
  stl/src/fiopen.cpp
  stl/src/locale.cpp
  stl/src/locale0.cpp
  stl/src/ushcerr.cpp
  stl/src/ushcin.cpp
  stl/src/ushclog.cpp
  stl/src/ushcout.cpp
  stl/src/ushiostr.cpp
  stl/src/wlocale.cpp
Labels: enhancement

#2802 Various header cleanups
  stl/inc/array
  stl/inc/chrono
  stl/inc/complex
  stl/inc/cvt/ebcdic
  stl/inc/cvt/one_one
  stl/inc/cvt/utf16
  stl/inc/cvt/utf8
  stl/inc/cvt/utf8_utf16
  stl/inc/cvt/xjis
  stl/inc/cvt/xtwo_byte
  stl/inc/deque
  stl/inc/experimental/filesystem
  stl/inc/filesystem
  stl/inc/format
  stl/inc/forward_list
  stl/inc/future
  stl/inc/list
  stl/inc/locale
  stl/inc/memory_resource
  stl/inc/regex
  stl/inc/system_error
  stl/inc/tuple
  stl/inc/xlocale
  stl/inc/xlocmon
  stl/inc/xlocnum
  stl/inc/xstring
Labels: enhancement

#1918 Recalculate lerp if we got infinity. Eliminates some overflows.
  stl/inc/cmath
  tests/std/tests/P0811R3_midpoint_lerp/test.cpp
Labels: bug

#2619 Implement P2441R2 views::join_with
  stl/inc/algorithm
  stl/inc/exception
  stl/inc/iterator
  stl/inc/ranges
  stl/inc/variant
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P0896R4_common_iterator_death/test.cpp
  tests/std/tests/P2441R2_views_join_with/env.lst
  tests/std/tests/P2441R2_views_join_with/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23

#2796 Use conditional `explicit` unconditionally
  stl/inc/optional
  stl/inc/tuple
  stl/inc/utility
  stl/inc/yvals_core.h
Labels: throughput

#2797 My Little Operator: Friendship Is Magic
  stl/inc/array
  stl/inc/chrono
  stl/inc/deque
  stl/inc/iomanip
  stl/inc/vector
  stl/inc/xstring
Labels: throughput

#2798 Delete unused, non-exported xmath machinery
  stl/src/xdtest.cpp
  stl/src/xfdtest.cpp
  stl/src/xldtest.cpp
  stl/src/xmath.hpp
  stl/src/xxxprec.hpp
Labels: enhancement

#2805 Status Chart: Weekly updates
  index.html
  package-lock.json
  package.json
  src/weekly_table.ts
Labels: documentation, uncharted

#2212 Encouraging Contributors
  CONTRIBUTING.md
  README.md
Labels: documentation

#2782 add default ctor for node types
  stl/inc/forward_list
  stl/inc/list
  stl/inc/type_traits
  stl/inc/xtree
Labels: bug

#2808 P0849R8 `auto(x)`: `decay-copy` In The Language
  stl/inc/yvals_core.h
Labels: cxx23

#2812 fix analyze in CI
  CMakeLists.txt
  azure-devops/cmake-configure-build.yml
  stl/src/tzdb.cpp
  stl/src/winapisupp.cpp
Labels: infrastructure

#2815 New BOOL rules
  stl/inc/mutex
  stl/inc/xcall_once.h
  stl/src/StlCompareStringA.cpp
  stl/src/cthread.cpp
  stl/src/excptptr.cpp
  stl/src/format.cpp
  stl/src/taskscheduler.cpp
Labels: enhancement

#2820 Don't get thread exit code as we don't care anyway
  stl/src/cthread.cpp
Labels: performance

#2821 Fix vectorized `min/max/minmax_element` for 64-bit types on x86
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: bug, high priority

#2784 fix hash_* visualizer issue
  stl/debugger/STL.natvis
Labels: visualizer

#2804 drop VC 2013 visualizers
  stl/debugger/STL.natvis
Labels: visualizer

#2811 add a visualizer for `_Ref_count_obj_alloc3` and `_Ref_count_obj2`
  stl/debugger/STL.natvis
Labels: visualizer

#2830 Port MSVC-PR-407767
  tests/std/run.pl
  tests/tr1/run.pl
Labels: test
