Repository microsoft/STL, pull requests merged in 2022-02, with the labels that each got.

#2493 <format> use _MSVC_EXECUTION_CHARACTER_SET
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_legacy_text_encoding/test.cpp
Labels: performance, format

#2507 gcd/lcm test from internal repo with questionable bits extracted
  tests/std/test.lst
  tests/std/tests/P0295R0_gcd_lcm/env.lst
  tests/std/tests/P0295R0_gcd_lcm/test.compile.pass.cpp
Labels: test

#2508 Changed _Unfancy_maybe_null() to _Unfancy()
  stl/inc/vector
Labels: enhancement

#2498 constexpr all the generate_canonical parameters
  stl/inc/random
  tests/std/test.lst
  tests/std/tests/GH_001964_constexpr_generate_canonical/env.lst
  tests/std/tests/GH_001964_constexpr_generate_canonical/test.cpp
Labels: performance

#2510 Rearrange feature test macros
  stl/inc/yvals_core.h
Labels: enhancement

#2519 updated _MSVC_STL_UPDATE
  stl/inc/yvals_core.h
Labels: enhancement

#2522 Speculatively implement LWG-3664
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
Labels: bug, ranges

#2514 Toolset update: VS 2022 17.1 Preview 5, CMake 3.22, sparse index
  .github/ISSUE_TEMPLATE/cxx23-feature.md
  CMakeLists.txt
  README.md
  azure-devops/checkout-sources.yml
  azure-pipelines.yml
  tools/CMakeLists.txt
Labels: infrastructure

#2516 Fix and test deduplicated header units
  stl/inc/__msvc_int128.hpp
  stl/inc/header-units.json
  tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
  tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
  tests/std/tests/P1502R1_standard_library_header_units/env.lst
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
  tests/utils/stl/util.py
  tools/scripts/print_failures.py
Labels: bug, test

#2525 resize_and_overwrite: fix warning C4018
  stl/inc/xstring
  tests/std/tests/P0980R1_constexpr_strings/test.cpp
Labels: bug

#2526 P0627R6: Function to mark unreachable code
  stl/inc/utility
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P0627R6_unreachable/env.lst
  tests/std/tests/P0627R6_unreachable/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#2528 LWG-3654: `basic_format_context::arg(size_t)` should be noexcept
  stl/inc/format
Labels: LWG, format

#2541 P2393R1 Cleaning Up Integer-Class Types
  stl/inc/xutility
  stl/inc/yvals_core.h
Labels: ranges, cxx23

#2544 LWG-3661: `constinit` `atomic<shared_ptr<T>>` a(nullptr); should work
  stl/inc/memory
  tests/std/tests/P0718R2_atomic_smart_ptrs/test.cpp
Labels: LWG

#2548 "Implement" LWG-3632 by commenting `unique_ptr` CTAD
  stl/inc/memory
Labels: LWG

#2549 Implement LWG-3660 for `iterator_traits<common_iterator>::pointer`
  stl/inc/iterator
  stl/inc/syncstream
  tests/std/tests/P0896R4_common_iterator/test.cpp
Labels: LWG

#2559 Update `__cpp_lib_concepts`
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: bug

#2560 Implement LWG-3598 `system_category().default_error_condition(0)`
  stl/inc/system_error
  tests/std/tests/Dev11_0493504_error_category_lifetime/test.cpp
  tests/tr1/tests/system_error/test.cpp
Labels: LWG

#2563 Internal test coverage for deduplicated header units
  tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
  tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
  tests/std/tests/P1502R1_standard_library_header_units/importable_cxx_library_headers.jsonc
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
Labels: high priority, test

#2564 Implement LWG-3657 `std::hash<std::filesystem::path>` is not enabled
  stl/inc/filesystem
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: LWG

#2566 Implement LWG-3618 Unnecessary `iter_move` for `transform_view::iterator`
  stl/inc/ranges
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0896R4_views_transform/test.cpp
Labels: LWG, ranges

#2569 `<format>`: fix single byte out of bounds access
  stl/inc/format
Labels: bug, format

#2573 Speculatively implement LWG-3636: `formatter<T>::format` should be const-qualified
  stl/inc/chrono
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp
Labels: LWG, format

#2366 `<charconv>`: Fix `from_chars()` `float` tiebreaking
  stl/inc/charconv
  tests/std/tests/P0067R5_charconv/float_from_chars_test_cases.hpp
Labels: bug, high priority

#2578 Add scripts to set the environment up to use just-built artifacts
  stl/CMakeLists.txt
  stl/set_environment.bat.in
  stl/set_environment.ps1.in
Labels: build
