Repository microsoft/STL, pull requests merged in 2022-11, with the labels that each got.

#3202 Toolset update: VS 2022 17.5 Preview 1, Python 3.11.0
  README.md
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  stl/inc/xstring
  tests/std/tests/Dev10_816787_swap_vector_bool_elements/test.cpp
  tests/std/tests/P0980R1_constexpr_strings/test.cpp
  tests/std/tests/P1004R2_constexpr_vector/test.cpp
  tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp
  tests/std/tests/P2321R2_proxy_reference/test.cpp
  tests/std/tests/VSO_0000000_allocator_propagation/test.cpp
Labels: infrastructure

#3065 Implement P2467R1 `ios_base::noreplace`: Exclusive Mode For `fstream`s (#2932)
  stl/inc/xiosbase
  stl/inc/yvals_core.h
  stl/src/fiopen.cpp
  tests/std/test.lst
  tests/std/tests/P2467R1_exclusive_mode_fstreams/env.lst
  tests/std/tests/P2467R1_exclusive_mode_fstreams/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23, affects redist

#3186 enable P0943R6_stdatomic_h test for clang
  tests/std/tests/P0943R6_stdatomic_h/test.compile.pass.cpp
Labels: test

#3187 P2278R4: `cbegin` should always return a constant iterator ("Ranges" and "Span" sections)
  stl/inc/ranges
  stl/inc/span
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_ranges_subrange/test.compile.pass.cpp
  tests/std/tests/P2278R4_const_span/env.lst
  tests/std/tests/P2278R4_const_span/test.cpp
  tests/std/tests/P2278R4_ranges_const_iterator_machinery/test.compile.pass.cpp
  tests/std/tests/P2278R4_ranges_const_range_machinery/env.lst
  tests/std/tests/P2278R4_ranges_const_range_machinery/test.cpp
Labels: ranges, cxx23

#3191 <yvals_core.h>: Update _MSVC_STL_UPDATE to November 2022
  stl/inc/yvals_core.h
Labels: enhancement

#3192 Change an error message in `<__msvc_cxx_stdatomic.hpp>`
  stl/inc/__msvc_cxx_stdatomic.hpp
Labels: documentation

#3196 [vscode settings] add `git.ignoredRepositories`
  .vscode/settings.json
Labels: enhancement

#3230 Status Chart: Weekly updates
  index.html
  package-lock.json
  package.json
  src/weekly_table.ts
  src_gather/video_table.ts
  usernames_contributors.txt
  usernames_maintainers.txt
Labels: documentation, uncharted

#3231 Implement LWG-3823 Unnecessary precondition for `is_aggregate` (workaround)
  stl/inc/type_traits
  tests/std/tests/VSO_0493909_is_aggregate/test.compile.pass.cpp
Labels: LWG

#3232 Standard Library Modules: Fix `time_put<wchar_t>` linker errors
  stl/inc/xlocale
  stl/inc/xloctime
  tests/std/include/test_header_units_and_modules.hpp
Labels: bug, modules

#3233 Standard Library Modules: Fix spurious `_Init_locks` dllexport
  stl/inc/yvals.h
  stl/src/cerr.cpp
  stl/src/cin.cpp
  stl/src/clog.cpp
  stl/src/cout.cpp
  stl/src/init_locks.hpp
  stl/src/iosptrs.cpp
  stl/src/stacktrace.cpp
  stl/src/syncstream.cpp
  stl/src/taskscheduler.cpp
  stl/src/wcerr.cpp
  stl/src/wcin.cpp
  stl/src/wclog.cpp
  stl/src/wcout.cpp
  stl/src/xlock.cpp
Labels: bug, modules

#3235 Don't rely on SSO zeroing in `basic_string::_Construct`
  stl/inc/xstring
Labels: bug, high priority

#3236 LWG-3515: [stacktrace.basic.nonmem]: `operator<<` should be less templatized
  stl/inc/stacktrace
  tests/std/tests/P0881R7_stacktrace/test.cpp
Labels: LWG

#3238 Update comments for approved LWG issues
  stl/inc/atomic
  stl/inc/ranges
  stl/inc/thread
  stl/inc/type_traits
  stl/inc/xutility
  tests/std/tests/P0660R10_jthread_and_cv_any/test.cpp
Labels: documentation
