Repository microsoft/STL, pull requests merged in 2022-09, with the labels that each got.

#3057 Implement P2438R2 `string::substr() &&`
  stl/inc/xstring
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/GH_003022_substr_allocator/env.lst
  tests/std/tests/GH_003022_substr_allocator/test.cpp
  tests/std/tests/P2438R2_substr_rvalue/env.lst
  tests/std/tests/P2438R2_substr_rvalue/test.cpp
Labels: cxx23

#3064 Add `$schema` to `cgmanifest.json`
  docs/cgmanifest.json
Labels: documentation

#3066 Enable `__builtin_bit_cast` for CUDA
  stl/inc/complex
  stl/inc/xutility
Labels: bug, high priority

#3071 1ES Hosted Pools: Use spot VMs
  azure-devops/create-1es-hosted-pool.ps1
  azure-pipelines.yml
Labels: infrastructure

#3068 Update `get_future`'s `[[nodiscard("message")]]`
  stl/inc/yvals_core.h
Labels: documentation

#3069 Improve warning suppressions for header units
  stl/inc/algorithm
  stl/inc/atomic
  stl/inc/format
  stl/inc/ranges
  stl/inc/regex
  stl/inc/span
  stl/inc/thread
  stl/inc/xstring
  stl/inc/xutility
Labels: bug, modules

#3070 Update `variant` "all types same/convertible" metaprogramming
  stl/inc/type_traits
  stl/inc/variant
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0088R3_variant/test.cpp
Labels: throughput

#3072 add test coverage for P2445R1 (`std::forward_like`)
  tests/std/tests/P2445R1_forward_like/test.compile.pass.cpp
  tests/std/tests/P2445R1_forward_like/test.cpp
Labels: test

#2949 Check the slide_view constructor precondition added by LWG-3711
  stl/inc/ranges
  tests/std/test.lst
  tests/std/tests/P2442R1_views_slide_death/env.lst
  tests/std/tests/P2442R1_views_slide_death/test.cpp
Labels: LWG, ranges

#3073 <yvals_core.h>: Update _MSVC_STL_UPDATE to September 2022
  stl/inc/yvals_core.h
Labels: enhancement

#3075 <yvals_core.h> Update P2549 to new revision
  stl/inc/yvals_core.h
Labels: cxx23

#3078 Skip Azure Pipelines for draft PRs
  azure-pipelines.yml
  stl/inc/yvals_core.h
Labels: infrastructure

#3082 Clean up validation
  tools/validate/validate.cpp
Labels: enhancement

#3083 Remove unneeded static_cast for xexp
  stl/src/xdscale.cpp
  stl/src/xfdscale.cpp
Labels: enhancement

#3084 Access _Clocptr statically, instead of through an instance
  stl/src/locale.cpp
Labels: enhancement

#3085 Compare the _W_decimal_point of the localeconv, not the decimal_point of said localeconv
  stl/src/xstoxflt.cpp
  stl/src/xwstoxfl.cpp
Labels: enhancement

#3086 Remove unneeded static casts
  stl/inc/__msvc_int128.hpp
Labels: enhancement

#3089 Cleanup `views::as_rvalue` tests
  tests/std/tests/P2446R2_views_as_rvalue/test.cpp
Labels: test

#3090 Use std::size over sizeof/sizeof
  stl/inc/cvt/wbuffer
  stl/inc/cvt/xjis
  stl/inc/cvt/xone_byte
  stl/inc/cvt/xtwo_byte
  stl/inc/regex
  stl/inc/xlocbuf
  stl/src/xdateord.cpp
  stl/src/xlsinh.cpp
  stl/src/xsinh.cpp
Labels: enhancement

#3091 Move assignment of xchar to declaration
  stl/src/xdnorm.cpp
  stl/src/xfdnorm.cpp
Labels: enhancement

#3092 Use a bitwise and instead of shifts
  stl/src/vector_algorithms.cpp
Labels: enhancement

#3093 Remove unneeded static_cast of return values.
  stl/src/xdscale.cpp
  stl/src/xdtest.cpp
  stl/src/xfdscale.cpp
  stl/src/xfdtest.cpp
Labels: enhancement

#3094 update working draft revision to N4917
  README.md
Labels: documentation

#3098 Add unwrapping to move_sentinel
  stl/inc/iterator
  stl/inc/xutility
  tests/std/tests/GH_002992_unwrappable_iter_sent_pairs/test.compile.pass.cpp
Labels: performance, ranges

#3104 Toolset update: VS 2022 17.4 Preview 2
  CMakeLists.txt
  README.md
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  tools/CMakeLists.txt
  tools/format/CMakeLists.txt
  tools/validate/CMakeLists.txt
Labels: infrastructure

#3074 Implement P2508R1 basic_format_string, format_string, wformat_string
  stl/inc/format
  stl/inc/yvals_core.h
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: format, cxx23

#3107 Suppress narrowing warnings in `piecewise_constant_distribution::densities`
  stl/inc/random
  tests/std/test.lst
  tests/std/tests/GH_003105_piecewise_densities/env.lst
  tests/std/tests/GH_003105_piecewise_densities/test.compile.pass.cpp
Labels: bug

#3113 Fix `ranges::is_permutation`'s helper lambdas
  stl/inc/algorithm
  tests/std/tests/P0896R4_ranges_alg_is_permutation/test.cpp
Labels: bug, ranges

#3115 `<any>`: Skip the contents when static RTTI is disabled
  stl/inc/any
  stl/inc/yvals_core.h
  stl/modules/std.ixx
  tests/std/include/test_header_units_and_modules.hpp
  tests/std/tests/P2465R3_standard_library_modules/env.lst
  tests/std/tests/VSO_0000000_has_static_rtti/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/env.lst
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: bug

#3116 Make `<xatomic.h>`, `<xbit_ops.h>`, and `<xerrc.h>` core headers
  stl/inc/xatomic.h
  stl/inc/xbit_ops.h
  stl/inc/xerrc.h
  tests/std/tests/GH_001411_core_headers/test.cpp
Labels: enhancement

#3117 Constexprize `bind_front` and `bind_back` tests
  tests/std/tests/P0356R5_bind_front/test.cpp
  tests/std/tests/P2387R3_bind_back/test.cpp
Labels: test

#3120 Fix ill-formed primary template in P0896R4_ranges_subrange
  tests/std/tests/P0896R4_ranges_subrange/test.compile.pass.cpp
Labels: test

#3129 Status Chart: Add the video backlog
  .gitignore
  README.md
  built/status_chart.mjs
  index.html
  package-lock.json
  package.json
  src/daily_table.ts
  src/status_chart.ts
  src/weekly_table.ts
  src_gather/gather_stats.ts
  src_gather/video_table.ts
  usernames_contributors.txt
Labels: documentation

#3121 Port MSBuild refactoring
  stl/msbuild/stl_1/dirs.proj
  stl/msbuild/stl_1/md/dirs.proj
  stl/msbuild/stl_1/msvcp_1.settings.targets
  stl/msbuild/stl_1/xmd/dirs.proj
  stl/msbuild/stl_2/dirs.proj
  stl/msbuild/stl_2/md/dirs.proj
  stl/msbuild/stl_2/msvcp_2.settings.targets
  stl/msbuild/stl_2/xmd/dirs.proj
  stl/msbuild/stl_asan/dirs.proj
  stl/msbuild/stl_atomic_wait/dirs.proj
  stl/msbuild/stl_atomic_wait/md/dirs.proj
  stl/msbuild/stl_atomic_wait/msvcp_atomic_wait.settings.targets
  stl/msbuild/stl_atomic_wait/xmd/dirs.proj
  stl/msbuild/stl_base/dirs.proj
  stl/msbuild/stl_base/md/dirs.proj
  stl/msbuild/stl_base/msvcp.settings.targets
  stl/msbuild/stl_base/mt/dirs.proj
  stl/msbuild/stl_base/mt1/dirs.proj
  stl/msbuild/stl_base/xmd/dirs.proj
  stl/msbuild/stl_base/xmt/dirs.proj
  stl/msbuild/stl_base/xmt0/dirs.proj
  stl/msbuild/stl_base/xmt1/dirs.proj
  stl/msbuild/stl_codecvt_ids/dirs.proj
  stl/msbuild/stl_codecvt_ids/md/dirs.proj
  stl/msbuild/stl_codecvt_ids/msvcp_codecvt_ids.settings.targets
  stl/msbuild/stl_codecvt_ids/xmd/dirs.proj
  stl/msbuild/stl_post/dirs.proj
  stl/msbuild/stl_post/md/dirs.proj
  stl/msbuild/stl_post/msvcp_post.settings.targets
  stl/msbuild/stl_post/xmd/dirs.proj
Labels: build

#3133 Port more MSBuild refactoring
  CMakeLists.txt
Labels: build
