Repository microsoft/STL, pull requests merged in 2022-07, with the labels that each got.

#2832 Fix cross-PR contamination by cleaning after checkout
  azure-devops/checkout-sources.yml
  azure-pipelines.yml
Labels: infrastructure

#2049 `xloctime`: `do_put` shouldn't modify errno on success
  stl/inc/xloctime
  tests/std/test.lst
  tests/std/tests/GH_002045_put_time_changes_errno/env.lst
  tests/std/tests/GH_002045_put_time_changes_errno/test.cpp
Labels: bug, affects redist

#2317 Hasta la Vista
  stl/inc/yvals_core.h
  stl/src/awint.hpp
  stl/src/filesystem.cpp
  stl/src/mutex.cpp
  stl/src/primitives.hpp
  stl/src/winapisupp.cpp
Labels: performance, affects redist

#2742 `syserror.cpp`: update `_Syserror_map`
  stl/inc/system_error
  stl/src/syserror.cpp
Labels: enhancement, affects redist

#2744 syserror.cpp: add more matches against std::errc::timed_out
  stl/src/syserror.cpp
  tests/std/tests/Dev11_0493504_error_category_lifetime/test.cpp
Labels: enhancement, affects redist

#2766 Refactor Filesystem Code for Clarity
  stl/inc/cvt/one_one
  stl/inc/cvt/utf8
  stl/inc/experimental/filesystem
  stl/inc/filesystem
  stl/src/filesys.cpp
  stl/src/filesystem.cpp
Labels: affects redist, filesystem

#2771 Improve filesystem file resizing
  stl/src/filesys.cpp
  stl/src/filesystem.cpp
Labels: performance, affects redist, filesystem

#2824 workaround for `std::source_location::current()`
  stl/inc/source_location
  tests/std/tests/P1208R6_source_location/test.cpp
Labels: bug

#2825 Extend range of min max optimization
  stl/inc/algorithm
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance, ranges

#2828 Move machinery from `inc/ymath.h` to `src/xmath.hpp`
  stl/inc/ymath.h
  stl/src/xmath.hpp
Labels: enhancement

#2833 `<tuple>`: Overhaul `tuple_cat()` for simplicity and less special-casing
  stl/inc/tuple
  tests/std/tests/Dev11_0000000_tuple_cat/test.cpp
Labels: enhancement

#2835 Status Chart: Dark mode with Primer CSS
  index.html
  package-lock.json
  package.json
  src/status_chart.ts
  src/weekly_table.ts
Labels: documentation

#2843 .natvis: Add view for unique_ptr/vector of chars
  stl/debugger/STL.natvis
Labels: visualizer

#2845 Status Chart: Colorized counters, mobile-optimized
  index.html
  package-lock.json
  package.json
  src/status_chart.ts
  src/weekly_table.ts
Labels: documentation

#2191 Adding mutex, ranges, functional, any and format visualizers
  stl/debugger/STL.natvis
Labels: visualizer

#2814 Fix chrono printing
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
Labels: bug, format, chrono

#2837 `syserror.cpp`: Assert that `_Win_errtab` is sorted and unique
  stl/src/syserror.cpp
Labels: enhancement

#2840 <yvals_core.h>: Update _MSVC_STL_UPDATE to July 2022
  stl/inc/yvals_core.h
Labels: enhancement

#2841 `winapisupp.cpp`: Dramatically shrink the function pointer table
  stl/src/awint.hpp
  stl/src/winapisupp.cpp
Labels: performance, affects redist

#2850 `<cstdlib>`: Provide `std::getenv` and `std::system` for UWP apps
  stl/inc/cstdlib
Labels: enhancement

#2851 <xloctime>: time_get::get can still assert 'istreambuf_iterator is not dereferenceable' when the format is longer than the stream
  stl/inc/xloctime
  tests/std/tests/Dev11_0836436_get_time/test.cpp
Labels: bug

#2853 run memory leaks tests only with Debug CRT
  tests/std/tests/Dev10_908702_string_memory_leak/test.cpp
  tests/std/tests/Dev11_0748972_function_crash_out_of_memory/test.cpp
Labels: test

#2854 remove `directory_entry::clear_cache`
  stl/inc/filesystem
  stl/inc/yvals_core.h
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: bug, filesystem

#2855 `<complex>`: avoid unnecessary conversion of real arguments to complex
  stl/inc/complex
Labels: performance

#2125 Move charconv tables
  stl/CMakeLists.txt
  stl/inc/charconv
  stl/inc/header-units.json
  stl/inc/xcharconv_ryu_tables.h
  stl/inc/xcharconv_tables.h
  stl/msbuild/stl_base/stl.files.settings.targets
  stl/src/charconv.cpp
  stl/src/xcharconv_ryu_tables.cpp
  stl/src/xcharconv_tables_double.cpp
  stl/src/xcharconv_tables_float.cpp
  tools/scripts/charconv_generate.cpp
  tools/scripts/charconv_tables_generate.cpp
Labels: throughput

#2302 Update filesystem library to use GetTempPath2 on Windows 11
  stl/src/filesys.cpp
  stl/src/filesystem.cpp
  stl/src/winapisupp.cpp
Labels: enhancement, affects redist, filesystem

#2846 <atomic> refactoring to support C11
  stl/inc/atomic
  stl/inc/memory
Labels: enhancement

#2863 Update workaround bug number
  stl/inc/type_traits
Labels: documentation

#2864 Don't assume that WaitOnAddress is not statically available on ARM/ARM64
  tests/std/tests/P1135R6_atomic_wait_vista/test.cpp
Labels: test, ARM64

#2865 Extract `_Bitmask_includes_any()`, `_Bitmask_includes_all()` from `_BITMASK_OPS`
  stl/inc/filesystem
  stl/inc/type_traits
  stl/inc/xfilesystem_abi.h
  stl/src/filesystem.cpp
Labels: throughput

#2870 Fix incorrect result of `complex` `log`/`log10`/`pow` on ARM64
  stl/inc/complex
  tests/std/tests/GH_000935_complex_numerical_accuracy/log_test_cases.hpp
Labels: bug, ARM64

#2061 add STL4038 prefix to "requires C++NN or later" messages
  stl/inc/any
  stl/inc/barrier
  stl/inc/bit
  stl/inc/charconv
  stl/inc/compare
  stl/inc/concepts
  stl/inc/coroutine
  stl/inc/execution
  stl/inc/expected
  stl/inc/filesystem
  stl/inc/format
  stl/inc/latch
  stl/inc/memory_resource
  stl/inc/numbers
  stl/inc/optional
  stl/inc/ranges
  stl/inc/semaphore
  stl/inc/source_location
  stl/inc/span
  stl/inc/spanstream
  stl/inc/stacktrace
  stl/inc/stdatomic.h
  stl/inc/stop_token
  stl/inc/string_view
  stl/inc/syncstream
  stl/inc/variant
  stl/inc/yvals.h
  stl/inc/yvals_core.h
Labels: enhancement

#2867 Fix LWG-3699 `lexically_relative` on UNC drive paths (`\\?\C:\...`) results in a default-constructed value
  stl/inc/filesystem
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: bug, filesystem

#2877 `<filesystem>` support junctions in `read_symlink`
  stl/inc/filesystem
  stl/inc/xfilesystem_abi.h
  stl/src/filesystem.cpp
Labels: bug, filesystem

#2878 Implement LWG-3710: The `end` of `chunk_view` for input ranges can be `const`
  stl/inc/ranges
  tests/std/tests/P2442R1_views_chunk/test.cpp
Labels: LWG

#2879 Implement LWG-3683: `operator==` for `polymorphic_allocator` cannot deduce template argument in common cases
  stl/inc/xpolymorphic_allocator.h
  tests/std/tests/P0220R1_polymorphic_memory_resources/test.cpp
Labels: LWG

#2880 Implement LWG-3656: Inconsistent bit operations returning a count
  stl/inc/bit
  stl/inc/format
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0556R3_bit_integral_power_of_two_operations/test.cpp
Labels: LWG

#2883 Implement LWG-3707: `chunk_view::outer-iterator::value_type::size` should return unsigned type
  stl/inc/ranges
  tests/std/tests/P2442R1_views_chunk/test.cpp
Labels: LWG, ranges

#2899 Map more Windows System errors
  stl/src/syserror.cpp
  tests/std/tests/Dev11_0493504_error_category_lifetime/test.cpp
Labels: enhancement, affects redist

#2902 Implement LWG-3719: Directory iterators should be usable with default sentinel
  stl/inc/filesystem
  stl/inc/regex
  tests/std/tests/P0896R4_stream_iterators/test.cpp
Labels: LWG, ranges

#2903 Implement LWG-3724: `decay-copy` should be constrained
  stl/inc/ranges
  tests/std/tests/P0896R4_views_all/test.cpp
Labels: LWG, ranges

#2905 Implement LWG-3671: `atomic_fetch_xor` missing from `stdatomic.h`
  stl/inc/stdatomic.h
  tests/std/tests/P0943R6_stdatomic_h/test.compile.pass.cpp
Labels: LWG

#2906 Implement LWG-3721: Allow an arg-id with a value of zero for width in std-format-spec
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_death/test.cpp
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Labels: LWG, format

#2907 Implement LWG-3672: `common_iterator::operator->()` should return by value
  stl/inc/iterator
  tests/std/tests/P0896R4_common_iterator/test.cpp
Labels: LWG, ranges

#2911 <algorithm> Implement P2302R4 ranges::contains
  stl/inc/algorithm
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2302R4_ranges_alg_contains/env.lst
  tests/std/tests/P2302R4_ranges_alg_contains/test.cpp
  tests/std/tests/P2302R4_ranges_alg_contains_subrange/env.lst
  tests/std/tests/P2302R4_ranges_alg_contains_subrange/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23

#2943 Implement LWG-3712: `chunk_view` and `slide_view` should not be `default_initializable`
  stl/inc/ranges
  tests/std/tests/P2442R1_views_chunk/test.cpp
  tests/std/tests/P2442R1_views_slide/test.cpp
Labels: LWG, ranges

#2946 Implement LWG-3715: `view_interface::empty` is overconstrained
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_subrange/test.compile.pass.cpp
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_elements/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
  tests/std/tests/P0896R4_views_transform/test.cpp
  tests/std/tests/P2442R1_views_chunk/test.cpp
Labels: LWG, ranges

#2947 Implement P2499R0: `string_view` Range Constructor Should Be `explicit`
  stl/inc/xstring
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0220R1_string_view/test.cpp
Labels: cxx23

#2950 Cleanup comments after merging LWG-3670 and LWG-3705
  stl/inc/ranges
  stl/inc/xstring
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: documentation

#2967 Status Chart: Fix CSS loading race
  index.html
  package-lock.json
  package.json
  src/status_chart.ts
  src/weekly_table.ts
Labels: bug, documentation
