Repository microsoft/STL, pull requests merged in 2023-09, with the labels that each got.

#3964 Remove some `#ifdef _CRTBLD` blocks
  stl/inc/xthreads.h
  stl/inc/yvals.h
  stl/src/awint.hpp
  stl/src/cerr.cpp
  stl/src/cin.cpp
  stl/src/clog.cpp
  stl/src/cond.cpp
  stl/src/cout.cpp
  stl/src/mutex.cpp
  stl/src/wcerr.cpp
  stl/src/wcin.cpp
  stl/src/wclog.cpp
  stl/src/wcout.cpp
  stl/src/xmtx.hpp
Labels: enhancement

#3973 Cleanups for `<exception>`
  stl/inc/chrono
  stl/inc/exception
  stl/inc/xmemory
Labels: enhancement

#3982 Fix `num_get`'s float-parsing problem
  stl/inc/xlocnum
  tests/std/tests/LWG2381_num_get_floating_point/test.cpp
Labels: bug, high priority

#4003 Update _MSVC_STL_UPDATE to September 2023
  stl/inc/yvals_core.h
Labels: enhancement

#4012 Remove `/clr` test workarounds
  tests/std/include/range_algorithm_support.hpp
  tests/std/include/test_atomic_wait.hpp
  tests/std/tests/P0019R8_atomic_ref/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_equal/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_for_each/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_inclusive_scan/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_mismatch/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_reduce/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_replace/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_transform_inclusive_scan/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_transform_reduce/test.cpp
  tests/std/tests/P0896R4_ranges_alg_equal/test.cpp
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_elements/test.cpp
  tests/std/tests/P0896R4_views_iota/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
  tests/std/tests/P1135R6_atomic_flag_test/test.cpp
  tests/std/tests/P1522R1_difference_type/test.cpp
Labels: test

#4013 Make `expected<any, ...>` and `expected<void, any>` copyable
  stl/inc/expected
  tests/std/tests/P0323R12_expected/test.cpp
Labels: bug

#3993 Various bugfixes / enhancements for `<flat_set>`
  stl/inc/flat_set
  tests/std/tests/P1222R4_flat_set/test.cpp
Labels: bug, flat_meow

#3911 `<valarray>`: Cleanups and length checking for binary operations
  stl/inc/valarray
Labels: enhancement

#3972 P0009R18 `<mdspan>`
  stl/CMakeLists.txt
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/header-units.json
  stl/inc/mdspan
  stl/inc/yvals_core.h
  stl/modules/std.ixx
  tests/std/include/test_header_units_and_modules.hpp
  tests/std/include/test_mdspan_support.hpp
  tests/std/test.lst
  tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp
  tests/std/tests/P0009R18_mdspan_default_accessor/env.lst
  tests/std/tests/P0009R18_mdspan_default_accessor/test.cpp
  tests/std/tests/P0009R18_mdspan_extents/env.lst
  tests/std/tests/P0009R18_mdspan_extents/test.cpp
  tests/std/tests/P0009R18_mdspan_extents_death/env.lst
  tests/std/tests/P0009R18_mdspan_extents_death/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_left/env.lst
  tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_left_death/env.lst
  tests/std/tests/P0009R18_mdspan_layout_left_death/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_right/env.lst
  tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_right_death/env.lst
  tests/std/tests/P0009R18_mdspan_layout_right_death/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_stride/env.lst
  tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_stride_death/env.lst
  tests/std/tests/P0009R18_mdspan_layout_stride_death/test.cpp
  tests/std/tests/P0009R18_mdspan_mdspan/env.lst
  tests/std/tests/P0009R18_mdspan_mdspan/test.cpp
  tests/std/tests/P0009R18_mdspan_mdspan_death/env.lst
  tests/std/tests/P0009R18_mdspan_mdspan_death/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/importable_cxx_library_headers.jsonc
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tests/std/tests/include_each_header_alone_matrix.lst
Labels: cxx23, mdspan

#4005 Remove some functions defined in `_CRTBLD` blocks
  stl/inc/__msvc_filebuf.hpp
  stl/inc/fstream
  stl/src/fiopen.cpp
Labels: enhancement

#4006 `<istream>`, `<ostream>`: Deprecate pre-Standard `ipfx`, `isfx`, `opfx`, and `osfx` functions
  stl/inc/istream
  stl/inc/ostream
  stl/inc/yvals_core.h
Labels: enhancement

#4014 Prepare for impending LLVM 17 release
  stl/inc/__msvc_iter_core.hpp
  stl/inc/ranges
  stl/inc/type_traits
  stl/inc/utility
  tests/std/tests/P2321R2_views_zip_transform/test.cpp
Labels: enhancement

#4015 Remove unnecessary #include "awint.hpp"
  stl/src/cthread.cpp
  stl/src/dllmain.cpp
  stl/src/primitives.hpp
  stl/src/taskscheduler.cpp
  stl/src/winapinls.cpp
  stl/src/winapisupp.cpp
  stl/src/xalloc.cpp
  stl/src/xdateord.cpp
  stl/src/xgetwctype.cpp
  stl/src/xmtx.cpp
  stl/src/xonce.cpp
Labels: enhancement

#4020 use only `static_assert` for `_EMIT_STL_ERROR`
  stl/inc/yvals_core.h
Labels: enhancement

#4024 updated working draft to N4958
  README.md
Labels: documentation

#4026 Silence a couple of `/Wall` warnings
  stl/inc/stacktrace
  stl/inc/yvals_core.h
Labels: enhancement

#4028 Toolset update: VS 2022 17.8 Preview 2
  CMakeLists.txt
  README.md
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  benchmarks/CMakeLists.txt
  stl/inc/mdspan
  tools/CMakeLists.txt
  tools/format/CMakeLists.txt
  tools/validate/CMakeLists.txt
Labels: infrastructure

#4034 More bugfixes for `flat_set`
  stl/inc/flat_set
  tests/std/tests/P1222R4_flat_set/test.cpp
Labels: bug, flat_meow

#4019 More enhancements for `<flat_set>`
  stl/inc/flat_set
Labels: bug, flat_meow

#3353 [vector.bool] Optimize copy / move algorithms
  benchmarks/CMakeLists.txt
  benchmarks/src/std/containers/sequences/vector.bool/copy/test.cpp
  benchmarks/src/std/containers/sequences/vector.bool/copy_n/test.cpp
  benchmarks/src/std/containers/sequences/vector.bool/move/test.cpp
  stl/inc/vector
  stl/inc/xutility
  tests/std/tests/GH_000625_vector_bool_optimization/test.cpp
Labels: performance

#3913 Implement debug-enabled `formatter` specializations
  stl/inc/format
  tests/std/include/test_format_support.hpp
  tests/std/test.lst
  tests/std/tests/P2286R8_text_formatting_debug_enabled_specializations/env.lst
  tests/std/tests/P2286R8_text_formatting_debug_enabled_specializations/test.cpp
  tests/std/tests/P2286R8_text_formatting_escaping/env.lst
  tests/std/tests/P2286R8_text_formatting_escaping/test.cpp
  tests/std/tests/P2286R8_text_formatting_escaping_legacy_text_encoding/env.lst
  tests/std/tests/P2286R8_text_formatting_escaping_legacy_text_encoding/test.cpp
  tests/std/tests/P2286R8_text_formatting_escaping_utf8/env.lst
  tests/std/tests/P2286R8_text_formatting_escaping_utf8/test.cpp
Labels: ranges, format

#3965 Bugfixes for `<any>`
  stl/inc/any
  tests/std/tests/P0220R1_any/test.cpp
Labels: bug

#3974 Cleanups for `condition_variable`'s waiting functions
  stl/inc/latch
  stl/inc/mutex
  stl/inc/semaphore
Labels: enhancement

#4017 Fix `deque`'s usage of `_Allocate_at_least_helper`
  stl/inc/deque
  tests/std/tests/GH_003570_allocate_at_least/test.cpp
Labels: bug

#4029 extract code format validation into a new template
  azure-devops/format-validation.yml
  azure-pipelines.yml
Labels: infrastructure

#4032 Tolerate 80-bit `long double` in `<xlocnum>`
  stl/inc/xlocnum
Labels: enhancement

#4036 Document `_Ref_fn`'s *raison d'etre*
  stl/inc/xutility
Labels: documentation

#4037 `<mdspan>`: Fixes signed overflow in `_Fwd_prod_of_extents`
  stl/inc/mdspan
  tests/std/test.lst
  tests/std/tests/GH_004023_mdspan_fwd_prod_overflow/env.lst
  tests/std/tests/GH_004023_mdspan_fwd_prod_overflow/test.compile.pass.cpp
Labels: bug

#4039 Require VS 2022 17.8, remove workaround
  stl/inc/ranges
  stl/inc/yvals_core.h
Labels: enhancement

#3940 `<future>` cleanups
  stl/inc/future
Labels: enhancement

#3984 Cleanups and enhancements for `basic_string`
  stl/inc/xstring
Labels: enhancement

#4025 Avoid unconditional `make_heap` for `priority_queue::push_range`
  benchmarks/CMakeLists.txt
  benchmarks/src/priority_queue_push_range.cpp
  stl/inc/queue
  stl/inc/xutility
Labels: performance

#4031 Fix the `_Choose_pocca_v` branch in `basic_string::operator=(const&)`
  stl/inc/xstring
  tests/std/tests/VSO_0000000_allocator_propagation/test.cpp
Labels: bug

#4016 Cleanups for `<deque>` part 1
  stl/inc/deque
Labels: enhancement

#4022 `<deque>`: Fix single-element insertion of `deque`
  stl/inc/deque
  tests/std/tests/Dev10_860421_deque_push_back_pop_front/test.cpp
Labels: bug

#4033 Status Chart: Weekly updates
  index.html
  package-lock.json
  package.json
  src/weekly_table.ts
Labels: documentation, uncharted

#4041 Fix comparison operators and `get` of `array`
  stl/inc/array
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/GH_004040_container_nonmember_functions/env.lst
  tests/std/tests/GH_004040_container_nonmember_functions/test.cpp
Labels: bug

#4042 Make `to_array` ADL-proof
  stl/inc/array
  tests/std/tests/P0325R4_to_array/test.cpp
Labels: bug

#4045 ASAN found _two_ bugs in `_Copy_vbool`!
  stl/inc/vector
Labels: bug

#4050 🛠️ for `flat_set`
  stl/inc/flat_set
  tests/std/tests/P1222R4_flat_set/test.cpp
Labels: flat_meow
