Repository microsoft/STL, pull requests merged in 2023-11, with the labels that each got.

#4150 ASan: Remove `noexcept` from `__sanitizer_annotate_contiguous_container`
  stl/inc/__msvc_sanitizer_annotate_container.hpp
Labels: bug, ASAN

#4134 Make invoke constexpr available in all modes
  stl/inc/type_traits
  stl/inc/yvals_core.h
  tests/std/tests/Dev11_0535636_functional_overhaul/test.cpp
Labels: enhancement

#4143 Various cleanups: `extern "C"`
  .clang-format
  stl/inc/__msvc_print.hpp
  stl/inc/__msvc_sanitizer_annotate_container.hpp
  stl/inc/__msvc_system_error_abi.hpp
  stl/inc/__msvc_tzdb.hpp
  stl/inc/algorithm
  stl/inc/atomic
  stl/inc/cmath
  stl/inc/complex
  stl/inc/execution
  stl/inc/memory
  stl/inc/stacktrace
  stl/inc/syncstream
  stl/inc/system_error
  stl/inc/xatomic_wait.h
  stl/inc/xfilesystem_abi.h
  stl/inc/xlocinfo
  stl/inc/xthreads.h
  stl/inc/xtimec.h
  stl/inc/xutility
  stl/inc/yvals_core.h
  stl/src/asan.cpp
  stl/src/asan_noop.cpp
  stl/src/atomic.cpp
  stl/src/atomic_wait.cpp
  stl/src/cond.cpp
  stl/src/cthread.cpp
  stl/src/filesystem.cpp
  stl/src/locale0.cpp
  stl/src/mutex.cpp
  stl/src/print.cpp
  stl/src/sharedmutex.cpp
  stl/src/special_math.cpp
  stl/src/stacktrace.cpp
  stl/src/syncstream.cpp
  stl/src/syserror_import_lib.cpp
  stl/src/tzdb.cpp
  stl/src/xlock.cpp
  stl/src/xnotify.cpp
  stl/src/xonce2.cpp
  stl/src/xtime.cpp
  stl/src/xxxdtent.hpp
  stl/src/xxxprec.hpp
Labels: enhancement

#4145 Various cleanups: Use `_STDEXT_BEGIN` and `_STDEXT_END`
  stl/inc/xhash
Labels: enhancement

#4147 Various cleanups: `<xatomic_wait.h>` constants
  stl/inc/atomic
  stl/inc/memory
  stl/inc/semaphore
  stl/inc/xatomic_wait.h
  stl/src/atomic_wait.cpp
  stl/src/parallel_algorithms.cpp
Labels: enhancement

#4132 `<flat_set>`: `flat_(multi)set`'s `iterator` type should be constant iterator
  stl/inc/flat_set
  tests/std/tests/P1222R4_flat_set/test.cpp
Labels: enhancement, flat_meow

#4138 ADL-proof implementation of algorithms in [alg.nonmodifying]
  stl/inc/algorithm
  stl/inc/atomic
  stl/inc/execution
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/GH_001596_adl_proof_algorithms/env.lst
  tests/std/tests/GH_001596_adl_proof_algorithms/test.compile.pass.cpp
  tests/std/tests/P2538R1_adl_proof_std_projected/test.compile.pass.cpp
Labels: bug

#4142 `<ranges>`: Avoid infinite recursion in `ranges::to` when the inner ranges match but the destination container is still not constructible
  stl/inc/ranges
Labels: bug, ranges

#4149 `<xutility>`: Fix inaccurate constraint of `_Equal_rev_pred`
  stl/inc/xutility
Labels: enhancement

#4151 Various cleanups: Declare `_Meow_vbool` to avoid ADL
  stl/inc/xutility
Labels: enhancement

#4148 `<flat_set>`: Correct allocator-extended constructors for `flat_(multi)set`
  stl/inc/flat_set
  tests/std/tests/P1222R4_flat_set/test.cpp
Labels: bug, flat_meow

#4156 `<flat_set>`: Restore insertion in `flat_(multi)set`'s iterator-pair/range constructors
  stl/inc/flat_set
Labels: flat_meow

#4197 Toolset update: VS 2022 17.9 Preview 1
  README.md
  azure-devops/config.yml
  azure-devops/provision-image.ps1
  stl/inc/stacktrace
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/std/include/test_atomic_wait.hpp
  tests/std/tests/P0226R1_math_special_functions/test.cpp
  tests/std/tests/VSO_0000000_type_traits/test.cpp
Labels: infrastructure

#4190 Implement LWG-3749 `common_iterator` should handle integer-class difference types
  stl/inc/iterator
  tests/std/tests/P0896R4_common_iterator/test.cpp
Labels: LWG, ranges

#4191 Remove more unnecessary `typename`s
  stl/inc/__msvc_iter_core.hpp
  stl/inc/iterator
  tests/std/include/range_algorithm_support.hpp
  tests/std/include/test_mdspan_support.hpp
  tests/std/tests/P0053R7_cpp_synchronized_buffered_ostream/test.cpp
  tests/std/tests/P0631R8_numbers_math_constants/test.cpp
  tests/std/tests/P0645R10_text_formatting_args/test.cpp
  tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp
  tests/std/tests/P0753R2_manipulators_for_cpp_synchronized_buffered_ostream/test.cpp
  tests/std/tests/P0768R1_spaceship_cpos/test.cpp
  tests/std/tests/P0896R4_common_iterator/test.cpp
  tests/std/tests/P0896R4_counted_iterator/test.cpp
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_ranges_to_address/test.cpp
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_filter_iterator/test.cpp
  tests/std/tests/P0896R4_views_lazy_split/test.cpp
  tests/std/tests/P0896R4_views_split/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
  tests/std/tests/P0896R4_views_transform/test.cpp
  tests/std/tests/P0898R3_identity/test.cpp
  tests/std/tests/P1206R7_ranges_to_mappish/test.cpp
  tests/std/tests/P1206R7_ranges_to_sequence/test.cpp
  tests/std/tests/P1206R7_ranges_to_settish/test.cpp
  tests/std/tests/P1614R2_spaceship/test.cpp
  tests/std/tests/P1899R3_views_stride/test.cpp
  tests/std/tests/P2165R4_tuple_like_tuple_members/test.cpp
  tests/std/tests/P2278R4_basic_const_iterator/test.cpp
  tests/std/tests/P2278R4_const_span/test.cpp
  tests/std/tests/P2286R8_text_formatting_formattable/test.compile.pass.cpp
  tests/std/tests/P2321R2_views_adjacent/test.cpp
  tests/std/tests/P2321R2_views_adjacent_transform/test.cpp
  tests/std/tests/P2321R2_views_zip/test.cpp
  tests/std/tests/P2321R2_views_zip_transform/test.cpp
  tests/std/tests/P2374R4_views_cartesian_product/test.cpp
  tests/std/tests/P2408R5_ranges_iterators_to_classic_algorithms/test.cpp
  tests/std/tests/P2441R2_views_join_with/test.cpp
  tests/std/tests/P2505R5_monadic_functions_for_std_expected/test.cpp
Labels: enhancement

#4192 Various cleanups: Enable more clang-format
  stl/inc/algorithm
  stl/inc/format
  stl/inc/iterator
  stl/inc/optional
  stl/inc/ranges
  stl/inc/spanstream
  stl/inc/xutility
  tests/std/include/range_algorithm_support.hpp
  tests/std/tests/P0896R4_P1614R2_comparisons/test.cpp
  tests/std/tests/P0896R4_counted_iterator/test.cpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_ranges_subrange/test.compile.pass.cpp
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_join/test.cpp
  tests/std/tests/P0896R4_views_lazy_split/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/std/tests/P1206R7_string_insert_range/test.cpp
  tests/std/tests/P1206R7_string_replace_with_range/test.cpp
  tests/std/tests/P1659R3_ranges_alg_ends_with/test.cpp
  tests/std/tests/P2286R8_text_formatting_formattable/test.compile.pass.cpp
  tests/std/tests/P2404R3_move_only_types_for_comparison_concepts/test.compile.pass.cpp
Labels: enhancement

#4204 Implement LWG-3949: `atomic<bool>`'s trivial destructor dropped in C++17 spec wording
  tests/std/tests/Dev11_0863628_atomic_compare_exchange/test.cpp
Labels: LWG

#4167 Update return type of `iter_move` to `decltype(auto)`
  stl/inc/iterator
Labels: LWG

#4186 Implement LWG-3897 `inout_ptr` will not update raw pointer to null
  stl/inc/memory
  tests/std/tests/P1132R7_out_ptr/test.cpp
Labels: LWG

#4187 Implement LWG-3946 The definition of `const_iterator_t` should be reworked
  stl/inc/ranges
  tests/std/tests/P2278R4_ranges_const_range_machinery/test.cpp
Labels: LWG, ranges

#4188 P2836R1: `basic_const_iterator` Should Follow Its Underlying Type's Convertibility
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/tests/P2278R4_basic_const_iterator/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23, defect report

#4193 Implement LWG-4001 `iota_view` should provide `empty`
  stl/inc/ranges
  tests/std/tests/P0896R4_views_iota/test.cpp
Labels: LWG, ranges

#4194 Implement LWG-3809 Is `subtract_with_carry_engine<uint16_t>` supposed to work?
  stl/inc/random
  tests/std/tests/Dev11_0577418_random_seed_0/test.cpp
Labels: LWG

#4195 Implement LWG-3947 Unexpected constraints on `adjacent_transform_view::base()`
  stl/inc/ranges
  tests/std/tests/P2321R2_views_adjacent_transform/test.cpp
Labels: LWG, ranges

#4203 Implement P2937R0 Freestanding Library: Remove strtok
  stl/inc/yvals_core.h
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx26

#4155 `<format>`: Reject dynamic width or precision of non-integral type
  stl/inc/chrono
  stl/inc/format
Labels: bug, format

#4189 Implement P2909R4 Fix Formatting Of Code Units As Integers
  stl/inc/format
  stl/inc/yvals_core.h
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx20, format, defect report

#4206 Disable CodeQL
  azure-devops/config.yml
Labels: infrastructure

#4207 Merge `main` to `feature/flat_set`
  azure-devops/config.yml
Labels: uncharted, flat_meow

#4133 Implement `formatter<vector<bool>::reference>`
  stl/CMakeLists.txt
  stl/inc/__msvc_formatter.hpp
  stl/inc/chrono
  stl/inc/format
  stl/inc/header-units.json
  stl/inc/stacktrace
  stl/inc/string
  stl/inc/thread
  stl/inc/vector
  stl/inc/xmemory
  tests/std/test.lst
  tests/std/tests/P2286R8_text_formatting_formattable/test.compile.pass.cpp
  tests/std/tests/P2286R8_text_formatting_vector_bool_reference/env.lst
  tests/std/tests/P2286R8_text_formatting_vector_bool_reference/test.cpp
Labels: ranges, format, cxx23

#4211 `<ranges>`: Fix the return types and overload resolution of range adaptor closure objects
  stl/inc/ranges
  tests/std/tests/P2387R3_pipe_support_for_user_defined_range_adaptors/test.cpp
Labels: bug, ranges

#4212 `<xlocnum>`: Drop `ios_base::showpoint` flag when printing non-finite values
  stl/inc/xlocnum
  tests/std/tests/GH_003867_output_nan/test.cpp
Labels: bug

#4213 Update _MSVC_STL_UPDATE to November 2023
  stl/inc/yvals_core.h
Labels: enhancement

#4214 `<mdspan>`: Check preconditions of `mdspan::operator[]` clarified by LWG-3974
  stl/inc/mdspan
  tests/std/tests/P0009R18_mdspan_mdspan_death/test.cpp
Labels: LWG, mdspan

#4217 ADL-proof implementation of `erase_if` and related algorithms
  stl/inc/deque
  stl/inc/experimental/deque
  stl/inc/experimental/forward_list
  stl/inc/experimental/list
  stl/inc/experimental/map
  stl/inc/experimental/set
  stl/inc/experimental/string
  stl/inc/experimental/unordered_map
  stl/inc/experimental/unordered_set
  stl/inc/experimental/vector
  stl/inc/forward_list
  stl/inc/list
  stl/inc/map
  stl/inc/set
  stl/inc/unordered_map
  stl/inc/unordered_set
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/xstring
  tests/std/tests/GH_001596_adl_proof_algorithms/test.compile.pass.cpp
  tests/std/tests/VSO_0000000_instantiate_containers/test.compile.pass.cpp
Labels: bug

#4218 `<ranges>`: Fix a correctness-damaging typo in `ranges::to`
  stl/inc/ranges
  tests/std/tests/P1206R7_ranges_to_misc/test.cpp
Labels: bug, ranges

#4219 `<sstream>`: Pass the correct size type to `_Allocate_at_least_helper`
  stl/inc/sstream
Labels: bug

#4220 Update `P1208R6_source_location` after MSVC-internal changes
  tests/std/tests/P1208R6_source_location/test.cpp
Labels: test
