Repository microsoft/STL, pull requests merged in 2023-03, with the labels that each got.

#3534 `<mdspan>`: Various cleanups
  stl/inc/mdspan
Labels: enhancement, mdspan

#3406 `<atomic>`: improve code documentation
  stl/inc/atomic
Labels: documentation

#3503 Implement LWG-3734 Inconsistency in `inout_ptr` and `out_ptr` for empty case
  stl/inc/memory
  tests/std/tests/P1132R7_out_ptr/test.cpp
Labels: LWG

#3504 Implement LWG-3877 Incorrect constraints on `const`-qualified monadic overloads for `std::expected`
  stl/inc/expected
  tests/std/tests/P2505R5_monadic_functions_for_std_expected/test.cpp
Labels: LWG

#3506 Implement LWG-2195 Missing constructors for `match_results`
  stl/inc/regex
  tests/std/tests/VSO_0000000_regex_interface/test.cpp
Labels: LWG

#3509 Implement LWG-3821 `uses_allocator_construction_args` should have overload for `pair-like`
  stl/inc/utility
  stl/inc/xmemory
  tests/std/tests/P0475R1_P0591R4_uses_allocator_construction/test.cpp
Labels: LWG

#3510 pool resources: respect `max_blocks_per_chunk`
  stl/inc/memory_resource
  tests/std/tests/P0220R1_polymorphic_memory_resources/test.cpp
Labels: bug

#3511 Implement LWG-3720 Restrict the valid types of arg-id for width and precision in std-format-spec
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Labels: LWG

#3513 Implement P2655R3 `common_reference_t` Of `reference_wrapper` Should Be A Reference Type
  stl/inc/concepts
  stl/inc/type_traits
  stl/inc/yvals_core.h
  tests/std/tests/VSO_0000000_type_traits/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#3518 Update _MSVC_STL_UPDATE to March 2023
  stl/inc/yvals_core.h
Labels: enhancement

#3466 Implement P2770R0 "Stashing stashing iterators for proper flattening"
  stl/inc/ranges
  stl/inc/regex
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/usual_matrix.lst
  tests/std/include/range_algorithm_support.hpp
  tests/std/tests/P0896R4_views_elements/test.cpp
  tests/std/tests/P0896R4_views_join/test.cpp
  tests/std/tests/P0896R4_views_transform/test.cpp
  tests/std/tests/P2441R2_views_join_with/test.cpp
Labels: ranges, cxx23

#3508 P2321R2: `views::adjacent`, `views::pairwise`
  stl/inc/ranges
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2164R9_views_enumerate/test.cpp
  tests/std/tests/P2321R2_views_adjacent/env.lst
  tests/std/tests/P2321R2_views_adjacent/test.cpp
Labels: ranges, cxx23

#3517 LWG-3851: `chunk_view::inner-iterator` missing custom `iter_move` and `iter_swap`
  stl/inc/ranges
  tests/std/tests/P2442R1_views_chunk/env.lst
  tests/std/tests/P2442R1_views_chunk/test.cpp
  tests/std/tests/P2442R1_views_chunk_death/env.lst
Labels: LWG, ranges

#3539 Cleanups: Consistently comment `enable_if_t` definitions
  stl/inc/__msvc_chrono.hpp
  stl/inc/bit
  stl/inc/limits
  stl/inc/tuple
  stl/inc/utility
  stl/inc/xmemory
Labels: documentation

#3543 Cleanups: Follow Standard order for `byteswap` in `<bit>`
  stl/inc/bit
Labels: enhancement

#3523 Cleanups: Formatting and comments
  stl/inc/__msvc_format_ucd_tables.hpp
  stl/inc/atomic
  stl/inc/charconv
  stl/inc/chrono
  stl/inc/cmath
  stl/inc/execution
  stl/inc/expected
  stl/inc/experimental/coroutine
  stl/inc/filesystem
  stl/inc/format
  stl/inc/functional
  stl/inc/iterator
  stl/inc/memory
  stl/inc/random
  stl/inc/ranges
  stl/inc/xmemory
  stl/inc/xsmf_control.h
  stl/inc/xstring
  stl/inc/xutility
  stl/inc/yvals.h
  stl/inc/yvals_core.h
  stl/src/StlCompareStringA.cpp
  stl/src/atomic_wait.cpp
  stl/src/filesys.cpp
  stl/src/ios.cpp
  stl/src/locale.cpp
  stl/src/multprec.cpp
  stl/src/ppltasks.cpp
  stl/src/special_math.cpp
  stl/src/vector_algorithms.cpp
  stl/src/winapisupp.cpp
  stl/src/xcharconv_tables_float.cpp
  stl/src/xtime.cpp
  tests/std/tests/Dev11_0437519_container_requirements/test.compile.pass.cpp
  tools/unicode_properties_parse/grapheme_break_property_data_gen.py
Labels: documentation

#3524 Cleanups: Friendship is magic
  stl/inc/bitset
  stl/inc/exception
  stl/inc/filesystem
  stl/inc/ranges
  stl/inc/xlocale
Labels: enhancement, ranges

#3525 Cleanups: Drop top-level `const` on value params in declarations
  stl/inc/algorithm
  stl/inc/memory
  stl/inc/numeric
  stl/inc/xutility
Labels: enhancement

#3526 Cleanups: Split type and object definitions
  stl/inc/xstring
  stl/src/ppltasks.cpp
  stl/src/taskscheduler.cpp
  tests/std/tests/Dev11_0235721_async_and_packaged_task/test.cpp
  tests/std/tests/P0019R8_atomic_ref/test.cpp
  tests/std/tests/VSO_0000000_list_iterator_debugging/test.cpp
  tests/std/tests/VSO_0961751_hash_range_erase/test.cpp
Labels: enhancement

#3527 Cleanups: Test options
  tests/std/tests/GH_002030_asan_annotate_string/env.lst
  tests/std/tests/GH_002030_asan_annotate_vector/env.lst
  tests/tr1/env.lst
  tests/tr1/env_minus_md_idl.lst
  tests/tr1/env_minus_pure.lst
  tests/universal_prefix.lst
Labels: test, ASAN

#3528 Cleanups: Test code using `ranges` as an identifier, plus more
  tests/std/tests/Dev09_056375_locale_cleanup/test.cpp
  tests/std/tests/Dev09_192736_tr1_prngs_not_copyconstructible/test.cpp
  tests/std/tests/P2321R2_views_zip/test.cpp
Labels: test, ranges

#3529 Cleanups: `#undef` macro hygiene
  stl/inc/fstream
  stl/inc/vector
  stl/inc/xstring
Labels: enhancement, ASAN

#3530 Cleanups: Avoid almost always `auto`
  stl/inc/__msvc_int128.hpp
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
  tests/std/tests/P0896R4_views_transform/test.cpp
  tests/std/tests/P1522R1_difference_type/test.cpp
  tests/std/tests/P2321R2_views_zip/test.cpp
Labels: enhancement, ranges

#3531 Cleanups: Very minor logic changes
  stl/inc/numeric
  stl/src/fiopen.cpp
  stl/src/ppltasks.cpp
Labels: enhancement

#3532 Cleanups: Simplify `thread` and `condition_variable`, identify unused dllexports
  stl/inc/condition_variable
  stl/inc/mutex
  stl/inc/thread
  stl/inc/xthreads.h
  stl/inc/xtimec.h
  stl/src/thread0.cpp
  stl/src/xtime.cpp
Labels: enhancement

#3533 Various cleanups
  stl/inc/__msvc_int128.hpp
  stl/inc/bit
  stl/inc/charconv
  stl/inc/limits
  stl/inc/memory_resource
  stl/inc/ranges
  stl/inc/regex
  stl/inc/type_traits
  stl/inc/xatomic.h
  stl/inc/xbit_ops.h
  stl/inc/xcharconv_ryu.h
  stl/inc/xutility
  stl/src/ppltasks.cpp
  stl/src/xmath.hpp
  stl/src/xmtx.hpp
Labels: enhancement

#3522 Use `SRWLOCK_INIT` to statically initialize `stl_critical_section_win7::m_srw_lock`
  stl/src/primitives.hpp
Labels: performance

#3540 Remove unneeded check `if (this != _STD addressof(_Right))`
  stl/inc/memory
Labels: performance

#3542 Implement P2652R2 Disallowing User Specialization Of `allocator_traits`
  stl/inc/xmemory
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/std/tests/P0401R6_allocate_at_least/env.lst
  tests/std/tests/P0401R6_allocate_at_least/test.cpp
  tests/std/tests/VSO_0000000_fancy_pointers/test.compile.pass.cpp
Labels: cxx23

#3560 `<mdspan>`: Require concepts
  stl/inc/mdspan
  tests/std/tests/P0009R18_mdspan/env.lst
  tests/std/tests/P0009R18_mdspan/test.cpp
Labels: mdspan

#3563 `<mdspan>`: Add `_EXPORT_STD`, tiny cleanups
  stl/inc/mdspan
Labels: modules, mdspan

#3452 enable ubsan
  stl/inc/regex
  stl/inc/sstream
  tests/std/tests/char8_t_17_matrix.lst
  tests/std/tests/char8_t_impure_matrix.lst
  tests/std/tests/char8_t_matrix.lst
  tests/std/tests/concepts_20_matrix.lst
  tests/std/tests/concepts_latest_matrix.lst
  tests/std/tests/impure_matrix.lst
  tests/std/tests/locale0_implib_cpp_matrix.lst
  tests/std/tests/strict_concepts_20_matrix.lst
  tests/std/tests/strict_concepts_latest_matrix.lst
  tests/std/tests/usual_17_matrix.lst
  tests/std/tests/usual_20_matrix.lst
  tests/std/tests/usual_latest_matrix.lst
  tests/std/tests/usual_matrix.lst
  tests/tr1/env.lst
  tests/tr1/env_minus_md_idl.lst
  tests/tr1/env_minus_pure.lst
  tests/tr1/tests/chrono/test.cpp
  tests/tr1/tests/cstddef/test.cpp
  tests/tr1/tests/streambuf1/test.cpp
  tests/tr1/tests/streambuf2/test.cpp
  tests/tr1/tests/type_traits5/test.cpp
  tests/utils/stl/test/features.py
  tests/utils/stl/test/tests.py
Labels: bug, test

#3547 Use `_Rewrap_iterator` consistently
  stl/inc/algorithm
  stl/inc/xutility
Labels: enhancement, ranges

#3551 `<ranges>`: Fix `ranges::equal` for ranges with integer-class `range_difference_t`
  stl/inc/algorithm
  tests/std/tests/P0896R4_ranges_alg_equal/test.cpp
Labels: bug, ranges

#3553 `<ranges>`: Test `c(begin|end)` members of range factories
  tests/std/tests/P0896R4_istream_view/test.cpp
  tests/std/tests/P0896R4_views_empty/test.cpp
  tests/std/tests/P0896R4_views_iota/test.cpp
  tests/std/tests/P0896R4_views_single/test.cpp
  tests/std/tests/P2474R2_views_repeat/test.cpp
Labels: test, ranges

#3554 LWG-3880: Clarify `operator+=` complexity for `{chunk,stride}_view::iterator`
  stl/inc/ranges
Labels: LWG, ranges

#3564 `<mdspan>`: Use concepts everywhere and add `mdspan` deduction guides
  stl/inc/mdspan
  tests/std/tests/P0009R18_mdspan/test.cpp
Labels: mdspan

#3569 Merge `main` to `feature/mdspan2`
  stl/inc/algorithm
  stl/inc/ranges
  stl/inc/regex
  stl/inc/sstream
  stl/inc/xutility
  tests/std/tests/P0896R4_istream_view/test.cpp
  tests/std/tests/P0896R4_ranges_alg_equal/test.cpp
  tests/std/tests/P0896R4_views_empty/test.cpp
  tests/std/tests/P0896R4_views_iota/test.cpp
  tests/std/tests/P0896R4_views_single/test.cpp
  tests/std/tests/P2474R2_views_repeat/test.cpp
  tests/std/tests/char8_t_17_matrix.lst
  tests/std/tests/char8_t_impure_matrix.lst
  tests/std/tests/char8_t_matrix.lst
  tests/std/tests/concepts_20_matrix.lst
  tests/std/tests/concepts_latest_matrix.lst
  tests/std/tests/impure_matrix.lst
  tests/std/tests/locale0_implib_cpp_matrix.lst
  tests/std/tests/strict_concepts_20_matrix.lst
  tests/std/tests/strict_concepts_latest_matrix.lst
  tests/std/tests/usual_17_matrix.lst
  tests/std/tests/usual_20_matrix.lst
  tests/std/tests/usual_latest_matrix.lst
  tests/std/tests/usual_matrix.lst
  tests/tr1/env.lst
  tests/tr1/env_minus_md_idl.lst
  tests/tr1/env_minus_pure.lst
  tests/tr1/tests/chrono/test.cpp
  tests/tr1/tests/cstddef/test.cpp
  tests/tr1/tests/streambuf1/test.cpp
  tests/tr1/tests/streambuf2/test.cpp
  tests/tr1/tests/type_traits5/test.cpp
  tests/utils/stl/test/features.py
  tests/utils/stl/test/tests.py
Labels: uncharted, mdspan

#3556 Unicode 15
  stl/inc/__msvc_format_ucd_tables.hpp
  stl/inc/yvals_core.h
  tests/std/tests/P0645R10_text_formatting_grapheme_clusterization/test.cpp
  tools/unicode_properties_parse/grapheme_break_property_data_gen.py
  tools/unicode_properties_parse/grapheme_break_test_data_gen.py
Labels: format, cxx23

#3566 `_Weakly_unwrappable` should use `_Allow_inheriting_unwrap_v`
  stl/inc/xutility
Labels: bug

#3580 `<mdspan>`: Add separate tests for `extents` and `default_accessor`
  stl/inc/mdspan
  tests/std/test.lst
  tests/std/tests/P0009R18_mdspan_default_accessor/env.lst
  tests/std/tests/P0009R18_mdspan_default_accessor/test.cpp
  tests/std/tests/P0009R18_mdspan_extents/env.lst
  tests/std/tests/P0009R18_mdspan_extents/test.cpp
Labels: mdspan

#3578 Prefer fill_n over fill where applicable
  stl/inc/deque
  stl/inc/vector
Labels: enhancement

#3581 Don't warn when using operator<=> with 0
  stl/inc/compare
  tests/std/tests/P0768R1_spaceship_operator/test.cpp
Labels: bug

#3583 P1467R9 Extended Floating-Point Types
  stl/CMakeLists.txt
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/header-units.json
  stl/inc/stdfloat
  stl/inc/yvals_core.h
  stl/modules/std.ixx
  tests/std/include/test_header_units_and_modules.hpp
  tests/std/tests/Dev10_555491_complex_linker_errors/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/importable_cxx_library_headers.jsonc
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
  tests/std/tests/include_each_header_alone_matrix.lst
Labels: cxx23

#3585 Fix CodeQL warnings, part 2
  stl/inc/xbit_ops.h
  stl/inc/xtimec.h
  stl/src/cond.cpp
  stl/src/cthread.cpp
  stl/src/mutex.cpp
  stl/src/vector_algorithms.cpp
  stl/src/xtime.cpp
Labels: enhancement

#3557 Status Chart: Weekly updates, TypeScript 5.0, Merged PRs range
  index.html
  package-lock.json
  package.json
  src/status_chart.ts
  src/weekly_table.ts
  src_gather/gather_stats.ts
  src_gather/video_table.ts
Labels: documentation

#3588 Fix modules test by using `static constexpr` arrays
  tests/std/include/test_header_units_and_modules.hpp
Labels: test, modules

#3586 `<mdspan>`: Completely rework `std::extents`
  stl/inc/mdspan
  tests/std/test.lst
  tests/std/tests/P0009R18_mdspan/test.cpp
  tests/std/tests/P0009R18_mdspan_extents/test.cpp
  tests/std/tests/P0009R18_mdspan_extents_death/env.lst
  tests/std/tests/P0009R18_mdspan_extents_death/test.cpp
Labels: mdspan

#3593 `<mdspan>`: Various cleanups (mostly renames)
  stl/inc/mdspan
  stl/inc/yvals_core.h
  tests/std/tests/P0009R18_mdspan_extents/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: mdspan

#3475 Implement LWG-3870 Remove `voidify`
  stl/inc/iterator
  stl/inc/memory
  stl/inc/optional
  stl/inc/ranges
  stl/inc/variant
  stl/inc/xmemory
  stl/inc/xpolymorphic_allocator.h
  stl/inc/xsmf_control.h
  stl/inc/xutility
  tests/libcxx/expected_results.txt
  tests/std/tests/Dev11_0920385_list_sort_allocator/test.cpp
  tests/std/tests/GH_000431_copy_move_family/test.cpp
  tests/std/tests/GH_002992_unwrappable_iter_sent_pairs/test.compile.pass.cpp
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P0220R1_optional/test.cpp
  tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
  tests/std/tests/P0896R4_common_iterator/test.cpp
  tests/std/tests/P0896R4_views_single/test.cpp
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
  tests/std/tests/VSO_0180469_fill_family/test.cpp
Labels: LWG

#3577 `<functional>`: Constrain functions used by `std::bind`
  stl/inc/functional
  tests/std/test.lst
  tests/std/tests/GH_000952_bind_constraints/env.lst
  tests/std/tests/GH_000952_bind_constraints/test.compile.pass.cpp
Labels: bug

#3579 `<chrono>`: Optimize `to_sys` and `to_local`
  stl/inc/__msvc_tzdb.hpp
  stl/inc/chrono
  stl/src/tzdb.cpp
Labels: performance, chrono

#3584 Prefer `consteval` to `_CONSTEVAL`, enable `<source_location>` for Clang
  stl/inc/chrono
  stl/inc/compare
  stl/inc/ranges
  stl/inc/source_location
  stl/inc/utility
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/tests/P1208R6_source_location/header.h
  tests/std/tests/P1208R6_source_location/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: enhancement

#3587 Implement LWG-3836 `std::expected<bool, E1>` conversion constructor `expected(const expected<U, G>&)` should take precedence over `expected(U&&)` with `operator bool`
  stl/inc/expected
  stl/inc/optional
  tests/libcxx/expected_results.txt
  tests/std/tests/P0220R1_optional/test.cpp
  tests/std/tests/P0323R12_expected/test.cpp
Labels: LWG

#3589 Implement LWG-3887 Version macro for `allocate_at_least`
  stl/inc/yvals_core.h
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: LWG

#3591 Update working draft from N4928 to N4944
  README.md
Labels: documentation

#3594 Eliminate `xtime` and its member `sec`, `nsec`
  stl/inc/__msvc_chrono.hpp
  stl/inc/condition_variable
  stl/inc/mutex
  stl/inc/shared_mutex
  stl/inc/thread
  stl/inc/xthreads.h
  stl/inc/xtimec.h
  stl/src/cond.cpp
  stl/src/cthread.cpp
  stl/src/mutex.cpp
  stl/src/xtime.cpp
  tests/std/test.lst
  tests/std/tests/GH_002206_unreserved_names/env.lst
  tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp
  tests/std/tests/VSO_0226079_mutex/test.cpp
Labels: enhancement, chrono

#3597 Merge `main` to `feature/mdspan2`
  README.md
  stl/inc/__msvc_chrono.hpp
  stl/inc/__msvc_tzdb.hpp
  stl/inc/chrono
  stl/inc/compare
  stl/inc/condition_variable
  stl/inc/expected
  stl/inc/functional
  stl/inc/iterator
  stl/inc/memory
  stl/inc/mutex
  stl/inc/optional
  stl/inc/ranges
  stl/inc/shared_mutex
  stl/inc/source_location
  stl/inc/thread
  stl/inc/utility
  stl/inc/variant
  stl/inc/xmemory
  stl/inc/xpolymorphic_allocator.h
  stl/inc/xsmf_control.h
  stl/inc/xthreads.h
  stl/inc/xtimec.h
  stl/inc/xutility
  stl/inc/yvals_core.h
  stl/src/cond.cpp
  stl/src/cthread.cpp
  stl/src/mutex.cpp
  stl/src/tzdb.cpp
  stl/src/xtime.cpp
  tests/libcxx/expected_results.txt
  tests/std/test.lst
  tests/std/tests/Dev11_0920385_list_sort_allocator/test.cpp
  tests/std/tests/GH_000431_copy_move_family/test.cpp
  tests/std/tests/GH_000952_bind_constraints/env.lst
  tests/std/tests/GH_000952_bind_constraints/test.compile.pass.cpp
  tests/std/tests/GH_002206_unreserved_names/env.lst
  tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp
  tests/std/tests/GH_002992_unwrappable_iter_sent_pairs/test.compile.pass.cpp
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P0220R1_optional/test.cpp
  tests/std/tests/P0323R12_expected/test.cpp
  tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
  tests/std/tests/P0896R4_common_iterator/test.cpp
  tests/std/tests/P0896R4_views_single/test.cpp
  tests/std/tests/P1208R6_source_location/header.h
  tests/std/tests/P1208R6_source_location/test.cpp
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tests/std/tests/VSO_0180469_fill_family/test.cpp
  tests/std/tests/VSO_0226079_mutex/test.cpp
Labels: uncharted, mdspan

#2116 Some Cpp Core Guidelines warning fixes
  stl/inc/atomic
  stl/inc/charconv
  stl/inc/coroutine
  stl/inc/execution
  stl/inc/memory_resource
Labels: enhancement

#3561 P2374R4: `views::cartesian_product`
  stl/inc/ranges
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2374R4_views_cartesian_product/env.lst
  tests/std/tests/P2374R4_views_cartesian_product/test.cpp
  tests/std/tests/P2374R4_views_cartesian_product_death/env.lst
  tests/std/tests/P2374R4_views_cartesian_product_death/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23

#3603 `<mdspan>`: `layout_left` improvements
  stl/inc/mdspan
  tests/std/include/test_mdspan_support.hpp
  tests/std/test.lst
  tests/std/tests/P0009R18_mdspan_extents/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_left/env.lst
  tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_left_death/env.lst
  tests/std/tests/P0009R18_mdspan_layout_left_death/test.cpp
Labels: mdspan
