Repository microsoft/STL, pull requests merged in 2023-10, with the labels that each got.

#4064 Cleanups for `<flat_set>`
  stl/inc/flat_set
  tests/std/tests/P1222R4_flat_set/test.cpp
Labels: enhancement, flat_meow

#4053 P1169R4 `static` `operator()`
  stl/inc/functional
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/std/test.lst
  tests/std/tests/P1169R4_static_call_operator/env.lst
  tests/std/tests/P1169R4_static_call_operator/test.compile.pass.cpp
Labels: cxx23

#4055 `<source_location>`: Light up detailed `function_name()` for Clang 17, add escape hatch
  stl/inc/source_location
  tests/std/include/test_header_units_and_modules.hpp
  tests/std/tests/P1208R6_source_location/header.h
  tests/std/tests/P1208R6_source_location/test.cpp
Labels: enhancement

#4058 [ASan] Disable annotations on unsupported platforms
  stl/CMakeLists.txt
  stl/inc/__msvc_sanitizer_annotate_container.hpp
  stl/msbuild/stl_base/libcp.settings.targets
Labels: bug, ASAN

#4062 Update _MSVC_STL_UPDATE to October 2023
  stl/inc/yvals_core.h
Labels: enhancement

#4067 Add C4868 to _STL_DISABLED_WARNINGS
  stl/inc/execution
  stl/inc/yvals_core.h
Labels: enhancement

#4049 `<deque>`: Fix iterator arithmetic
  stl/inc/deque
  tests/std/tests/GH_002769_handle_deque_block_pointers/test.cpp
Labels: bug

#4057 `<functional>`: Fixes around `not_fn`
  stl/inc/functional
  tests/std/tests/Dev11_0535636_functional_overhaul/test.cpp
Labels: bug

#4066 Implement LWG-3561 Issue with internal counter in `discard_block_engine`
  stl/inc/random
  tests/std/test.lst
  tests/std/tests/LWG3561_discard_block_engine_counter/env.lst
  tests/std/tests/LWG3561_discard_block_engine_counter/test.cpp
  tests/tr1/tests/random4/test.cpp
Labels: LWG

#4068 Add `*` tags to all non-tagged configs
  tests/libcxx/usual_matrix.lst
  tests/std/tests/Dev08_527068_scl_no_exceptions/env.lst
  tests/std/tests/Dev10_909646_stringstream_vd2/env.lst
  tests/std/tests/GH_000639_nvcc_include_all/env.lst
  tests/std/tests/GH_002030_asan_annotate_string/env.lst
  tests/std/tests/GH_002030_asan_annotate_vector/env.lst
  tests/std/tests/GH_002094_cpp_core_guidelines/env.lst
  tests/std/tests/GH_002558_format_presetPadding/env.lst
  tests/std/tests/GH_002655_alternate_name_broke_linker/env.lst
  tests/std/tests/P0088R3_variant/env.lst
  tests/std/tests/P0645R10_text_formatting_legacy_text_encoding/env.lst
  tests/std/tests/P0912R5_coroutine/env.lst
  tests/std/tests/P1502R1_standard_library_header_units/env.lst
  tests/std/tests/P2286R8_text_formatting_escaping_legacy_text_encoding/env.lst
  tests/std/tests/P2465R3_standard_library_modules/env.lst
  tests/std/tests/VSO_0000000_c_math_functions/env.lst
  tests/std/tests/VSO_0157762_feature_test_macros/env.lst
  tests/std/tests/VSO_0938757_attribute_order/env.lst
  tests/std/tests/VSO_0971246_legacy_await_headers/env.lst
  tests/std/tests/callconv_matrix.lst
  tests/std/tests/char8_t_17_matrix.lst
  tests/std/tests/char8_t_impure_matrix.lst
  tests/std/tests/char8_t_matrix.lst
  tests/std/tests/clr_matrix.lst
  tests/std/tests/concepts_20_matrix.lst
  tests/std/tests/concepts_latest_matrix.lst
  tests/std/tests/eha_matrix.lst
  tests/std/tests/fast_matrix.lst
  tests/std/tests/fast_no_asan_matrix.lst
  tests/std/tests/floating_point_model_matrix.lst
  tests/std/tests/impure_matrix.lst
  tests/std/tests/include_each_header_alone_matrix.lst
  tests/std/tests/locale0_implib_cpp_matrix.lst
  tests/std/tests/rtti_matrix.lst
  tests/std/tests/strict_concepts_20_matrix.lst
  tests/std/tests/strict_concepts_latest_matrix.lst
  tests/std/tests/usual_17_matrix.lst
  tests/std/tests/usual_20_matrix.lst
  tests/std/tests/usual_latest_matrix.lst
  tests/std/tests/usual_matrix.lst
  tests/tr1/env.lst
  tests/tr1/env_minus_md_idl.lst
  tests/tr1/env_minus_pure.lst
  tests/tr1/env_single.lst
Labels: infrastructure

#3994 P2675R1 `<format>` generator converted from C++ to Python
  stl/inc/format
  tools/unicode_properties_parse/format_width_estimate_intervals.cpp
  tools/unicode_properties_parse/format_width_estimate_intervals.py
Labels: enhancement, format

#4069 build and test infra cleanup
  azure-devops/asan-pipeline.yml
  azure-devops/cmake-configure-build.yml
  azure-devops/config.yml
  azure-devops/cross-build.yml
  azure-devops/native-build-test.yml
  azure-devops/run-tests.yml
  azure-pipelines.yml
Labels: infrastructure, build

#4071 `<deque>`: Use unchecked iterators
  stl/inc/deque
  tests/std/tests/VSO_0000000_allocator_propagation/test.cpp
Labels: bug

#4075 Fix ASAN CI failure caused by stealth merge conflict
  tests/libcxx/expected_results.txt
Labels: test, ASAN

#4083 Toolset update: VS 2022 17.8 Preview 3
  README.md
  azure-devops/config.yml
  azure-devops/provision-image.ps1
  stl/inc/charconv
  stl/inc/xutility
  tests/CMakeLists.txt
  tests/std/tests/VSO_0000000_instantiate_containers/test.compile.pass.cpp
  tests/std/tests/VSO_0105317_expression_sfinae/test.cpp
  tests/tr1/tests/memory1/test.cpp
Labels: infrastructure

#4086 Clean up emitted files as the test harness runs
  tests/utils/stl/test/format.py
Labels: test

#4047 Lifetime cleanups for `basic_string`
  stl/inc/xstring
  tests/std/tests/VSO_0000000_allocator_propagation/test.cpp
Labels: bug

#4073 `<xstring>`: Use `memmove` in construction of `basic_string` when the source is a suitable contiguous range
  stl/inc/xstring
  tests/std/tests/P1206R7_string_from_range/test.cpp
Labels: performance

#4076 `<format>`: Guard one use of `_MSVC_EXECUTION_CHARACTER_SET`
  stl/inc/format
Labels: enhancement, format

#4085 README.md: Update Azure Pipelines status badges
  README.md
Labels: documentation

#4079 `<flat_set>`: the copy/move functions should be user-defined
  stl/inc/flat_set
  tests/std/tests/P1222R4_flat_set/test.cpp
Labels: flat_meow

#3914 Make `this_thread::sleep_until` clock-aware
  stl/inc/thread
  stl/inc/xthreads.h
  stl/src/cthread.cpp
  stl/src/sharedmutex.cpp
Labels: bug

#3925 Vectorize `ranges::find_last`
  stl/inc/algorithm
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance, ranges

#4096 Update Draft to N4964
  README.md
Labels: documentation

#4098 Turn niebloids into function objects
  stl/inc/algorithm
  stl/inc/memory
  stl/inc/numeric
  stl/inc/ranges
  stl/inc/xutility
Labels: enhancement, ranges

#4103 Fix and simplify the feature-test macro test
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: test

#4112 Merge `main` to `feature/flat_set`, fix `__cpp_lib_flat_set` test
  README.md
  stl/inc/algorithm
  stl/inc/memory
  stl/inc/numeric
  stl/inc/ranges
  stl/inc/thread
  stl/inc/xthreads.h
  stl/inc/xutility
  stl/src/cthread.cpp
  stl/src/sharedmutex.cpp
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: test, flat_meow

#4114 Status Chart: Add `tools/count_libcxx.py`, weekly updates
  README.md
  package-lock.json
  package.json
  src/weekly_table.ts
  tools/count_libcxx.py
Labels: documentation

#4084 `<flat_set>`: Test transparent insertion and more
  stl/inc/flat_set
  tests/std/tests/P1222R4_flat_set/test.cpp
Labels: flat_meow

#4087 Cleanup `_Execute_once()`
  stl/inc/xcall_once.h
  stl/src/dllmain.cpp
  stl/src/excptptr.cpp
  stl/src/ppltasks.cpp
  stl/src/xonce.cpp
Labels: enhancement

#4106 make `extern "C"` functions explicitly `noexcept`
  stl/inc/__msvc_sanitizer_annotate_container.hpp
  stl/inc/experimental/coroutine
  stl/inc/experimental/filesystem
  stl/inc/memory
  stl/inc/xlocinfo
  stl/inc/xlocnum
  stl/inc/xthreads.h
  stl/inc/xtimec.h
  stl/src/StlCompareStringA.cpp
  stl/src/StlCompareStringW.cpp
  stl/src/StlLCMapStringA.cpp
  stl/src/StlLCMapStringW.cpp
  stl/src/_tolower.cpp
  stl/src/_toupper.cpp
  stl/src/atomic.cpp
  stl/src/awint.hpp
  stl/src/cond.cpp
  stl/src/cthread.cpp
  stl/src/dllmain_satellite.cpp
  stl/src/filesys.cpp
  stl/src/filesystem.cpp
  stl/src/locale0.cpp
  stl/src/mutex.cpp
  stl/src/sharedmutex.cpp
  stl/src/vector_algorithms.cpp
  stl/src/winapinls.cpp
  stl/src/winapisupp.cpp
  stl/src/xdateord.cpp
  stl/src/xexp.cpp
  stl/src/xfexp.cpp
  stl/src/xgetwctype.cpp
  stl/src/xlcosh.cpp
  stl/src/xlexp.cpp
  stl/src/xlock.cpp
  stl/src/xmath.hpp
  stl/src/xmbtowc.cpp
  stl/src/xnotify.cpp
  stl/src/xstod.cpp
  stl/src/xstof.cpp
  stl/src/xstol.cpp
  stl/src/xstold.cpp
  stl/src/xstoll.cpp
  stl/src/xstoul.cpp
  stl/src/xstoull.cpp
  stl/src/xstrcoll.cpp
  stl/src/xstrxfrm.cpp
  stl/src/xtime.cpp
  stl/src/xtowlower.cpp
  stl/src/xtowupper.cpp
  stl/src/xwcscoll.cpp
  stl/src/xwcsxfrm.cpp
  stl/src/xwctomb.cpp
  stl/src/xwstod.cpp
  stl/src/xwstof.cpp
  stl/src/xwstold.cpp
  stl/src/xwstopfx.cpp
  stl/src/xxxdtent.hpp
  stl/src/xxxprec.hpp
Labels: enhancement

#4111 Add a Standard mode check to `<__msvc_print.hpp>`
  stl/inc/__msvc_print.hpp
  stl/inc/ostream
  stl/inc/xcharconv.h
  stl/inc/xcharconv_ryu.h
  stl/inc/xcharconv_ryu_tables.h
  stl/inc/xnode_handle.h
  tests/std/tests/GH_001411_core_headers/test.cpp
Labels: enhancement

#4113 inline internal function that are called only once in `vector_algorithms.cpp`
  stl/src/vector_algorithms.cpp
Labels: enhancement

#4117 Various cleanups: Comments and strings
  stl/inc/memory
  stl/inc/system_error
  stl/inc/xstring
  stl/inc/xutility
  stl/src/ppltasks.cpp
  stl/src/stdthrow.cpp
  stl/src/xgetwctype.cpp
  stl/src/xlock.cpp
Labels: documentation

#4118 Remove test workarounds for an ASAN bug
  tests/std/tests/GH_002030_asan_annotate_string/test.cpp
Labels: test, ASAN

#4120 `<random>`: Fix minor conformance issues
  stl/inc/random
  tests/tr1/tests/random1/test.cpp
Labels: bug

#4121 Various cleanups: Simplify product code
  stl/inc/exception
  stl/inc/ios
  stl/inc/random
  stl/inc/xstring
  stl/inc/xutility
Labels: enhancement

#4122 Various cleanups: Test code
  tests/std/include/range_algorithm_support.hpp
  tests/std/include/test_mdspan_support.hpp
  tests/std/tests/Dev09_174589_tr1_function_storing_pmf_called_with_reference_or_pointer/test.cpp
  tests/std/tests/Dev10_646244_bad_alloc_message/test.cpp
  tests/std/tests/Dev10_722102_shared_ptr_nullptr/test.cpp
  tests/std/tests/Dev10_860421_deque_push_back_pop_front/test.cpp
  tests/std/tests/Dev11_0485243_condition_variable_crash/test.cpp
  tests/std/tests/Dev11_0836436_get_time/test.cpp
  tests/std/tests/Dev11_0920385_list_sort_allocator/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_find_first_of/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_is_heap/test.cpp
  tests/std/tests/P0083R3_splicing_maps_and_sets/test.cpp
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P0218R1_filesystem/test.cpp
  tests/std/tests/P0220R1_polymorphic_memory_resources/test.cpp
  tests/std/tests/P0288R9_move_only_function/test.cpp
  tests/std/tests/P0323R12_expected/test.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_zoned_time/test.cpp
  tests/std/tests/P0811R3_midpoint_lerp/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_end/test.cpp
  tests/std/tests/P0896R4_ranges_alg_minmax/test.cpp
  tests/std/tests/P0896R4_ranges_algorithm_machinery/test.compile.pass.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/std/tests/P2136R3_invoke_r/test.cpp
  tests/std/tests/P2441R2_views_join_with/test.cpp
  tests/std/tests/VSO_0000000_type_traits/test.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
  tests/std/tests/VSO_0095837_current_exception_dtor/test.cpp
  tests/utils/stl/test/format.py
Labels: test

#4123 Various cleanups: Store properly-typed function pointers in `winapisupp.cpp`
  stl/src/tzdb.cpp
  stl/src/winapisupp.cpp
Labels: enhancement

#4124 Various cleanups: Use unnamed namespaces
  stl/src/stdhndlr.cpp
  stl/src/xtime.cpp
Labels: enhancement

#4125 Various cleanups: Simplify `ios_base` and `locale` constants
  stl/inc/xiosbase
  stl/inc/xlocale
Labels: enhancement

#4116 Implement `formattable`, `range_format`, and `format_kind`
  stl/inc/chrono
  stl/inc/format
  stl/inc/thread
  tests/libcxx/expected_results.txt
  tests/std/test.lst
  tests/std/tests/P2286R8_text_formatting_formattable/env.lst
  tests/std/tests/P2286R8_text_formatting_formattable/test.compile.pass.cpp
Labels: ranges, format, cxx23

#4119 Various cleanups: `<chrono>`
  stl/inc/__msvc_tzdb.hpp
  stl/inc/chrono
  stl/inc/yvals.h
  tests/std/tests/P0355R7_calendars_and_time_zones_clocks/test.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_time_zones/test.cpp
Labels: enhancement, chrono
