Repository microsoft/STL, pull requests merged in 2023-07, with the labels that each got.

#3833 `<flat_set>`: Fix `erase_if` for `flat_set`/`flat_multiset`
  stl/inc/flat_set
  tests/std/tests/P1222R4_flat_set/test.cpp
Labels: bug, flat_meow

#3821 `<mdspan>`: Improve debug checks
  stl/inc/mdspan
  tests/std/include/test_mdspan_support.hpp
  tests/std/test.lst
  tests/std/tests/P0009R18_mdspan_extents_death/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_left_death/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_right_death/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_stride_death/test.cpp
  tests/std/tests/P0009R18_mdspan_mdspan_death/env.lst
  tests/std/tests/P0009R18_mdspan_mdspan_death/test.cpp
Labels: mdspan

#3829 `<mdspan>`: Finish `layout_stride`'s tests
  tests/std/include/test_mdspan_support.hpp
  tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
Labels: test, mdspan

#3825 `<mdspan>`: Make `extents` truly empty when `rank_dynamic() == 0`
  stl/inc/mdspan
  tests/std/tests/P0009R18_mdspan_extents/test.cpp
Labels: performance, mdspan

#3847 `<mdspan>`: More EBO
  stl/inc/mdspan
  tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp
  tests/std/tests/P0009R18_mdspan_default_accessor/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
  tests/std/tests/P0009R18_mdspan_mdspan/test.cpp
Labels: performance, mdspan

#3846 Status Chart: Add C++26 line
  .github/workflows/compile-typescript.yml
  .vscode/settings.json
  README.md
  built/status_chart.mjs
  index.html
  package-lock.json
  package.json
  src/daily_table.ts
  src/status_chart.ts
  src/weekly_table.ts
  src_gather/gather_stats.ts
Labels: documentation

#3852 `<mdspan>`: Final cleanups
  stl/inc/mdspan
  tests/std/include/test_mdspan_support.hpp
  tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp
  tests/std/tests/P0009R18_mdspan_extents_death/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_stride_death/test.cpp
  tests/std/tests/P0009R18_mdspan_mdspan/test.cpp
  tests/std/tests/P0009R18_mdspan_mdspan_death/test.cpp
Labels: mdspan

#3856 Status Chart: Fix error TS2590
  .github/workflows/compile-typescript.yml
  README.md
  package-lock.json
  package.json
  src_gather/gather_stats.ts
Labels: documentation

#3866 Toolset update: VS 2022 17.7 Preview 3, Clang 16.0.5
  .github/workflows/update-status-chart.yml
  README.md
  azure-devops/create-1es-hosted-pool.ps1
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  stl/inc/__msvc_int128.hpp
  stl/inc/complex
  stl/inc/memory
  stl/inc/stop_token
  stl/inc/tuple
  stl/inc/type_traits
  stl/inc/variant
  stl/inc/xtree
  stl/inc/yvals_core.h
  stl/src/StlCompareStringA.cpp
  stl/src/StlLCMapStringA.cpp
  tests/libcxx/expected_results.txt
  tests/std/tests/GH_000431_copy_move_family/test.cpp
  tests/std/tests/GH_000431_equal_family/test.cpp
  tests/std/tests/GH_000431_equal_memcmp_is_safe/test.compile.pass.cpp
  tests/std/tests/GH_000431_iter_copy_move_cat/test.compile.pass.cpp
  tests/std/tests/P0040R3_parallel_memory_algorithms/test.cpp
  tests/std/tests/P0067R5_charconv/test.cpp
  tests/std/tests/P0220R1_any/test.cpp
  tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp
  tests/std/tests/P0645R10_text_formatting_legacy_text_encoding/env.lst
  tests/std/tests/P1208R6_source_location/header.h
  tests/std/tests/P1208R6_source_location/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tests/std/tests/prefix.lst
  tests/tr1/prefix.lst
Labels: infrastructure

#3818 `<iterator>`: Modernize and deprecate `(un)checked_array_iterator`
  stl/inc/iterator
  stl/inc/yvals_core.h
  tests/std/tests/Dev10_500860_overloaded_address_of/test.cpp
  tests/std/tests/Dev10_709166_checked_and_unchecked_array_iterator/test.cpp
  tests/std/tests/Dev10_709168_marking_iterators_as_checked/test.compile.pass.cpp
  tests/std/tests/Dev11_0000000_null_forward_iterators/test.cpp
  tests/std/tests/P0040R3_extending_memory_management_tools/test.cpp
  tests/std/tests/P1614R2_spaceship/test.cpp
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
  tests/std/tests/VSO_0299624_checked_array_iterator_idl/test.cpp
Labels: enhancement

#3827 Test coverage for LWG-2682 `filesystem::copy()` won't create a symlink to a directory
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: test, filesystem

#3831 Add `[[msvc::lifetimebound]]` to `minmax`
  stl/inc/algorithm
  stl/inc/yvals_core.h
  tests/std/lit.site.cfg.in
  tests/std/rulesets/stl.ruleset
  tests/std/test.lst
  tests/std/tests/GH_002094_cpp_core_guidelines/env.lst
  tests/std/tests/GH_002094_cpp_core_guidelines/test.compile.pass.cpp
  tests/utils/stl/test/format.py
  tests/utils/stl/test/tests.py
Labels: enhancement

#3837 C++26 freestanding feature-test macros
  stl/inc/yvals_core.h
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx26

#3839 `<ranges>`: Improve implementation of recommended practices in `views::cartesian_product`
  stl/inc/ranges
  tests/std/test.lst
  tests/std/tests/P2374R4_views_cartesian_product/test.cpp
  tests/std/tests/P2374R4_views_cartesian_product_recommended_practices/env.lst
  tests/std/tests/P2374R4_views_cartesian_product_recommended_practices/test.compile.pass.cpp
Labels: enhancement, ranges

#3844 `<functional>`: Make `function::target` return null function pointers without cast
  stl/inc/functional
  tests/std/tests/Dev11_0535636_functional_overhaul/test.cpp
Labels: bug

#3850 enhancements for `<filesystem>`
  benchmarks/CMakeLists.txt
  benchmarks/src/path_lexically_normal.cpp
  stl/inc/filesystem
Labels: performance, filesystem

#3851 Update _MSVC_STL_UPDATE
  stl/inc/yvals_core.h
Labels: enhancement

#3863 Initialize array<T, 0>'s single element
  stl/inc/array
  tests/libcxx/expected_results.txt
  tests/std/tests/Dev11_1074023_constexpr/test.cpp
Labels: bug

#3864 Reallocate at least
  stl/inc/deque
  stl/inc/sstream
  stl/inc/syncstream
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/xstring
  tests/std/test.lst
  tests/std/tests/GH_003570_allocate_at_least/env.lst
  tests/std/tests/GH_003570_allocate_at_least/test.cpp
Labels: performance

#3775 `<functional>`: Deleted `operator()` overloads for return types of `bind`, `bind_front`, and `bind_back`
  stl/inc/functional
  tests/libcxx/expected_results.txt
  tests/std/tests/GH_000952_bind_constraints/test.compile.pass.cpp
Labels: bug

#3823 Test coverage and precondition checking for LWG-2295 Locale name when the provided `Facet` is a `nullptr`
  stl/inc/xlocale
  tests/std/tests/Dev09_056375_locale_cleanup/test.cpp
Labels: LWG

#3826 Optimizations for `<format>`
  stl/inc/format
Labels: performance, format

#3838 Enhancements for `<bitset>`
  benchmarks/CMakeLists.txt
  benchmarks/src/bitset_to_string.cpp
  stl/inc/bitset
Labels: performance

#3855 Strengthen exception specification for some facet base types
  stl/inc/xlocale
  stl/inc/xlocmes
  stl/inc/xlocmon
  stl/inc/xloctime
  tests/std/tests/Dev09_056375_locale_cleanup/test.cpp
Labels: enhancement

#3865 Add `[[noreturn]]` for some functions
  stl/src/cthread.cpp
  stl/src/mutex.cpp
  stl/src/ppltasks.cpp
Labels: enhancement

#3868 fix writing NaN to the output stream with a set locale
  stl/inc/xlocnum
  tests/std/test.lst
  tests/std/tests/GH_003867_output_nan/env.lst
  tests/std/tests/GH_003867_output_nan/test.cpp
Labels: bug

#3869 `<filesystem>`: fix dangerous `noexcept` specification of `_Current_path`
  stl/inc/filesystem
Labels: bug, filesystem

#3664 add [[msvc::intrinsic]] for some cast funcs.
  stl/inc/cstddef
  stl/inc/utility
  stl/inc/xutility
Labels: performance

#3873 fixing std::shared_ptr<void> initialization from void*
  stl/inc/memory
Labels: bug

#3877 Fix iostreams with imbued locales to print INFs correctly
  stl/inc/xlocnum
  tests/libcxx/expected_results.txt
  tests/std/tests/Dev11_0496153_locale_ctor/test.cpp
  tests/std/tests/GH_003867_output_nan/test.cpp
Labels: bug

#3881 Follow-up enhancements for `<filesystem>`
  benchmarks/src/path_lexically_normal.cpp
  stl/inc/filesystem
Labels: bug, filesystem

#3882 `<functional>`: add `noreturn` for !_HAS_STATIC_RTTI
  stl/inc/functional
Labels: enhancement

#3884 Fix `string::replace` under ASan
  stl/inc/xstring
  tests/std/tests/GH_002030_asan_annotate_string/test.cpp
Labels: bug, ASAN

#3891 Detect allocate_at_least with a concept
  stl/inc/xmemory
  tests/std/tests/GH_003570_allocate_at_least/test.cpp
Labels: bug, high priority

#3824 `constexpr` `mutex` constructor
  stl/inc/mutex
  stl/inc/xthreads.h
  stl/src/cond.cpp
  stl/src/mutex.cpp
  stl/src/primitives.hpp
  tests/std/tests/VSO_0226079_mutex/env.lst
  tests/std/tests/VSO_0226079_mutex/test.cpp
Labels: bug, affects redist

#3880 Strengthen exception specification for `complex`
  stl/inc/complex
  stl/inc/xutility
  stl/inc/ymath.h
  stl/src/xcosh.cpp
  stl/src/xdint.cpp
  stl/src/xdnorm.cpp
  stl/src/xdscale.cpp
  stl/src/xdtest.cpp
  stl/src/xdunscal.cpp
  stl/src/xexp.cpp
  stl/src/xfcosh.cpp
  stl/src/xfdint.cpp
  stl/src/xfdnorm.cpp
  stl/src/xfdscale.cpp
  stl/src/xfdtest.cpp
  stl/src/xfdunsca.cpp
  stl/src/xferaise.cpp
  stl/src/xfexp.cpp
  stl/src/xfsinh.cpp
  stl/src/xlcosh.cpp
  stl/src/xldint.cpp
  stl/src/xldscale.cpp
  stl/src/xldtest.cpp
  stl/src/xldunsca.cpp
  stl/src/xlexp.cpp
  stl/src/xlpoly.cpp
  stl/src/xlsinh.cpp
  stl/src/xmath.hpp
  stl/src/xpoly.cpp
  stl/src/xsinh.cpp
  stl/src/xstoflt.cpp
  stl/src/xstopfx.cpp
  stl/src/xstoxflt.cpp
  stl/src/xwstoflt.cpp
  stl/src/xwstoxfl.cpp
  stl/src/xxxprec.hpp
  tests/std/tests/Dev10_555491_complex_linker_errors/test.cpp
Labels: enhancement

#3887 Strengthen exception specification for numeric operations
  stl/inc/cmath
  stl/inc/random
  stl/inc/valarray
  stl/src/xlgamma.cpp
  tests/libcxx/expected_results.txt
  tests/std/tests/GH_000940_missing_valarray_copy/test.cpp
Labels: enhancement

#3892 Remove unnecessary `typename`s for `<format>`
  stl/inc/filesystem
  stl/inc/format
  stl/inc/xfilesystem_abi.h
Labels: enhancement, format, filesystem

#3893 Remove unnecessary `typename`s for all standard headers introduced in C++20
  stl/inc/compare
  stl/inc/numbers
  stl/inc/ranges
  stl/inc/stacktrace
  stl/inc/syncstream
Labels: enhancement

#3894 Remove unnecessary `typename`s in all remaining headers
  stl/inc/atomic
  stl/inc/chrono
  stl/inc/deque
  stl/inc/forward_list
  stl/inc/functional
  stl/inc/list
  stl/inc/map
  stl/inc/memory
  stl/inc/regex
  stl/inc/set
  stl/inc/spanstream
  stl/inc/tuple
  stl/inc/type_traits
  stl/inc/unordered_map
  stl/inc/unordered_set
  stl/inc/vector
  stl/inc/xhash
  stl/inc/xmemory
  stl/inc/xstring
  stl/inc/xutility
Labels: enhancement

#3897 `<xthreads.h>`: Use `enum class _Thrd_result` for type safety
  stl/inc/condition_variable
  stl/inc/mutex
  stl/inc/thread
  stl/inc/xthreads.h
  stl/src/cond.cpp
  stl/src/cthread.cpp
  stl/src/mutex.cpp
  stl/src/thread0.cpp
Labels: enhancement

#3898 Fix `is_assignable` test coverage
  tests/std/tests/P0608R3_improved_variant_converting_constructor/test.cpp
  tests/std/tests/P0718R2_atomic_smart_ptrs/test.cpp
  tests/std/tests/P2321R2_proxy_reference/test.cpp
Labels: test

#3905 Cleanups for `don't-call` functions
  stl/inc/functional
  stl/inc/future
  stl/inc/xutility
Labels: enhancement

#3901 `<mdspan>`: Drop `#pragma once`
  stl/inc/mdspan
Labels: bug, modules, mdspan

#3902 `<flat_set>`: Drop `#pragma once`
  stl/inc/flat_set
Labels: bug, modules, flat_meow
