Repository microsoft/STL, pull requests merged in 2023-01, with the labels that each got.

#3338 Status Chart: Weekly updates, dependency updates
  built/status_chart.mjs
  index.html
  package-lock.json
  package.json
  src/daily_table.ts
  src/status_chart.ts
  src/weekly_table.ts
  src_gather/video_table.ts
Labels: documentation

#3340 Pool update: Jan 2023 Patch Tuesday
  azure-pipelines.yml
Labels: infrastructure

#3291 Fix for `std::numeric_limits<std::_Signed128>::is_signed`
  stl/inc/__msvc_int128.hpp
  tests/std/tests/P1522R1_difference_type/test.cpp
Labels: bug

#3292 Use symbolic constants in implementation of stacktrace
  stl/src/stacktrace.cpp
Labels: bug

#3293 Casey's miscellaneous branch
  README.md
  stl/inc/type_traits
  stl/inc/vector
  stl/inc/xutility
  tests/std/include/range_algorithm_support.hpp
Labels: enhancement

#3295 Fix `C4365: '=': signed/unsigned mismatch` with `/J`
  stl/inc/xcharconv_ryu.h
  tests/std/tests/GH_002711_Zc_alignedNew-/env.lst
  tests/std/tests/GH_002711_Zc_alignedNew-/test.compile.pass.cpp
Labels: bug

#3299 remove unused internal identifiers
  stl/inc/deque
  stl/inc/format
  stl/inc/regex
  stl/inc/variant
  stl/inc/xmemory
  stl/inc/xutility
  stl/src/parallel_algorithms.cpp
Labels: enhancement, throughput

#3300 add transition comment to `ios_base::hexfloat`
  stl/inc/xiosbase
Labels: documentation

#3308 Update working draft from N4917 to N4928
  README.md
Labels: documentation

#3315 Make some special member functions of `promise` and `packaged_task` defaulted
  stl/inc/future
  tests/std/tests/Dev11_0235721_async_and_packaged_task/test.cpp
Labels: enhancement

#3316 Fix handling of array rvalues for `ranges::cbegin` and its friends
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
Labels: bug, ranges

#3318 Implement LWG-3736 `move_iterator` missing `disable_sized_sentinel_for` specialization
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
Labels: LWG, ranges

#3319 Implement LWG-3785 `ranges::to` is over-constrained on the destination type being a range
  stl/inc/ranges
  tests/std/tests/P1206R7_ranges_to_misc/test.cpp
Labels: LWG, ranges

#3320 Implement LWG-3737 `take_view::sentinel` should provide `operator-`
  stl/inc/ranges
  tests/std/tests/P0896R4_views_take/test.cpp
Labels: LWG, ranges

#3321 `<mutex>`: Scope guards for lock algorithms and exception specification strengthening
  stl/inc/mutex
Labels: enhancement

#3326 `<expected>`: Workaround LLVM-59854
  stl/inc/expected
  tests/std/tests/P0323R12_expected/test.cpp
Labels: bug

#3328 `<ranges>`: Workaround LLVM-47414
  stl/inc/ranges
Labels: bug, ranges

#3331 workaround DevCom-10247495
  stl/inc/xfilesystem_abi.h
Labels: bug, modules

#3332 Implement LWG-3778 `vector<bool>` missing exception specifications
  stl/inc/vector
  tests/std/tests/Dev11_0437519_container_requirements/test.compile.pass.cpp
  tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp
Labels: LWG

#3334 `<xstring>`: constexpr string element lifetime
  stl/inc/xstring
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: bug

#3351 Toolset update: VS 2022 17.5 Preview 3
  CMakeLists.txt
  README.md
  azure-pipelines.yml
  stl/inc/memory
  stl/src/special_math.cpp
  tests/std/tests/GH_002030_asan_annotate_string/env.lst
  tests/std/tests/P0980R1_constexpr_strings/test.cpp
  tests/std/tests/P1004R2_constexpr_vector/test.cpp
  tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp
  tests/std/tests/P2321R2_proxy_reference/test.cpp
  tests/std/tests/VSO_0000000_allocator_propagation/test.cpp
Labels: infrastructure

#3145 Implement P0040R3 parallel specialized memory algorithms
  stl/inc/execution
  stl/inc/memory
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P0040R3_parallel_memory_algorithms/env.lst
  tests/std/tests/P0040R3_parallel_memory_algorithms/test.cpp
Labels: bug

#3314 Strengthen exception specifications for stream types
  stl/inc/fstream
  stl/inc/ios
  stl/inc/istream
  stl/inc/ostream
  stl/inc/spanstream
  stl/inc/sstream
  stl/inc/streambuf
  stl/inc/strstream
  stl/inc/syncstream
  stl/inc/xiosbase
  tests/std/tests/GH_001858_iostream_exception/test.cpp
Labels: enhancement

#3323 P2165R4: Compatibility Between `tuple`, `pair`, And tuple-like Objects (changes to `pair` only)
  stl/inc/__msvc_iter_core.hpp
  stl/inc/ranges
  stl/inc/span
  stl/inc/tuple
  stl/inc/utility
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2165R4_tuple_like_pair/env.lst
  tests/std/tests/P2165R4_tuple_like_pair/test.cpp
Labels: cxx23

#3342 Fix the behavior of `vector<bool, HugeAlloc>` whose size overflows `uint32_t`
  stl/inc/vector
  tests/std/tests/GH_000625_vector_bool_optimization/test.cpp
Labels: bug

#3348 Speculatively implement LWG-3857
  stl/inc/format
  stl/inc/xstring
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0220R1_string_view/test.cpp
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Labels: LWG, format

#3350 Improve `views::elements` tests
  tests/std/tests/P0896R4_views_elements/test.cpp
Labels: test, ranges

#3357 Fix XPASSing `visit_format_arg.pass.cpp`
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: test

#3358 Standard Library Modules: Add `modules/modules.json`
  stl/CMakeLists.txt
  stl/modules/modules.json
Labels: enhancement, modules

#3345 P2404R3: Move-Only Types For Comparison Concepts
  stl/inc/compare
  stl/inc/concepts
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/P2404R3_move_only_types_for_comparison_concepts/env.lst
  tests/std/tests/P2404R3_move_only_types_for_comparison_concepts/test.compile.pass.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#3359 Implement LWG-3798 Rvalue reference and `iterator_category`
  stl/inc/__msvc_iter_core.hpp
  stl/inc/ranges
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
  tests/std/tests/P0896R4_views_transform/test.cpp
  tests/std/tests/P2441R2_views_join_with/test.cpp
Labels: LWG

#3362 Update _MSVC_STL_UPDATE to January 2023 #3317
  stl/inc/yvals_core.h
Labels: enhancement

#3142 Implement P2474R2 `views::repeat`
  stl/debugger/STL.natvis
  stl/inc/ranges
  stl/inc/utility
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2474R2_views_repeat/env.lst
  tests/std/tests/P2474R2_views_repeat/test.cpp
  tests/std/tests/P2474R2_views_repeat_death/env.lst
  tests/std/tests/P2474R2_views_repeat_death/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23

#3322 P2321R2: Added `std::views::zip_transform`.
  stl/inc/ranges
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2321R2_views_zip/test.cpp
  tests/std/tests/P2321R2_views_zip_transform/env.lst
  tests/std/tests/P2321R2_views_zip_transform/test.cpp
Labels: ranges, cxx23
