Repository microsoft/STL, pull requests merged in 2023-04, with the labels that each got.

#3615 `<mdspan>`: `layout_right` improvements
  stl/inc/mdspan
  tests/std/test.lst
  tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_right/env.lst
  tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_right_death/env.lst
  tests/std/tests/P0009R18_mdspan_layout_right_death/test.cpp
Labels: mdspan

#3616 `<mdspan>`: Improve accessor testing
  stl/inc/mdspan
  tests/std/include/test_mdspan_support.hpp
  tests/std/tests/P0009R18_mdspan_default_accessor/test.cpp
Labels: mdspan

#3607 Revert the ppltasks change that introduced an `ole32.dll` dependency
  stl/CMakeLists.txt
  stl/msbuild/stl_base/msvcp.settings.targets
  stl/src/ppltasks.cpp
Labels: bug, high priority, affects redist

#3632 `<mdspan>`: Cleanup `extents`'s deduction guide
  stl/inc/mdspan
  tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
Labels: mdspan

#2141 Document import library
  docs/import_library.md
  stl/inc/xcharconv_tables.h
  stl/inc/xfacet
  stl/inc/yvals.h
  stl/src/charconv.cpp
  stl/src/filesystem.cpp
  stl/src/format.cpp
  stl/src/locale0.cpp
  stl/src/print.cpp
  stl/src/sharedmutex.cpp
  stl/src/stacktrace.cpp
  stl/src/syserror_import_lib.cpp
  stl/src/vector_algorithms.cpp
  stl/src/xcharconv_ryu_tables.cpp
  stl/src/xcharconv_tables_double.cpp
  stl/src/xcharconv_tables_float.cpp
  stl/src/xonce2.cpp
  tests/std/tests/GH_001411_core_headers/test.cpp
Labels: documentation

#3621 Build the import lib with `_ENFORCE_ONLY_CORE_HEADERS`
  stl/CMakeLists.txt
  stl/src/locale0.cpp
  stl/src/nothrow.cpp
Labels: build

#3600 `type_index::operator<=>` should not call the comparison function twice
  stl/inc/typeindex
Labels: performance

#3609 `<ranges>`: Explicitly specify the template parameters for `tuple`
  stl/inc/ranges
Labels: bug, ranges

#3610 Testing: Check new C++23 CPOs
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
Labels: test, ranges

#3612 Testing: Check `c(begin|end)` members of C++20 ranges
  tests/std/tests/P0896R4_ranges_ref_view/test.cpp
  tests/std/tests/P0896R4_ranges_subrange/test.compile.pass.cpp
  tests/std/tests/P0896R4_views_common/test.cpp
  tests/std/tests/P0896R4_views_filter/test.cpp
  tests/std/tests/P0896R4_views_join/test.cpp
  tests/std/tests/P0896R4_views_reverse/test.cpp
  tests/std/tests/P0896R4_views_transform/test.cpp
Labels: test, ranges

#3619 Fix silent bad codegen for vectorized `meow_element()` above 4 GB
  stl/src/vector_algorithms.cpp
  tests/std/include/test_min_max_element_support.hpp
  tests/std/test.lst
  tests/std/tests/GH_003617_vectorized_meow_element/env.lst
  tests/std/tests/GH_003617_vectorized_meow_element/test.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: bug

#3624 Don't include `<xmemory>` in `<optional>` and `<variant>`
  stl/inc/optional
  stl/inc/variant
Labels: throughput

#3625 Move `_Char_traits_eq` and `_Char_traits_lt` from `<xstring>` to `<regex>`
  stl/inc/regex
  stl/inc/xstring
  tests/std/tests/GH_000431_equal_memcmp_is_safe/test.compile.pass.cpp
  tests/std/tests/GH_000431_lex_compare_memcmp_classify/test.compile.pass.cpp
Labels: throughput

#3626 Don't include `<algorithm>` in `<chrono>`
  stl/inc/chrono
Labels: throughput

#3627 Don't include `<bit>` in `<compare>`
  stl/inc/compare
  stl/inc/format
  stl/inc/type_traits
  stl/inc/xutility
Labels: throughput

#3630 `vector_algorithms.cpp`: Add `vzeroupper`, so that it is there even in `/Od`
  stl/src/vector_algorithms.cpp
Labels: performance

#3645 Status Chart: Weekly updates, drop es-module-shims, hide Combined Wait
  index.html
  package-lock.json
  package.json
  src/status_chart.ts
  src/weekly_table.ts
  src_gather/video_table.ts
  usernames_maintainers.txt
Labels: documentation, uncharted

#3651 Toolset update: VS 2022 17.6 Preview 3
  .github/ISSUE_TEMPLATE/bug-report.md
  CMakeLists.txt
  README.md
  azure-devops/create-1es-hosted-pool.ps1
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  benchmarks/CMakeLists.txt
  stl/CMakeLists.txt
  stl/inc/array
  stl/inc/atomic
  stl/inc/chrono
  stl/inc/execution
  stl/inc/tuple
  stl/inc/xatomic.h
  stl/inc/xfilesystem_abi.h
  tests/std/include/test_header_units_and_modules.hpp
  tests/std/tests/P0980R1_constexpr_strings/test.cpp
  tests/std/tests/P1004R2_constexpr_vector/test.cpp
  tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp
  tests/std/tests/P2321R2_proxy_reference/test.cpp
  tests/std/tests/P2465R3_standard_library_modules/env.lst
  tests/std/tests/P2505R5_monadic_functions_for_std_expected/test.cpp
  tests/std/tests/VSO_0000000_allocator_propagation/test.cpp
  tools/CMakeLists.txt
  tools/format/CMakeLists.txt
  tools/validate/CMakeLists.txt
Labels: high priority, infrastructure

#2436 `static_assert` that container and allocator type parameters are object types
  stl/inc/array
  stl/inc/deque
  stl/inc/forward_list
  stl/inc/list
  stl/inc/map
  stl/inc/queue
  stl/inc/set
  stl/inc/stack
  stl/inc/unordered_map
  stl/inc/unordered_set
  stl/inc/vector
  stl/inc/xmemory
Labels: enhancement

#3623 Move numerous components from `<xstddef>` to other headers and reduce inclusion
  stl/inc/bit
  stl/inc/exception
  stl/inc/functional
  stl/inc/iosfwd
  stl/inc/limits
  stl/inc/type_traits
  stl/inc/utility
  stl/inc/xlocinfo
  stl/inc/xmemory
  stl/inc/xstddef
  stl/inc/xutility
  tests/libcxx/expected_results.txt
Labels: throughput

#3629 Implement P2572R1 `std::format()` fill character allowances
  stl/inc/format
  stl/inc/yvals_core.h
  tests/std/tests/P0645R10_text_formatting_legacy_text_encoding/test.cpp
  tests/std/tests/P0645R10_text_formatting_parsing/test.cpp
  tests/std/tests/P0645R10_text_formatting_utf8/test.cpp
Labels: format, cxx23

#3633 `<numbers>`: Rework the implementation when concepts are missing
  stl/inc/numbers
  tests/std/tests/P0631R8_numbers_math_constants/test.cpp
Labels: enhancement

#3635 `<system_error>`: Optimize internal class `_System_error`
  stl/inc/system_error
Labels: performance

#3639 `<ranges>`: Cleanup for `_CONSTEVAL`
  stl/inc/ranges
Labels: enhancement, ranges

#3643 Update `yvals_core.h` to April 2023
  stl/inc/yvals_core.h
Labels: enhancement

#3647 `<memory>`: Workaround for MSVC bug on `operator<=>` (`shared_ptr` only)
  stl/inc/memory
  tests/std/tests/P1614R2_spaceship/test.cpp
Labels: bug

#3650 Fix `ambiguous_local_time`'s message is slightly incorrect
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
Labels: bug, chrono

#3482 Implement P2614R2 Deprecating `float_denorm_style`, `numeric_limits::has_denorm`, `numeric_limits::has_denorm_loss`
  stl/inc/limits
  stl/inc/yvals_core.h
  tests/std/tests/Dev11_1074023_constexpr/test.cpp
  tests/tr1/tests/limits/test.cpp
Labels: cxx23

#3654 Fuse `<xstddef>` into `<type_traits>`
  stl/CMakeLists.txt
  stl/inc/header-units.json
  stl/inc/type_traits
  stl/inc/xstddef
  tests/std/tests/GH_001411_core_headers/test.cpp
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
  tests/std/tests/VSO_0000000_instantiate_type_traits/test.compile.pass.cpp
Labels: throughput

#3660 `<map>`, `<unordered_map>`: Allow `MapLike<K, V&>` again
  stl/inc/map
  stl/inc/unordered_map
  tests/std/tests/Dev11_0437519_container_requirements/test.compile.pass.cpp
Labels: bug, high priority

#3672 `<mdspan>`: Cleanup `mdspan` class a little bit
  stl/inc/mdspan
Labels: mdspan

#3673 `<mdspan>`: `layout_stride` improvements
  stl/inc/mdspan
  tests/std/test.lst
  tests/std/tests/P0009R18_mdspan_layout_stride/env.lst
  tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_stride_death/env.lst
  tests/std/tests/P0009R18_mdspan_layout_stride_death/test.cpp
Labels: mdspan

#3674 `<mdspan>`: Reduce amount of function calls in non-optimized debug mode
  stl/inc/mdspan
  tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
Labels: mdspan

#3649 `<chrono>`: Fix formatting for unusual `duration`s
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp
Labels: bug, format, chrono

#3658 Ensure _Idx is only worked on if it has to be.
  stl/inc/valarray
Labels: enhancement

#3668 `<optional>`: Fix exception specification for `optional`'s transform-construction
  stl/inc/optional
  tests/std/tests/P0798R8_monadic_operations_for_std_optional/test.cpp
Labels: bug

#3670 `<charconv>`: Fix `from_chars` for floating-point types
  stl/inc/charconv
  tests/std/tests/P0067R5_charconv/double_from_chars_test_cases.hpp
  tests/std/tests/P0067R5_charconv/test.cpp
Labels: bug
