Repository microsoft/STL, pull requests merged in 2023-02, with the labels that each got.

#3352 Make some special member functions of `shared_mutex`, `shared_timed_mutex`, and `shared_lock` defaulted
  stl/inc/shared_mutex
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/Dev11_1150223_shared_mutex/test.cpp
Labels: enhancement

#3366 `<algorithm>`: `ranges::minmax` should dereference iterators only once
  stl/inc/algorithm
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/P0896R4_ranges_alg_minmax/test.cpp
Labels: bug, ranges

#3367 Speculatively implement LWG-3867
  stl/inc/syncstream
  tests/std/tests/GH_001858_iostream_exception/test.cpp
Labels: enhancement

#3373 Minor modules modifications
  stl/inc/ctime
  stl/modules/std.ixx
Labels: bug, modules

#3207 Grammar Updates
  README.md
Labels: documentation

#3277 Use Brace Lists to initialize objects.
  stl/inc/cvt/wbuffer
  stl/inc/cvt/wstring
  stl/inc/experimental/filesystem
  stl/inc/filesystem
  stl/inc/fstream
  stl/inc/istream
  stl/inc/ostream
  stl/inc/spanstream
  stl/inc/sstream
  stl/inc/streambuf
  stl/inc/strstream
  stl/inc/xlocale
  stl/inc/xlocbuf
  stl/src/locale0.cpp
Labels: enhancement

#3399 `<atomic>`: Improve ARM64 performance
  stl/inc/atomic
Labels: performance, ARM64

#3361 Implement P2505R5 Monadic Functions For std::expected
  stl/inc/expected
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/test.lst
  tests/std/tests/P2505R5_monadic_functions_for_std_expected/env.lst
  tests/std/tests/P2505R5_monadic_functions_for_std_expected/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#3380 `<system_error>`: Use uglified `[[clang::require_constant_initialization]]` attribute
  stl/inc/system_error
Labels: bug

#3381 `<xiosbase>`: Remove out-of-class definitions of `static constexpr` data members
  stl/inc/xiosbase
Labels: bug

#3384 Refactor ranges::minmax and ranges::minmax_element
  stl/inc/algorithm
Labels: enhancement

#3386 Infinite range find algorithm: update transition comment for memchr optimization for ARM64
  stl/inc/xutility
Labels: performance

#3389 Use `if constexpr` dispatch for `_Pass_fn`
  stl/inc/xutility
Labels: throughput

#3394 Unmention DevCom-10111923 in test `P0088R3_variant`
  tests/std/tests/P0088R3_variant/test.cpp
Labels: test

#3395 Updated _MSVC_STL_UPDATE to February 2023
  stl/inc/yvals_core.h
Labels: enhancement

#3397 Change `_NODISCARD` in source and test files to `[[nodiscard]]`
  stl/src/atomic_wait.cpp
  stl/src/excptptr.cpp
  stl/src/memory_resource.cpp
  stl/src/multprec.cpp
  stl/src/parallel_algorithms.cpp
  stl/src/special_math.cpp
  stl/src/syncstream.cpp
  stl/src/syserror_import_lib.cpp
  stl/src/tzdb.cpp
  stl/src/xmath.hpp
  tests/std/tests/P2321R2_views_zip/test.cpp
Labels: enhancement

#3404 Status Chart: Weekly updates, dependency updates
  index.html
  package-lock.json
  package.json
  src/weekly_table.ts
  src_gather/video_table.ts
Labels: documentation, uncharted

#3388 Strengthen exception specifications for [thread] types
  stl/inc/condition_variable
  stl/inc/mutex
  stl/inc/shared_mutex
  stl/inc/thread
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/Dev11_1150223_shared_mutex/test.cpp
  tests/std/tests/P0156R2_scoped_lock/test.cpp
  tests/std/tests/VSO_0000000_condition_variable_any_exceptions/test.cpp
Labels: enhancement

#3390 Improve `views::drop(_while)` and `views::take(_while)` tests
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_drop_while/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
  tests/std/tests/P0896R4_views_take_while/test.cpp
Labels: test, ranges

#3393 Assign new pull requests to Code Review
  .github/workflows/assign-new-prs.yml
Labels: infrastructure

#3402 `stl/CMakeLists.txt`: Fix `add_compile_options()` ordering
  stl/CMakeLists.txt
Labels: bug, build

#3403 `<format>`: Make instantiation used by `vformat_to` lazier
  stl/inc/format
Labels: bug, format

#3410 LWG-3848: `slide_view` missing `base` accessor
  stl/inc/ranges
  tests/std/tests/P2442R1_views_slide/test.cpp
Labels: LWG, ranges

#3421 LWG-3810: CTAD for `basic_format_args`
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_args/test.cpp
Labels: LWG, format

#3423 LWG-3850: `views::as_const` on `empty_view<T>` should return `empty_view<const T>`
  stl/inc/ranges
  tests/std/tests/P2278R4_views_as_const/test.cpp
Labels: LWG, ranges

#3451 Implement P2711R1 Making Multi-Param Constructors Of Views `explicit`
  stl/inc/ranges
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: ranges, cxx23

#3453 Eliminate spaces in `operator"" name()`
  stl/inc/__msvc_chrono.hpp
  stl/inc/chrono
  stl/inc/xstring
  tests/std/tests/P0092R1_polishing_chrono/test.cpp
  tests/std/tests/P1522R1_difference_type/test.cpp
Labels: enhancement

#3455 `<barrier>`: Declare victory!
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#3459 LWG-3769 `basic_const_iterator::operator==` causes infinite constraint recursion
  stl/inc/xutility
Labels: LWG

#3461 Uncomment resolutions of applied LWG issues
  stl/inc/deque
  stl/inc/queue
  stl/inc/syncstream
  stl/inc/xstring
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/tests/P0220R1_string_view/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: documentation

#3462 LWG-3772 repeat_view's piecewise constructor is missing Postconditions
  stl/inc/ranges
  stl/inc/tuple
Labels: LWG

#3464 Reorganize libc++ skips
  tests/libcxx/expected_results.txt
  tests/libcxx/skipped_tests.txt
Labels: test

#3467 Toolset update: VS 2022 17.5 Preview 6
  README.md
  azure-devops/create-1es-hosted-pool.ps1
  azure-devops/provision-image.ps1
  azure-pipelines.yml
Labels: infrastructure

#3468 LWG-3853: `basic_const_iterator<volatile int*>::operator->` is ill-formed
  stl/inc/xutility
  tests/std/tests/P2278R4_basic_const_iterator/test.cpp
Labels: LWG

#3488 Finalize `modules.json` format
  stl/modules/modules.json
Labels: enhancement, high priority, modules

#3490 Toolset update: VS 2022 17.6 Preview 1
  CMakeLists.txt
  README.md
  azure-pipelines.yml
  benchmarks/CMakeLists.txt
  stl/CMakeLists.txt
  stl/inc/type_traits
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tools/CMakeLists.txt
  tools/format/CMakeLists.txt
  tools/validate/CMakeLists.txt
Labels: infrastructure

#3405 `ios_base` constants should have bitmask types
  stl/inc/xiosbase
  tests/std/tests/P2467R1_exclusive_mode_fstreams/test.cpp
Labels: bug

#3469 Implement LWG-2309 `mutex::lock()` should not throw `device_or_resource_busy`
  stl/inc/mutex
Labels: bug, LWG

#3470 LWG-3872: `basic_const_iterator` should have custom `iter_move`
  stl/inc/xutility
  tests/std/tests/P2278R4_basic_const_iterator/env.lst
  tests/std/tests/P2278R4_basic_const_iterator/test.cpp
Labels: LWG

#3471 LWG-3862: `basic_const_iterator`'s `common_type` specialization is underconstrained
  stl/inc/xutility
  tests/std/tests/P2278R4_ranges_const_iterator_machinery/test.compile.pass.cpp
Labels: LWG

#3476 Implement LWG-3865 Sorting a range of `pair`s
  stl/inc/utility
  tests/libcxx/expected_results.txt
  tests/std/tests/Dev11_1140665_unique_ptr_array_conversions/test.cpp
Labels: LWG

#3477 LWG-3833 Remove specialization `template<size_t N> struct formatter<const charT[N], charT>`
  stl/inc/format
Labels: LWG, format

#3479 LWG-3847 `ranges::to` can still return views
  stl/inc/ranges
Labels: LWG, ranges

#3480 Implement LWG-3860 `range_common_reference_t` is missing
  stl/inc/xutility
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
Labels: LWG, ranges

#3483 Workaround some Clang-16-rc2 regressions
  stl/inc/ranges
  stl/inc/xutility
  tests/std/tests/P0323R12_expected/test.cpp
Labels: bug

#3485 LWG-3875: `ranges::repeat_view<T, IntegerClass>::iterator` may be ill-formed
  stl/inc/ranges
  tests/std/tests/P2474R2_views_repeat/test.cpp
Labels: bug, LWG, ranges

#3486 P2609R3: Relaxing Ranges Just A Smidge
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2609R3_relaxing_ranges_just_a_smidge/env.lst
  tests/std/tests/P2609R3_relaxing_ranges_just_a_smidge/test.compile.pass.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23

#3487 Implement LWG-3869 Deprecate `std::errc` constants related to UNIX STREAMS
  stl/inc/xerrc.h
  stl/inc/yvals_core.h
  stl/src/syserror.cpp
  tests/tr1/tests/system_error/test.cpp
Labels: LWG

#3489 fix codeql warnings
  stl/inc/charconv
  stl/inc/system_error
Labels: enhancement

#3502 Implement P0009R18 `<mdspan>` et al.
  stl/CMakeLists.txt
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/header-units.json
  stl/inc/mdspan
  stl/inc/yvals_core.h
  stl/modules/std.ixx
  tests/std/test.lst
  tests/std/tests/P0009R18_mdspan/env.lst
  tests/std/tests/P0009R18_mdspan/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/importable_cxx_library_headers.jsonc
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23, mdspan

#3372 P2165R4: Compatibility Between `tuple`, `pair`, And tuple-like Objects
  stl/inc/ranges
  stl/inc/tuple
  stl/inc/utility
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/std/test.lst
  tests/std/tests/P0433R2_deduction_guides/test.cpp
  tests/std/tests/P2165R4_tuple_like_common_reference/env.lst
  tests/std/tests/P2165R4_tuple_like_common_reference/test.compile.pass.cpp
  tests/std/tests/P2165R4_tuple_like_common_type/env.lst
  tests/std/tests/P2165R4_tuple_like_common_type/test.compile.pass.cpp
  tests/std/tests/P2165R4_tuple_like_operations/env.lst
  tests/std/tests/P2165R4_tuple_like_operations/test.compile.pass.cpp
  tests/std/tests/P2165R4_tuple_like_relational_operators/env.lst
  tests/std/tests/P2165R4_tuple_like_relational_operators/test.compile.pass.cpp
  tests/std/tests/P2165R4_tuple_like_tuple_members/env.lst
  tests/std/tests/P2165R4_tuple_like_tuple_members/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: cxx23

#3493 `<ranges>`: Fix misused list-initializations
  stl/inc/iterator
  stl/inc/ranges
  tests/std/include/range_algorithm_support.hpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
  tests/std/tests/P0896R4_views_elements/test.cpp
  tests/std/tests/P0896R4_views_join/test.cpp
  tests/std/tests/P0896R4_views_transform/test.cpp
  tests/std/tests/P2441R2_views_join_with/test.cpp
Labels: bug, ranges

#3494 Implement LWG-3204 `sub_match::swap` only swaps the base class
  stl/inc/regex
  tests/std/tests/Dev09_173612_tr1_regex_leak/test.cpp
Labels: LWG

#3495 Implement LWG-3655: The `INVOKE` operation and `union` types
  stl/inc/type_traits
  tests/std/tests/P2136R3_invoke_r/test.cpp
Labels: LWG

#3496 Implement LWG-3733 `ranges::to` misuses `cpp17-input-iterator`
  stl/inc/ranges
  tests/std/tests/P1206R7_ranges_to_misc/test.cpp
Labels: LWG, ranges

#3497 Avoid new warning C5267 for deprecated implicit copy ctor/assign
  stl/inc/bitset
  tests/std/tests/Dev08_576265_list_remove/test.cpp
  tests/std/tests/Dev11_0437519_container_behavior/test.cpp
  tests/std/tests/GH_002488_promise_not_default_constructible_types/test.cpp
  tests/std/tests/P0220R1_any/test.cpp
  tests/std/tests/P0220R1_optional/test.cpp
  tests/std/tests/P0608R3_improved_variant_converting_constructor/test.cpp
  tests/std/tests/P0674R1_make_shared_for_arrays/test.cpp
  tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
  tests/std/tests/P0896R4_views_join/test.cpp
  tests/std/tests/P2231R1_complete_constexpr_optional_variant/test.cpp
Labels: enhancement

#3396 Implement LWG-3677 Is a cv-qualified `pair` specially handled in uses-allocator construction?
  stl/inc/scoped_allocator
  stl/inc/xmemory
  stl/inc/xpolymorphic_allocator.h
  tests/std/tests/P0220R1_polymorphic_memory_resources/test.cpp
  tests/std/tests/P0475R1_P0591R4_uses_allocator_construction/test.cpp
Labels: LWG

#3499 Remove workarounds for `/clr` C++20
  stl/inc/algorithm
  stl/inc/format
  tests/std/tests/GH_002558_format_presetPadding/env.lst
  tests/std/tests/P0088R3_variant/env.lst
  tests/std/tests/P0645R10_text_formatting_legacy_text_encoding/env.lst
  tests/std/tests/P0912R5_coroutine/env.lst
  tests/std/tests/P1208R6_source_location/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/env.lst
  tests/std/tests/char8_t_17_matrix.lst
  tests/std/tests/char8_t_impure_matrix.lst
  tests/std/tests/char8_t_matrix.lst
  tests/std/tests/clr_matrix.lst
  tests/std/tests/concepts_20_matrix.lst
  tests/std/tests/impure_matrix.lst
  tests/std/tests/locale0_implib_cpp_matrix.lst
  tests/std/tests/strict_concepts_20_matrix.lst
  tests/std/tests/usual_17_matrix.lst
  tests/std/tests/usual_20_matrix.lst
  tests/std/tests/usual_matrix.lst
  tests/tr1/env.lst
  tests/tr1/env_minus_md_idl.lst
  tests/tr1/env_minus_pure.lst
Labels: enhancement

#3472 P2164R9: `views::enumerate`
  stl/inc/ranges
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/P2164R9_views_enumerate/env.lst
  tests/std/tests/P2164R9_views_enumerate/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx23
