Repository microsoft/STL, pull requests merged in 2023-06, with the labels that each got.

#3744 Merge `main` to `feature/mdspan2`
  .clang-format
  CMakeLists.txt
  stl/CMakeLists.txt
  stl/inc/__msvc_iter_core.hpp
  stl/inc/charconv
  stl/inc/chrono
  stl/inc/deque
  stl/inc/exception
  stl/inc/format
  stl/inc/future
  stl/inc/iomanip
  stl/inc/ios
  stl/inc/istream
  stl/inc/list
  stl/inc/memory_resource
  stl/inc/ostream
  stl/inc/ranges
  stl/inc/regex
  stl/inc/streambuf
  stl/inc/type_traits
  stl/inc/utility
  stl/inc/xiosbase
  stl/inc/xlocale
  stl/inc/xlocnum
  stl/inc/xloctime
  stl/inc/xutility
  stl/inc/yvals.h
  stl/src/atomic.cpp
  stl/src/excptptr.cpp
  stl/src/ppltasks.cpp
  stl/src/primitives.hpp
  stl/src/sharedmutex.cpp
  stl/src/vector_algorithms.cpp
  stl/src/winapisupp.cpp
  stl/src/xonce2.cpp
  stl/src/xstol.cpp
  stl/src/xstoll.cpp
  tests/std/test.lst
  tests/std/tests/GH_002769_handle_deque_block_pointers/test.cpp
  tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp
  tests/std/tests/P0896R4_views_iota_death/env.lst
  tests/std/tests/P0896R4_views_iota_death/test.cpp
  tests/std/tests/P1208R6_source_location/test.cpp
  tests/std/tests/P1522R1_difference_type/test.cpp
  tests/std/tests/P2374R4_views_cartesian_product/test.cpp
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
  tests/tr1/tests/type_traits1/test.cpp
  tests/tr1/tests/utility/test.cpp
Labels: uncharted, mdspan

#3749 `<mdspan>`: Test `mdspan`
  stl/inc/mdspan
  tests/std/include/test_mdspan_support.hpp
  tests/std/test.lst
  tests/std/tests/P0009R18_mdspan/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
  tests/std/tests/P0009R18_mdspan_mdspan/env.lst
  tests/std/tests/P0009R18_mdspan_mdspan/test.cpp
Labels: mdspan

#3769 Toolset update: VS 2022 17.7 Preview 2
  README.md
  azure-devops/cmake-configure-build.yml
  azure-devops/create-1es-hosted-pool.ps1
  azure-devops/cross-build.yml
  azure-devops/native-build-test.yml
  azure-devops/provision-image.ps1
  azure-devops/run-tests.yml
  azure-pipelines.yml
  stl/inc/memory
  stl/inc/xutility
Labels: infrastructure

#3721 Concentrated header for internal bit utilities
  stl/CMakeLists.txt
  stl/inc/__msvc_bit_utils.hpp
  stl/inc/__msvc_format_ucd_tables.hpp
  stl/inc/__msvc_int128.hpp
  stl/inc/bit
  stl/inc/bitset
  stl/inc/complex
  stl/inc/header-units.json
  stl/inc/limits
  stl/inc/numeric
  stl/inc/random
  stl/inc/ranges
  stl/inc/vector
  tests/std/tests/GH_001411_core_headers/test.cpp
  tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp
  tests/std/tests/GH_002431_byte_range_find_with_unreachable_sentinel/test.cpp
Labels: throughput

#3727 Fix `hh_mm_ss` formatting for values >= 1 day
  stl/inc/__msvc_chrono.hpp
  stl/inc/chrono
  tests/std/test.lst
  tests/std/tests/GH_003676_format_large_hh_mm_ss_values/env.lst
  tests/std/tests/GH_003676_format_large_hh_mm_ss_values/test.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
Labels: bug, format, chrono

#3737 Implement LWG-3843 `std::expected<T,E>::value() &` assumes `E` is copy constructible
  stl/inc/expected
  tests/libcxx/expected_results.txt
  tests/std/tests/P0323R12_expected/test.cpp
Labels: LWG

#3742 Change _MSVC_STL_UPDATE to June 2023
  stl/inc/yvals_core.h
Labels: enhancement

#3745 Implement LWG-3631 `basic_format_arg(T&&)` should use `remove_cvref_t<T>` throughout
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_args/test.cpp
  tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp
Labels: LWG, format

#3755 Add static for some `_Xxxx()` member functions
  stl/inc/array
  stl/inc/bitset
  stl/inc/deque
  stl/inc/vector
Labels: performance

#3758 Cleanups for `<future>`
  stl/inc/future
Labels: enhancement

#3759 Cleanups for `<mutex>` etc.
  stl/inc/mutex
  stl/inc/shared_mutex
Labels: enhancement

#3760 Workaround for non-_Ugly attribute tokens
  stl/inc/memory
  stl/inc/system_error
  stl/inc/type_traits
  stl/inc/utility
  stl/inc/xtr1common
  stl/inc/xutility
  tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp
Labels: bug

#3761 `<condition_variable>`: Fixes bad timeout in wait_until with unsigned rep
  stl/inc/condition_variable
  tests/std/tests/GH_000685_condition_variable_any/test.cpp
Labels: bug

#3762 `<ranges>`: Strengthen exception specification for `_Defaultabox`
  stl/inc/ranges
Labels: enhancement, ranges

#3765 Remove redundant template parameters for `_XX_iter_types`
  stl/inc/deque
  stl/inc/forward_list
  stl/inc/list
  stl/inc/vector
  stl/inc/xhash
  stl/inc/xstring
  stl/inc/xtree
Labels: enhancement

#3768 Remove some unnecessary clang-format hacks
  stl/inc/__msvc_iter_core.hpp
  stl/inc/algorithm
  stl/inc/chrono
  stl/inc/execution
  stl/inc/expected
  stl/inc/memory
  stl/inc/ranges
  stl/inc/tuple
  stl/inc/utility
  stl/inc/xmemory
  stl/inc/xutility
  tests/std/tests/P0896R4_common_iterator/test.cpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
  tests/std/tests/P1899R3_views_stride/test.cpp
  tests/std/tests/P2164R9_views_enumerate/test.cpp
  tests/std/tests/P2374R4_views_cartesian_product/test.cpp
  tests/std/tests/P2387R3_pipe_support_for_user_defined_range_adaptors/test.cpp
Labels: enhancement

#3712 Utilize `allocate_at_least`
  stl/inc/deque
  stl/inc/sstream
  stl/inc/syncstream
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/xstring
  tests/std/test.lst
  tests/std/tests/GH_003570_allocate_at_least/env.lst
  tests/std/tests/GH_003570_allocate_at_least/test.cpp
Labels: performance

#3738 `<xstring>`: Strengthen exception specification for `sv.compare("NTBS")`
  stl/inc/xstring
  tests/std/tests/P0220R1_string_view/test.cpp
Labels: enhancement

#3747 `<semaphore>`: Add missed mandates for `counting_semaphore`
  stl/inc/semaphore
Labels: bug

#3753 Make `P2415R2_owning_view/test.cpp` test something
  tests/std/include/range_algorithm_support.hpp
  tests/std/tests/P2415R2_owning_view/test.cpp
Labels: test, ranges

#3757 Enhance `_STL_VERIFY` for `std::barrier`
  stl/inc/barrier
Labels: enhancement

#3763 `<mutex>`: Make `_Mtx_internal_imp_mirror` more closely match `_Mtx_internal_imp_t`
  stl/CMakeLists.txt
  stl/inc/mutex
  stl/msbuild/stl_base/libcp.settings.targets
  stl/msbuild/stl_base/msvcp.settings.targets
  stl/src/cond.cpp
  stl/src/mutex.cpp
  stl/src/primitives.hpp
Labels: bug

#3772 Better char vector visualization
  stl/debugger/STL.natvis
Labels: visualizer

#3739 Implement signature changes for `char_traits` in N2349
  stl/inc/xstring
  tests/std/test.lst
  tests/std/tests/GH_003735_char_traits_signatures/env.lst
  tests/std/tests/GH_003735_char_traits_signatures/test.compile.pass.cpp
Labels: bug

#3767 `<mdspan>`: Remove old tests
  stl/inc/mdspan
  tests/std/include/test_mdspan_support.hpp
  tests/std/test.lst
  tests/std/tests/P0009R18_mdspan/env.lst
  tests/std/tests/P0009R18_mdspan/test.cpp
  tests/std/tests/P0009R18_mdspan_extents/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
  tests/std/tests/P0009R18_mdspan_mdspan/test.cpp
Labels: test, mdspan

#3786 `<mdspan>`: `extents` improvements
  stl/inc/mdspan
  tests/std/include/test_mdspan_support.hpp
  tests/std/tests/P0009R18_mdspan_extents_death/test.cpp
Labels: mdspan

#3770 `mutex.cpp`, `cond.cpp`: Use static dispatch
  stl/inc/mutex
  stl/src/cond.cpp
  stl/src/mutex.cpp
  stl/src/primitives.hpp
  tests/std/tests/Dev11_1150223_shared_mutex/test.cpp
Labels: performance

#3773 Fix `fstream.seekp(0, ios::cur)`
  stl/inc/__msvc_filebuf.hpp
  tests/std/test.lst
  tests/std/tests/GH_003572_fstream_seekp_0_cur/env.lst
  tests/std/tests/GH_003572_fstream_seekp_0_cur/test.cpp
Labels: bug

#3776 Avoid evil macros
  stl/inc/__msvc_bit_utils.hpp
  stl/inc/complex
  stl/inc/deque
  stl/inc/mutex
  stl/inc/random
  stl/inc/regex
Labels: enhancement

#3777 Don't include `<limits>` in `<xutility>`
  stl/inc/xutility
Labels: throughput

#3781 Implement LWG-3904 `lazy_split_view::outer-iterator`'s `const`-converting constructor isn't setting `trailing_empty_`
  stl/inc/ranges
  tests/std/tests/P0896R4_views_lazy_split/test.cpp
Labels: LWG

#3784 Documentation Fix for #3780
  stl/inc/ranges
Labels: documentation

#3785 Documentation fix for #3779
  stl/inc/expected
  tests/libcxx/expected_results.txt
Labels: documentation

#3787 `<format>`: Move the major part of `visit_format_arg` into a member function of `basic_format_arg`
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_args/test.cpp
Labels: bug, format

#3815 `<format>`: fix `std::format("{:#.precision}", floating)`
  stl/inc/format
  tests/libcxx/expected_results.txt
  tests/std/test.lst
  tests/std/tests/GH_003003_format_decimal_point/env.lst
  tests/std/tests/GH_003003_format_decimal_point/test.cpp
Labels: bug, format

#3816 Standard Library Modules: Add workaround for `<format>` `/utf-8`
  stl/inc/ostream
  tests/std/tests/P2465R3_standard_library_modules/env.lst
Labels: format, modules

#3819 Deallocate at least
  stl/inc/deque
  stl/inc/sstream
  stl/inc/syncstream
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/xstring
  tests/std/test.lst
  tests/std/tests/GH_003570_allocate_at_least/env.lst
  tests/std/tests/GH_003570_allocate_at_least/test.cpp
Labels: bug, high priority

#3841 Revert `fstream.seekp(0, ios::cur)` change
  stl/inc/__msvc_filebuf.hpp
  tests/std/test.lst
  tests/std/tests/GH_003572_fstream_seekp_0_cur/test.cpp
  tests/std/tests/GH_003840_tellg_when_reading_lf_file_in_text_mode/env.lst
  tests/std/tests/GH_003840_tellg_when_reading_lf_file_in_text_mode/test.cpp
Labels: bug, high priority
