Repository microsoft/STL, pull requests merged in 2024-11, with the labels that each got.

#5046 Refactor `_Copy_memmove` and `_Copy_memmove_n`
  stl/inc/algorithm
  stl/inc/xutility
  tests/std/tests/GH_000431_copy_move_family/test.cpp
Labels: bug

#5056 Fix internal Perl script for Standard Library Header Units test coverage
  tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
Labels: test, modules

#5058 `<regex>`: Small cleanups
  stl/inc/regex
  tests/std/tests/GH_000431_equal_memcmp_is_safe/test.compile.pass.cpp
  tests/std/tests/GH_000431_lex_compare_memcmp_classify/test.compile.pass.cpp
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: enhancement

#5061 Guard `__restrict` usage for CUDA
  stl/inc/numeric
  stl/inc/yvals_core.h
Labels: bug

#5063 Partition vector algorithms test: move out lex compare family
  tests/std/test.lst
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
  tests/std/tests/VSO_0000000_vector_algorithms_mismatch_and_lex_compare/env.lst
  tests/std/tests/VSO_0000000_vector_algorithms_mismatch_and_lex_compare/test.cpp
Labels: test

#5065 Clarify `optional::swap` conditions
  stl/inc/optional
Labels: documentation

#5067 `<locale>`: Hide some non-Standard functions of `locale::id`
  stl/inc/locale
  stl/inc/xlocale
  stl/src/locale.cpp
  stl/src/locale0.cpp
  stl/src/wlocale.cpp
  stl/src/xlocale.cpp
  tests/std/tests/Dev09_056375_locale_cleanup/test.cpp
Labels: enhancement

#5077 Fix `filesystem::directory_entry::refresh` on Win11 24H2
  stl/inc/xfilesystem_abi.h
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: bug, filesystem

#5082 Toolset update: VS 2022 17.13 Preview 1, Windows Server 2025
  CMakeLists.txt
  README.md
  azure-devops/config.yml
  azure-devops/create-1es-hosted-pool.ps1
  azure-devops/provision-image.ps1
  benchmarks/CMakeLists.txt
  tools/CMakeLists.txt
  tools/format/CMakeLists.txt
  tools/validate/CMakeLists.txt
Labels: infrastructure

#5057 Vectorize `basic_string::rfind` (the string needle overload)
  benchmarks/src/search.cpp
  stl/inc/__msvc_string_view.hpp
  stl/inc/algorithm
  stl/inc/xutility
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#5071 `<filesystem>`: Improve `symlink_status` performance
  benchmarks/CMakeLists.txt
  benchmarks/src/filesystem.cpp
  stl/src/filesystem.cpp
Labels: performance, filesystem

#5072 `<regex>`: Silence CodeQL false positive warning
  stl/inc/regex
Labels: enhancement

#5078 `<xutility>`: Extend vectorization condition for `_Synth_three_way`
  stl/inc/xutility
Labels: performance

#5079 Use `__restrict__` for CUDA
  stl/inc/yvals_core.h
Labels: enhancement

#5085 Merge `main` to `feature/flat_map`
  CMakeLists.txt
  README.md
  azure-devops/config.yml
  azure-devops/create-1es-hosted-pool.ps1
  azure-devops/provision-image.ps1
  benchmarks/CMakeLists.txt
  benchmarks/src/filesystem.cpp
  benchmarks/src/search.cpp
  stl/inc/__msvc_string_view.hpp
  stl/inc/algorithm
  stl/inc/istream
  stl/inc/locale
  stl/inc/numeric
  stl/inc/optional
  stl/inc/regex
  stl/inc/xfilesystem_abi.h
  stl/inc/xlocale
  stl/inc/xutility
  stl/inc/yvals_core.h
  stl/src/filesystem.cpp
  stl/src/locale.cpp
  stl/src/locale0.cpp
  stl/src/wlocale.cpp
  stl/src/xlocale.cpp
  tests/libcxx/expected_results.txt
  tests/std/test.lst
  tests/std/tests/Dev09_056375_locale_cleanup/test.cpp
  tests/std/tests/GH_000431_copy_move_family/test.cpp
  tests/std/tests/GH_000431_equal_memcmp_is_safe/test.compile.pass.cpp
  tests/std/tests/GH_000431_lex_compare_memcmp_classify/test.compile.pass.cpp
  tests/std/tests/GH_001858_iostream_exception/test.cpp
  tests/std/tests/P0218R1_filesystem/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
  tests/std/tests/VSO_0000000_regex_use/test.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
  tests/std/tests/VSO_0000000_vector_algorithms_mismatch_and_lex_compare/env.lst
  tests/std/tests/VSO_0000000_vector_algorithms_mismatch_and_lex_compare/test.cpp
  tools/CMakeLists.txt
  tools/format/CMakeLists.txt
  tools/validate/CMakeLists.txt
Labels: uncharted, flat_meow

#5089 Status Chart: Weekly/dependency updates
  index.html
  package-lock.json
  package.json
  src/weekly_table.mts
Labels: documentation, uncharted

#5097 Don't use `__restrict__` for CUDA
  stl/inc/yvals_core.h
Labels: bug, high priority

#5086 Enforce `assign_range()` mandates for sequence containers
  stl/inc/deque
  stl/inc/forward_list
  stl/inc/list
  stl/inc/vector
Labels: bug, ranges

#5087 Vectorize `basic_string::rfind` (the single character overload)
  benchmarks/src/find_and_count.cpp
  stl/inc/__msvc_string_view.hpp
  stl/inc/algorithm
  stl/inc/xutility
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#5091 `<algorithm>`: Fix bogus pointer arithmetic with integer-class
  stl/inc/algorithm
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/GH_002885_stable_sort_difference_type/env.lst
  tests/std/tests/GH_002885_stable_sort_difference_type/test.cpp
Labels: bug, ranges

#5099 More specific assertion for unlocking mutex not owned by the current thread
  stl/src/mutex.cpp
Labels: enhancement

#5105 Move `system_clock` from `<__msvc_chrono.hpp>` to `<chrono>`
  stl/inc/__msvc_chrono.hpp
  stl/inc/chrono
  stl/inc/experimental/filesystem
Labels: throughput
