Repository microsoft/STL, pull requests merged in 2024-07, with the labels that each got.

#4758 Implement LWG-4061 Should `std::basic_format_context` be default-constructible/copyable/movable?
  stl/inc/format
  tests/libcxx/expected_results.txt
  tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp
Labels: LWG, format

#4748 Properly test the resolution of LWG-4053
  tests/std/tests/P2474R2_views_repeat/test.cpp
Labels: test, ranges

#4749 `<xtree>`: Use scope guard for node copy failure
  stl/inc/xtree
Labels: enhancement

#4753 Inline `_Memcmp_ranges` that is used only once
  stl/inc/xutility
Labels: enhancement

#4754 Updated _MSVC_STL_UPDATE to July 2024
  stl/inc/yvals_core.h
Labels: enhancement

#4775 Inspect unwrapped iterators by `_Prefer_iterator_copies`
  stl/inc/algorithm
  stl/inc/xutility
Labels: performance, ranges

#4777 P2968R2 Make std::ignore A First-Class Object
  stl/inc/tuple
  stl/inc/utility
  stl/inc/yvals_core.h
Labels: cxx26

#4782 Remove `_NODISCARD_FRIEND` workaround
  stl/inc/__msvc_int128.hpp
  stl/inc/__msvc_ranges_to.hpp
  stl/inc/__msvc_string_view.hpp
  stl/inc/array
  stl/inc/charconv
  stl/inc/compare
  stl/inc/deque
  stl/inc/exception
  stl/inc/expected
  stl/inc/filesystem
  stl/inc/functional
  stl/inc/iosfwd
  stl/inc/iterator
  stl/inc/mdspan
  stl/inc/random
  stl/inc/ranges
  stl/inc/span
  stl/inc/stacktrace
  stl/inc/stop_token
  stl/inc/system_error
  stl/inc/tuple
  stl/inc/valarray
  stl/inc/vector
  stl/inc/xcharconv.h
  stl/inc/xhash
  stl/inc/xpolymorphic_allocator.h
  stl/inc/xstring
  stl/inc/xutility
  stl/inc/yvals_core.h
Labels: enhancement

#4784 Implement LWG-3944 Formatters converting sequences of `char` to sequences of `wchar_t`
  stl/inc/__msvc_formatter.hpp
  tests/std/tests/P2286R8_text_formatting_formattable/test.compile.pass.cpp
Labels: LWG, format

#4785 Implement LWG-4096 `views::iota(views::iota(0))` should be rejected
  stl/inc/ranges
  tests/std/tests/P0896R4_views_iota/test.cpp
Labels: LWG, ranges

#4757 Implement LWG-4106 `basic_format_args` should not be default-constructible
  stl/inc/format
  tests/libcxx/expected_results.txt
  tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp
Labels: LWG, format

#4751 Always use cmpxchg16b on x64 for `atomic_ref<16 bytes>`
  stl/inc/atomic
  stl/inc/yvals.h
  stl/inc/yvals_core.h
  stl/src/atomic_wait.cpp
  tests/std/tests/P0019R8_atomic_ref/env.lst
  tests/std/tests/P0019R8_atomic_ref/test.cpp
Labels: performance

#4813 Status Chart: Extract bugChart
  built/status_chart.mjs
  index.html
  package-lock.json
  package.json
  src/status_chart.mts
  src/weekly_table.mts
Labels: documentation

#4778 Fix insert for flat_map and flat_multimap
  stl/inc/flat_map
  tests/std/tests/P0429R9_flat_map/test.cpp
Labels: bug, flat_meow

#4828 `<flat_map>`: Fix ordering in insertion and access control in construction
  stl/inc/flat_map
  tests/std/tests/P0429R9_flat_map/test.cpp
Labels: bug, flat_meow

#4824 Toolset update: VS 2022 17.11 Preview 3
  CMakeLists.txt
  README.md
  azure-devops/config.yml
  azure-devops/create-1es-hosted-pool.ps1
  azure-devops/provision-image.ps1
  benchmarks/CMakeLists.txt
  stl/inc/__msvc_bit_utils.hpp
  stl/inc/yvals_core.h
  tools/CMakeLists.txt
  tools/format/CMakeLists.txt
  tools/validate/CMakeLists.txt
Labels: infrastructure

#4776 `<numeric>`: check for gcd / lcm overflows
  stl/inc/numeric
  stl/inc/utility
  stl/inc/xutility
  tests/std/tests/P0295R0_gcd_lcm/test.compile.pass.cpp
Labels: enhancement

#4786 Implement LWG-4083 `views::as_rvalue` should reject non-input ranges
  stl/inc/ranges
  tests/std/tests/P2446R2_views_as_rvalue/test.cpp
Labels: LWG, ranges

#4814 Implement LWG-4074 `compatible-joinable-ranges` is underconstrained
  stl/inc/ranges
  tests/std/tests/P2441R2_views_join_with/test.cpp
Labels: LWG, ranges

#4815 Implement LWG-4098 `views::adjacent<0>` should reject non-forward ranges
  stl/inc/ranges
  tests/std/tests/P2321R2_views_adjacent/test.cpp
  tests/std/tests/P2321R2_views_adjacent_transform/test.cpp
Labels: LWG, ranges

#4816 Implement P2997R1 Removing The Common Reference Requirement From The Indirectly Invocable Concepts
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/std/tests/P0896R4_ranges_algorithm_machinery/test.compile.pass.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, cxx26

#4817 Fix `<bitset>` benchmark correctness
  benchmarks/src/bitset_to_string.cpp
Labels: test

#4818 Fewer allocations to put smaller bitset to stream
  stl/inc/bitset
Labels: performance

#4819 Use `requires`-clauses for `pair` and `tuple` since C++20
  stl/inc/expected
  stl/inc/tuple
  stl/inc/utility
Labels: enhancement

#4827 `<generator>`: Revert unnecessary ADL firewall for `_Gen_promise_base`
  stl/inc/generator
  tests/std/tests/P2502R2_generator_promise/test.cpp
Labels: enhancement, generator

#4844 Fix `filesystem::weakly_canonical()` on Win11 24H2
  stl/inc/xfilesystem_abi.h
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: bug, high priority, filesystem

#4857 Temporarily restore support for Win7 / Server 2008 R2
  stl/CMakeLists.txt
  stl/inc/xatomic_wait.h
  stl/inc/yvals_core.h
  stl/msbuild/stl_atomic_wait/msvcp_atomic_wait.settings.targets
  stl/src/atomic_wait.cpp
  stl/src/awint.hpp
  stl/src/ppltasks.cpp
  stl/src/winapisupp.cpp
  stl/src/xtime.cpp
  tests/std/test.lst
  tests/std/tests/P1135R6_atomic_wait_win7/env.lst
  tests/std/tests/P1135R6_atomic_wait_win7/test.cpp
Labels: performance

#4867 Status Chart: Weekly updates
  index.html
  package-lock.json
  package.json
  src/weekly_table.mts
Labels: documentation, uncharted

#4870 Improve ARM64 atomics for Clang
  stl/inc/atomic
  stl/inc/xatomic.h
Labels: performance, ARM64
