Repository microsoft/STL, pull requests merged in 2024-01, with the labels that each got.

#4294 Fix an issue in the special snowflake windows version of the STL
  stl/inc/xthreads.h
Labels: bug, high priority

#4301 Drop `#pragma detect_mismatch` for `mutex` size
  stl/inc/xthreads.h
Labels: bug, high priority

#4264 Make join_view and join_with_view iterators default-constructible (the forgotten part of P2770R0)
  stl/inc/ranges
  tests/libcxx/expected_results.txt
  tests/std/tests/P0896R4_views_join/test.cpp
  tests/std/tests/P2441R2_views_join_with/test.cpp
Labels: bug, ranges

#4270 Partially analyze some `SKIPPED` libcxx tests
  tests/libcxx/expected_results.txt
Labels: test

#4272 Mark ASAN failures in libcxx
  tests/libcxx/expected_results.txt
Labels: test, ASAN

#4287 `<atomic>`: Add missing `atomic& operator=(const atomic&) volatile = delete;` overload
  stl/inc/atomic
  tests/libcxx/expected_results.txt
Labels: bug

#4293 Update yvals_core.h
  stl/inc/yvals_core.h
Labels: enhancement

#4295 Enable STL-ASAN-CI on PRs
  azure-devops/asan-pipeline.yml
Labels: infrastructure

#4299 Updated working draft revision to N4971
  README.md
Labels: documentation

#4303 Toolset update: Jan 2024 Patch Tuesday
  azure-devops/config.yml
Labels: infrastructure

#4198 Implement P2510R3: Formatting Pointers
  stl/inc/format
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/std/test.lst
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
  tests/std/tests/P2510R3_text_formatting_pointers/env.lst
  tests/std/tests/P2510R3_text_formatting_pointers/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: format, cxx26

#4260 `<numeric>`: switch `transform_reduce` from direct list initialization to copy non-list initialization
  stl/inc/execution
  tests/std/tests/P0024R2_parallel_algorithms_transform_reduce/test.cpp
Labels: bug

#4275 `<vector>`, `<string>`: Avoid dereferencing null (fancy) pointers when calling `_Seek_to`/`_Unwrapped` on or comparing `vector` and `basic_string`'s iterators
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/xstring
  tests/libcxx/expected_results.txt
  tests/std/test.lst
  tests/std/tests/GH_004275_seeking_fancy_iterators/env.lst
  tests/std/tests/GH_004275_seeking_fancy_iterators/test.cpp
Labels: bug

#4276 `<vector>`: Cast to the correct base type in `vector<bool, Alloc>::_Orphan_range_unlocked`
  stl/inc/vector
  tests/libcxx/expected_results.txt
Labels: bug

#4277 `<type_traits>`: Workaround for DevCom-10543093 (ICE with some uses of pointers to data members)
  stl/inc/type_traits
  tests/libcxx/expected_results.txt
Labels: bug

#4283 `<chrono>`: Fix `formatter` ignoring dynamically provided width
  stl/inc/chrono
  tests/std/test.lst
  tests/std/tests/GH_004201_chrono_formatter/env.lst
  tests/std/tests/GH_004201_chrono_formatter/test.cpp
Labels: bug, format, chrono

#4285 Mitigate non-conformance of extensions of non-reserved names by the `push_macro`/`pop_macro` mechanism
  stl/inc/exception
  stl/inc/istream
  stl/inc/iterator
  stl/inc/ostream
  stl/inc/random
  stl/inc/typeindex
  stl/inc/typeinfo
  stl/inc/yvals_core.h
  tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp
Labels: bug

#4288 All atomic exchanges with _Api_level should be acq_rel
  stl/src/atomic_wait.cpp
Labels: performance

#4290 `<memory>`: Fix constraints of `shared_ptr`'s constructors when the involved pointer type would be invalid
  stl/inc/memory
  tests/libcxx/expected_results.txt
Labels: enhancement

#4304 `<xcharconv_ryu.h>`: Fix `__ryu_shiftright128` for ARM64
  stl/inc/xcharconv_ryu.h
Labels: bug, ARM64

#3896 [WIP] Implementation of <flat_map>
  stl/CMakeLists.txt
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/flat_map
  stl/inc/header-units.json
  stl/inc/yvals_core.h
  stl/modules/std.ixx
  tests/std/include/test_header_units_and_modules.hpp
  tests/std/test.lst
  tests/std/tests/P0429R9_flat_map/env.lst
  tests/std/tests/P0429R9_flat_map/test.cpp
Labels: cxx23, flat_meow

#4312 Status Chart: Weekly updates
  index.html
  package-lock.json
  package.json
  src/weekly_table.ts
Labels: documentation, uncharted

#4315 `<flat_map>`: Remove `zip_view` dependency and other cleanups
  stl/inc/flat_map
  tests/std/tests/P0429R9_flat_map/env.lst
  tests/std/tests/P0429R9_flat_map/test.cpp
Labels: flat_meow

#4309 Minor test improvements
  tests/libcxx/expected_results.txt
  tests/utils/stl/util.py
Labels: test

#4323 Report as UNRESOLVED when exception is thrown in `execute`
  tests/utils/stl/test/format.py
Labels: infrastructure, test

#4255 `<ranges>`: Fix truncation warnings and improve overflow check for `repeat_view`
  stl/inc/ranges
  tests/libcxx/expected_results.txt
  tests/std/tests/P2474R2_views_repeat/test.cpp
  tests/std/tests/P2474R2_views_repeat_death/test.cpp
Labels: bug, ranges

#4221 `<atomic>`: ADL-proof implementation of `atomic` and `atomic_ref`
  stl/inc/atomic
  tests/std/tests/P0019R8_atomic_ref/test.cpp
  tests/std/tests/P1135R6_atomic_wait/test.cpp
Labels: bug

#4256 ADL-proof implementation of [alg.modifying.operations]
  stl/inc/algorithm
  stl/inc/execution
  stl/inc/xutility
  tests/std/tests/GH_001596_adl_proof_algorithms/test.compile.pass.cpp
  tests/std/tests/P2538R1_adl_proof_std_projected/test.compile.pass.cpp
Labels: bug

#4258 ADL-proof container operations for iterator pairs and comparators
  stl/inc/deque
  stl/inc/forward_list
  stl/inc/list
  stl/inc/vector
  stl/inc/xhash
  stl/inc/xmemory
  stl/inc/xstring
  stl/inc/xtree
  tests/libcxx/expected_results.txt
  tests/std/tests/VSO_0000000_instantiate_containers/test.compile.pass.cpp
Labels: bug

#4311 Adjusted behavior of filesystem::is_empty and filesystem::directory_iterator to work with empty volumes
  stl/inc/filesystem
Labels: bug, filesystem

#4318 `<type_traits>`: Make `is_nothrow_convertible` a class template and ADL-proof
  stl/inc/type_traits
  tests/std/tests/P0758R1_is_nothrow_convertible/test.compile.pass.cpp
Labels: bug

#4313 Support instrumenting the STL with ASan
  CMakeLists.txt
  azure-devops/asan-pipeline.yml
  azure-devops/cmake-configure-build.yml
  azure-devops/native-build-test.yml
  stl/CMakeLists.txt
  tests/libcxx/lit.site.cfg.in
  tests/libcxx/usual_matrix.lst
  tests/std/include/force_include.hpp
  tests/std/include/vso1913897.hpp
  tests/std/tests/GH_002030_asan_annotate_string/env.lst
  tests/std/tests/GH_002030_asan_annotate_vector/env.lst
  tests/utils/stl/test/tests.py
Labels: infrastructure, test, ASAN

#4326 Merge `main` to `feature/flat_set`
  CMakeLists.txt
  azure-devops/asan-pipeline.yml
  azure-devops/cmake-configure-build.yml
  azure-devops/native-build-test.yml
  stl/CMakeLists.txt
  stl/inc/algorithm
  stl/inc/atomic
  stl/inc/deque
  stl/inc/execution
  stl/inc/filesystem
  stl/inc/forward_list
  stl/inc/list
  stl/inc/ranges
  stl/inc/type_traits
  stl/inc/vector
  stl/inc/xhash
  stl/inc/xmemory
  stl/inc/xstring
  stl/inc/xtree
  stl/inc/xutility
  tests/libcxx/expected_results.txt
  tests/libcxx/lit.site.cfg.in
  tests/libcxx/usual_matrix.lst
  tests/std/include/force_include.hpp
  tests/std/include/vso1913897.hpp
  tests/std/tests/GH_001596_adl_proof_algorithms/test.compile.pass.cpp
  tests/std/tests/GH_002030_asan_annotate_string/env.lst
  tests/std/tests/GH_002030_asan_annotate_vector/env.lst
  tests/std/tests/P0019R8_atomic_ref/test.cpp
  tests/std/tests/P0758R1_is_nothrow_convertible/test.compile.pass.cpp
  tests/std/tests/P1135R6_atomic_wait/test.cpp
  tests/std/tests/P2474R2_views_repeat/test.cpp
  tests/std/tests/P2474R2_views_repeat_death/test.cpp
  tests/std/tests/P2538R1_adl_proof_std_projected/test.compile.pass.cpp
  tests/std/tests/VSO_0000000_instantiate_containers/test.compile.pass.cpp
  tests/utils/stl/test/format.py
  tests/utils/stl/test/tests.py
  tests/utils/stl/util.py
Labels: uncharted, flat_meow

#4330 `<xcharconv_ryu.h>`: `__umulh` is already an intrinsic for `_M_HYBRID_X86_ARM64`
  stl/inc/xcharconv_ryu.h
Labels: enhancement, ARM64

#4233 `iter_value_t<I>` should always use direct-initialization
  stl/inc/algorithm
  stl/inc/numeric
  stl/inc/random
  tests/std/test.lst
  tests/std/tests/Dev11_0253803_debug_pointer/test.cpp
  tests/std/tests/GH_004109_iter_value_t_direct_initialization/env.lst
  tests/std/tests/GH_004109_iter_value_t_direct_initialization/test.compile.pass.cpp
  tests/std/tests/P0896R4_common_iterator/test.cpp
Labels: bug, ranges

#4239 `<sstream>`: Don't swap `basic_stringbuf`s in move assignment and allocator-extended construction
  stl/inc/sstream
  tests/libcxx/expected_results.txt
  tests/std/tests/GH_001858_iostream_exception/test.cpp
  tests/std/tests/P0408R7_efficient_access_to_stringbuf_buffer/test.cpp
Labels: bug

#4271 `<expected>`: Make copy/move assignment operators of `expected` propagate triviality
  stl/inc/expected
  tests/std/tests/P0323R12_expected/test.cpp
Labels: enhancement

#4284 `<random>`: Deprecate TR1 components in the `std` namespace
  stl/inc/random
  stl/inc/yvals_core.h
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
  tests/tr1/tests/random1/test.cpp
  tests/tr1/tests/random6/test.cpp
Labels: enhancement

#4327 fix formatting floating-point values without type and precision provided
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Labels: bug, format

#4334 Make implicit conversion to `bool` ADL-proof (except for views)
  stl/inc/expected
  stl/inc/optional
  stl/inc/type_traits
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/GH_000140_adl_proof_comparison/env.lst
  tests/std/tests/GH_000140_adl_proof_comparison/test.compile.pass.cpp
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
Labels: bug

#4335 Run CTest tests serially to avoid oversubscribing cores
  tests/CMakeLists.txt
Labels: test

#4336 Clarify some ASan-related libcxx FAILs
  tests/libcxx/expected_results.txt
Labels: test, ASAN

#4339 Revert "Make the constexpr mutex constructor opt-in (#4000)"
  stl/inc/mutex
  tests/std/tests/VSO_0226079_mutex/env.lst
  tests/std/tests/VSO_0226079_mutex/test.cpp
Labels: enhancement

#4342 `generator` WIP
  stl/CMakeLists.txt
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/generator
  stl/inc/header-units.json
  stl/inc/ranges
  stl/inc/yvals_core.h
  stl/modules/std.ixx
  tests/std/include/test_header_units_and_modules.hpp
  tests/std/test.lst
  tests/std/tests/P1502R1_standard_library_header_units/importable_cxx_library_headers.jsonc
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
  tests/std/tests/P2502R2_generator/env.lst
  tests/std/tests/P2502R2_generator/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tests/std/tests/include_each_header_alone_matrix.lst
Labels: cxx23, generator

#4341 ARM64 test improvements
  tests/std/tests/Dev09_056375_locale_cleanup/custombuild.pl
  tests/std/tests/GH_002030_asan_annotate_string/notarget.lst
  tests/std/tests/GH_002030_asan_annotate_vector/notarget.lst
  tests/std/tests/P0226R1_math_special_functions/test.cpp
  tests/std/tests/P0881R7_stacktrace/test.cpp
  tests/std/tests/usual_17_matrix.lst
  tests/std/tests/usual_20_matrix.lst
  tests/std/tests/usual_latest_matrix.lst
  tests/std/tests/usual_matrix.lst
Labels: test, ARM64

#4344 `<flat_map>` Fix compile errors
  stl/inc/flat_map
  tests/std/tests/P0429R9_flat_map/env.lst
  tests/std/tests/P0429R9_flat_map/test.cpp
Labels: bug, flat_meow

#3960 SSE2 vectorization for `bitset::to_string`
  stl/inc/bitset
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#4091 `<deque>`: Make `deque::shrink_to_fit` never relocate elements
  stl/inc/deque
  tests/std/tests/Dev10_860421_deque_push_back_pop_front/test.cpp
  tests/std/tests/VSO_0000000_allocator_propagation/test.cpp
Labels: bug

#4136 `<filesystem>`: Preallocate memory in `path::operator/`
  stl/inc/filesystem
  tests/std/tests/P0218R1_filesystem/test.cpp
Labels: performance, filesystem

#4274 `<memory>`: Add different control block types for `allocate_shared_for_overwrite`
  stl/debugger/STL.natvis
  stl/inc/memory
  tests/libcxx/expected_results.txt
Labels: bug

#4347 ADL-proof implementation of [alg.merge], [alg.set.operations], [alg.heap.operations], and [alg.permutation.generators]
  stl/inc/algorithm
  stl/inc/execution
  stl/inc/xmemory
  stl/inc/xutility
  tests/std/tests/GH_001596_adl_proof_algorithms/test.compile.pass.cpp
  tests/std/tests/P2538R1_adl_proof_std_projected/test.compile.pass.cpp
Labels: bug

#4351 `<generator>`: Mark strengthened noexcept (plus tiny drive-by changes)
  stl/inc/generator
Labels: bug, generator
