Repository microsoft/STL, pull requests merged in 2024-02, with the labels that each got.

#4296 Enable `__cpp_lib_concepts` for EDG, part 1
  stl/inc/memory
  stl/inc/ranges
  stl/inc/tuple
  stl/inc/utility
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/tests/GH_002558_format_presetPadding/env.lst
  tests/std/tests/P0009R18_mdspan_default_accessor/test.cpp
  tests/std/tests/P0323R12_expected/test.cpp
  tests/std/tests/P0645R10_text_formatting_legacy_text_encoding/env.lst
  tests/std/tests/P0896R4_P1614R2_comparisons/test.cpp
  tests/std/tests/P0896R4_ranges_alg_equal/test.cpp
  tests/std/tests/P0896R4_ranges_alg_find_end/test.cpp
  tests/std/tests/P0896R4_ranges_alg_mismatch/test.cpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
  tests/std/tests/P0896R4_views_common/test.cpp
  tests/std/tests/P0896R4_views_iota/test.cpp
  tests/std/tests/P0896R4_views_join/test.cpp
  tests/std/tests/P0896R4_views_single/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/std/tests/P1659R3_ranges_alg_ends_with/test.cpp
  tests/std/tests/P1659R3_ranges_alg_starts_with/test.cpp
  tests/std/tests/P2165R4_tuple_like_operations/test.compile.pass.cpp
  tests/std/tests/P2278R4_views_as_const/test.cpp
  tests/std/tests/P2286R8_text_formatting_escaping_legacy_text_encoding/env.lst
  tests/std/tests/P2322R6_ranges_alg_fold/test.cpp
  tests/std/tests/P2374R4_views_cartesian_product/test.cpp
  tests/std/tests/P2441R2_views_join_with/test.cpp
  tests/std/tests/P2474R2_views_repeat/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tests/std/tests/concepts_20_matrix.lst
  tests/std/tests/concepts_latest_matrix.lst
  tests/std/tests/strict_concepts_20_matrix.lst
  tests/std/tests/strict_concepts_latest_matrix.lst
Labels: enhancement

#4355 Mark more libcxx tests as FAIL due to ASan oversized allocations
  tests/libcxx/expected_results.txt
Labels: test, ASan

#4356 Enable warnings for the benchmarks, and fix them
  benchmarks/CMakeLists.txt
  benchmarks/inc/udt.hpp
  benchmarks/inc/utility.hpp
  benchmarks/src/std/containers/sequences/vector.bool/copy/test.cpp
  benchmarks/src/std/containers/sequences/vector.bool/copy_n/test.cpp
  benchmarks/src/std/containers/sequences/vector.bool/move/test.cpp
Labels: test

#4361 Update yvals_core to February 2024
  stl/inc/yvals_core.h
Labels: enhancement

#4366 Use Python `backslashreplace` to avoid UNRESOLVED tests
  tests/utils/stl/util.py
Labels: test

#4358 `static operator()` for stateless functors
  stl/inc/__msvc_bit_utils.hpp
  stl/inc/__msvc_tzdb.hpp
  stl/inc/algorithm
  stl/inc/bitset
  stl/inc/compare
  stl/inc/concepts
  stl/inc/coroutine
  stl/inc/execution
  stl/inc/experimental/filesystem
  stl/inc/filesystem
  stl/inc/format
  stl/inc/memory
  stl/inc/memory_resource
  stl/inc/mutex
  stl/inc/numeric
  stl/inc/ranges
  stl/inc/regex
  stl/inc/stacktrace
  stl/inc/system_error
  stl/inc/thread
  stl/inc/type_traits
  stl/inc/typeindex
  stl/inc/variant
  stl/inc/vector
  stl/inc/xstring
  stl/inc/xutility
  stl/inc/yvals_core.h
Labels: performance

#4364 Test coarse-grained `_HAS_CXXnn` instead of fine-grained `__cpp_lib_MEOW`
  stl/inc/__msvc_filebuf.hpp
  stl/inc/ostream
  stl/inc/print
  stl/inc/ranges
  tests/std/tests/Dev11_0000000_tuple_cat/test.cpp
  tests/std/tests/GH_000545_include_compare/test_stacktrace.cpp
  tests/std/tests/GH_000690_overaligned_function/test.cpp
  tests/std/tests/GH_001411_core_headers/test.cpp
  tests/std/tests/P0769R2_shift_left_shift_right/test.cpp
Labels: enhancement

#4365 Add permissions to the Update Status Chart action
  .github/workflows/update-status-chart.yml
Labels: infrastructure

#3928 vectorize `min/max_element` using SSE4.1 for floats
  benchmarks/CMakeLists.txt
  benchmarks/src/minmax_element.cpp
  stl/inc/algorithm
  stl/inc/xutility
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#4386 `<flat_map>`: Re-enable `/permissive` with miscellaneous fixes and test coverage
  stl/inc/flat_map
  tests/std/include/test_header_units_and_modules.hpp
  tests/std/tests/P0429R9_flat_map/env.lst
  tests/std/tests/P0429R9_flat_map/test.cpp
Labels: bug, flat_meow

#4375 Export VCRuntime entities properly
  stl/inc/exception
  stl/inc/new
  stl/inc/typeinfo
  stl/modules/std.ixx
  tests/std/include/test_header_units_and_modules.hpp
Labels: bug, modules

#4372 Fix rethrowing the caught exception from streambuf
  stl/inc/ostream
  tests/std/tests/GH_001858_iostream_exception/test.cpp
Labels: bug

#4373 Properly destroy `vector<shared_ptr<uninstantiable>>`
  stl/inc/vector
  stl/inc/xmemory
  tests/libcxx/expected_results.txt
  tests/std/tests/VSO_0000000_instantiate_containers/test.compile.pass.cpp
Labels: bug

#4374 ADL-proof implementation of uninitialized memory algorithms
  stl/inc/memory
  stl/inc/new
  stl/inc/xmemory
  tests/std/tests/GH_001596_adl_proof_algorithms/test.compile.pass.cpp
  tests/std/tests/P2538R1_adl_proof_std_projected/test.compile.pass.cpp
Labels: bug

#4379 `<functional>`: Make `default_searcher` ADL-proof
  stl/inc/functional
  tests/std/tests/P0220R1_searchers/test.cpp
Labels: bug

#4382 Return after SSE2 code
  stl/src/vector_algorithms.cpp
Labels: performance

#4383 README.md: allow htmlLabels inside flowchart
  README.md
Labels: documentation

#4392 Toolset update: VS 2022 17.10 Preview 1
  CMakeLists.txt
  README.md
  azure-devops/config.yml
  azure-devops/cross-build.yml
  azure-devops/native-build-test.yml
  azure-devops/provision-image.ps1
  azure-devops/run-tests.yml
  benchmarks/CMakeLists.txt
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/__msvc_iter_core.hpp
  stl/inc/atomic
  stl/inc/chrono
  stl/inc/exception
  stl/inc/format
  stl/inc/memory
  stl/inc/ranges
  stl/inc/type_traits
  stl/inc/variant
  stl/inc/vector
  stl/inc/xlocnum
  stl/inc/xmemory
  stl/inc/xstring
  stl/inc/xutility
  stl/inc/yvals_core.h
  stl/modules/std.ixx
  stl/src/vector_algorithms.cpp
  tests/libcxx/expected_results.txt
  tests/std/include/test_header_units_and_modules.hpp
  tests/std/tests/GH_000639_nvcc_include_all/env.lst
  tests/std/tests/P0009R18_mdspan_mdspan/test.cpp
  tests/std/tests/P0339R6_polymorphic_allocator/test.cpp
  tests/std/tests/P0660R10_jthread_and_cv_any/test.cpp
  tests/std/tests/P0896R4_views_iota/test.cpp
  tests/std/tests/P0896R4_views_split/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/std/tests/P1208R6_source_location/test.cpp
  tests/std/tests/P2273R3_constexpr_unique_ptr/test.compile.pass.cpp
  tests/std/tests/P2278R4_views_as_const/test.cpp
  tests/std/tests/P2374R4_views_cartesian_product_recommended_practices/test.compile.pass.cpp
  tests/std/tests/P2465R3_standard_library_modules/test3.cpp
  tests/std/tests/P2465R3_standard_library_modules/test4.cpp
  tests/utils/stl/util.py
  tools/CMakeLists.txt
  tools/format/CMakeLists.txt
  tools/validate/CMakeLists.txt
Labels: infrastructure

#4387 Add `find` / `count` benchmark
  benchmarks/CMakeLists.txt
  benchmarks/src/find_and_count.cpp
Labels: test

#4389 `<ranges>`: Make views ADL-proof
  stl/inc/ranges
  tests/std/test.lst
  tests/std/tests/GH_000140_adl_proof_views/env.lst
  tests/std/tests/GH_000140_adl_proof_views/test.compile.pass.cpp
Labels: bug, ranges

#4390 Make `~mutex` trivial
  stl/inc/mutex
  stl/inc/xthreads.h
  stl/src/mutex.cpp
Labels: performance

#4391 ADL-proof implementation of numeric algorithms
  stl/inc/execution
  stl/inc/numeric
  stl/inc/vector
  stl/inc/xmemory
  tests/std/tests/GH_001596_adl_proof_algorithms/test.compile.pass.cpp
Labels: bug

#3655 `std::atomic<std::shared_ptr>::wait` should compare control blocks
  stl/inc/memory
  tests/std/include/test_atomic_wait.hpp
Labels: bug

#4395 Handle paths case-insensitively when running tests
  tests/utils/stl/test/format.py
Labels: test

#4401 `vector_algorithms.cpp`, `*minmax*`: invert the condition to improve `*_element` cases a bit more
  stl/src/vector_algorithms.cpp
Labels: performance

#4402 ADL-proof implementation of range verifying and functor passing components that involve arbitrary types
  stl/inc/mutex
  stl/inc/span
  stl/inc/xutility
  tests/std/tests/Dev11_1114006_condition_variable_pred/test.cpp
  tests/std/tests/P0122R7_span/test.cpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
Labels: bug

#4403 `<memory>`: ADL-proof implementation of `shared_ptr` creation functions and atomic smart pointers
  stl/inc/memory
  stl/inc/xmemory
  tests/std/tests/Dev10_445289_make_shared/test.cpp
  tests/std/tests/P0718R2_atomic_smart_ptrs/test.cpp
Labels: bug

#4405 Unify stringification macros
  stl/inc/use_ansi.h
  stl/inc/yvals.h
  stl/inc/yvals_core.h
Labels: enhancement

#4406 Equality for unordered_set and unordered_map should be based on equality of elements
  stl/inc/hash_map
  stl/inc/hash_set
  stl/inc/unordered_map
  stl/inc/unordered_set
  stl/inc/xhash
  tests/std/test.lst
  tests/std/tests/GH_004388_unordered_meow_operator_equal/env.lst
  tests/std/tests/GH_004388_unordered_meow_operator_equal/test.cpp
Labels: bug

#4407 `<new>`: `SRWLOCK` to protect the `new` handler instead of an indexed `CRITICAL_SECTION`
  stl/inc/yvals.h
  stl/src/stdhndlr.cpp
Labels: performance

#4408 `xnotify.cpp`: `SRWLOCK` to protect the at-thread-exit data instead of an indexed `CRITICAL_SECTION`
  stl/inc/yvals.h
  stl/src/xlock.cpp
  stl/src/xnotify.cpp
Labels: performance

#4410 <xutility>, <algorithm>: Add top level const on pointer parameters
  stl/inc/algorithm
  stl/inc/xutility
Labels: enhancement

#4416 `<ranges>`: Fix `zip_transform_view` by not using possibly ill-formed static data member
  stl/inc/ranges
  tests/std/tests/P2321R2_views_zip_transform/test.cpp
Labels: bug, ranges

#4420 Modules workaround for `views::pairwise_transform`
  stl/inc/ranges
  tests/std/include/test_header_units_and_modules.hpp
Labels: bug, modules

#4399 Status Chart: Remove Average Age, update timeframes
  built/status_chart.mjs
  index.html
  package-lock.json
  package.json
  src/daily_table.ts
  src/status_chart.ts
  src/weekly_table.ts
  src_gather/gather_stats.ts
Labels: documentation

#4419 `<execution>`, `<numeric>`: Change improper direct-initialization to copy-initialization in C++17 numeric algorithms
  stl/inc/execution
  stl/inc/numeric
  tests/std/test.lst
  tests/std/tests/GH_004129_conversion_in_new_numeric_algorithms/env.lst
  tests/std/tests/GH_004129_conversion_in_new_numeric_algorithms/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_exclusive_scan/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_inclusive_scan/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_transform_exclusive_scan/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_transform_inclusive_scan/test.cpp
Labels: bug

#4421 Fix the incorrect width that occurred when formatting a floating number in the locale specific form
  stl/inc/format
  tests/libcxx/expected_results.txt
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Labels: bug, format

#4426 Silence warning C4324: structure was padded due to alignment specifier
  stl/inc/execution
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/tests/P2374R4_views_cartesian_product/test.cpp
Labels: bug, ranges

#4422 AVX2 vectorization for very large bitsets
  benchmarks/src/bitset_to_string.cpp
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance
