Repository microsoft/STL, pull requests merged in 2024-03, with the labels that each got.

#4430 ADL-proof implementation of `function`, `move_only_function`, `packaged_task`, `promise`, and `optional`
  stl/inc/functional
  stl/inc/future
  stl/inc/memory
  stl/inc/optional
  stl/inc/xmemory
  tests/libcxx/expected_results.txt
  tests/std/test.lst
  tests/std/tests/GH_000140_adl_proof_construction/env.lst
  tests/std/tests/GH_000140_adl_proof_construction/test.compile.pass.cpp
  tests/std/tests/GH_001596_adl_proof_algorithms/test.compile.pass.cpp
Labels: bug

#4435 Tools: add a script to download Unicode data files, and rename `grapheme_break_property_data_gen.py` to `unicode_properties_data_gen.py`
  stl/inc/__msvc_format_ucd_tables.hpp
  tools/unicode_properties_parse/download_unicode_data_files.py
  tools/unicode_properties_parse/grapheme_break_test_data_gen.py
  tools/unicode_properties_parse/unicode_properties_data_gen.py
Labels: enhancement, format

#4437 Enforce `std::time_base::mdy` for "C" locale
  stl/src/xdateord.cpp
Labels: bug

#4447 `<random>`: Implement Mandates for `seed_seq::generate`
  stl/inc/random
Labels: bug

#4452 Test updates for LLVM18
  tests/std/include/test_format_support.hpp
  tests/std/tests/GH_000431_equal_family/test.cpp
  tests/std/tests/GH_000935_complex_numerical_accuracy/test.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
  tests/std/tests/P2093R14_formatted_output/test.cpp
  tests/std/tests/floating_point_model_matrix.lst
Labels: test

#4432 `<xmemory>`: Unify overloads of `_Allocate` and `_Deallocate` with `if constexpr`
  stl/inc/xmemory
Labels: enhancement

#4446 Move `_Width_estimate_intervals_v2` to `__msvc_format_ucd_tables.hpp`
  stl/inc/__msvc_format_ucd_tables.hpp
  stl/inc/format
  tools/unicode_properties_parse/format_width_estimate_intervals.py
  tools/unicode_properties_parse/unicode_properties_data_gen.py
Labels: enhancement, format

#4439 Comment cleanups
  stl/inc/compare
  stl/inc/concepts
  stl/inc/ranges
  stl/inc/tuple
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/tests/GH_000431_equal_memcmp_is_safe/test.compile.pass.cpp
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P0220R1_optional/test.cpp
  tests/std/tests/P0896R4_ranges_algorithm_machinery/test.compile.pass.cpp
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
Labels: enhancement

#4440 Tests: Rename the strict matrices
  tests/std/tests/GH_000140_adl_proof_views/env.lst
  tests/std/tests/P0323R12_expected/env.lst
  tests/std/tests/P0896R4_common_iterator/env.lst
  tests/std/tests/P0896R4_views_drop/env.lst
  tests/std/tests/P0896R4_views_elements/env.lst
  tests/std/tests/P0896R4_views_filter/env.lst
  tests/std/tests/P0896R4_views_filter_death/env.lst
  tests/std/tests/P0896R4_views_filter_iterator/env.lst
  tests/std/tests/P0896R4_views_join/env.lst
  tests/std/tests/P0896R4_views_lazy_split/env.lst
  tests/std/tests/P0896R4_views_split/env.lst
  tests/std/tests/P0896R4_views_take/env.lst
  tests/std/tests/P0896R4_views_transform/env.lst
  tests/std/tests/P1899R3_views_stride/env.lst
  tests/std/tests/P2164R9_views_enumerate/env.lst
  tests/std/tests/P2165R4_tuple_like_common_reference/env.lst
  tests/std/tests/P2165R4_tuple_like_relational_operators/env.lst
  tests/std/tests/P2278R4_basic_const_iterator/env.lst
  tests/std/tests/P2321R2_views_adjacent/env.lst
  tests/std/tests/P2321R2_views_adjacent_transform/env.lst
  tests/std/tests/P2321R2_views_zip/env.lst
  tests/std/tests/P2321R2_views_zip_transform/env.lst
  tests/std/tests/P2374R4_views_cartesian_product/env.lst
  tests/std/tests/P2374R4_views_cartesian_product_death/env.lst
  tests/std/tests/P2374R4_views_cartesian_product_recommended_practices/env.lst
  tests/std/tests/P2387R3_pipe_support_for_user_defined_range_adaptors/env.lst
  tests/std/tests/P2441R2_views_join_with/env.lst
  tests/std/tests/P2442R1_views_chunk/env.lst
  tests/std/tests/P2442R1_views_chunk_death/env.lst
  tests/std/tests/strict_20_matrix.lst
  tests/std/tests/strict_latest_matrix.lst
Labels: test

#4441 Enable more test coverage for warning C4668 ('MEOW' is not defined as a preprocessor macro)
  stl/inc/climits
  tests/std/include/test_death.hpp
  tests/std/include/test_thread_support.hpp
  tests/std/tests/Dev08_563686_ostream/test.cpp
  tests/std/tests/Dev09_056375_locale_cleanup/test.cpp
  tests/std/tests/Dev09_056375_locale_cleanup/testdll.cpp
  tests/std/tests/Dev11_0493504_error_category_lifetime/test.cpp
  tests/std/tests/GH_002431_byte_range_find_with_unreachable_sentinel/test.cpp
  tests/std/tests/P2093R14_formatted_output/test.cpp
  tests/std/tests/VSO_0000000_exception_ptr_rethrow_seh/test.cpp
  tests/std/tests/VSO_0104705_throwing_copy_in_current_exception_seh/test.cpp
  tests/std/tests/VSO_0121275_filesystem_canonical_should_handle_many_double_dots/test.cpp
  tests/std/tests/VSO_0226079_mutex/test.cpp
  tests/std/tests/VSO_0744055_atomic_load_8_bytes_readonly/test.cpp
  tests/std/tests/prefix.lst
  tests/tr1/include/tdefs.h
  tests/tr1/prefix.lst
  tests/tr1/tests/regex2/test.cpp
Labels: test

#4442 Tests: Extract `is_permissive.hpp`
  tests/std/include/is_permissive.hpp
  tests/std/include/range_algorithm_support.hpp
  tests/std/include/test_mdspan_support.hpp
  tests/std/tests/P0645R10_text_formatting_args/test.cpp
  tests/std/tests/P0896R4_ranges_algorithm_machinery/test.compile.pass.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/std/tests/P2136R3_invoke_r/test.cpp
  tests/std/tests/VSO_0000000_type_traits/test.cpp
Labels: test

#4443 Expand old test coverage
  benchmarks/inc/utility.hpp
  benchmarks/inc/xoshiro.hpp
  tests/std/tests/Dev09_172497_tr1_mem_fn_const_correctness/test.cpp
  tests/std/tests/Dev09_174589_tr1_function_storing_pmf_called_with_reference_or_pointer/test.cpp
  tests/std/tests/P0088R3_variant/test.cpp
Labels: test

#4444 Various cleanups: product code
  stl/inc/__msvc_bit_utils.hpp
  stl/inc/algorithm
  stl/inc/xutility
  stl/inc/yvals_core.h
Labels: enhancement

#4445 Various cleanups: `ppltasks.cpp`
  stl/src/ppltasks.cpp
Labels: enhancement

#4450 Fix vectorized `ranges::find` with `unreachable_sentinel` to properly mask the beginning and handle unaligned pointers
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: bug, ranges

#4451 `<regex>`: Limit capture groups
  stl/inc/regex
Labels: enhancement

#4464 `<generator>`: Make nested types of `generator` ADL-proof
  stl/inc/generator
  stl/inc/ranges
  tests/std/tests/P2502R2_generator/test.cpp
Labels: bug, generator

#4471 `<generator>`: Various fixes and cleanups
  stl/inc/coroutine
  stl/inc/generator
  tests/std/tests/P2502R2_generator/test.cpp
Labels: bug, generator

#4468 `<flat_map>`: Various cleanups and bug fixes
  stl/inc/flat_map
  tests/std/include/test_header_units_and_modules.hpp
  tests/std/tests/P0429R9_flat_map/test.cpp
Labels: bug, flat_meow

#4475 Toolset update: VS 2022 17.10 Preview 2, WinSDK 22621, CUDA 12.4.0
  CMakeLists.txt
  README.md
  azure-devops/config.yml
  azure-devops/provision-image.ps1
  stl/inc/memory
  stl/inc/ostream
  stl/inc/tuple
  stl/inc/utility
  stl/inc/xhash
  stl/inc/xlocale
  stl/inc/yvals_core.h
  tests/std/tests/GH_000639_nvcc_include_all/env.lst
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/VSO_0000000_allocator_propagation/test.cpp
Labels: infrastructure

#4438 Implement `formatter` specializations for `pair` and `tuple`
  docs/cgmanifest.json
  stl/inc/__msvc_formatter.hpp
  stl/inc/format
  stl/inc/vector
  tests/libcxx/expected_results.txt
  tests/std/test.lst
  tests/std/tests/P2286R8_text_formatting_formattable/test.compile.pass.cpp
  tests/std/tests/P2286R8_text_formatting_tuple/env.lst
  tests/std/tests/P2286R8_text_formatting_tuple/test.cpp
Labels: format, cxx23

#4457 Wait on condition variables independently on system time
  stl/CMakeLists.txt
  stl/inc/__msvc_chrono.hpp
  stl/inc/__msvc_threads_core.hpp
  stl/inc/condition_variable
  stl/inc/header-units.json
  stl/inc/mutex
  stl/inc/thread
  stl/inc/xthreads.h
  stl/src/cond.cpp
  stl/src/mutex.cpp
  stl/src/primitives.hpp
  stl/src/sharedmutex.cpp
  tests/std/tests/GH_001411_core_headers/test.cpp
Labels: bug

#4459 `<format>`: Always enable compile-time format string checking for `wchar_t`
  stl/inc/format
Labels: bug, format

#4461 `<format>`: Conditionally emit special diagnostic message for lack of `const`
  stl/inc/format
Labels: enhancement, format

#4465 `<ranges>`: Drop one superfluous `_Fake_copy_init<bool>` where the argument type is always `bool`
  stl/inc/ranges
Labels: throughput

#4467 <yvals_core.h> Update _MSVC_STL_UPDATE to March 2024
  stl/inc/yvals_core.h
Labels: enhancement

#4469 `download_unicode_data_files.py`: Select latest or a specific version
  tools/unicode_properties_parse/download_unicode_data_files.py
Labels: enhancement, format

#4470 Delete `std::experimental::erase/erase_if`
  stl/CMakeLists.txt
  stl/inc/__msvc_all_public_headers.hpp
  stl/inc/experimental/deque
  stl/inc/experimental/forward_list
  stl/inc/experimental/list
  stl/inc/experimental/map
  stl/inc/experimental/set
  stl/inc/experimental/string
  stl/inc/experimental/unordered_map
  stl/inc/experimental/unordered_set
  stl/inc/experimental/vector
  stl/inc/yvals_core.h
  tests/std/tests/Dev11_0000000_user_defined_literals/test.cpp
  tests/std/tests/VSO_0000000_instantiate_containers/test.compile.pass.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
  tests/std/tests/include_each_header_alone_matrix.lst
Labels: enhancement

#4474 Initialize pointer in `basic_string::_Allocate_for_capacity`
  stl/inc/xstring
Labels: bug

#4476 Update GitHub workflows
  .github/workflows/assign-new-prs.yml
  .github/workflows/move-ready-for-review-prs.yml
  .github/workflows/move-work-in-progress-prs.yml
  .github/workflows/update-status-chart.yml
Labels: infrastructure

#4460 Status Chart: Modernize modules, chart.js 4.4.2
  .github/workflows/compile-typescript.yml
  .gitignore
  README.md
  index.html
  package-lock.json
  package.json
  src/daily_table.mts
  src/monthly_table.mts
  src/status_chart.mts
  src/tsconfig.json
  src/weekly_table.mts
  src_gather/gather_stats.mts
  src_gather/tsconfig.json
  tsconfig.universal.json
Labels: documentation

#4478 Fix `atomic_ref<16 bytes>::is_always_lock_free`
  stl/inc/atomic
  tests/std/tests/P0019R8_atomic_ref/env.lst
  tests/std/tests/P0019R8_atomic_ref/test.cpp
Labels: bug

#4486 Remove attempt on unsized find vectorization...
  benchmarks/src/find_and_count.cpp
  stl/inc/xutility
  stl/src/vector_algorithms.cpp
Labels: bug, ASan

#4487 Standard Library Modules: Fix warning C4365 (signed/unsigned mismatch) with `/ZI`
  stl/inc/yvals.h
Labels: bug, modules

#4488 `<tuple>`, `<utility>`: Make `tuple`-related functions ADL-proof
  stl/inc/tuple
  stl/inc/utility
  tests/std/tests/Dev11_0000000_tuple_cat/test.cpp
Labels: bug

#4489 `<format>`: Make non-Standard constructors of `basic_format_arg::handle` and `basic_format_context` private
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp
Labels: enhancement, format

#4431 Auto vectorize `replace_copy`, `replace_copy_if`
  benchmarks/CMakeLists.txt
  benchmarks/src/replace.cpp
  stl/inc/algorithm
Labels: performance

#4466 Vectorize `find_first_of` for 8 and 16 bit elements with SSE4.2 `pcmpestri`
  benchmarks/CMakeLists.txt
  benchmarks/src/find_first_of.cpp
  stl/inc/algorithm
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#4490 `vector_algorithms.cpp`: clearer control flow in `bitset::to_string`
  stl/src/vector_algorithms.cpp
Labels: enhancement

#4492 libcxx `stol.pass.cpp` is now passing for ASAN
  tests/libcxx/expected_results.txt
Labels: test, ASan

#4493 Add binary flag to xiosbase class to correct place
  stl/inc/xiosbase
Labels: enhancement

#4534 `<generator>`: Test `generator::promise_type`
  stl/inc/generator
  tests/std/test.lst
  tests/std/tests/P2502R2_generator_promise/env.lst
  tests/std/tests/P2502R2_generator_promise/test.cpp
Labels: bug, test, generator

#4495 `mismatch` vectorization
  benchmarks/CMakeLists.txt
  benchmarks/src/mismatch.cpp
  stl/inc/algorithm
  stl/inc/xutility
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#4510 Implement LWG-3950 `std::basic_string_view` comparison operators are overspecified
  stl/inc/xstring
  tests/std/tests/P0220R1_string_view/test.cpp
Labels: LWG, spaceship

#4525 Implement LWG-4035 single_view should provide empty
  stl/inc/ranges
  tests/std/tests/P0896R4_views_single/test.cpp
Labels: LWG, ranges

#4526 Implement LWG-3919 `enumerate_view` may invoke UB for sized common non-forward underlying ranges
  stl/inc/ranges
  tests/std/tests/P2164R9_views_enumerate/test.cpp
Labels: LWG, ranges

#4527 Add an STL-wide suppression for C5246
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/GH_004477_mdspan_warning_5246/env.lst
  tests/std/tests/GH_004477_mdspan_warning_5246/test.compile.pass.cpp
Labels: bug

#4528 `<tuple>`: Make `std::make_from_tuple` SFINAE friendly
  stl/inc/tuple
  tests/std/test.lst
  tests/std/tests/LWG3528_make_from_tuple_impl/env.lst
  tests/std/tests/LWG3528_make_from_tuple_impl/test.compile.pass.cpp
Labels: enhancement

#4529 Implement LWG-4012 `common_view::begin`/`end` are missing the `simple-view` check
  stl/inc/ranges
  tests/std/tests/P0896R4_views_common/test.cpp
Labels: LWG, ranges

#4532 Implement P2875R4 Undeprecate `polymorphic_allocator::destroy`
  stl/inc/xpolymorphic_allocator.h
  stl/inc/yvals_core.h
  tests/std/tests/P0220R1_polymorphic_memory_resources/test.cpp
Labels: cxx26

#4538 `vector_algorithms.cpp`: Fix ARM64EC build break
  stl/src/vector_algorithms.cpp
Labels: bug, ARM64

#4535 `create-1es-hosted-pool.ps1`: Avoid `ConvertTo-SecureString`
  azure-devops/create-1es-hosted-pool.ps1
Labels: infrastructure
