Repository microsoft/STL, pull requests merged in 2024-10, with the labels that each got.

#4839 Vectorize `bitset` from string construction
  benchmarks/CMakeLists.txt
  benchmarks/src/bitset_from_string.cpp
  stl/inc/bitset
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#4917 Use AVX/AVX2 masks in `minmax_element` and `minmax` vectorization
  benchmarks/src/minmax_element.cpp
  stl/src/vector_algorithms.cpp
Labels: performance

#4934 Vectorize `basic_string::find_last_of`
  benchmarks/src/find_first_of.cpp
  stl/inc/__msvc_string_view.hpp
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#4946 `<future>`: Make `packaged_task` accept move-only functors
  stl/inc/functional
  stl/inc/future
  tests/std/tests/Dev10_561430_list_and_tree_leaks/test.cpp
  tests/std/tests/Dev11_0235721_async_and_packaged_task/test.cpp
  tests/std/tests/GH_000140_adl_proof_construction/test.compile.pass.cpp
  tests/std/tests/GH_002488_promise_not_default_constructible_types/test.cpp
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
Labels: bug

#4977 `<vector>`: More scope guards
  stl/inc/vector
  stl/inc/xmemory
Labels: enhancement

#4983 Refactoring around `tuple-like`, `pair-like`, and `subrange`
  stl/inc/__msvc_iter_core.hpp
  stl/inc/tuple
  stl/inc/utility
  stl/inc/xmemory
  stl/inc/xutility
Labels: enhancement

#4990 `<cmath>`, `<limits>`: Locally disable `-Wnan-infinity-disabled` for Clang
  stl/inc/cmath
  stl/inc/limits
  stl/inc/yvals_core.h
  tests/std/tests/VSO_0000000_vector_algorithms_floats/env.lst
Labels: enhancement

#4994 Update _MSVC_STL_UPDATE to October 2024
  stl/inc/yvals_core.h
Labels: enhancement

#5001 Use `if constexpr` in locale facets
  stl/inc/xlocmon
  stl/inc/xlocnum
  stl/inc/xloctime
Labels: throughput

#5003 Reduce inclusion for `<queue>`, `<stack>`, `<stacktrace>`, and `<thread>`
  stl/CMakeLists.txt
  stl/inc/__msvc_formatter.hpp
  stl/inc/__msvc_ranges_tuple_formatter.hpp
  stl/inc/format
  stl/inc/header-units.json
  stl/inc/queue
  stl/inc/stack
  stl/inc/stacktrace
  stl/inc/thread
  tests/std/test.lst
  tests/std/tests/P2286R8_text_formatting_header_queue/env.lst
  tests/std/tests/P2286R8_text_formatting_header_queue/test.compile.pass.cpp
  tests/std/tests/P2286R8_text_formatting_header_stack/env.lst
  tests/std/tests/P2286R8_text_formatting_header_stack/test.compile.pass.cpp
  tests/std/tests/P2286R8_text_formatting_header_vector/env.lst
  tests/std/tests/P2286R8_text_formatting_header_vector/test.compile.pass.cpp
  tests/std/tests/P2693R1_text_formatting_header_stacktrace/env.lst
  tests/std/tests/P2693R1_text_formatting_header_stacktrace/test.compile.pass.cpp
  tests/std/tests/P2693R1_text_formatting_header_thread/env.lst
  tests/std/tests/P2693R1_text_formatting_header_thread/test.compile.pass.cpp
Labels: throughput, format

#5006 Simplify control flow in `_Traits_find_MEOW_not_of`
  stl/inc/__msvc_string_view.hpp
Labels: enhancement

#5017 Toolset update: VS 2022 17.12 Preview 3, Python 3.13.0
  README.md
  azure-devops/config.yml
  azure-devops/provision-image.ps1
  stl/inc/chrono
  stl/inc/format
  stl/inc/yvals_core.h
  tests/CMakeLists.txt
  tests/libcxx/expected_results.txt
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P1206R7_ranges_to_mappish/test.cpp
  tests/std/tests/P1206R7_ranges_to_misc/test.cpp
  tests/std/tests/P1206R7_ranges_to_sequence/test.cpp
  tests/std/tests/P1206R7_ranges_to_settish/test.cpp
  tests/std/tests/P2136R3_invoke_r/test.cpp
Labels: infrastructure

#5014 Casey's miscellaneous changes, definitive edition
  stl/inc/__msvc_ranges_to.hpp
  stl/inc/__msvc_ranges_tuple_formatter.hpp
  stl/inc/algorithm
  stl/inc/array
  stl/inc/execution
  stl/inc/format
  stl/inc/print
  stl/inc/ranges
  stl/inc/xmemory
  stl/inc/xutility
  tests/std/include/range_algorithm_support.hpp
  tests/std/tests/GH_004109_iter_value_t_direct_initialization/test.compile.pass.cpp
  tests/std/tests/P1502R1_standard_library_header_units/env.lst
  tests/std/tests/P2165R4_tuple_like_operations/test.compile.pass.cpp
  tests/std/tests/P2165R4_tuple_like_relational_operators/test.compile.pass.cpp
  tests/std/tests/P2502R2_generator/test.cpp
Labels: enhancement

#5015 Unwrapping output iterators in range algorithms
  stl/inc/__msvc_iter_core.hpp
  stl/inc/algorithm
  stl/inc/memory
  stl/inc/xutility
  tests/libcxx/expected_results.txt
Labels: performance, ranges

#5028 Status Chart: Weekly/dependency updates
  index.html
  package-lock.json
  package.json
  src/weekly_table.mts
Labels: documentation, uncharted

#5027 Don't throw arbitrary iterators at `sized_sentinel_for`
  stl/inc/algorithm
  stl/inc/xutility
  tests/libcxx/expected_results.txt
Labels: bug

#5005 Add visualizer for `std::chrono::system_clock::time_point`
  stl/debugger/STL.natvis
Labels: visualizer

#5008 `<bitset>`: optimize streaming `operator >>`
  benchmarks/src/bitset_from_string.cpp
  stl/inc/bitset
Labels: performance

#5013 Generalize vectorized `bitset::to_string` implementation
  stl/src/vector_algorithms.cpp
Labels: enhancement

#5016 Fix floating `minmax` performance
  stl/src/vector_algorithms.cpp
Labels: performance

#5024 Update list to remove bogus strengthened comment
  stl/inc/list
  stl/inc/xtree
Labels: documentation

#5025 `<regex>`: Fix goofy message for `error_badbrace`
  stl/inc/regex
Labels: enhancement

#5026 Update N4988 to N4993 in README.md
  README.md
Labels: documentation

#4672 Optimize `println()` overloads added in P3142R0
  stl/inc/__msvc_filebuf.hpp
  stl/inc/__msvc_print.hpp
  stl/inc/ostream
  stl/inc/print
  stl/src/print.cpp
Labels: performance

#4943 Vectorize `find_end `
  benchmarks/src/search.cpp
  stl/inc/algorithm
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#4987 `remove` vectorization
  benchmarks/CMakeLists.txt
  benchmarks/inc/lorem.hpp
  benchmarks/src/remove.cpp
  benchmarks/src/replace.cpp
  benchmarks/src/search.cpp
  benchmarks/src/sv_equal.cpp
  stl/inc/algorithm
  stl/inc/xmemory
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#4991 Auto-vectorize arrays `swap`
  benchmarks/src/swap_ranges.cpp
  stl/inc/concepts
  stl/inc/type_traits
  stl/inc/utility
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#5032 Add LIT parameter `priority`
  tests/utils/stl/test/params.py
Labels: test

#4887 Add visualizer for `std::flat_map`
  stl/debugger/STL.natvis
Labels: visualizer, flat_meow

#5041 Revert product changes for `find_end` vectorization
  stl/inc/algorithm
  stl/src/vector_algorithms.cpp
Labels: bug, high priority

#5052 Merge `main` to `feature/flat_map`
  README.md
  benchmarks/CMakeLists.txt
  benchmarks/inc/lorem.hpp
  benchmarks/src/bitset_from_string.cpp
  benchmarks/src/remove.cpp
  benchmarks/src/replace.cpp
  benchmarks/src/search.cpp
  benchmarks/src/sv_equal.cpp
  benchmarks/src/swap_ranges.cpp
  stl/debugger/STL.natvis
  stl/inc/__msvc_filebuf.hpp
  stl/inc/__msvc_print.hpp
  stl/inc/algorithm
  stl/inc/bitset
  stl/inc/concepts
  stl/inc/list
  stl/inc/ostream
  stl/inc/print
  stl/inc/regex
  stl/inc/type_traits
  stl/inc/utility
  stl/inc/xmemory
  stl/inc/xtree
  stl/inc/xutility
  stl/src/print.cpp
  stl/src/vector_algorithms.cpp
  tests/libcxx/expected_results.txt
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
  tests/utils/stl/test/params.py
Labels: uncharted, flat_meow

#4958 Help the compiler vectorize `adjacent_difference`
  benchmarks/CMakeLists.txt
  benchmarks/src/adjacent_difference.cpp
  stl/inc/numeric
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#5030 Abandon Windows-internal size optimizations for `mutex` and `condition_variable`
  stl/inc/__msvc_threads_core.hpp
Labels: bug

#5040 Add `.mailmap` file
  .mailmap
Labels: documentation

#5042 Vectorize `find_end`, make sure ASan passes
  stl/inc/algorithm
  stl/src/vector_algorithms.cpp
Labels: performance

#5043 Provide consistent alignment to `swap_ranges` benchmark
  benchmarks/inc/skewed_allocator.hpp
  benchmarks/src/swap_ranges.cpp
Labels: test

#5044 `requires` for `chrono::parse` and comparison category detection
  stl/inc/__msvc_string_view.hpp
  stl/inc/chrono
  stl/inc/regex
Labels: enhancement

#5049 Mention ASan testing steps in `README.md`
  README.md
Labels: documentation
