Repository microsoft/STL, pull requests merged in 2024-04, with the labels that each got.

#4558 `<generator>`: Add death tests
  tests/std/test.lst
  tests/std/tests/P2502R2_generator_death/env.lst
  tests/std/tests/P2502R2_generator_death/test.cpp
Labels: test, generator

#4566 `<flat_map>`: flat_multimap construction test
  tests/std/tests/P0429R9_flat_map/test.cpp
Labels: test, flat_meow

#4537 `<cmath>`: Complete additional overloads for integers
  stl/inc/cmath
  tests/libcxx/expected_results.txt
  tests/std/test.lst
  tests/std/tests/GH_000519_cmath_int_overloads/env.lst
  tests/std/tests/GH_000519_cmath_int_overloads/test.cpp
Labels: bug

#4539 Implement LWG-4016 `container-insertable` checks do not match what `container-inserter` does
  stl/inc/ranges
  tests/std/tests/P1206R7_ranges_to_misc/test.cpp
Labels: LWG, ranges

#4540 Implement LWG-4054 Repeating a `repeat_view` should repeat the view
  stl/inc/ranges
  tests/std/tests/P2474R2_views_repeat/test.cpp
Labels: LWG, ranges

#4542 Implement LWG-3767 `codecvt<charN_t, char8_t, mbstate_t>` incorrectly added to locale
  stl/inc/xlocale
  stl/inc/yvals_core.h
  tests/std/tests/Dev09_056375_locale_cleanup/test.cpp
  tests/std/tests/VSO_0397980_codecvt_length/test.cpp
Labels: LWG

#4543 Implement LWG-3984 `ranges::to`'s recursion branch may be ill-formed
  stl/inc/ranges
  tests/std/tests/P1206R7_ranges_to_sequence/test.cpp
Labels: LWG, ranges

#4544 Standardize vector algorithms dispatch
  stl/inc/algorithm
  stl/inc/xutility
  stl/src/vector_algorithms.cpp
Labels: enhancement

#4545 `<condition_variable>`: Avoid squirrelly forward declaration of `_Cnd_internal_imp_t`
  stl/inc/__msvc_threads_core.hpp
  stl/inc/condition_variable
  stl/inc/mutex
  stl/src/cond.cpp
  stl/src/primitives.hpp
  stl/src/sharedmutex.cpp
Labels: enhancement

#4546 Drop `inline`/`_INLINE_VAR` from templated `constexpr` variables in product and test codes
  stl/inc/__msvc_bit_utils.hpp
  stl/inc/__msvc_chrono.hpp
  stl/inc/__msvc_filebuf.hpp
  stl/inc/__msvc_iter_core.hpp
  stl/inc/algorithm
  stl/inc/any
  stl/inc/atomic
  stl/inc/chrono
  stl/inc/compare
  stl/inc/complex
  stl/inc/execution
  stl/inc/filesystem
  stl/inc/format
  stl/inc/functional
  stl/inc/mdspan
  stl/inc/numbers
  stl/inc/numeric
  stl/inc/ranges
  stl/inc/ratio
  stl/inc/regex
  stl/inc/span
  stl/inc/system_error
  stl/inc/tuple
  stl/inc/type_traits
  stl/inc/utility
  stl/inc/variant
  stl/inc/vector
  stl/inc/xcharconv_ryu_tables.h
  stl/inc/xhash
  stl/inc/xlocale
  stl/inc/xmemory
  stl/inc/xstring
  stl/inc/xtr1common
  stl/inc/xutility
  tests/std/include/is_permissive.hpp
  tests/std/include/range_algorithm_support.hpp
  tests/std/include/test_mdspan_support.hpp
  tests/std/tests/GH_000140_adl_proof_views/test.compile.pass.cpp
  tests/std/tests/GH_000935_complex_numerical_accuracy/floating_point_utils.hpp
  tests/std/tests/LWG3528_make_from_tuple_impl/test.compile.pass.cpp
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P0122R7_span/test.cpp
  tests/std/tests/P0220R1_optional/test.cpp
  tests/std/tests/P0448R4_spanstream/test.cpp
  tests/std/tests/P0768R1_spaceship_cpos/test.cpp
  tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
  tests/std/tests/P0896R4_counted_iterator/test.cpp
  tests/std/tests/P0896R4_ranges_algorithm_machinery/test.compile.pass.cpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
  tests/std/tests/P0896R4_ranges_subrange/test.compile.pass.cpp
  tests/std/tests/P0896R4_ranges_to_address/test.cpp
  tests/std/tests/P0896R4_views_drop/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
  tests/std/tests/P1614R2_spaceship/test.cpp
  tests/std/tests/P2165R4_tuple_like_common_type/test.compile.pass.cpp
Labels: enhancement

#4550 Manually vectorize for at least SSE4.2
  stl/src/vector_algorithms.cpp
Labels: enhancement

#4551 `<ranges>`: Check and test preconditions for `take_view` and `drop_view`'s constructors
  stl/inc/ranges
  tests/std/test.lst
  tests/std/tests/P0896R4_views_drop_death/env.lst
  tests/std/tests/P0896R4_views_drop_death/test.cpp
  tests/std/tests/P0896R4_views_take_death/env.lst
  tests/std/tests/P0896R4_views_take_death/test.cpp
Labels: enhancement

#4554 vectorize `replace` 🎭
  benchmarks/src/replace.cpp
  stl/inc/algorithm
  stl/inc/xutility
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#4556 Update _MSVC_STL_UPDATE to April 2024
  stl/inc/yvals_core.h
Labels: enhancement

#4557 vectorize `find_first_of` for long needle 🪡
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#4559 `<mdspan>`: Throughput improvements
  stl/inc/mdspan
  tests/std/include/test_mdspan_support.hpp
Labels: throughput, mdspan

#4561 Check if `find_last` can find anything
  stl/inc/algorithm
  tests/std/tests/Dev11_0316853_find_memchr_optimization/env.lst
  tests/std/tests/Dev11_0316853_find_memchr_optimization/test.cpp
Labels: bug

#4563 Optimize `find_first_of` for one element needle
  benchmarks/src/find_first_of.cpp
  stl/inc/algorithm
Labels: performance

#4576 Toolset update: VS 2022 17.10 Preview 3
  README.md
  azure-devops/cmake-configure-build.yml
  azure-devops/config.yml
  azure-devops/create-1es-hosted-pool.ps1
  azure-devops/provision-image.ps1
  stl/inc/exception
  stl/inc/new
  stl/inc/ranges
  stl/inc/type_traits
  stl/inc/typeinfo
  stl/modules/std.ixx
  tests/std/tests/P0896R4_ranges_algorithm_machinery/test.compile.pass.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
Labels: infrastructure

#4568 Skip Component Governance autodetection
  azure-devops/config.yml
Labels: infrastructure

#4552 Vectorize `lexicographical_compare`!
  benchmarks/src/mismatch.cpp
  stl/inc/algorithm
  stl/inc/xutility
  tests/std/tests/GH_000431_lex_compare_memcmp_classify/env.lst
  tests/std/tests/GH_000431_lex_compare_memcmp_classify/test.compile.pass.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#4572 `<yvals_core.h>`: avoid using the 'container' word for something that has `empty()` member in `[[nodiscard]]` messages
  stl/inc/queue
  stl/inc/stack
  stl/inc/stacktrace
  stl/inc/yvals_core.h
Labels: enhancement

#4577 Optimized string concatenation in `_Tzdb_update_version()`
  stl/inc/chrono
Labels: enhancement

#4578 `<tuple>`, `<variant>`: Make error messages from get-by-type functions clearer
  stl/inc/__msvc_iter_core.hpp
  stl/inc/tuple
  stl/inc/variant
Labels: enhancement

#4590 `<flat_map>`: more `flat_multimap` coverage copied from `flat_map`
  tests/std/tests/P0429R9_flat_map/test.cpp
Labels: test, flat_meow

#4574 `<generator>`: Test `generator::iterator`
  tests/std/include/test_generator_support.hpp
  tests/std/test.lst
  tests/std/tests/P2502R2_generator/test.cpp
  tests/std/tests/P2502R2_generator_iterator/env.lst
  tests/std/tests/P2502R2_generator_iterator/test.cpp
  tests/std/tests/P2502R2_generator_promise/test.cpp
Labels: test, cxx23, generator

#4583 Status Chart: Weekly updates
  index.html
  package-lock.json
  package.json
  src/weekly_table.mts
Labels: documentation, uncharted

#4594 Toolset update: VS 2022 17.10 Preview 4, non-spot VMs, Azure Pipelines overhaul
  README.md
  azure-devops/asan-pipeline.yml
  azure-devops/build-and-test.yml
  azure-devops/checkout-self.yml
  azure-devops/checkout-sources.yml
  azure-devops/checkout-submodule.yml
  azure-devops/cmake-configure-build.yml
  azure-devops/config.yml
  azure-devops/create-1es-hosted-pool.ps1
  azure-devops/cross-build.yml
  azure-devops/format-validation.yml
  azure-devops/native-build-test.yml
  azure-devops/provision-image.ps1
  azure-devops/run-tests.yml
  azure-pipelines.yml
Labels: infrastructure

#4591 Change `_Always_false` to `false` for functions
  stl/inc/algorithm
  stl/inc/bit
  stl/inc/chrono
  stl/inc/compare
  stl/inc/experimental/generator
  stl/inc/functional
  stl/inc/ranges
  stl/inc/tuple
  stl/inc/type_traits
  stl/inc/variant
  stl/inc/vector
  stl/inc/xlocnum
  stl/inc/xmemory
  stl/inc/xutility
  tests/std/include/range_algorithm_support.hpp
  tests/std/tests/Dev11_0000000_null_forward_iterators/test.cpp
  tests/std/tests/GH_003570_allocate_at_least/test.cpp
  tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
  tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
  tests/std/tests/P0896R4_views_single/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/std/tests/VSO_0000000_fancy_pointers/test.compile.pass.cpp
  tests/std/tests/VSO_0000000_more_pair_tuple_sfinae/test.cpp
Labels: enhancement

#4584 missed `vzeroupper` in `mismatch` and `replace`
  stl/src/vector_algorithms.cpp
Labels: performance

#4585 Check `is_clock_v` for thread utilities before C++20
  stl/inc/__msvc_chrono.hpp
  stl/inc/condition_variable
  stl/inc/future
  stl/inc/mutex
  stl/inc/shared_mutex
  stl/inc/thread
Labels: enhancement

#4587 Vectorize `find_first_of` for 4 and 8 byte elements
  benchmarks/src/find_first_of.cpp
  stl/inc/algorithm
  stl/src/vector_algorithms.cpp
Labels: performance

#4589 `swap_ranges` benchmark
  benchmarks/CMakeLists.txt
  benchmarks/src/swap_ranges.cpp
Labels: test

#4598 Update README.md
  README.md
Labels: documentation

#4600 Avoid `__vectorcall` on ARM64EC
  stl/inc/type_traits
  tests/std/tests/Dev09_158457_tr1_mem_fn_calling_conventions/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
Labels: bug, ARM64

#4605 Emit 'MS extension' deprecation warnings in all Standard modes
  stl/inc/yvals_core.h
Labels: enhancement

#4606 Remove `_FPOSOFF` and non-Standard `std::fpos::seekpos()`
  stl/inc/cstdio
  stl/inc/iosfwd
  stl/inc/yvals_core.h
  tests/std/test.lst
  tests/std/tests/VSO_0000000_oss_workarounds/env.lst
  tests/std/tests/VSO_0000000_oss_workarounds/test.cpp
Labels: enhancement

#4607 Remove `lower_bound()`/`upper_bound()` from `hash_meow`/`unordered_meow`
  stl/inc/xhash
  stl/inc/yvals_core.h
  tests/tr1/tests/hash_map/test.cpp
  tests/tr1/tests/hash_set/test.cpp
Labels: enhancement

#4608 `<ranges>`: Refactor `ranges::to`
  stl/inc/ranges
Labels: enhancement, ranges

#4610 Replace `enable_if_t` in `_Debug_lt_pred` with `if constexpr` and variable template
  stl/inc/xutility
Labels: enhancement

#4611 P3142R0: Printing Blank Lines with `println`
  stl/inc/ostream
  stl/inc/print
  stl/inc/yvals_core.h
  tests/std/include/test_header_units_and_modules.hpp
  tests/std/tests/P2093R14_formatted_output/test.cpp
Labels: cxx26

#4612 `<cmath>`: Use Clang builtins for classification/comparison functions
  stl/inc/cmath
  tests/std/test.lst
  tests/std/tests/GH_000519_cmath_overloads/env.lst
  tests/std/tests/GH_000519_cmath_overloads/test.cpp
Labels: performance

#4613 `<xstring>`: Make `char_traits::assign` not start lifetime of elements
  stl/inc/xstring
Labels: enhancement

#4614 Improve `count` vectorization: replace `popcnt` implementation with vector counting
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#4615 Move `_Floating_type_traits`-related functions
  stl/inc/cmath
  stl/inc/complex
  stl/inc/numeric
  stl/inc/type_traits
  stl/inc/xutility
Labels: throughput

#4616 `<ranges>`: Consistently check preconditions for `iota_view` and `_Counted_fn`
  stl/inc/ranges
  tests/std/tests/P0896R4_views_iota_death/test.cpp
Labels: enhancement, ranges

#4618 `<random>`: Skip reset in `normal_distribution::operator()` with custom params
  stl/inc/random
  tests/std/test.lst
  tests/std/tests/GH_004618_mixed_operator_usage_keeps_statistical_properties/env.lst
  tests/std/tests/GH_004618_mixed_operator_usage_keeps_statistical_properties/test.cpp
  tests/std/tests/GH_004618_normal_distribution_avoids_resets/env.lst
  tests/std/tests/GH_004618_normal_distribution_avoids_resets/test.cpp
Labels: performance

#4623 `find_first_of` vectorized: generalize fast approach for 4 and 8 bytes elements
  stl/src/vector_algorithms.cpp
Labels: performance

#4624 Use `_STL_INTERNAL_STATIC_ASSERT(false)` when appropriate
  stl/inc/algorithm
  stl/inc/bit
  stl/inc/chrono
  stl/inc/compare
  stl/inc/functional
  stl/inc/ranges
  stl/inc/tuple
  stl/inc/variant
  stl/inc/vector
  stl/inc/xlocnum
  stl/inc/xmemory
  stl/inc/xutility
Labels: enhancement

#4626 Fix `import std;` interaction with `<intrin.h>` emitting bogus error C2733
  stl/inc/exception
  stl/modules/std.ixx
Labels: bug, modules

#4627 Help the compiler vectorize `std::iota`
  benchmarks/CMakeLists.txt
  benchmarks/src/iota.cpp
  stl/inc/numeric
  stl/inc/utility
Labels: performance

#4628 `<ranges>`: Replace one improper use of `_Iter_value_t` with `iter_value_t` in `_Stable_sort_fn`
  stl/inc/algorithm
Labels: enhancement, ranges

#4629 `README.md`: mention `--filter` for testing
  README.md
Labels: documentation

#4641 Restore `<exception>`'s inclusion of `<malloc.h>`
  stl/inc/exception
Labels: enhancement, high priority
