Repository microsoft/STL, pull requests merged in 2024-12, with the labels that each got.

#5098 Maybe Clang _does_ work with `ALTERNATENAME`
  stl/inc/xcall_once.h
  tests/std/tests/GH_002030_asan_annotate_string/env.lst
  tests/std/tests/GH_002030_asan_annotate_vector/env.lst
Labels: enhancement

#5101 Vectorize `basic_string::find`
  stl/inc/__msvc_string_view.hpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#5104 Prefer US English for `system_category()` messages, fall back to system locale, then ID 0
  stl/src/syserror_import_lib.cpp
Labels: bug

#5128 Implement LWG-4169 `std::atomic<T>`'s default constructor should be constrained
  stl/inc/atomic
  tests/std/tests/Dev11_0863628_atomic_compare_exchange/test.cpp
Labels: LWG

#5129 Implement LWG-4140 Useless default constructors for bit reference types
  stl/inc/bitset
  stl/inc/vector
  tests/std/tests/Dev10_860410_bitset_ctors/test.cpp
  tests/std/tests/Dev11_0437519_container_requirements/test.compile.pass.cpp
Labels: LWG

#5130 Fix false positives by `filesystem::equivalent` on file systems with transient file IDs
  stl/inc/filesystem
  stl/inc/xfilesystem_abi.h
  stl/src/filesys.cpp
  stl/src/filesystem.cpp
Labels: bug, affects redist, filesystem

#5131 Implement LWG-4135 The helper lambda of `std::erase` for `list` should specify return type as `bool`
  stl/inc/forward_list
  stl/inc/list
  tests/std/test.lst
  tests/std/tests/Dev11_0000000_user_defined_literals/test.cpp
  tests/std/tests/P1209R0_erase_if_erase/env.lst
  tests/std/tests/P1209R0_erase_if_erase/test.cpp
Labels: LWG

#5132 Implement LWG-4014 LWG-3809 changes behavior of some existing `std::subtract_with_carry_engine` code
  stl/inc/random
  tests/std/tests/Dev11_0577418_random_seed_0/test.cpp
Labels: LWG

#5135 Implement LWG-3918 `std::uninitialized_move/_n` and guaranteed copy elision
  stl/inc/execution
  stl/inc/memory
  stl/inc/xmemory
  tests/std/tests/P0040R3_extending_memory_management_tools/test.cpp
  tests/std/tests/P0784R7_library_machinery/test.cpp
Labels: LWG

#5151 Implement LWG-4084 `std::fixed` ignores `std::uppercase`
  stl/inc/xlocnum
  tests/std/test.lst
  tests/std/tests/LWG4084_iostream_uppercase_inf_nan/env.lst
  tests/std/tests/LWG4084_iostream_uppercase_inf_nan/test.cpp
Labels: LWG

#5152 Implement LWG-4112 `has-arrow` should require `operator->()` to be `const`-qualified
  stl/inc/ranges
  tests/libcxx/expected_results.txt
  tests/std/tests/P0896R4_views_filter/test.cpp
  tests/std/tests/P0896R4_views_join/test.cpp
Labels: LWG, ranges

#5155 Implement LWG-4124 Cannot format `zoned_time` with resolution coarser than seconds
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
Labels: LWG, format, chrono

#5156 Avoid arithmetic overflow in the constructors of `weekday`
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp
Labels: bug, chrono

#5157 `<valarray>`: Make `valarray` ADL-proof as required
  stl/inc/valarray
  tests/std/tests/GH_000140_adl_proof_construction/test.compile.pass.cpp
Labels: LWG

#5158 `<regex>`: Always reject character ranges with set limits
  stl/inc/regex
  tests/libcxx/expected_results.txt
  tests/std/include/test_regex_support.hpp
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: bug

#5160 `<regex>`: Repair character class escapes outside character class definitions
  stl/inc/regex
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: bug

#5163 Globally suppress C5278
  stl/inc/yvals_core.h
Labels: enhancement

#5186 Toolset update: VS 2022 17.13 Preview 2, F32as_v6
  README.md
  azure-devops/config.yml
  azure-devops/create-1es-hosted-pool.ps1
  azure-devops/provision-image.ps1
  tests/std/tests/Dev09_056375_locale_cleanup/test.cpp
  tests/std/tests/P0323R12_expected/test.cpp
  tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
  tests/std/tests/P2502R2_generator/test.cpp
Labels: infrastructure

#5169 Stop using ctest
  CMakeLists.txt
  README.md
  azure-devops/asan-pipeline.yml
  azure-devops/build-and-test.yml
  azure-devops/run-tests.yml
  tests/CMakeLists.txt
  tests/utils/stl/test/params.py
Labels: test

#5029 Improve `basic_string::find_first_of` and `basic_string::find_last_of` vectorization for large needles or very large haystacks
  benchmarks/src/find_first_of.cpp
  stl/inc/__msvc_string_view.hpp
  stl/inc/algorithm
  stl/inc/xutility
  stl/src/vector_algorithms.cpp
Labels: performance

#5162 Update _MSVC_STL_UPDATE to December 2024
  stl/inc/yvals_core.h
Labels: enhancement

#5168 `<stack>`, `<queue>`: Add `std::forward` for `append_range`
  stl/inc/queue
  stl/inc/stack
Labels: bug, ranges

#5170 `<xmemory>`: Tolerate bogus const-overloading in iterators passed to `uninitialized_meow()`
  stl/inc/xmemory
  tests/std/test.lst
  tests/std/tests/VSO_2318081_bogus_const_overloading/env.lst
  tests/std/tests/VSO_2318081_bogus_const_overloading/test.compile.pass.cpp
Labels: enhancement

#5173 `<ranges>`: Fix regression with `ranges::to` for ADL-only `begin`/`end`
  stl/inc/__msvc_ranges_to.hpp
  tests/std/tests/P1206R7_ranges_to_misc/test.cpp
Labels: bug, ranges

#5178 `<ranges>`: Fix formatting ranges for ADL-only ranges
  stl/inc/format
Labels: bug, ranges, format

#5176 `STL.natvis`: Simplify visualization for `string_view`
  stl/debugger/STL.natvis
Labels: visualizer

#5177 `STL.natvis`: Simplify visualization for `string`
  stl/debugger/STL.natvis
Labels: visualizer

#5174 Mark `expected`, `unexpected`, and ALL exception types as `[[nodiscard]]`
  stl/inc/__msvc_ranges_tuple_formatter.hpp
  stl/inc/any
  stl/inc/chrono
  stl/inc/exception
  stl/inc/execution
  stl/inc/expected
  stl/inc/experimental/filesystem
  stl/inc/filesystem
  stl/inc/functional
  stl/inc/future
  stl/inc/memory
  stl/inc/optional
  stl/inc/regex
  stl/inc/stdexcept
  stl/inc/system_error
  stl/inc/typeinfo
  stl/inc/xiosbase
  tests/libcxx/expected_results.txt
  tests/std/tests/P2505R5_monadic_functions_for_std_expected/test.cpp
Labels: enhancement

#5190 Status Chart: Weekly/dependency updates
  index.html
  package-lock.json
  package.json
  src/weekly_table.mts
Labels: documentation, uncharted

#5191 Update C++20 section of <yvals_core.h> for WG21-P3136R1 Retiring Niebloids
  stl/inc/yvals_core.h
Labels: ranges, cxx26

#5194 Add support for running only edg tests
  tests/CMakeLists.txt
  tests/utils/stl/test/params.py
  tests/utils/stl/test/tests.py
Labels: test
