Repository microsoft/STL, pull requests merged in 2024-08, with the labels that each got.

#4869 Implement P2787R1 `pmr::generator`
  stl/inc/generator
  stl/inc/yvals_core.h
  tests/std/tests/P2502R2_generator/test.cpp
Labels: generator

#4755 Wait `condition_variable_any` for `steady_clock`
  stl/inc/condition_variable
  stl/inc/mutex
  stl/inc/xthreads.h
  stl/src/sharedmutex.cpp
  tests/libcxx/expected_results.txt
Labels: bug

#4835 Remove `std::ranges::view_interface` visualizer.
  stl/debugger/STL.natvis
Labels: bug, visualizer

#4836 `move_iterator` visualizer should use `_Current`
  stl/debugger/STL.natvis
Labels: bug, visualizer

#4837 `<expected>`: Add deleted copy function overloads
  stl/inc/expected
  tests/std/tests/P0323R12_expected/test.cpp
Labels: bug

#4838 Add `[[msvc::lifetimebound]]` to more min/max functions
  stl/inc/algorithm
  stl/inc/utility
  stl/inc/xutility
Labels: enhancement

#4840 Fix `put_time()` crash on invalid format specifier
  stl/inc/xloctime
  tests/std/tests/Dev11_0836436_get_time/test.cpp
Labels: bug

#4841 Don't use `auto` in some ranges algos.
  stl/inc/algorithm
  tests/std/test.lst
  tests/std/tests/GH_004108_some_ranges_algos_construct_wrong_type/env.lst
  tests/std/tests/GH_004108_some_ranges_algos_construct_wrong_type/test.compile.pass.cpp
Labels: bug, ranges

#4846 Fix truncation warnings in `conjunction`/`disjunction`
  stl/inc/type_traits
  stl/inc/xtr1common
  tests/libcxx/expected_results.txt
  tests/std/test.lst
  tests/std/tests/GH_004845_logical_operator_traits_with_non_bool_constant/env.lst
  tests/std/tests/GH_004845_logical_operator_traits_with_non_bool_constant/test.compile.pass.cpp
Labels: bug

#4849 Verify in vector::pop_back if _CONTAINER_DEBUG_LEVEL > 0
  stl/inc/vector
Labels: enhancement

#4850 Avoid using wider types in `generate_canonical` when the range of the random generator is a power of 2
  stl/inc/random
  tests/std/tests/P0952R2_new_generate_canonical/test.cpp
Labels: performance

#4854 Update `README.md` working draft revision to N4986
  README.md
Labels: documentation

#4856 Fix and improve `array` and `mdspan` static analysis warnings
  stl/inc/array
  stl/inc/mdspan
  tests/libcxx/expected_results.txt
  tests/std/include/test_mdspan_support.hpp
  tests/std/test.lst
  tests/std/tests/P0009R18_mdspan_extents_death/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_left_death/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_right_death/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_stride_death/test.cpp
  tests/std/tests/P0218R1_filesystem/test.cpp
  tests/std/tests/P2321R2_views_adjacent/test.cpp
  tests/std/tests/P2321R2_views_adjacent_transform/test.cpp
  tests/std/tests/VSO_1804139_static_analysis_warning_with_single_element_array/env.lst
  tests/std/tests/VSO_1804139_static_analysis_warning_with_single_element_array/test.compile.pass.cpp
Labels: bug

#4859 `README.md`: Add instructions for building ARM and ARM64.
  README.md
Labels: documentation

#4864 Simplify the comparison of sizes of different ranges
  stl/inc/algorithm
Labels: enhancement, ranges

#4872 Update _MSVC_STL_UPDATE to August 2024
  stl/inc/yvals_core.h
Labels: enhancement

#4873 Call CRT `wmemcmp`/`wmemchr` when possible in `char_traits` for better performance
  stl/inc/__msvc_string_view.hpp
Labels: performance

#4878 Enforce [alg.three.way]/2 mandate
  stl/inc/xutility
Labels: bug, ranges

#4886 Build with the conformant preprocessor, improve validator
  benchmarks/CMakeLists.txt
  stl/CMakeLists.txt
  tools/validate/CMakeLists.txt
  tools/validate/validate.cpp
Labels: infrastructure, build

#4885 Skip libcxx tests with timing assumptions
  tests/libcxx/expected_results.txt
Labels: test

#4889 Toolset update: VS 2022 17.12 Preview 1
  README.md
  azure-devops/config.yml
  azure-devops/provision-image.ps1
  stl/inc/type_traits
  stl/src/vector_algorithms.cpp
  tests/libcxx/expected_results.txt
Labels: infrastructure

#4701 `<execution>`: parallel scans should avoid passing output values to the binary (reduce) operation
  stl/inc/execution
  stl/inc/vector
  stl/inc/xmemory
  tests/std/tests/P0024R2_parallel_algorithms_exclusive_scan/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_inclusive_scan/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_transform_exclusive_scan/test.cpp
  tests/std/tests/P0024R2_parallel_algorithms_transform_inclusive_scan/test.cpp
Labels: bug

#4825 Implement `formatter` specializations for container adaptors
  stl/inc/format
  stl/inc/queue
  stl/inc/stack
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/std/test.lst
  tests/std/tests/P2286R8_text_formatting_container_adaptors/env.lst
  tests/std/tests/P2286R8_text_formatting_container_adaptors/test.cpp
  tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Labels: ranges, format, cxx23

#4884 Updated C++ latest working draft to N4988
  README.md
Labels: documentation

#4888 Overhaul how we search for clang-format
  tools/format/CMakeLists.txt
Labels: build

#4895 Workaround Intellisense bug in some `ranges::to` tests
  tests/std/tests/P1206R7_ranges_to_mappish/test.cpp
  tests/std/tests/P1206R7_ranges_to_misc/test.cpp
  tests/std/tests/P1206R7_ranges_to_sequence/test.cpp
  tests/std/tests/P1206R7_ranges_to_settish/test.cpp
Labels: test

#4909 Status Chart: Weekly updates
  index.html
  package-lock.json
  package.json
  src/weekly_table.mts
Labels: documentation

#4734 Floating minmax: fix negative zero handling and dedicated test coverage for arrays of +0.0 and -0.0 only
  stl/inc/algorithm
  stl/inc/xutility
  stl/src/vector_algorithms.cpp
  tests/std/include/test_min_max_element_support.hpp
  tests/std/include/test_vector_algorithms_support.hpp
  tests/std/test.lst
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
  tests/std/tests/VSO_0000000_vector_algorithms_floats/env.lst
  tests/std/tests/VSO_0000000_vector_algorithms_floats/test.cpp
Labels: bug

#4883 Fix put_time() crash on invalid struct tm data
  stl/inc/xloctime
  tests/std/tests/Dev11_0836436_get_time/test.cpp
Labels: bug

#4894 Use `wmemchr` in optimizations
  stl/inc/xutility
  stl/src/vector_algorithms.cpp
Labels: performance

#4897 Test LWG-4105 `ranges::ends_with`'s Returns misses difference casting
  tests/std/include/range_algorithm_support.hpp
  tests/std/test.lst
  tests/std/tests/LWG4105_ranges_ends_with_and_integer_class/env.lst
  tests/std/tests/LWG4105_ranges_ends_with_and_integer_class/test.cpp
Labels: LWG, test, ranges

#4898 Avoid truncation warnings for contiguous iterators with unusual difference types
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/GH_003663_cast_contiguous_iterator_difference_type/env.lst
  tests/std/tests/GH_003663_cast_contiguous_iterator_difference_type/test.compile.pass.cpp
Labels: bug

#4900 Casey's accumulated miscellaneous changes
  stl/inc/__msvc_iter_core.hpp
  stl/inc/forward_list
  stl/inc/list
  stl/inc/ranges
  stl/inc/span
  stl/inc/utility
  tests/std/tests/P0323R12_expected/test.cpp
Labels: enhancement

#4902 Speculatively implement LWG-4139 [time.zone.leap] recursive constraint in `<=>`
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_clocks/test.cpp
Labels: LWG, chrono

#4903 `<variant>`: Workaround for LLVM-59854 in the case of destructor of `variant`
  stl/inc/variant
  tests/std/tests/P0088R3_variant_msvc/test.cpp
Labels: bug

#4904 Optimize equality comparison of two empty `string_view`s
  benchmarks/CMakeLists.txt
  benchmarks/src/sv_equal.cpp
  stl/inc/__msvc_string_view.hpp
Labels: performance

#4905 Fix MSVC-only compiler options for the internal test harness
  tests/std/run.pl
  tests/tr1/run.pl
Labels: test

#4906 Standard Library Modules: Add compiler workarounds for `<random>`
  stl/inc/__msvc_int128.hpp
  tests/std/include/test_header_units_and_modules.hpp
Labels: bug, modules

#4907 `<format>`: crash when formatting a floating-point value with #/L and a large precision
  stl/inc/format
  tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Labels: bug, format

#4908 `<ranges>`: rename `views::iota` and `views::repeat` parameters
  stl/inc/ranges
Labels: enhancement, ranges

#4914 Adjust tests relying on CWG-1351 noexcept behavior
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P2136R3_invoke_r/test.cpp
Labels: test

#4911 Unskip tests that no longer have `ALLOW_RETRIES`
  tests/libcxx/expected_results.txt
Labels: test

#4912 Make the test suite more friendly to Clang 19
  tests/libcxx/expected_results.txt
  tests/std/tests/P2286R8_text_formatting_range_formatter/test.cpp
  tests/std/tests/P2374R4_views_cartesian_product_recommended_practices/test.compile.pass.cpp
Labels: test

#4916 `locale0.cpp`: Protect memory integrity of `_Fac_node`
  stl/src/locale0.cpp
Labels: enhancement

#4920 `<chrono>`: Add comments for compiler bug workarounds
  stl/inc/chrono
Labels: documentation

#4921 Avoid `rand()` in the legacy `tr1` test suite
  tests/tr1/tests/algorithm/test.cpp
  tests/tr1/tests/memory2/test.cpp
Labels: test
