Repository microsoft/STL, pull requests merged in 2025-06, with the labels that each got.

#5533 Make benchmarks compiling in clang-cl
  azure-devops/build-and-test.yml
  azure-devops/build-benchmarks.yml
  azure-devops/cmake-configure-build.yml
  benchmarks/CMakeLists.txt
  benchmarks/src/bitset_from_string.cpp
  benchmarks/src/bitset_to_string.cpp
  benchmarks/src/filesystem.cpp
  benchmarks/src/has_single_bit.cpp
  benchmarks/src/locale_classic.cpp
  benchmarks/src/move_only_function.cpp
  benchmarks/src/priority_queue_push_range.cpp
  benchmarks/src/search.cpp
  benchmarks/src/sv_equal.cpp
Labels: test

#5576 `<regex>`: Speed up searches for regexes that start with assertions
  benchmarks/src/regex_search.cpp
  stl/inc/regex
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: performance, regex

#5543 Optimize `std::includes` by using `ranges::includes` approach
  benchmarks/CMakeLists.txt
  benchmarks/src/includes.cpp
  stl/inc/algorithm
Labels: performance

#5558 `tzdb.cpp`: Fall back to numeric offset when the current code page cannot represent the time zone short ID
  stl/src/tzdb.cpp
Labels: bug, chrono

#5559 `validate.cpp`: report error lines
  tools/validate/validate.cpp
Labels: enhancement, infrastructure

#5560 Use `_STL_REPORT_ERROR` in headers
  stl/inc/atomic
  stl/inc/format
  stl/inc/functional
  stl/inc/future
  stl/inc/memory
  stl/inc/utility
  stl/inc/xcall_once.h
  stl/inc/xlocale
  stl/inc/xutility
  stl/inc/yvals.h
Labels: enhancement

#5565 `filesystem.cpp`: Avoid loading `GetTempPath2W` for OneCore
  stl/src/filesystem.cpp
Labels: enhancement, filesystem

#5566 `<vector>`: Avoid another compiler warning with Defect Report P2280R4
  stl/inc/vector
Labels: enhancement

#5568 Update _MSVC_STL_UPDATE macro to 202506L
  stl/inc/yvals_core.h
Labels: enhancement

#5575 `<semaphore>`: use `steady_clock`
  stl/inc/semaphore
  stl/inc/xatomic_wait.h
  stl/src/atomic_wait.cpp
Labels: bug, chrono
