Repository microsoft/STL, pull requests merged in 2025-03, with the labels that each got.

#5318 Destructor Tombstones
  stl/inc/any
  stl/inc/deque
  stl/inc/exception
  stl/inc/forward_list
  stl/inc/functional
  stl/inc/list
  stl/inc/memory
  stl/inc/optional
  stl/inc/regex
  stl/inc/valarray
  stl/inc/variant
  stl/inc/vector
  stl/inc/xhash
  stl/inc/xpolymorphic_allocator.h
  stl/inc/xstring
  stl/inc/xtree
  stl/inc/yvals.h
  tests/std/test.lst
  tests/std/tests/GH_005315_destructor_tombstones/env.lst
  tests/std/tests/GH_005315_destructor_tombstones/test.cpp
  tests/std/tests/VSO_0000000_wcfb01_idempotent_container_destructors/test.cpp
Labels: enhancement, high priority

#5335 Toolset update: VS 2022 17.14 Preview 2, Clang 19.1.5
  .github/workflows/update-status-chart.yml
  README.md
  azure-devops/checkout-self.yml
  azure-devops/config.yml
  azure-devops/create-1es-hosted-pool.ps1
  azure-devops/provision-image.ps1
  stl/inc/__msvc_bit_utils.hpp
  stl/inc/__msvc_int128.hpp
  stl/inc/__msvc_iter_core.hpp
  stl/inc/__msvc_ranges_tuple_formatter.hpp
  stl/inc/array
  stl/inc/cmath
  stl/inc/string
  stl/inc/utility
  stl/inc/xmemory
  stl/inc/yvals_core.h
  tests/libcxx/expected_results.txt
  tests/std/tests/Dev11_0535636_functional_overhaul/test.cpp
  tests/std/tests/GH_000639_nvcc_include_all/test.compile.pass.cpp
  tests/std/tests/P0019R8_atomic_ref/test.cpp
  tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp
  tests/std/tests/P0896R4_views_take/test.cpp
  tools/format/CMakeLists.txt
Labels: infrastructure

#5256 `<random>`: Optimized divisionless implementation of `minstd_rand`, `minstd_rand0`
  stl/inc/random
Labels: performance

#5323 Update _MSVC_STL_UPDATE to March 2025
  stl/inc/yvals_core.h
Labels: enhancement

#5325 `<xutility>`: Fix conversion between `basic_const_iterator`s
  stl/inc/xutility
  tests/std/tests/P2278R4_basic_const_iterator/test.cpp
Labels: bug

#5328 `<functional>`: make `move_only_function` do less work
  benchmarks/CMakeLists.txt
  benchmarks/src/move_only_function.cpp
  stl/inc/functional
Labels: performance

#5334 Implement LWG-3956 `chrono::parse` uses `from_stream` as a customization point
  stl/inc/chrono
  tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp
Labels: LWG, chrono

#5336 Various cleanups
  stl/inc/algorithm
  stl/inc/atomic
  stl/inc/bitset
  stl/inc/chrono
  stl/inc/format
  stl/inc/functional
  stl/inc/future
  stl/inc/random
  stl/inc/regex
  stl/inc/variant
  stl/inc/xloctime
  stl/inc/xtree
  stl/inc/yvals_core.h
  stl/src/primitives.hpp
  stl/src/print.cpp
  tests/std/tests/P0088R3_variant_msvc/test.cpp
  tests/std/tests/P0092R1_polishing_chrono/test.cpp
  tests/std/tests/P0220R1_sample/test.cpp
  tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp
  tests/std/tests/P2502R2_generator/test.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
  tests/utils/stl/util.py
Labels: enhancement

#5337 Make `unique_lock` and `shared_lock` use self-swap implementation of move assignment
  stl/inc/mutex
  stl/inc/shared_mutex
  tests/std/test.lst
  tests/std/tests/LWG4172_unique_lock_self_move_assignment/env.lst
  tests/std/tests/LWG4172_unique_lock_self_move_assignment/test.cpp
Labels: LWG

#5306 `<flat_map>`: Fix several bugs found by libcxx tests
  stl/inc/flat_map
  stl/inc/vector
  stl/inc/xutility
  tests/libcxx/expected_results.txt
  tests/std/tests/P0429R9_flat_map/env.lst
Labels: bug, flat_meow

#5341 Status Chart: Weekly updates, PAT instructions
  .github/workflows/compile-typescript.yml
  README.md
  package-lock.json
  package.json
  src/weekly_table.mts
Labels: documentation, uncharted

#5353 Add visualizer for `std::flat_set` and flat-map iterators
  stl/debugger/STL.natvis
Labels: visualizer, flat_meow

#5102 Vectorize `find_first_not_of`/`find_last_not_of` member functions (single character)
  benchmarks/src/find_and_count.cpp
  stl/inc/__msvc_string_view.hpp
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#5206 Vectorize `find_first_not_of`/`find_last_not_of` member functions (multiple characters overloads)
  benchmarks/src/find_first_of.cpp
  stl/inc/__msvc_string_view.hpp
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#5331 Vectorize `adjacent_find`
  benchmarks/CMakeLists.txt
  benchmarks/src/adjacent_find.cpp
  stl/inc/algorithm
  stl/inc/xutility
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#5092 Vectorize `unique`
  benchmarks/CMakeLists.txt
  benchmarks/src/unique.cpp
  stl/inc/algorithm
  stl/src/vector_algorithms.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#5343 `<algorithm>`: avoid `continue` in `ranges::search_n`
  stl/inc/algorithm
Labels: enhancement, ranges

#5346 Use `find` for `search_n` when n=1
  benchmarks/CMakeLists.txt
  benchmarks/src/search_n.cpp
  stl/inc/algorithm
  tests/std/tests/P0896R4_ranges_alg_search_n/test.cpp
Labels: performance

#5165 `<regex>`: Revise caret parsing in basic and grep mode
  stl/inc/regex
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: bug, regex

#5218 `<regex>`: Fix depth-first and leftmost-longest matching rules
  stl/inc/regex
  tests/std/include/test_regex_support.hpp
  tests/std/tests/VSO_0000000_regex_use/test.cpp
  tests/tr1/tests/regex2/test.cpp
Labels: bug, regex

#5238 `<regex>`: Implement collating ranges
  stl/inc/regex
  tests/std/test.lst
  tests/std/tests/GH_005204_regex_collating_ranges/env.lst
  tests/std/tests/GH_005204_regex_collating_ranges/test.cpp
Labels: bug, regex

#5253 `<regex>`: Clean up parsing logic for quantifiers
  stl/inc/regex
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: enhancement, regex

#4960 Initially use `[[msvc::no_unique_address]]` for some C++23 components
  stl/inc/algorithm
  stl/inc/mdspan
  stl/inc/ranges
  stl/inc/xmemory
  stl/inc/xutility
  stl/inc/yvals_core.h
  tests/std/include/test_mdspan_support.hpp
  tests/std/test.lst
  tests/std/tests/GH_001394_msvc_no_unique_address_23/env.lst
  tests/std/tests/GH_001394_msvc_no_unique_address_23/test.compile.pass.cpp
  tests/std/tests/P0009R18_mdspan_extents/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
  tests/std/tests/P0009R18_mdspan_mdspan/test.cpp
  tests/std/tests/P0009R18_mdspan_msabi/env.lst
  tests/std/tests/P0009R18_mdspan_msabi/test.compile.pass.cpp
Labels: performance

#5344 Update README.md to reference N5008 instead of N5001
  README.md
Labels: documentation
