Repository microsoft/STL, pull requests merged in 2025-07, with the labels that each got.

#5594 Remove support for 32-bit ARM
  CMakeLists.txt
  CMakePresets.json
  README.md
  azure-devops/asan-pipeline.yml
  azure-devops/provision-image.ps1
  azure-pipelines.yml
  benchmarks/CMakeLists.txt
  stl/inc/__msvc_bit_utils.hpp
  stl/inc/__msvc_chrono.hpp
  stl/inc/__msvc_int128.hpp
  stl/inc/__msvc_sanitizer_annotate_container.hpp
  stl/inc/atomic
  stl/inc/bit
  stl/inc/new
  stl/inc/xatomic.h
  stl/msbuild/stl_1/arm.exports
  stl/msbuild/stl_1/stl_1.files.settings.targets
  stl/msbuild/stl_2/arm.exports
  stl/msbuild/stl_2/stl_2.files.settings.targets
  stl/msbuild/stl_base/arm.exports
  stl/msbuild/stl_base/stl.files.settings.targets
  stl/msbuild/stl_codecvt_ids/arm.exports
  stl/msbuild/stl_codecvt_ids/stl_codecvt_ids.files.settings.targets
  stl/src/xonce2.cpp
  tests/libcxx/expected_results.txt
  tests/std/tests/Dev09_158457_tr1_mem_fn_calling_conventions/test.cpp
  tests/std/tests/GH_000690_overaligned_function/test.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/std/tests/P1135R6_atomic_wait/test.cpp
  tests/std/tests/floating_point_model_matrix.lst
  tests/utils/stl/test/features.py
  tests/utils/stl/test/tests.py
Labels: enhancement, ARM

#5641 Toolset update: VS 2022 17.14.8 Preview 1
  CMakeLists.txt
  README.md
  azure-devops/config.yml
  azure-devops/provision-image.ps1
Labels: infrastructure

#5584 Remove comments for LWG-4245
  stl/inc/iterator
Labels: LWG

#5588 `<regex>`: Limit recursion in the parser
  stl/inc/regex
Labels: enhancement, regex

#5597 Optimize `find` for ARM64EC
  stl/src/vector_algorithms.cpp
Labels: performance, ARM64

#5625 `<xloctime>`: Silence CodeQL warning SM03231 about leap year arithmetic
  stl/inc/xloctime
Labels: enhancement

#5628 Restore `wmemchr` optimization in `ranges::find`
  stl/inc/xutility
Labels: performance, ranges

#5636 Cleanup: Mostly remove `_VCRT_ALLOW_INTERNALS`
  stl/CMakeLists.txt
  stl/msbuild/stl_1/msvcp_1.settings.targets
  stl/msbuild/stl_2/msvcp_2.settings.targets
  stl/msbuild/stl_atomic_wait/msvcp_atomic_wait.settings.targets
  stl/msbuild/stl_base/libcp.settings.targets
  stl/msbuild/stl_base/msvcp.settings.targets
  stl/msbuild/stl_codecvt_ids/msvcp_codecvt_ids.settings.targets
  stl/src/excptptr.cpp
  stl/src/pplerror.cpp
Labels: enhancement

#5645 Silence ABI warning C5291 for the entire STL
  stl/inc/yvals_core.h
Labels: enhancement

#5659 Update WinSDK comments
  CMakeLists.txt
  README.md
  tests/utils/stl/test/tests.py
Labels: documentation
