Repository microsoft/STL, pull requests merged in 2025-10, with the labels that each got.

#5544 Vectorize `search_n` for CPUs with SSE4.2 but not AVX2 support; handle AVX2 tail
  stl/src/vector_algorithms.cpp
Labels: performance

#5710 Optimize `any::swap`
  benchmarks/CMakeLists.txt
  benchmarks/src/any_swap.cpp
  stl/inc/any
Labels: performance

#5728 Add some coverage of constexpr `vector<bool>`
  stl/inc/vector
  tests/std/tests/GH_000625_vector_bool_optimization/test.cpp
Labels: test

#5742 Fix non-inline `random_bool_vector` in benchmarks
  benchmarks/inc/utility.hpp
  benchmarks/src/vector_bool_copy.cpp
  benchmarks/src/vector_bool_copy_n.cpp
  benchmarks/src/vector_bool_count.cpp
  benchmarks/src/vector_bool_move.cpp
Labels: enhancement, benchmark

#5743 `vector_algorithms.cpp`: Improve conformance by adding missing `template` and `typename` for dependent things
  stl/src/vector_algorithms.cpp
Labels: enhancement

#5744 `vector_algorithms.cpp`: remove unused functions
  stl/src/vector_algorithms.cpp
Labels: enhancement

#5745 `<regex>`: Process disjunctions non-recursively
  stl/inc/regex
Labels: enhancement, regex

#5746 Reactivate Clang UBSan test coverage
  stl/inc/__msvc_string_view.hpp
  tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
  tests/std/tests/VSO_0000000_vector_algorithms_floats/env.lst
  tests/std/tests/VSO_0000000_vector_algorithms_mismatch_and_lex_compare/test.cpp
  tests/std/tests/usual_matrix.lst
  tests/utils/stl/test/features.py
Labels: test

#5752 fixing MSVC_STL_UPDATE Macro
  stl/inc/yvals_core.h
Labels: enhancement
