Repository microsoft/STL, pull requests merged in 2025-05, with the labels that each got.

#5455 `<flat_map>`: Workaround for CWG-2369 in deduction guides
  stl/inc/flat_map
  tests/libcxx/expected_results.txt
Labels: bug, flat_meow

#5454 `<flat_map>`: move invariants preserving
  stl/inc/flat_map
  tests/libcxx/expected_results.txt
Labels: bug, flat_meow

#5460 `<flat_map>`: drop bogus exception specifications
  stl/inc/flat_map
Labels: bug, flat_meow

#5465 `<flat_set>`: Fix some significant bugs caught by latest libcxx tests
  stl/inc/algorithm
  stl/inc/flat_map
  stl/inc/flat_set
  stl/inc/vector
Labels: bug, flat_meow

#5474 Make implementation details of `flat_meow` more similar
  stl/inc/flat_map
  stl/inc/flat_set
Labels: enhancement, flat_meow

#5437 `<regex>`: Make `wregex` handle small character ranges containing U+00FF and U+0100 correctly
  stl/inc/regex
  tests/std/tests/GH_005204_regex_collating_ranges/test.cpp
Labels: bug, regex

#5438 `<regex>`: Make `wregex` properly match the combination of `\w` and another named character class
  stl/inc/regex
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: bug, regex

#5444 `<regex>`: `regex_traits::transform_primary` should yield primary sort keys appropriate for the imbued locale
  stl/CMakeLists.txt
  stl/inc/locale
  stl/inc/regex
  stl/inc/yvals.h
  stl/msbuild/stl_base/stl.files.settings.targets
  stl/src/awint.hpp
  stl/src/regex.cpp
  tests/libcxx/expected_results.txt
  tests/std/tests/GH_005204_regex_collating_ranges/test.cpp
  tests/std/tests/VSO_0000000_regex_use/test.cpp
  tests/tr1/tests/regex1/test.cpp
  tests/tr1/tests/regex2/test.cpp
Labels: bug, LWG, regex

#5456 `<regex>`: Correctly reset capture groups for ECMAScript grammar
  stl/inc/regex
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: bug, regex

#5457 `<regex>`: Fix quadratic complexity in `regex_search` when regex starts with `?` quantifier or several alternatives
  stl/inc/regex
Labels: performance, regex

#5469 `<locale>`: make `collate::hash` return the same hash for strings that collate the same
  stl/inc/locale
  tests/std/tests/GH_005236_collate_facet/test.cpp
Labels: bug

#5439 Test coverage for `search_n` with forward iterators
  tests/std/tests/VSO_0000000_vector_algorithms_search_n/test.cpp
Labels: test

#5440 Test coverage for `search_n` with impossible value
  tests/std/tests/Dev11_0316853_find_memchr_optimization/test.cpp
Labels: test

#5443 Benchmark: use `not_highly_aligned_allocator` in more places
  benchmarks/src/adjacent_difference.cpp
  benchmarks/src/adjacent_find.cpp
  benchmarks/src/iota.cpp
  benchmarks/src/minmax_element.cpp
  benchmarks/src/mismatch.cpp
  benchmarks/src/remove.cpp
  benchmarks/src/replace.cpp
  benchmarks/src/std_copy.cpp
Labels: test

#5450 `vector_algorithms.cpp`: introduce namespaces
  stl/src/vector_algorithms.cpp
Labels: enhancement

#5471 Add casts to vector algorithms entry points
  stl/inc/algorithm
  stl/inc/xmemory
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/GH_005421_vector_algorithms_integer_class_type_iterator/env.lst
  tests/std/tests/GH_005421_vector_algorithms_integer_class_type_iterator/test.cpp
Labels: bug

#5449 `<memory>`: Make algorithms properly destroy objects in constant evaluation
  stl/inc/memory
  stl/inc/xmemory
  tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
Labels: bug

#5475 Replace `_GET_PROXY_ALLOCATOR` with a function template
  stl/inc/forward_list
  stl/inc/list
  stl/inc/vector
  stl/inc/xhash
  stl/inc/xmemory
  stl/inc/xstring
  stl/inc/xtree
Labels: enhancement

#5476 Fix `num_get::do_get` for `bool` on bad grouping
  stl/inc/xlocnum
  tests/std/tests/GH_001277_num_get_bad_grouping/test.cpp
Labels: bug

#5459 Enable `thread::hardware_concurrency()` to handle more than 64 processors
  stl/msbuild/stl_base/msvcp.settings.targets
  stl/src/cthread.cpp
Labels: bug

#5464 Update `_MSVC_STL_UPDATE` to May 2025 and update `_MSVC_STL_VERSION` to 145
  stl/inc/yvals_core.h
Labels: enhancement

#5477 `<mdspan>`: Fix `layout_stride::mapping<E>::is_exhaustive()`
  stl/inc/mdspan
  tests/libcxx/expected_results.txt
  tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
Labels: bug, mdspan

#5458 RWC workaround: Use `__builtin_trap` for ancient Clang
  stl/inc/type_traits
  stl/inc/yvals.h
Labels: enhancement

#5480 `features.py`: Recognize the `'Czech_Czechia.1250'` locale
  tests/utils/stl/test/features.py
Labels: test

#5499 Use the `_Transparent` concept for `flat_meow`
  stl/inc/flat_map
  stl/inc/flat_set
Labels: enhancement, flat_meow

#5508 `<flat_set>`: some libc++ tests look bogus
  tests/libcxx/expected_results.txt
Labels: test, flat_meow

#5514 `<flat_set>`: insert range invariant fix
  stl/inc/flat_set
  tests/libcxx/expected_results.txt
Labels: bug, flat_meow

#5512 Toolset update: VS 2022 17.14 Preview 7
  CMakeLists.txt
  README.md
  azure-devops/config.yml
  azure-devops/provision-image.ps1
  benchmarks/CMakeLists.txt
  tools/CMakeLists.txt
  tools/format/CMakeLists.txt
  tools/validate/CMakeLists.txt
Labels: infrastructure

#5492 Add arm64EC pipeline
  CMakeLists.txt
  azure-devops/asan-pipeline.yml
  azure-devops/build-and-test.yml
  azure-devops/cmake-configure-build.yml
  azure-devops/run-tests.yml
  azure-pipelines.yml
  benchmarks/CMakeLists.txt
  stl/CMakeLists.txt
Labels: infrastructure, ARM64

#5484 Vectorize `search` for 32-bit and 64-bit elements, also improve 8-bit and 16-bit vectorization
  benchmarks/src/search.cpp
  stl/inc/__msvc_string_view.hpp
  stl/inc/xutility
  stl/src/vector_algorithms.cpp
  tests/std/tests/GH_005421_vector_algorithms_integer_class_type_iterator/test.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#5485 `vector_algorithms.cpp`: further cleanup
  stl/src/vector_algorithms.cpp
Labels: enhancement

#5493 Benchmark vectorized `reverse` and `reverse_copy`, use traits, optimize `reverse_copy` tail
  benchmarks/CMakeLists.txt
  benchmarks/src/reverse.cpp
  stl/src/vector_algorithms.cpp
Labels: performance, test

#5487 `<regex>`: Cache bitmasks of negated character classes during matching
  stl/inc/regex
Labels: performance, regex

#5494 `<regex>`: Reject empty repetitions when required by regex grammars
  stl/inc/regex
  tests/std/tests/VSO_0000000_regex_use/test.cpp
  tests/tr1/tests/regex2/test.cpp
Labels: bug, regex

#5488 `<__msvc_string_view.hpp>`: Avoid redundant forwarding in `char_traits::assign`
  stl/inc/__msvc_string_view.hpp
Labels: enhancement

#5495 Use `_Verify_ranges_do_not_overlap` in more places
  stl/inc/algorithm
  tests/std/test.lst
  tests/std/tests/GH_005472_do_not_overlap/env.lst
  tests/std/tests/GH_005472_do_not_overlap/test.cpp
Labels: enhancement

#5498 Use the `_Transparent` concept and remove `_Is_transparent`
  stl/inc/xhash
  stl/inc/xmemory
  stl/inc/xtree
Labels: enhancement

#5500 Avoid calling `memcpy` in `swap`
  stl/inc/type_traits
Labels: enhancement

#5505 `<mdspan>`: Implement missing precondition in `layout_stride::mapping<E>`'s constructor
  stl/inc/mdspan
  tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_stride_death/test.cpp
Labels: enhancement, mdspan

#5496 `stl/CMakeLists.txt`: Remove redundant `Synchronization.lib`
  stl/CMakeLists.txt
Labels: build, ARM64

#5510 Win10 baseline: Drop support for Win8.1 / Server 2012 R2
  stl/inc/yvals_core.h
Labels: enhancement

#5509 `<regex>`: Improve search performance for regexes with initial `+` quantifiers
  benchmarks/CMakeLists.txt
  benchmarks/src/regex_search.cpp
  stl/inc/regex
  tests/std/include/test_regex_support.hpp
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: performance, regex

#5515 Merge `main` to `feature/flat_map`
  CMakeLists.txt
  README.md
  azure-devops/asan-pipeline.yml
  azure-devops/build-and-test.yml
  azure-devops/cmake-configure-build.yml
  azure-devops/config.yml
  azure-devops/provision-image.ps1
  azure-devops/run-tests.yml
  azure-pipelines.yml
  benchmarks/CMakeLists.txt
  benchmarks/src/regex_search.cpp
  benchmarks/src/reverse.cpp
  benchmarks/src/rotate.cpp
  benchmarks/src/search.cpp
  stl/CMakeLists.txt
  stl/inc/__msvc_string_view.hpp
  stl/inc/algorithm
  stl/inc/mdspan
  stl/inc/regex
  stl/inc/type_traits
  stl/inc/xhash
  stl/inc/xmemory
  stl/inc/xtree
  stl/inc/xutility
  stl/inc/yvals_core.h
  stl/src/vector_algorithms.cpp
  tests/std/include/test_regex_support.hpp
  tests/std/test.lst
  tests/std/tests/GH_005421_vector_algorithms_integer_class_type_iterator/test.cpp
  tests/std/tests/GH_005472_do_not_overlap/env.lst
  tests/std/tests/GH_005472_do_not_overlap/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
  tests/std/tests/P0009R18_mdspan_layout_stride_death/test.cpp
  tests/std/tests/VSO_0000000_regex_use/test.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
  tests/tr1/tests/regex2/test.cpp
  tools/CMakeLists.txt
  tools/format/CMakeLists.txt
  tools/validate/CMakeLists.txt
Labels: uncharted, flat_meow

#5516 `<flat_set>`: more invariants fixes
  stl/inc/flat_set
  tests/libcxx/expected_results.txt
Labels: bug, flat_meow

#5520 `<flat_map>`: Remove unreachable code
  stl/inc/flat_map
Labels: enhancement, flat_meow

#5522 Revert incorrect `<flat_set>` change, and update test failure reason
  stl/inc/flat_set
  tests/libcxx/expected_results.txt
Labels: test, flat_meow

#5526 Status Chart: Weekly updates
  README.md
  package-lock.json
  package.json
  src/weekly_table.mts
Labels: documentation, uncharted

#5524 `<regex>`: Restrict control letters in escapes to alphabetic ASCII characters
  stl/inc/regex
  tests/std/include/test_regex_support.hpp
  tests/std/tests/GH_005244_regex_escape_sequences/test.cpp
Labels: bug, regex

#5517 Build benchmarks for ARM64EC pipeline
  azure-pipelines.yml
  benchmarks/CMakeLists.txt
Labels: infrastructure, test, ARM64

#5521 Build tests for ARM64EC pipeline
  CMakeLists.txt
  azure-pipelines.yml
  tests/std/tests/GH_001103_countl_zero_correctness/test.cpp
  tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp
  tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
  tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
  tests/std/tests/P1502R1_standard_library_header_units/test.cpp
  tests/std/tests/P2465R3_standard_library_modules/test.cpp
  tests/std/tests/VSO_1775715_user_defined_modules/test.cpp
  tests/utils/stl/test/features.py
  tests/utils/stl/test/tests.py
Labels: infrastructure, test, ARM64

#5519 Improve `search` and `find_end` vectorization
  stl/src/vector_algorithms.cpp
Labels: performance

#5528 `<algorithm>`: Fix conditions for vectorization on trivial assignability
  stl/inc/algorithm
  stl/inc/xutility
  tests/std/test.lst
  tests/std/tests/GH_004686_vectorization_on_trivial_assignability/env.lst
  tests/std/tests/GH_004686_vectorization_on_trivial_assignability/test.cpp
Labels: bug

#5532 Clean up `vector_algorithms.cpp` again: unsigned bit manipulation, scope guard for multiple return
  stl/src/vector_algorithms.cpp
Labels: enhancement

#5542 `<regex>`: Remove `error_syntax`
  stl/inc/regex
  tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: bug, regex

#5534 `<bit>`: Use popcount for `has_single_bit()` if it's always available
  stl/inc/__msvc_bit_utils.hpp
  stl/inc/bit
Labels: performance

#5550 `<vector>`: Avoid a compiler warning with Defect Report P2280R4
  stl/inc/vector
Labels: enhancement

#5551 Update `source_location` tests for upcoming EDG changes
  tests/std/tests/P1208R6_source_location/header.h
  tests/std/tests/P1208R6_source_location/test.cpp
Labels: test
