Repository microsoft/STL, pull requests merged in 2025-04, with the labels that each got.

#5362 `<regex>`: Properly parse dollar anchors in basic and grep mode
  stl/inc/regex
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: bug, regex

#5364 `<regex>`: Allow initial `]` to start character ranges in POSIX regular expressions
  stl/inc/regex
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: bug, regex

#5375 `<regex>`: Fix word bounds `\b` and `\B` when applied to the empty string
  stl/inc/regex
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: bug, regex

#5376 `<regex>`: Make back-references to unmatched capture groups not match anything in POSIX basic regexes
  stl/inc/regex
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: bug, regex

#5377 `<regex>`: Do not reset matched capture groups in POSIX regexes
  stl/inc/regex
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: bug, regex

#5380 `<regex>`: Revise parsing of escape sequences
  stl/inc/regex
  tests/std/test.lst
  tests/std/tests/GH_005244_regex_escape_sequences/env.lst
  tests/std/tests/GH_005244_regex_escape_sequences/test.cpp
  tests/tr1/tests/regex2/test.cpp
Labels: bug, regex

#5358 `<type_traits>`: Use the `__is_scoped_enum` intrinsic for Clang
  stl/inc/type_traits
Labels: enhancement

#5360 Remove comments for LWG-3210, LWG-4024, and LWG-4154
  stl/inc/future
  stl/inc/memory
Labels: documentation

#5363 Search for first duplicate in vectorized `unique`
  benchmarks/src/unique.cpp
  stl/src/vector_algorithms.cpp
Labels: performance

#5367 `<bit>`: Improve `has_single_bit()` codegen
  benchmarks/CMakeLists.txt
  benchmarks/src/has_single_bit.cpp
  stl/inc/bit
Labels: performance

#5372 `bug-report.md`: Add backticks to default title
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: documentation

#5381 Added a missing case for `__std_is_file_not_found()`.
  stl/inc/xfilesystem_abi.h
Labels: bug, filesystem

#5382 Implement P0472R3 - Put `monostate` in `<utility>`
  stl/inc/utility
  stl/inc/variant
  stl/inc/xutility
  stl/inc/yvals_core.h
Labels: cxx26

#5383 Fix sporadic test failures by avoiding excessive compiler memory consumption
  tests/std/tests/P0896R4_ranges_alg_copy/test.cpp
  tests/std/tests/P0896R4_ranges_alg_transform_unary/test.cpp
  tests/std/tests/P2321R2_views_adjacent/test.cpp
  tests/std/tests/P2321R2_views_adjacent_transform/test.cpp
  tests/std/tests/P2441R2_views_join_with/test.cpp
Labels: test, ranges

#5385 Update _MSVC_STL_UPDATE to April 2025
  stl/inc/yvals_core.h
Labels: enhancement

#5388 `<ranges>`: Fix piecewise construction for `repeat_view`
  stl/inc/ranges
  tests/std/tests/P2474R2_views_repeat/test.cpp
Labels: bug, ranges

#5389 `STL.natvis`: Fixed `time_point` visualization of year off-by-one
  stl/debugger/STL.natvis
Labels: bug, visualizer

#5390 `STL.natvis`: Add alternative type name for `time_point`
  stl/debugger/STL.natvis
Labels: enhancement, visualizer

#5414 Fix [flat.map.access] bugs found by libcxx tests
  stl/inc/flat_map
  tests/libcxx/expected_results.txt
Labels: bug, flat_meow

#5415 Status Chart: Weekly updates
  .vscode/settings.json
  index.html
  package-lock.json
  package.json
  src/weekly_table.mts
Labels: documentation, uncharted

#5419 Fix [flat.map.modifiers] bugs found by libcxx tests
  stl/inc/flat_map
  tests/libcxx/expected_results.txt
Labels: bug, flat_meow

#5422 `<flat_map>`: Restore use of `push_back` in `flat_(multi)map::insert`
  stl/inc/deque
  stl/inc/flat_map
  stl/inc/vector
  stl/inc/xmemory
  stl/inc/xstring
Labels: performance, flat_meow

#5410 Toolset update: VS 2022 17.14 Preview 3
  CMakeLists.txt
  README.md
  azure-devops/config.yml
  azure-devops/provision-image.ps1
  stl/inc/random
  tests/libcxx/expected_results.txt
  tests/std/tests/P0088R3_variant/test.cpp
  tests/std/tests/P0220R1_optional/test.cpp
  tests/std/tests/P0758R1_is_nothrow_convertible/test.compile.pass.cpp
  tests/std/tests/P0898R3_concepts/test.cpp
  tests/std/tests/P2165R4_tuple_like_relational_operators/test.compile.pass.cpp
Labels: infrastructure

#5352 Vectorize `search_n` for small values of n
  benchmarks/src/search_n.cpp
  stl/inc/algorithm
  stl/src/vector_algorithms.cpp
  tests/std/test.lst
  tests/std/tests/VSO_0000000_vector_algorithms_search_n/env.lst
  tests/std/tests/VSO_0000000_vector_algorithms_search_n/test.cpp
Labels: performance

#5392 `<regex>`: Properly parse and match collating symbols and equivalences
  stl/inc/regex
  tests/std/tests/GH_005204_regex_collating_ranges/test.cpp
  tests/std/tests/GH_005244_regex_escape_sequences/test.cpp
  tests/tr1/tests/regex1/test.cpp
  tests/tr1/tests/regex2/test.cpp
Labels: bug, regex

#5399 `<regex>`: Permit escaping of closing brackets in POSIX regexes
  stl/inc/regex
  tests/std/tests/GH_005244_regex_escape_sequences/test.cpp
Labels: enhancement, regex

#5405 `<regex>`: Simplify matching of `_N_if` NFA nodes in leftmost-longest mode
  stl/inc/regex
Labels: enhancement, regex

#5347 Handle aligned `vector<bool>` in `constexpr` `copy()` properly
  stl/inc/vector
  tests/libcxx/expected_results.txt
  tests/std/tests/GH_000625_vector_bool_optimization/test.cpp
Labels: bug

#5361 `<locale>`: Repair `std::collate<unsigned short>`
  stl/inc/locale
  stl/inc/xlocinfo
  tests/std/test.lst
  tests/std/tests/GH_005204_regex_collating_ranges/test.cpp
  tests/std/tests/GH_005236_collate_facet/env.lst
  tests/std/tests/GH_005236_collate_facet/test.cpp
  tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
Labels: bug

#5355 Vectorize `remove_copy` and `unique_copy`
  benchmarks/src/remove.cpp
  benchmarks/src/unique.cpp
  stl/inc/algorithm
  stl/src/vector_algorithms.cpp
  tests/std/tests/Dev11_0316853_find_memchr_optimization/test.cpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: performance

#5398 `<barrier>`: Fix constructor's exception specification
  stl/inc/barrier
  tests/std/tests/P1135R6_barrier/test.cpp
Labels: bug

#5400 Add `std::fill` and `std::fill_n` benchmarks
  benchmarks/CMakeLists.txt
  benchmarks/src/fill.cpp
Labels: test

#5403 `<regex>`: Make `wregex` correctly match negated character classes
  stl/inc/regex
  tests/std/tests/VSO_0000000_regex_use/test.cpp
Labels: bug, regex

#5404 Fix inconsistent use of `normal_distribution` in benchmarks and tests
  benchmarks/src/adjacent_difference.cpp
  benchmarks/src/minmax_element.cpp
  tests/std/tests/VSO_0000000_vector_algorithms_floats/test.cpp
Labels: test

#5406 Fix heap-use-after-free for `_HAS_EXCEPTIONS=0`
  stl/inc/chrono
  stl/inc/system_error
  tests/std/test.lst
  tests/std/tests/GH_005276_system_error_heap_use_after_free/env.lst
  tests/std/tests/GH_005276_system_error_heap_use_after_free/test.cpp
Labels: bug

#5407 `<optional>`: Extend compiler bug workaround to MSVC
  stl/inc/optional
Labels: enhancement

#5409 `<string>`: Fix construction and insertion of `basic_string` with volatile ranges
  stl/inc/xstring
  tests/std/test.lst
  tests/std/tests/GH_005402_string_with_volatile_range/env.lst
  tests/std/tests/GH_005402_string_with_volatile_range/test.cpp
Labels: bug, ranges

#5411 `<random>`: Improve performance of `poisson_distribution` constructor
  stl/inc/random
Labels: performance

#5412 `<random>`: Fast `discard()` for `minstd_rand` and `minstd_rand0` via fast exponentiation
  benchmarks/src/random_integer_generation.cpp
  stl/inc/random
Labels: performance

#5417 Remove mentions of 'fast math' from floating vectorization control
  stl/inc/xutility
Labels: documentation

#5425 Reduce vector algorithms test run time with ASan
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Labels: test

#5420 Vectorize `is_sorted_until`
  benchmarks/CMakeLists.txt
  benchmarks/inc/utility.hpp
  benchmarks/src/is_sorted_until.cpp
  stl/inc/algorithm
  stl/inc/xutility
  stl/src/vector_algorithms.cpp
  tests/std/include/test_is_sorted_until_support.hpp
  tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
  tests/std/tests/VSO_0000000_vector_algorithms_floats/test.cpp
Labels: performance

#5100 `<algorithm>`: Implement worst-case linear-time `nth_element`
  benchmarks/CMakeLists.txt
  benchmarks/src/nth_element.cpp
  stl/inc/algorithm
  tests/std/test.lst
  tests/std/tests/GH_000856_nth_element_linear/env.lst
  tests/std/tests/GH_000856_nth_element_linear/test.cpp
Labels: bug, performance

#5432 Win8 baseline: Drop support for Win7 / Server 2008 R2
  stl/CMakeLists.txt
  stl/inc/xatomic_wait.h
  stl/inc/yvals_core.h
  stl/msbuild/stl_atomic_wait/msvcp_atomic_wait.settings.targets
  stl/src/atomic_wait.cpp
  stl/src/awint.hpp
  stl/src/ppltasks.cpp
  stl/src/winapisupp.cpp
  stl/src/xtime.cpp
  tests/std/test.lst
  tests/std/tests/P1135R6_atomic_wait_win7/env.lst
  tests/std/tests/P1135R6_atomic_wait_win7/test.cpp
Labels: performance

#5433 Win8 baseline: Improve STL Hardening codegen size
  stl/inc/ranges
  stl/inc/yvals.h
Labels: performance

#5434 Win8 baseline: Simplify `<filesystem>` API calls
  stl/src/filesys.cpp
  stl/src/filesystem.cpp
Labels: enhancement, filesystem

#5428 README.md: Fix odd wording
  README.md
Labels: documentation, uncharted

#5430 README.md: Fix a few more typos
  README.md
Labels: documentation

#5429 `vector_algorithms.cpp`: cleanup
  stl/src/vector_algorithms.cpp
Labels: enhancement, uncharted

#5436 `<random>`: Use `_Unsigned128` for `linear_congruential_engine`
  stl/inc/random
  stl/src/multprec.cpp
Labels: performance
