Repository microsoft/STL, pull requests merged in 2025-09, with the labels that each got.

#5711 `<xloctime>`: Silence CodeQL warning SM03231 about leap years, again
  stl/inc/xloctime
Labels: enhancement

#5696 Promote internal `_Countl_zero` to `__msvc_bit_utils.hpp` to reduce code duplication and improve consistency
  stl/inc/__msvc_bit_utils.hpp
  stl/inc/__msvc_int128.hpp
  stl/inc/bit
  stl/inc/random
Labels: enhancement

#5703 `<regex>`: Rename the matcher again
  stl/inc/regex
Labels: enhancement, regex

#5708 `<atomic>`: Workaround `__iso_volatile_{load,store}64` being non-atomic with clang-cl on 32-bit x86
  stl/inc/atomic
Labels: bug, compiler

#5709 Update _MSVC_STL_UPDATE macro to September 2025
  stl/inc/yvals_core.h
Labels: enhancement

#5589 `README.md`: expand benchmarking examples
  README.md
Labels: documentation

#5716 `<regex>`: Handle overflow and allocation failure when parsing repetitions
  stl/inc/regex
Labels: bug, regex

#5726 Fix UB in `vector<bool>` by adding missing special case
  stl/inc/vector
Labels: bug

#5729 `<vector>`: Fix allocator types in reallocation guards
  stl/inc/vector
Labels: bug

#5730 Deduction failures in pointer interconvertibility trait tests
  tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp
Labels: test

#5735 `<algorithm>`: Optimize `sample()` and `shuffle()` with Lemire's algorithm
  benchmarks/CMakeLists.txt
  benchmarks/src/sample.cpp
  benchmarks/src/shuffle.cpp
  stl/inc/algorithm
  stl/inc/random
  tests/std/tests/P0896R4_ranges_alg_shuffle/test.cpp
  tests/tr1/tests/algorithm/test.cpp
Labels: performance

#5740 `<random>`: Prevent full-width shifts in `independent_bits_engine`
  stl/inc/random
Labels: bug
